missioonRequest refactor
official-antistasi-community/A3-Antistasi pull request #1101
Opened 2020-06-08 15:55 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [x] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the Mission in Singleplayer?
2. [ ] Have you loaded the Mission in a Dedicated Server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:
any further changes will have to be done stage wise as the mission related to the case is altered. depending on current prs open merge order alteration would be needed to add changes to this, but it would be minimal changes.

2020-06-09 23:33 UTC, CalebSerafin commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		}forEach _control;
Running on a fresh start with `BIS_fnc_codePerformance` reveals that it takes **44ms** to complete just these two loops (long!). <br/>
It can be made **1811,59%** faster by applying some optimisations with a similar level of readability.
* Cache global variables to local variables (Biggest impact **1,8ms**)
* Loop through `controlsX` once.
* Lazy Evaluation; bool && {bool} vs bool && bool
* `deleteAt`&`find` instead of `_arr= _arr- ["element"];`
* Assign `_pos = getmarkerPos _x;` once each loop. And define it before the loop.
*  `isEqualTo` instead of `==`
* `distanceSqr` instead of `distance` (compare to distanceSPWN^2)

In total, that brings us to **1,38ms** for this loop.
***
Some of these optimisations also apply to other loops used. <br/>
Accepting these specific changes for optimisation is not necessary if you already have an alternate method.

```Suggestion
		private _markersX = markersX;
		private _controlsX = controlsX;
		private _distanceSPWNSqr = distanceSPWN^2;
		private _sidesX = sidesX;
		private _teamPlayer = teamPlayer;
		private _pos = [0,0];
		{
			_pos = getmarkerPos _x;
			if !(isOnRoad _pos) then {
				_markersX = _markersX select {(getMarkerPos _x distanceSqr _pos < _distanceSPWNSqr) and {_sidesX getVariable [_x,sideUnknown] isEqualTo _teamPlayer}};
				_markersX deleteAt (_markersX find "Synd_HQ");
				if !(_markersX isEqualTo []) then {_possibleMarkers pushBack _x};
			};
		}forEach _controlsX;
```

2020-06-09 23:48 UTC, HakonRydland commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +private _type = _this select 0;
done

2020-06-10 00:01 UTC, CalebSerafin commented
Some other loops could use optimization, I don't know if I will get time tomorrow to write these up. @HakonRydland If you could try your hand at the other loops that would be amazing.

2020-06-10 10:27 UTC, Bob-Murphy commented
@CalebSerafin @HakonRydland @jaj22 
I need feedback here.
Should that be in 2.2.2/2.3? Does it make sense to merge it?
If so, what is needed before this is ready to merge?

2020-06-10 10:29 UTC, CalebSerafin commented
Right now I don't see any problems merging it. It will probabl cause less lag when requesting a mission than before. But it need to be tested after integration.

2020-08-17 16:21 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +			if (_site in antennas) then {[[_site],"DES_antenna"] remoteExec ["A3A_fnc_scheduler",2]}
Old bug, DES_antenna missing the function prefix. May as well fix it while you're rewriting the thing.

2020-08-17 16:22 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		private _distanceSPWNSqr = distanceSPWN^2;
Wait, really? Why would this ever be a useful value? Old bug copied?

2020-08-17 16:36 UTC, CalebSerafin commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		private _distanceSPWNSqr = distanceSPWN^2;
Okay, I'll take the blame for that. I was under the impression that SQF may try to perform software level square roots. I checked recently and discovered that it's hardware-level like other reasonable languages. 

> Ln41: `(getMarkerPos _x distanceSqr _pos < _distanceSPWNSqr)` will need to be `(getMarkerPos _x distance _pos < _distanceSPWN)`

2020-08-19 23:25 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint","Assasination Missions require cities, Patrolled Jungles or Airports closer than 4Km from your HQ.", "Missions"] remoteExec ["A3A_fnc_commsMP",theBoss];
If I'm reading this correctly, the case of "or finish some other assasination (sic) missions" isn't valid because that's already handled in the "I already gave you a mission of that type" check earlier. Misleading text should be avoided.

There's one of these for every mission type, I think. Not gonna mark them all.

2020-08-20 05:43 UTC, HakonRydland commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint","Assasination Missions require cities, Patrolled Jungles or Airports closer than 4Km from your HQ.", "Missions"] remoteExec ["A3A_fnc_commsMP",theBoss];
the refactor did not touch the feedback at all. but i can go trough and check the "no mission for you" text for each case

2020-08-23 17:50 UTC, jaj22 requested changes
Apologies for the drip-feeding. Attempted to be comprehensive this time.

You can ignore the second half if you don't want to deal with the convoy requests at the moment. I don't think there are any new bugs there.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +			if (_spawner == 2) then {_possibleMarkers pushBack _x};
_spawner should be private or one-lined.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +			_prestige = server getVariable _x;
_prestige should be private.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		_Markers = _Markers select {(sidesX getVariable [_x,sideUnknown] != teamPlayer) and !(_x in blackListDest)};
Old code, but blackListDest is removed twice. _Markers should be private.

Also this whole section seems very confused about whether rebel cities are valid targets or not. They're excluded by the second line, but that makes the garrison check redundant (enemies don't garrison cities), and then there's a ton of code in the middle that only operates on rebel cities...

Original intention was probably something like this, but as it's re-enabling dead code, it'd need further testing:
```
private _Markers = (airportsX + resourcesX + factories + seaports + outposts - blackListDest);
_Markers = _Markers select {sidesX getVariable [_x,sideUnknown] != teamPlayer};
_Markers append (citiesX select {count (garrison getVariable [_x,[]]) < 10 && !(_x in blackListDest)});
```
Not sure if the blackListDest check on towns is necessary. It'd only be used for towns without roads, and I don't think those get names.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		if (count _Markers > 0) then
Maybe make this an exitWith and save a level of indentation.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
>  			{
Barbolani brackets start here. I assume they're not intentionally preserved.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
>  					else
Unless I'm misreading, this whole section is currently never called because teamPlayer sites are blocked earlier. If you're going to keep & activate it, there are a bunch of vars in the middle (_dataX, _prestigeOPFOR, _prestigeBLUFOR) that should be private.

2020-08-23 17:50 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				_base = [_site] call A3A_fnc_findBasesForConvoy;
_pos and _base should be private. Would also prefer something like _target/_base or _dest/_source rather than _site/_base to make it clear what these are.

2020-08-25 14:58 UTC, HakonRydland commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				_base = [_site] call A3A_fnc_findBasesForConvoy;
would cause no feedback when there is no possible sites as that would exit out of the switch scope, unless i misunderstood you

2020-08-25 15:00 UTC, HakonRydland commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		if (count _Markers > 0) then
would cause no feedback as it would exit the switch scope. all mission specific feedback is within the case for said mission, unless i misunderstood what you are saying

2020-08-25 18:10 UTC, jaj22 approved these changes
Tweak the two things I mentioned if you like, but they're not important.

PR ready to merge.

2020-08-25 18:10 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +			(getMarkerPos _x inArea [getMarkerPos respawnTeamPlayer, distanceMission+distanceSPWN, distanceMission+distanceSPWN, 0, false])
Hah, nice bonus optimisation. `distance2d` is actually twice as fast as `inArea` for circles though, as well as being shorter. `inAreaArray` is special because it'll process the whole array without touching SQF.

Fastest version is probably to filter the whole array with inAreaArray first, and then strip out synd_HQ and the non-teamPlayer markers.

2020-08-25 18:13 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +		if (count _Markers > 0) then
Yeah, you're correct. Could instead remove the check entirely, as `for "_i" from 0 to -1 do {}` doesn't do anything, or change to a forEach where that result is more obvious. Minor stuff though, particularly now that the code inside is shorter and clearer.

2020-08-28 06:18 UTC, Bob-Murphy commented
@HakonRydland Merge conflict

2020-08-28 06:25 UTC, merged