Phase 2 of mod integration safety work.
official-antistasi-community/A3-Antistasi pull request #1268
Opened 2020-07-14 21:24 UTC by SonorousMeerkat

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Pulled mod detection out of initVarCommon into a file in the templates folder.

### Please specify which Issue this PR Resolves.
closes #1268

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
  Load the mission with each of the supported mods, checking the log for "detected xxx" lines and checking petros for the right gear.
********************************************************
Notes:

2020-07-14 21:57 UTC, SonorousMeerkat commented
For the sake of reviewer sanity, this is now aimed at the phase 1 branch.

2020-07-15 21:30 UTC, SonorousMeerkat commented
Testing completed, All mods load on all environments so it should be good.

2021-01-10 10:55 UTC, CalebSerafin commented
7 liner notes for me.
* [ ] Indentation
* [ ] Naming Conventions
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic

2021-01-10 12:06 UTC, CalebSerafin requested changes
### These are in addition to the smaller comments on source files.

`activeAFRF` & `activeUSAF` can be removed in one swoop. Replace them with `hasRHS` in Ln22 `A3-Antistasi\functions\Ammunition\fn_equipmentIsValidForCurrentModset.sqf`
***
`modUnautorized` spelling mistake can be fixed; Nessary changes are required in `A3-Antistasi\functions\init\fn_modBlacklist.sqf` & `A3-Antistasi\MissionDescription\endMission.hpp` & `A3-Antistasi\Templates\detector.sqf`.
***
`detector.sqf` is should follow the standard of using `functions.hpp`. Although not required, it should begin with `fn_` to maintain consistency.
***
`detector.sqf` should preferably follow the [standard header format](https://docs.google.com/document/d/1dKvEdbA3DxpkVMcZHZBV78-qUQIlaD9QUfufEzLFnqg/edit?usp=sharing).

2021-01-10 12:31 UTC, CalebSerafin commented on A3-Antistasi/Templates/detector.sqf
> +if (isClass (configfile >> "CfgPatches" >> "ffaa_armas")) then {hasFFAA = true; diag_log format ["%1: [Antistasi] | INFO | initVar | FFAA Detected.",servertime];};
Please finish file off with newline & carriage return.

2021-01-10 17:57 UTC, SonorousMeerkat commented on A3-Antistasi/functions/init/fn_initVarCommon.sqf
> +//Content Mods (Units, Vehicles, Weapons, Clothes etc.)
Out of scope, All I did was remove the detection lines.

2021-01-10 18:04 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/detector.sqf
> +  diag_log format ["%1: [Antistasi] | INFO | initVar | RHS Pack Detected.",servertime];
Fixed

2021-01-10 18:05 UTC, SonorousMeerkat commented on A3-Antistasi/functions/init/fn_initVarCommon.sqf
> +call compile preProcessFileLineNumbers "Templates\detector.sqf";
Beyond my understanding as to why it is necessary and how that would effect its implementation.

2021-01-10 18:08 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/detector.sqf
> +if (hasRHS && (
I don't understand what you mean here, I see no problem with this setup.

2021-01-10 18:12 UTC, SonorousMeerkat commented
> ### These are in addition to the smaller comments on source files.
> `activeAFRF` & `activeUSAF` can be removed in one swoop. Replace them with `hasRHS` in Ln22 `A3-Antistasi\functions\Ammunition\fn_equipmentIsValidForCurrentModset.sqf`
> 
> `modUnautorized` spelling mistake can be fixed; Nessary changes are required in `A3-Antistasi\functions\init\fn_modBlacklist.sqf` & `A3-Antistasi\MissionDescription\endMission.hpp` & `A3-Antistasi\Templates\detector.sqf`.
> 
> `detector.sqf` is should follow the standard of using `functions.hpp`. Although not required, it should begin with `fn_` to maintain consistency.
> 
> `detector.sqf` should preferably follow the [standard header format](https://docs.google.com/document/d/1dKvEdbA3DxpkVMcZHZBV78-qUQIlaD9QUfufEzLFnqg/edit?usp=sharing).

1. Out of scope in this PR, is handled later in the removal of obsolete vars. (Phase 6)

2. Typo in this file can be fixed though it was inherited when the code was transferred from initVar to here. Other files are out of scope.

3. I have no knowledge of the conventions for functions and such, I have no idea how to implement them or what effect they may have. 

4. Header will be updated to follow the standard.

2021-01-10 18:18 UTC, SonorousMeerkat commented
Header has now been added, but I am unsure how to fill some of the details out, if they are even applicable.

2021-01-10 19:56 UTC, CalebSerafin commented on A3-Antistasi/Templates/detector.sqf
> +if (hasRHS && (
It prevents the SQF Interpreter from checking code inside of {} if the previous condition would make the total outcome false. IE: if RHS is not loaded, and lazy condition checking is used, it will not perform 5 config checks. Even though in this case where it is executed only once at mission start, it is a good habit to develop when working with more frequently executed code.

2021-01-10 19:57 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initVarCommon.sqf
> +//Content Mods (Units, Vehicles, Weapons, Clothes etc.)
Okay, it would be convient now since you are touching it, but thats fine for now.

2021-01-10 20:00 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initVarCommon.sqf
> +call compile preProcessFileLineNumbers "Templates\detector.sqf";
It makes tracing functions far easier than looking for loadFile of it's path which could be dynamically creating. IE: if someone wanted to quickly search for code that calls this function, they can type `A3A_fnc_detector` by just knowing the filename. It keeps the register of functions in concentrated and standard places, like functions.hpp's.

2021-01-10 20:08 UTC, CalebSerafin commented
If you would like, I could push a commit to fill in the headers? (mostly all that's needed is description and environment as well as when & where it should run)

For migrating to functions.hpp, Since I haven't looked at further MIE PRs, I'll take a note now, so I can revisit it after they have been merged.

2021-01-11 13:14 UTC, CalebSerafin commented on A3-Antistasi/Templates/detector.sqf
> +if (hasRHS && (
I'll take a note of this for now as it is not critical.

2021-01-11 13:16 UTC, CalebSerafin approved these changes

2021-01-11 14:00 UTC, SonorousMeerkat commented
> If you would like, I could push a commit to fill in the headers? (mostly all that's needed is description and environment as well as when & where it should run)
> 
> For migrating to functions.hpp, Since I haven't looked at further MIE PRs past 4, I'll take a note now, so I can revisit it after they have been merged.

If you would, It would be much appreciated. You could either do it here, or when you convert it to being in functions.hpp i guess.

2021-01-23 19:41 UTC, merged