Phase 3 MIE implementation
official-antistasi-community/A3-Antistasi pull request #1281
Opened 2020-07-15 15:12 UTC by SonorousMeerkat

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Moves JNL definition to mod specific files in the Templates folder
    Changes the weapon compatibility listings to arrays that can be updated by various files, instead of hard coding all weapons 
    for all vehicles.

### Please specify which Issue this PR Resolves.
closes #1278 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
  Load all modsets and check that all JNL actions still work as intended.
********************************************************
Notes:
  Can't test weapon points as they require JNG which has been disabled for some time.

2020-07-15 21:32 UTC, SonorousMeerkat commented
Testing completed, Each modset's vehicles had crate loading. Should be fine.

2021-01-10 12:23 UTC, CalebSerafin commented
7 Liner for myself.
* [ ] Indentation
* [ ] Naming Conventions
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic

2021-01-10 13:27 UTC, CalebSerafin requested changes
### These are in addition to the smaller comments on source files.
The logic in `selector.sqf` seems repetitive. However, I understand this is low priority.
***
`selector.sqf` should try follow our [standard header format](https://docs.google.com/document/d/1dKvEdbA3DxpkVMcZHZBV78-qUQIlaD9QUfufEzLFnqg/edit?usp=sharing)
***
`selector.sqf` should be referenced in `function.hpp` and prefixed with fn to make it consistent and easy to find. EG:
```sqf
	class Templates
	{
		class aceModCompat {};
		class getLoadout {};
		class ifaModCompat {};
		class rhsModCompat {};
		class templateSelector {file="Templates\fn_selector.sqf";};
	};
```
***
Code critiques in JNL files have been omitted.

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/Example/Example_JNL_Nodes.sqf
> +];//To make it easier to navigate, it is a good idea to keep the lines for similar vehicles together. Usually we list 4 wheeled vehicles, then 6 wheeled, then 8 wheeled, then boats. It is also good t
Comma after Introduction: `Usually` -> `Usually,`

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/Example/Example_JNL_Nodes.sqf
> +  The weapon sets are used to tell the game what weapons can be mounted on what vehicles and are seperated into 2 categories.
Spelling Error: `seperated` -> `separated`

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/Example/Example_JNL_Nodes.sqf
> +  This makes sure that the vehicle can mount all apropriate weapons from all mods loaded.
Spelling Error: `apropriate` -> `appropriate`

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/Example/Example_JNL_Nodes.sqf
> +  The entries are usually seperated by an inline comment that says what vehicle the next entry is for, as model paths aren't always obvious.
Spelling Error: `seperated` -> `separated `

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/Example/Example_JNL_Nodes.sqf
> +  This is usually seperated into 3 sections; Weapons, Crates and Other.
Spelling Error: `seperated` -> `separated`

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/Example/Example_JNL_Nodes.sqf
> +//That covers everything, you should make you file by replacing values in an already complete file rather than using this as the active files will have the propper commenting there already. Using thi
Make Pronoun Posessive: `you should make you` -> `you should make your`
Spelling Error: `propper` -> `proper`

2021-01-10 13:27 UTC, CalebSerafin commented on A3-Antistasi/Templates/selector.sqf
>  tropicalmaps = ["Tanoa"];
for map names, it would be better processing them all in lower case to save headaches (or upper, but uncommon). EG:
```sqf
temperatemaps = ["Enoch","chernarus_summer","vt7","Tembelan"] apply {toLower _x};
```
for checking:
```sqf
case (toLower worldName in temperatemaps): {
```

2021-01-10 13:28 UTC, CalebSerafin commented
@HakonRydland Take note of JNL changes as they might impact your work.

2021-01-10 18:56 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/selector.sqf
>  tropicalmaps = ["Tanoa"];
Out of scope.

2021-01-10 19:07 UTC, SonorousMeerkat commented
White space changes are not going to be made as JNL is going to be replaced with Hakon's logistics. This will entirely replace these files and will be rolled out in the same major version.
(It's also a metric fucktonne of work that makes no functional change.)

Changes to the selector file's function (other than those related to JNL) are out of scope for this PR.

2021-01-11 13:31 UTC, CalebSerafin commented on A3-Antistasi/Templates/selector.sqf
>  aridmaps = ["Altis","Kunduz","Malden","tem_anizay","takistan"];
Okay, preferable these will need to be updated before 2.4 release.

2021-01-11 13:31 UTC, CalebSerafin approved these changes

2021-01-23 19:40 UTC, merged