Phase 4 MIE Implementation
official-antistasi-community/A3-Antistasi pull request #1283
Opened 2020-07-15 18:48 UTC by SonorousMeerkat

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Worked out how to create an additive civ template,
    Created such a template for Ivory Car Pack,
    Added detection for said pack,
    Added extra logging to the template selection for verifying what loads. (in case there are future issues).

### Please specify which Issue this PR Resolves.
closes #1263 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
  Load the game with the mod and see if they spawn. See #1263 
********************************************************
Notes:
  1263 closed as this saves the conflict resolution later.

2020-07-15 21:33 UTC, SonorousMeerkat commented
Testing completed, Vehicles were showing up as they did on previous implementation.

2021-01-10 13:39 UTC, CalebSerafin commented
7 Liner for myself.
* [ ] Indentation
* [ ] Naming Conventions & Spelling
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic

2021-01-10 13:54 UTC, CalebSerafin requested changes
Cool. These changes are notably solid. See small attached comments.

2021-01-10 13:54 UTC, CalebSerafin commented on A3-Antistasi/Templates/AddonVics/ivory_Civ.sqf
> +	"ivory_gti",2.0					//VW Golf GTI
Convert Tabs to spaces.

2021-01-10 13:54 UTC, CalebSerafin commented on A3-Antistasi/Templates/detector.sqf
> +if (isClass (configfile >> "CfgPatches" >> "Ivory_Data")) then {hasIvory = true; diag_log format ["%1: [Antistasi] | INFO | initVar | Ivory Cars Detected.",servertime];};
Please use `A3A_fnc_log` instead of `diag_log`.

2021-01-10 13:54 UTC, CalebSerafin commented on A3-Antistasi/Templates/detector.sqf
> +hasIvory = false;
Since Ivory is a new mod, it would be preferential to set an example for a prefixed hasMod naming standard.
Reccomend prefixing with `A3A_` `A3A_Tmpl_` ect...

2021-01-10 19:10 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/detector.sqf
> +hasIvory = false;
For what reason? This has remain unchanged since Barbs made them, why change it now?

2021-01-10 19:15 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/detector.sqf
> +if (isClass (configfile >> "CfgPatches" >> "Ivory_Data")) then {hasIvory = true; diag_log format ["%1: [Antistasi] | INFO | initVar | Ivory Cars Detected.",servertime];};
done

2021-01-10 19:15 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/AddonVics/ivory_Civ.sqf
> +	"ivory_gti",2.0					//VW Golf GTI
Done

2021-01-11 13:38 UTC, CalebSerafin commented on A3-Antistasi/Templates/detector.sqf
> +hasIvory = false;
All code running in Arma 3 shares the global namespace, therefore, all global variables that are created by antistasi mission should be prefixed.
It also makes the domain and creation of the variable more obvious. 
Just because it has remained unchanged since the formation of the team, does not verify it as a good practice.

2021-01-11 13:44 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/detector.sqf
> +hasIvory = false;
In this case, I will cover all of these variables in the phase 6 PR as by your description here, they all need doing and some of the changes will require looking into a wide part of the code base.

2021-01-11 13:46 UTC, CalebSerafin approved these changes

2021-01-23 19:40 UTC, merged