Meer MIE phase 5 (FFAA)
official-antistasi-community/A3-Antistasi pull request #1314
Opened 2020-07-20 16:34 UTC by SonorousMeerkat

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Expands and reintegrates FFAA as a full template. Major change to selector.sqf to allow for this.

### Please specify which Issue this PR Resolves.
closes none

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
  Load one of each environment with FFAA loaded and check that the units are spawning.
********************************************************
Notes:
Only Temp and Arid available, it's all they have.

2020-07-20 16:36 UTC, SonorousMeerkat commented
Provided it is much the same as FFAA, BWMod can be set up and integrated like this once it's pulled into unstable for 2.4

2020-07-20 17:53 UTC, Lazejun commented on A3-Antistasi/Templates/FFAA/FFAA_Occ_FFAA_Arid.sqf
> +if ((gameMode != 4) and (!hasFFAA)) then
I think you oversaw one

if (gameMode != 4) then

2021-01-10 13:58 UTC, CalebSerafin commented
7 Liner for myself.
* [ ] Indentation
* [ ] Naming Conventions & Spelling
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic

2021-01-11 14:24 UTC, CalebSerafin requested changes
Okay, straight-forward mod addition. I like that RHS's long mod-features essay has been shortened.
One minor change requested for worldName FFAA selector.

2021-01-11 14:24 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initClient.sqf
> +if (hasTFAR or hasACE or hasRHS or hasACRE or hasFFAA or has3CB or hasIvory) then {
Since this line will grow in size, it could be simplfied:
```sqf
if !(_textX isEqualTo []) then {
```
However, I might rework the display here after MIE anyway, so you can resolve this comment.

2021-01-11 14:24 UTC, CalebSerafin commented on A3-Antistasi/Templates/selector.sqf
> +        case (worldName in arcticmaps): {
Combine the worldName checks here so it can be less repetative:
```sqf
case (worldName in (arcticmaps+temperatemaps+tropicalmaps)): {
```
This can be expanded out later if more colour schemes become available.

2021-01-11 14:41 UTC, SonorousMeerkat commented on A3-Antistasi/functions/init/fn_initClient.sqf
> +if (hasTFAR or hasACE or hasRHS or hasACRE or hasFFAA or has3CB or hasIvory) then {
A proper overhaul to that message box is probably in order, I'll let you handle it.

2021-01-11 14:42 UTC, SonorousMeerkat commented on A3-Antistasi/Templates/selector.sqf
> +        case (worldName in arcticmaps): {
For the time being I'd say leave it as this is going to have an overhaul for the new template system, the details of which I am not sure of.

2021-01-11 14:48 UTC, CalebSerafin approved these changes

2021-01-23 19:39 UTC, merged