Loot to crate
official-antistasi-community/A3-Antistasi pull request #1343
Opened 2020-07-26 18:06 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Loot to crate function is finally here. this allows you to load all nearby loot into the surrender crates (to its capacity) and then also allow you to transfer that again to nearby vehicles, this speeds up looting and due to being able to filter out unlocked stuff it allows for more efficient utilization of cargo space.

Use: 
you can now buy new surrender crates at the vehicle box at HQ.
when looking at the surrender crates you will have tre options in the action menu
 1) "Load loot to crate" loots nearby bodies and loot on the ground to the surrender crate.
 2) "Load loot from crate to vehicle" loads contents of the crate to nearest vehicle.
 3) "Carry Crate"/"Drop Crate" carry or drop the crate (context dependent)

Notes:
I'm considering adding JNL load to vehicle action to it. i'm considering it as there is currently no way to transport the crates by vehicle (except sling loading) without using ace.

### Please specify which Issue this PR Resolves.
closes #1342

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
1) buy or find surrender crates
2) go kil stuff
3) use the functions on the crates to loot
4) did something funny happen?
********************************************************
Notes:
the further testing that is needed is stress testing

2020-07-28 06:15 UTC, nicksc14 commented
It would be better if the surrender crates can be loaded onto vehicles!

2020-07-28 06:20 UTC, SonorousMeerkat commented
> the surrender crates now support jnl loading, like the ammo crates at outposts do

2020-07-28 06:32 UTC, nicksc14 commented
> > the surrender crates now support jnl loading, like the ammo crates at outposts do

Forget I'm using ace3! lol never mind. it's a great enhancement to the game

2020-07-28 06:34 UTC, SonorousMeerkat commented
Those crates have always been ACE loadable too from what i remember.

2020-07-28 06:35 UTC, nicksc14 commented
> Those crates have always been ACE loadable too from what i remember.

yes, it works

2020-07-28 08:33 UTC, nicksc14 commented
Sometimes the scroll wheel options don't show. I have to quit and reconnect to have those options again. Any idea please?

2020-07-28 08:37 UTC, Bob-Murphy commented
@nicksc14 this sound more like a general Antistasi question which seems not related to this pull request in particular.
Can you confirm that you are currently testing this branch and have the problem whilst doing so?
If not, please feel free to join our discord to ask this question there in the #help channel.
The comments within the PRs and issues should only focus on the topic.
Thank you.

2020-07-28 08:42 UTC, wurzel0701 commented
Need to correct Bob here. This is an internal isssue of this PR, but one that should be fixed by yesterday commit 823dc26

2020-07-28 09:00 UTC, Lazejun commented
> the surrender crates now support jnl loading, like the ammo crates at outposts do

#920 Heavy Breathing:
Update Garbage Cleaner?

2020-07-28 09:00 UTC, nicksc14 commented
> @nicksc14 this sound more like a general Antistasi question which seems not related to this pull request in particular.
> Can you confirm that you are currently testing this branch and have the problem whilst doing so?
> If not, please feel free to join our discord to ask this question there in the #help channel.
> The comments within the PRs and issues should only focus on the topic.
> Thank you.

Confirm, I'm testing this LTC function, I added this function to my mission and played with a group. sometimes the scroll wheel options of the surrender crates don't show. I have to reconnect to game to see these options again.

2020-07-28 09:07 UTC, nicksc14 commented
> Need to correct Bob here. This is an internal isssue of this PR, but one that should be fixed by yesterday commit [823dc26](https://github.com/official-antistasi-community/A3-Antistasi/commit/823dc2621ed46da3f1685dc86410870d3577ba40)

But I'm using this build, still have this issue.

2020-07-28 10:17 UTC, HakonRydland commented
@nicksc14 im sorry to hear the latest patch didnt solve your problem, could you tell me the mods you are running and under what circumstance the actions disappeared. IE did it happen after being revived, if so was it by ai or a player?

2020-07-28 22:22 UTC, nicksc14 commented
> @nicksc14 im sorry to hear the latest patch didnt solve your problem, could you tell me the mods you are running and under what circumstance the actions disappeared. IE did it happen after being revived, if so was it by ai or a player?

I'm using ACE3 No Medical and RHS. I also added a "spawn on squad leader" function to my mission. This could be the trigger of this issue. Problem happens usually after a revive or respawn. Weird thing is sometimes, scroll wheel options of the crates appear again after another respawn. I will continue testing your latest commits with my friends tonight(without spawn on squad leader function). I will report any further issues. Thank you for your work!

2020-07-28 22:24 UTC, HakonRydland commented
we had some internal testing on our dedicated test server and found no issues with missing actions as of the latest commit, hopefully your problem is solved.

2020-08-05 03:10 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
I think you have a fundamental dupe risk here. Global setVariables can be propagated quite slowly, and setting variables from multiple instances is also undefined behaviour. Two players using the same loot action at the same time is also not a well-concealed exploit.

Easiest fix is to run all the transfer code strictly on the server, and gate it there with local variables. Given that it's quite a lot of load to dump on the server, a fancier method would be to run it where the crate is local (hopefully on clients, as they pick up the crates), but that may need a timeout after locality changes for a bit more security. Either method would need to remoteExec any hints.

The other function is more annoying because I think you'd need to run it where the corpses are local, as two players with their own crates could otherwise dupe the same corpse. Maybe a better method would be to bounce a looting request through the server, which does the lockout check locally and then remoteExecs back to the client to perform the bulk of the looting operation.

2020-08-05 03:19 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +player setVariable ["BuyCrateCooldown",true,true];
Another one that probably doesn't need to be a global variable.

2020-08-05 03:23 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +_money = player getVariable "moneyX";
I don't think you have any player-owner checks around this, so it would break if done while controlling an AI. Probably a good idea to throw in a default 0 anyway.

2020-08-05 03:24 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +_position = (getPos _unit) findEmptyPosition [1,10,"Box_IND_Wps_F"];
Knowing these crates, I feel like you should probably find a position for something much larger to avoid inadvertently wrecking the HQ.

2020-08-05 03:31 UTC, jaj22 commented on A3-Antistasi/JeroenArsenal/JNL/fn_logistics_unLoad.sqf
> +if((_nodeLast == 0) or (_nodeLast == -1))then{
I'm curious about the reason for this change. Old bug?

2020-08-05 03:33 UTC, jaj22 commented on A3-Antistasi/MissionDescription/params.hpp
> +          title = "loot unlocked items";
Seems too context-reliant. "Loot to crate transfers unlocked items"?

2020-08-05 03:37 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
> +	if (_inRange == 0) then { detach _object; deleteVehicle _object };
Other approach would be to assume that if an object is attached to a vehicle it should get cleaned up with it, or not at all. Wouldn't deleting a vehicle-attached box break JNL and probably ACE cargo anyway?

2020-08-05 03:40 UTC, jaj22 commented on A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
> +	call A3A_fnc_Statistics;
Minor point, resourcesPlayer calls statistics now anyway.

2020-08-05 14:20 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_carryCrate.sqf
> +		_crate setVelocity [0,0,0.3];
it sometimes decides to remain floating like a magic trick, this reduced the occurrence by about 70% ish.

2020-08-05 14:24 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
> +		and ({!(_x isEqualTo onjNull)} count attachedObjects _this isEqualTo 0)
that is to check if the player is already carrying stuff, attachedTo wouldnt work as we never attach the player to something, except for JNL loading unconscious units with our revive system

2020-08-05 14:25 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_carryCrate.sqf
> +	player setVariable ["carryingCrate", true, true];
leftover from previous code where i used that variable to block trying to carry a crate already being carried, i changed to attachedTo at a later point and forgot about this one

2020-08-05 14:59 UTC, HakonRydland commented on A3-Antistasi/JeroenArsenal/JNL/fn_logistics_unLoad.sqf
> +if((_nodeLast == 0) or (_nodeLast == -1))then{
to make it remove the action if the all cargo thats left on the vehicle was deleted, ie to make it not break when attached objects are deleted, whit this it clears the action once you try to unload whit nothing on it

2020-08-05 15:00 UTC, HakonRydland commented on A3-Antistasi/MissionDescription/params.hpp
> +          title = "loot unlocked items";
yes i will rephrase it

2020-08-05 15:04 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
> +	if (_inRange == 0) then { detach _object; deleteVehicle _object };
didnt think about ace cargo, JNL wont break now due to the above band aid on JNL, but i will need to test to if its breaks ace cargo

2020-08-05 15:36 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
> +	if (_inRange == 0) then { detach _object; deleteVehicle _object };
tested and ACE cargo dosnt break if loaded cargo is deleted, but yes we could just block attached objects from being deleted

2020-08-05 15:45 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +_position = (getPos _unit) findEmptyPosition [1,10,"Box_IND_Wps_F"];
so far i havent seen it break unless you spam so many it cant find a position anymore and it falls back to its fallback position for spawning, the cooldown is there to help avoid this becoming a reality (or at least a frequent one)

2020-08-05 17:03 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_carryCrate.sqf
> +		_crate setVelocity [0,0,0.3];
Maybe Arma doing some background simulation disable when a crate's been sitting on the ground for a while. If it was 100% success then fair enough, but at 70% it could do with more investigation. Was that hosted or on a DS?

2020-08-05 17:04 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_carryCrate.sqf
> +		_crate setVelocity [0,0,0.3];
ds

2020-08-05 17:07 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +_position = (getPos _unit) findEmptyPosition [1,10,"Box_IND_Wps_F"];
The surrender crate spawning was regularly disastrous when it tried to spawn them inside a building, so I guess that breaks findEmptyPosition and might break it regardless of allocated size. There's not much reason to put the vehicle or arsenal boxes inside a building, although some players don't know that.

I guess it's fine for the moment, as I'm doubting that my suggestion would help anyway.

2020-08-05 17:24 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
I think the best solution is to have a loot transfer check function on the server that takes source object, destination object and clientOwner as parameters, probably with a remoteExecCall to bump the priority and make absolutely sure that there's no interleaving. That function does a local variable check & set on the source object. If that check passes, it remoteExecs back to clientOwner to perform the actual transfer. If not, it can customHint back to the correct client using clientOwner.

Probably best for the transfer check function to just timeout the lock (say 20 seconds) rather than relying on the client-side transfer function to complete successfully.

Ideally you have a single A->B transfer function that can be used for both cases (and probably other stuff later). I'm not sure if the functionality varies much as I didn't read it too hard.

2020-08-05 17:27 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
> +		and ({!(_x isEqualTo onjNull)} count attachedObjects _this isEqualTo 0)
Shouldn't it be doing both checks then? Player doesn't have any objects attached, and box isn't already being carried.

2020-08-05 17:31 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
> +		and ({!(_x isEqualTo onjNull)} count attachedObjects _this isEqualTo 0)
ehh it is checking both

2020-08-05 17:31 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
> +		and ({!(_x isEqualTo onjNull)} count attachedObjects _this isEqualTo 0)
Ah ok, you added the other check.

2020-08-05 18:50 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
so i just tested it the new dupe block system i wrote on test 2 and it seams to be working perfectly

2020-08-05 18:53 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_carryCrate.sqf
> +		_crate setVelocity [0,0,0.3];
i managed to finally duplicate the bug, it claimed simulation was enabled but the when to check i ran enablesimulation on it and it droppe to the ground, dont know if it is just because of the time difference that a refresh made it realize it should be falling or what, but at least arma claimed it was still simulating it

2020-08-09 20:10 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
Either I'm missing something or you only handled the loot-to-container case and not the container-to-vehicle case. It looks like two players could simply use the container-to-vehicle function on the same container to cause duping.

2020-08-09 20:13 UTC, Lazejun commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
Maybe he was missing the words that day, but he asked me to hop on the server and we Tried 3 times to intentionally Duplicate items by Transfering to a Vehicle with no success of Duplication.

2020-08-09 20:18 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
no your right, did try to dupe with crate to vehicle action, but due to how quicker it is to do i was never able to duplicate everything, i belive that to be able to duplicate with it youd need to already be killing the server and have inhuman timing. i can still make another middle man to block based on the crate itself, its definitely a faster check than what the loot to crate has, as it needs to block an whole area (for the crate to vehicle action)

2020-08-10 02:42 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_target setVariable ["LootingNow", true, true];
Amusing point: If you found it was harder to dupe with crate-to-vehicle than body-to-crate, the setVariable lockouts were apparently doing nothing (too low priority, I guess) and the speed of the cargo clearing operations was the limiting factor.

2020-08-11 12:04 UTC, nicksc14 commented
Hi, sorry to bother again but my team found another potential bug. Sometimes when we try to carry a crate, we can't pick it up, and a message says "you are carrying or attached to something" in bottom left corner. But we are not carrying anything. It rarely happens.

2020-10-01 04:33 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
Is this code ever called?

2020-10-01 05:59 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
vanilla medical, calls remove all actions on downed players sometimes, learned that the hard way

2020-10-01 06:03 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
In that case, is line 34 a bug? What's the actionX check for?

2020-10-01 06:12 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
i think its old code, thats now dead, actionX is always nil, dont know why i didnt remove it to be honest

2020-10-01 17:00 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
Ah right, A3A_fnc_transfer and the truckX flagaction only call each other, so potentially you could delete both of those and the condition here and behaviour would be unchanged.

I'm generally unhappy with re-running big piles of action init code just because a player got downed. Seems cleaner and less error-prone to block the relevant actions with an incapacitation check instead. Maybe outside the scope of this PR though.

2020-10-01 17:21 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
yea i feel that falls under a medical rewrite, as for transfer and truckX i would want to know a lot more about it before i delete them. and again would be another pr in it self regardless

2020-10-02 04:27 UTC, jaj22 requested changes
Looking reasonably solid now, just minor points except this one:

Are you sure you want to use the same box as the surrender crates? The actual surrender crates despawn after an hour at the moment (see the postmortem call), and that needs to be addressed before some poor fool tries to use them for moving valuable loot around. Not sure about the best solution.

2020-10-02 04:27 UTC, jaj22 commented on A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf
> +_ace_cargo_canLoad = if (getNumber (configFile >> "CfgVehicles" >> typeOf _object >> "ace_cargo_canLoad") isEqualTo 1) then {true} else {false};
What's this for? It looks like a workaround for a weird bug.

2020-10-02 04:27 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +player spawn {sleep 5; _this setVariable ["BuyCrateCooldown",nil]};
Nicer way to handle cooldowns is usually to store time + cooldown in the variable, and then you don't need the hanging spawn. Not too bothered about this example though as it's client-side and fairly self-contained.

2020-10-02 04:27 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
> +	_unit setVariable ["LootingNow", true, true];
Not sure whether these were left in intentionally (also in the other function), or what case they might be covering that the server-side check isn't.

If that's an open question then maybe you should log the hits.

2020-10-02 04:27 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +if (_money < 10) exitWith {["Loot crate", "You cant afford a loot crate"] call A3A_fnc_customHint};
cant => can't

2020-10-02 04:27 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
>              }
I'll mark this as resolved and write an issue when I have the energy.

2020-10-02 05:43 UTC, HakonRydland commented on A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf
> +_ace_cargo_canLoad = if (getNumber (configFile >> "CfgVehicles" >> typeOf _object >> "ace_cargo_canLoad") isEqualTo 1) then {true} else {false};
ace loading cargo dosnt have the variables like the rest on them by default, results in unloadable crates, this is to prevent that

2020-10-02 06:25 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
> +	_unit setVariable ["LootingNow", true, true];
this was left as a bit of extra precaution, it shouldnt be necessary, if youd like i can remove it

2020-10-02 06:44 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_canLoot.sqf
> +	if (_pos in _lootingPos) then {
with few exceptions, and when it does break it only blokks the area for a few seconds, i dont see it as a problem, but if you have more reliable solutions im all ears

2020-10-02 06:50 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_canLoot.sqf
> +private _lootingPos = missionNamespace getVariable ["LTClootingAreas", []];
still your right no need for set/getVariable here

2020-10-02 06:50 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_canLoot.sqf
> +	_pos spawn {
oversight

2020-10-02 06:51 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +[] spawn A3A_fnc_statistics;
yes it should

2020-10-02 06:52 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
> +player spawn {sleep 5; _this setVariable ["BuyCrateCooldown",nil]};
also gives opportunity for better feedback

2020-10-02 06:58 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
> +	_unlocked = (unlockedHeadgear + unlockedVests + unlockedNVGs + unlockedOptics + unlockedItems + unlockedWeapons + unlockedBackpacks + unlockedMagazines);
you are correct

2020-10-02 06:59 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf
> +		and (attachedTo cursorTarget isEqualTo objNull)
we can give it a try, might have some trouble picking up other items when looking at the crate, but i dont belive it will be a problem seing as it is more accurate

2020-10-02 16:55 UTC, jaj22 commented on A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf
> +_ace_cargo_canLoad = if (getNumber (configFile >> "CfgVehicles" >> typeOf _object >> "ace_cargo_canLoad") isEqualTo 1) then {true} else {false};
Doesn't that suggest that it's an obsolete variable (old ACE version maybe?) and there's no point in copying it around?

2020-10-02 16:58 UTC, HakonRydland commented on A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf
> +_ace_cargo_canLoad = if (getNumber (configFile >> "CfgVehicles" >> typeOf _object >> "ace_cargo_canLoad") isEqualTo 1) then {true} else {false};
if the variable isnt set it uses the config property otherwise it uses whats set on the variable, the other ones have the variable set but not the canLoad one for some reason, dont know why or if it ever actually did worked

2020-10-02 17:02 UTC, jaj22 commented on A3-Antistasi/functions/LTC/fn_canLoot.sqf
> +	if (_pos in _lootingPos) then {
I suppose you could do a distance search (eg. `_lootingPos inAreaArray [_pos, 5, 5]`), given that there's a guarantee of only having one position within 10m. Depends how rarely it screws up though. People wouldn't often be using loot-to-crate twice within 20 seconds anyway.

2020-10-02 17:04 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_canLoot.sqf
> +	if (_pos in _lootingPos) then {
i would say maybe 1/20 times if your unlucky

2020-10-02 18:16 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_canLoot.sqf
> +	if (_pos in _lootingPos) then {
after some testing i found i was wrong, it can be sort of reliably done by dropping the crate then start looting before it drops down, i added your suggestion but with a 1m radius as that should be plenty.

2020-10-02 18:20 UTC, HakonRydland commented on A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
> +	_unit setVariable ["LootingNow", true, true];
i removed it as i dont belive this will ever return true whit the new server side check

2020-10-19 16:02 UTC, jaj22 approved these changes
Looks good to me now.

2020-10-28 18:38 UTC, merged