General parameter saving with individual overrides
official-antistasi-community/A3-Antistasi pull request #1429
Opened 2020-09-05 04:37 UTC by jaj22

### What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
I never liked the parameter saving system in KP Liberation or CO10 Escape because you have to set every non-default parameter each time you change one, which is annoying and extremely error-prone. So I wrote this instead.

The principle is that every parameter defaults to a string named "Default (some value)". If this parameter is unchanged, it uses the value from the save game if there is one, or the default otherwise. If the parameter is changed, it overrides any other source. So you can simply change the params you want to change, and the rest will remain as they were before.

The init order was changed slightly to load saved params before initVar is executed, as initVar depends on some params (eg. gameMode, enabled DLC). Clients (including HCs) are blocked from running initVar until the server has finished loading and publishing params. Shouldn't have any significant impact on loading times.

I also moved the global variables that are currently user-adjustable (spawn distance, civ count, max units) to the same system. This is a bit questionable as it doesn't save much complexity at the moment, but it should simplify things later if we want to expose more adjustable parameters to the in-game UI.

Otherwise, behaviour should be unchanged. Parameter names, variable names and defaults are untouched. Variables that were public or bool-converted before retain those qualities. Inconsistencies, dead parameters and weird names are retained. I could do a cleanup here but I didn't want to confuse the issues.

### Please specify which Issue this PR Resolves.
closes #650

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in singleplayer?
2. [X] Have you loaded the mission in LAN host?
3. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

It's not based on bugfix and so will conflict heavily with that branch without modifications. I don't know what milestone this should go in, so I'm leaving it on unstable at the moment.

There's some spammy debug code in initParams that should be disabled before merging.

### How can the changes be tested?
Fiddle with parameters, start games, check the outcome in the RPT debug spam. Try with new games, old saves and new saves.

2020-12-04 20:12 UTC, CalebSerafin requested changes
* Haven't tested in-game.
* The changes are easy to understand and straight forward 👍 
* However, there are some questions in the review comments where I may not have full understanding:

2020-12-04 20:12 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initParams.sqf
> +			if (_default isEqualType true) then { _val = if (_val == 1) then {true} else {false} };
I'm interested why we might not instead try:
```suggestion
            if (_default isEqualType true) then { _val = _val isEqualTo 1 };
```
As it is faster and is less verbose.

2020-12-04 20:12 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initParams.sqf
> +
This new file is indented with tabs and not spaces.

2020-12-04 20:12 UTC, CalebSerafin commented on A3-Antistasi/MissionDescription/params.hpp
> +	};
This file's indentation has been converted from spaces to tabs.

2020-12-04 20:12 UTC, CalebSerafin commented on A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf
> +if (!allowDLCOfficialMod) then {_disabledMods pushBack "officialmod"};
So we don't need to check the marksman DLC?

2020-12-05 00:42 UTC, HakonRydland reviewed
quick look trough, some initial feedback, still need to go trough it properly and test, but most of it looks good.

2020-12-05 00:42 UTC, HakonRydland commented on A3-Antistasi/MissionDescription/params.hpp
> +	};
why 9999 instead of say -1? theres already some params that push values in that range, and then theres the 9998 hidden in initParams.

2020-12-05 00:42 UTC, HakonRydland commented on A3-Antistasi/functions/init/fn_initParams.sqf
> +		if !("server" in _options)	then { publicVariable (_x select 0) };
_X select 0 is _varname, no need for the select

2020-12-05 00:42 UTC, HakonRydland commented on A3-Antistasi/functions/init/fn_initServer.sqf
> +initParamsDone = true; publicVariable "initParamsDone";
i would have preferred this in initParams.

2020-12-05 00:42 UTC, HakonRydland commented on A3-Antistasi/functions/init/fn_initParams.sqf
> +			private _val = [_paramName, 9998] call BIS_fnc_getParamValue;
what if some one uses 9998 for some reason, unlikely but possible, i find a negative number to be more unlikely.

2020-12-21 21:28 UTC, Bob-Murphy commented
@jaj22 changes requested and merge conflicts

2021-02-13 05:02 UTC, jaj22 commented on A3-Antistasi/MissionDescription/params.hpp
> +	};
This file was 5-space indented, with some chunks of tabs, so needed fixing one way or another. I'll convert it to 4-space.

2021-02-13 05:17 UTC, jaj22 commented on A3-Antistasi/functions/init/fn_initParams.sqf
> +			private _val = [_paramName, 9998] call BIS_fnc_getParamValue;
I thought it was far more likely that someone would need to use the value -1 than 9999 or 9998, given that 10000 is fine. I found it slightly odd that there weren't any negative numbers in there already.

Ideally I'd drop BIS_fnc_getParamValue (because it's daft and can't distinguish the no-value case directly) and write the config check manually, but it's a fair amount of extra code, so I need two reserved values.

2021-02-13 05:26 UTC, jaj22 commented on A3-Antistasi/functions/init/fn_initClient.sqf
> +//	tkPunish = if ("tkPunish" call BIS_fnc_getParamValue == 1) then {true} else {false};
These two can go. Temporary memory aid.

2021-02-13 05:28 UTC, jaj22 commented on A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf
> +if (!allowDLCOfficialMod) then {_disabledMods pushBack "officialmod"};
Lost a line somewhere. Good spot.

2021-02-13 05:42 UTC, jaj22 commented on A3-Antistasi/functions/Save/fn_loadServer.sqf
> +//	["difficultyX"] call A3A_fnc_getStatVariable;
I think I'll just get rid of these too. Not much value in them when they're marked in the save code.

2021-02-13 06:33 UTC, jaj22 commented on A3-Antistasi/functions/init/fn_initServer.sqf
> +initParamsDone = true; publicVariable "initParamsDone";
My inclination would be to move all of these to initServer, but I guess I should make it consistent with initVarDone for the moment.

2021-02-13 07:21 UTC, jaj22 commented
- Merged with unstable
- Applied review requests
- Added some documentation
- Retested on hosted & DS

The params.hpp diff was a disaster but I think I caught everything. Might want a second pair of eyes on that though.

2021-02-13 09:30 UTC, Lazejun commented
The Version still says 2.3 even tho "Unstable" is merged into it, could it be that you used your Repos Unstable which is still at 2.2. ?

Commit just says merged Unstable instead of Upstream/Unstable

2021-02-13 18:57 UTC, jaj22 commented
> The Version still says 2.3 even tho "Unstable" is merged into it, could it be that you used your Repos Unstable which is still at 2.2. ?
> 
> The Commit message just says merged Unstable instead of Upstream/Unstable

I pull remote unstable into my local unstable and then merge it into the branch, so the message will say that. It's just text and I'm pretty sure the merge is correct. I don't know where you're seeing a version 2.3.

2021-02-13 19:02 UTC, Lazejun commented
Woopsi on my End with Github Desktop, ignore :D

2021-02-15 15:42 UTC, HakonRydland approved these changes
justification for changes are aceptable, changes looks good (couldnt spot any mistakes in params.hpp since you asked about it specifically)

2021-02-17 12:15 UTC, CalebSerafin approved these changes
All previous concerns accounted for.

2021-02-23 19:25 UTC, jaj22 commented
Added parameter and filtering for Art of War DLC. Supersedes #1729.

2021-02-23 20:12 UTC, Bob-Murphy commented
@jaj22 please create a second PR from your branch into test_branch_2021_16_2_06_43
Thank you

2021-02-27 09:59 UTC, merged