Add more Item sorting | Add Radiobackpack Category
official-antistasi-community/A3-Antistasi pull request #1445
Opened 2020-09-10 19:55 UTC by Lazejun

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
**Why?:**
The less unusable items that spawn in loot the higher the chance to get usefull items.

Added a new Cateogory of Backpacks for TFAR-Radios/Radios that are Compatable with it.
They were Defined in **allBackpacksEmpty** before.
Added Side Filtering for Radiobackpacks (You only get Radios of Your own Side in loot)
Removed Radios that are not usuable due to Side Restriction between Radios in TFAR.
Added allRadiobackpacks in Fn_Loot in the Array used for **lootDevice**. (Loot Device will be 1 Items without DLCs enabled).
---------> Didn't Add Contact DLC Radios to it due to only working in TFAR Beta, not Stable.
**allRadiobackpacks**

Added Side Filtering for Item allRadios ------> Only Radios of your Side apear in Loot.
Removed Radios that are not usuable due to Side Restriction between Radios in TFAR.
**allRadios**

remove rhsusf_Rhino" from **lootNVG** due to just being a Headmount not NVG

Added Side filtering for **allUAVTerminals**.
Removed unaccessable and DLC UAV Terminals ------> Civ (Laws of War DLC), Csat (Never player Faction), LDF (Contact DLC) cause they are not needed.

### Please specify which Issue this PR Resolves.
closes #731 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?

Steps: All Modsets:
UAVTerminal Filtering:
Get ingame 
```sqf
allUAVTerminals
``` 
It should return only 1 Entry which is either "B_UavTerminal" for Bluefor and "I_UavTerminal" for Greenfor.

Radio Filtering:
With TFAR
```sqf
allRadios
```
It should only return "tf_anprc148jem" for Green and "tf_anprc152" for Blue.

Radiobackpack sorting:
With TFAR:
```sqf
allRadiobackpacks
```
and
```sqf
lootDevice
```
It should only Return side fitting Equipment, Device filtering worked before, i only added Radiobackpacks to it, to also Increase the Chances for them to spawn. (The Parameter is also 2 by Default).
********************************************************
Notes: Having Radiobackpacks actually apear in Loot by default would make #720 being turned off by default more Logical as when it first came around.

Since lootBackpack USED to Contain the Radiobackpacks but Default Value for them is 0 so they dont spawn.

2020-09-18 04:26 UTC, jaj22 reviewed
Submitted as comment because I don't really know what I'm doing.

2020-09-18 04:26 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +};
So this is a bit interesting. Removing items from the radio category when they are, in fact, radios. I guess it's valid if the categories are purely for rebel purposes and these items aren't usable for the defined purpose. I do worry a bit that we might need categories for other purposes in the future.

If the purpose is just to get them out of crates, the soft option would be to create a tfarModCompat in functions/Templates, and delete this stuff from lootItem/lootDevice there. Not sure what the right option is at the moment though.

2020-09-18 04:26 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +allUAVTerminals deleteAt (allUAVTerminals find "B_UavTerminal");
These appear to get their side locking from itemInfo >> side, although maybe there's some hardcoded stuff underneath, especially if the LDF version doesn't work the same as the standard greenfor terminal. Short list anyway, and probably won't change, so it doesn't much matter.

Similar point about whether you want to delete these from the category or just from loot though.

2020-09-20 18:15 UTC, Lazejun commented
Ok Updated the PR with your Suggestions, Used the Category Overrides to remove the Rhino Headmount instead of removing it from the other Categories.

With the LDF-UAV Terminal i came up with the Solution of i dont care, it is ofcourse the same but Idea was so Blue and Green both only have 1 UAV terminal which would make the chance to Unlock sort of "Fairer" in each Game but its only if Enoch is enabled in the end it doesent matter that much.

Removed the 3CB Faction Radios from Cateogory overrides due to them not working with TFAR anymore, 3CB BAF Radios work fine.

2020-10-01 03:37 UTC, jaj22 approved these changes
Looks good.

2020-10-25 12:46 UTC, Lazejun commented
So i was curious how well the Radio Filtering would work with TFAR BETA and found out that it changed:
"tf_guer_radio_code"
 to 
"tf_independent_radio_code"

And also leaving (_encrypt isEqualTo "") in leads to Issues as it still giving Radios that have no Encryption set so i removed that aswell.

I also got rid of Equipment overrides for the BackpackRadios and let used the Filtering for Encryption to filter from AllBackpacksEmpty.
The only new Issue would be that now Unfiltered/Left alone Radios remain in BackpacksEmpty.

I will update the PRs Description in a bit with the New stuff, cause most is now taken care by Autodetection.

2020-10-26 06:27 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +private _encryptRebel = if (teamPlayer == west) (teamPlayer == west) then { ["tf_west_radio_code"] } else { ["tf_guer_radio_code" or "tf_independent_radio_code"]; };
Looks like the condition got doubled up, and the array at the end should have a comma in the middle rather than an `or`, unless I'm missing something.

2020-10-26 06:29 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +private _encryptRebel = if (teamPlayer == west) then { ["tf_west_radio_code"] } else { ["tf_guer_radio_code" or "tf_independent_radio_code"] };
Broken array here too.

2020-10-26 06:29 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +private _encryptRebel = if (teamPlayer == west) (teamPlayer == west) then { ["tf_west_radio_code"] } else { ["tf_guer_radio_code" or "tf_independent_radio_code"]; };
Never mind, already fixed.

2020-10-26 06:40 UTC, jaj22 requested changes

2020-10-26 06:40 UTC, jaj22 commented on A3-Antistasi/functions/init/fn_initVarCommon.sqf
> +	"RebelUniforms", "CivilianUniforms", "BackpacksEmpty", "BackpacksTool", "BackpacksStatic", "BackpacksDevice", "BackpackRadio", "CivilianVests", "ArmoredVests", "ArmoredHeadgear", "CivilianHeadgear",
Should probably be BackpacksRadio rather than BackpackRadio, to match the others.

2020-10-26 06:40 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +allBackpackRadio = [];
Already done by initVarServer line 185.

2020-10-26 06:40 UTC, jaj22 commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +};
I think allRadios matters slightly for vanilla too, so this filter shouldn't be applied unless tfar is running.

2020-10-26 20:12 UTC, Lazejun commented on A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
> +};
I was actually thinking about that, cause i noticed it Filtered "ItemRadio" away without TFAR, but i wasn't sure if AllRadios was used anywhere else than Loot, cause we check directly for "ItemRadio".

The has TFAR Check wouldnt hurt.

2020-10-26 20:13 UTC, Lazejun commented on A3-Antistasi/functions/init/fn_initVarCommon.sqf
> +	"RebelUniforms", "CivilianUniforms", "BackpacksEmpty", "BackpacksTool", "BackpacksStatic", "BackpacksDevice", "BackpackRadio", "CivilianVests", "ArmoredVests", "ArmoredHeadgear", "CivilianHeadgear",
Yeah it would make sense for Consistency.

2020-10-26 20:25 UTC, Lazejun commented
Updated the PR, Changed Backpack to Backpacks, Removed the unneeded empty Array, 
Added the TFAR check which is funny cause apparently our (HasTFAR) uses a Variable that's Common on Both TFARs.

2020-11-20 04:58 UTC, jaj22 approved these changes
All looks good now.

2020-11-23 21:04 UTC, merged