fixed two errors with mission request
official-antistasi-community/A3-Antistasi pull request #1456
Opened 2020-09-15 19:33 UTC by HakonRydland

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    missionRequest can be called by functions at init, and the boss is not defined yet, this holds those untill theBoss is defined. in addition auto mission requests when all missions exists it exits out now

### Please specify which Issue this PR Resolves.
closes #1455

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2020-09-15 22:45 UTC, jaj22 requested changes

2020-09-15 22:45 UTC, jaj22 commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +if ((isNil "theBoss") || (theBoss isEqualTo objNull)) exitWith {
These need to be written as if (isNil "theBoss" || { isNull theBoss}), because SQF doesn't do lazy evaluation and so the second part will break if the first part is true.

Concept also looks rather horrible and could do with a look at var init timings and mixed call/spawn use. I guess it's ok as a temporary fix for 2.3.1.

2020-09-16 07:52 UTC, HakonRydland commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +if ((isNil "theBoss") || (theBoss isEqualTo objNull)) exitWith {
yea you are right, the nil case came from the save loading i think, that should now be fixed, as for the oter cases it exits out now, not exactly ideal in my opinion but its better than nothing( this is purely to avoid errors so auto requests still go trough)

2020-09-18 03:04 UTC, jaj22 approved these changes
Could have been done without the third parameter, I think. The function is either called for a real player or has no text output, so you could pass a player object if feedback is required, or objNull otherwise.

Should work as-in and isn't too horrible, so I'll leave it up to you whether to polish it or not.

2020-09-19 17:08 UTC, merged