Switched the aggro-capture behaviour, low aggro now wins the map
official-antistasi-community/A3-Antistasi pull request #1553
Opened 2020-10-17 19:09 UTC by wurzel0701

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Currently the most aggressive faction wins the map as their attacks are way more frequent to fight the player advancing. This however leads to the more fought faction (mostly Occupants) to stop the other faction (mostly Invaders).

Now there is a chance for the attacked faction to defend the attack and counter attack the attacking force, dependent on aggro ratio between them. Lower aggro increases chance of winning attacks/defending attacks.

In the end the faction which is mostly inactive, should take over the map quickly until they are actively fighting the rebels and therefor get active.

### Please specify which Issue this PR Resolves.
None opened

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [X] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
```
[[50, 60], [0, 0]] spawn A3A_fnc_prestige;
[] spawn 
{
    while {true} do 
    {
        [Occupants] spawn A3A_fnc_rebelAttack;
        sleep 50;
        [Invaders] spawn A3A_fnc_rebelAttack;
        sleep 50;
    };
};
```
Execute as server and watch what is happening
********************************************************
Notes: Idea is only a day old, not sure how the balance is in the end

2020-10-21 17:28 UTC, Bob-Murphy commented
Makes sense as the faction with the higher aggro has to deal with the rebels and therefore is kinda busy.
@jaj22 @HakonRydland @CalebSerafin 
We talked about that in the last meeting and everybody had some time thinking about it. Any input?

2020-10-22 03:00 UTC, jaj22 commented
So this is essentially turning any simulated gov vs inv attack into an aggro-based coinflip, which probably does remove any factors except aggro from the gov vs inv progression, with the exception that the rate of progression (in the aggro-dependent direction) will still depend on mission completion. If you complete a lot of missions, gov vs inv progression will slow. If you fail a lot of missions, it'll be fast. 

I don't really get it. If you want gov vs inv attacks to be a pure aggro-dependent coinflip then it seems a lot cleaner to implement that early in the function rather than tacking it onto the simulation results. Also the previous logic mostly worked aside from the mission failure problem, and that's still kinda weird.

Unintentional stuff:
- If I'm reading this correctly, the counter-attack target will almost always be an airfield (the attack origins are airfields, it uses nearest position, and 4-easy-target attacks are almost never used for gov vs inv), so those will be flipping very frequently.
- timingCA doesn't get incremented in the single target counter-attack case.

2020-10-22 06:31 UTC, wurzel0701 commented
> Unintentional stuff:
> 
>     * If I'm reading this correctly, the counter-attack target will almost always be an airfield (the attack origins are airfields, it uses nearest position, and 4-easy-target attacks are almost never used for gov vs inv), so those will be flipping very frequently.
> 
>     * timingCA doesn't get incremented in the single target counter-attack case.

Good calls, fixed, counter attacks on large attacks will now target, the outpost or airport nearest to the counter attacking faction carrier marker

> Also the previous logic mostly worked aside from the mission failure problem, and that's still kinda weird.
Care to elaborate that? Cause I dont think the logic is weird at all

> If you complete a lot of missions, gov vs inv progression will slow. If you fail a lot of missions, it'll be fast.
It is actually the other way around. If you copy paste the Occupants attack command from the testing command, and have them attack multiple times while Invaders attack only once per round, you will see, that Occupants are losing even quicker. Due to the inverted win chance to attack ratio, Occupants are losing most of their attacks and the Invaders are advancing without even doing much.

As a calculation example.
CSAT Aggro: 0
NATO Aggro: 50
These should be relatively normal values, CSAT is chilling as they are not attacked, NATO takes a few beatings from rebels

CSAT Win/Defend chance: 75%
NATO Win/Defend chance: 25%
So out of 4 attacks, CSAT wins 3, while NATO only wins 1. During a single attack, there is a high chance CSAT wins/defends it while NATO loses it

CSAT attack frequency: 1 attack every 2 hours
NATO attack frequency: 2 attacks every 2 hours
Lets pump this even more up, due to missions they attack 3 times in 2 hours.
Out of their 3 times, NATO loses 2 attack, while CSAT wins their one attack on average. After two hours CSAT took 2 locations on average with the current values. The more NATO attacks, they more the lose.

On the other side, winning more missions, will decrease NATO attack frequency, therefor keeping CSAT out of play longer. This is intented for smaller player groups or even SP, so they have a easier start until they have to fight both factions,

2020-11-20 04:55 UTC, jaj22 commented
Not directly related to this PR, but the suggestion that missions changing attack rate benefits small groups worries me: If that's currently true, it's only because the community servers play the game as CTI. If the community chose to complete missions, they'd slow attacks far more than a small server could. Antistasi rookies really struggle at missions too, IME.

I see you did pull out the duplicated marker-flipping code, which is good, but I'd still prefer having the gov vs inv attack direction decided early rather than in the simulation code. It's simpler, and not spawn-dependent. Currently, if you keep the gov vs inv engagement area spawned, there will be no counter-attacks and captures will follow the previous pattern.

2020-11-27 11:23 UTC, Bob-Murphy commented
@wurzel0701 Any comment to the last paragraph by John?
Adaptation maybe useful?

2021-01-13 01:15 UTC, Bob-Murphy commented
Please create an issue for that PR.
Thank you.

2021-02-16 15:35 UTC, wurzel0701 commented
Maybe we need to adapt/delete the attack timer rewards from missions. However occupants missions are way more common, so they would only slow them down, not the invaders. And if that is the way to get the community to play it along the intended way then so be it.

Fixed the counter order and such, should be good to go now

2021-02-24 06:04 UTC, jaj22 requested changes
I'd be slightly concerned that this accelerates invader capture rate *too* much in common cases, but whatever. More factions, more fun.

A problematic side-effect is that invaders don't seem concerned about flying over multiple kilometers of government territory, so you may want to kill gov/inv cross-spawning if that's not being addressed.

2021-02-24 06:45 UTC, wurzel0701 commented
I made a stupid mistake, this is the wrong branch I am pulling from (my fork, not the official one)

Might need to redo this PR

Added an issue for the side dependant spawning

2021-02-24 06:46 UTC, wurzel0701 commented
Cant change the branch I am pulling from, so closing this PR

2021-02-24 06:46 UTC, closed without merging