fixed broken salvage rope, improved functionality
official-antistasi-community/A3-Antistasi pull request #1570
Opened 2020-10-29 18:13 UTC by HakonRydland

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: last fix for the salvage rope damage problem introduced a disconnect between the player and the vehicle, this made it impossible to recover the cargo in the salvage mission, the other actions was also partially broken as well. i fixed this and improved a oversight of the original design that prevents you from re recovering cargo if say the boat is sunk before you reach shore
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2020-11-20 04:00 UTC, jaj22 requested changes
General implementation notes:
- I don't think you need two separate rope variables now that WinchHelper is sufficient to distinguish between the two cases. WinchRopeUnit is also surplus now for the same reason. Might be handy for debugging but shouldn't be used in conditions.
- Consider using adjustRope to clear up the rope & helper in cases where the player dies or moves too far away. Currently the player can end up with a permanent helper if the boat is deleted while they're on the rope, for example.
- canXXX functions could do with more exitWith.
- Global function names should probably be tagged to avoid stomping the namespace.

2020-11-20 09:48 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +		player != _cargo && _cargo getVariable ["SalvageCrate", false] && player distance _cargo <= 13 && ((ropeAttachedTo _helper) getVariable "WinchRopeUnit") == player && (getPosASLW _cargo#2)<0;
was originally a future proofing but as it is whitelisted we can just not add it to players

2020-11-21 18:35 UTC, jaj22 requested changes
Some extra bits, also expecting the orphaned helper fix.

2020-11-21 18:35 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    _vehicle setVariable ["WinchHelper",nil,true];
Should be removing WinchHelperObj from the player as well here, and probably move the WinchRope setVariable up here. As the rope+helper delete is done from two places (three if you add it to adjustRope), you may want to pull that out to a worker function.

2020-11-21 18:35 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if !(isNil {_vehicle getVariable "WinchRope2"}) exitWith {false};
Not necessary because WinchHelper will be nil if WinchRope2 exists.

2020-11-21 18:35 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _attachedPlayer) exitWith {false}; //winch not deployed
Not necessary because `alive objNull` returns false, although it's arguably clearer.

2020-11-21 19:31 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if !(isNil {_vehicle getVariable "WinchRope2"}) exitWith {false};
removed, attachRope now reuses WinchRope variable

2020-11-21 19:31 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _attachedPlayer) exitWith {false}; //winch not deployed
still needed to prevent stow action when cargo is being retrieved (prevent stowing during ropeAttach)

2020-11-21 19:31 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    _vehicle setVariable ["WinchHelper",nil,true];
new cleaner function created, added cleaning to adjustRope when vehicle is destroyed when it ends

2020-11-22 18:27 UTC, jaj22 requested changes

2020-11-22 18:27 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _attachedPlayer) exitWith {false};//this is the case when retrieving cargo
This is also true for dead->deleted players, so you need to do this check on the helper rather than the attachedTo.

2020-11-22 18:27 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _rope) exitWith {};
This is only possible if the vehicle is deleted (destroyed?), correct? If so, could maybe make that check more explicit.

If that's not true then you'd need to move the WinchRope nil setVariable up here.

2020-11-22 18:27 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (!alive _vehicle) then { [_helper, _vehicle] call A3A_SR_cleanHelper };
This doesn't cover all orphan cases. For example, you could break the rope by teleporting, and then the boat could be despawned.

My inclination is to delete both the helper *and* the rope at this point, provided that the helper still exists and regardless of the condition of the vehicle. If the winch is now attached to a crate, the helper won't exist but we don't want to clear the rope.

If you want to leave trailing ropes on breakage then that makes things tricky because you potentially have two rope-only cases to distinguish between.

2020-11-22 18:27 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +        [player] spawn A3A_SR_attachRope;
Does this one need to be a spawn? According to the addAction docs this is run as scheduled code anyway, and in extreme cases the additional spawn might delay so that the canAttach conditions are no longer valid.

2020-11-22 18:31 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _rope) exitWith {};
its the case when destroyed or deleted yes

2020-11-22 19:48 UTC, HakonRydland reviewed
could you clarify the on the unresolved comments.

2020-11-22 19:48 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _attachedPlayer) exitWith {false};//this is the case when retrieving cargo
not for dead, but for deleted, fixed by checking isNull _helper

2020-11-22 19:48 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    player setVariable ["WinchHelperObj", nil];
fixed

2020-11-22 19:48 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (!alive _vehicle) then { [_helper, _vehicle] call A3A_SR_cleanHelper };
if the rope breaks, the helper is cleaned when the rope is stowed, if the boat despawns then the its no longer alive and adjustRope will clean up the helper. 

Ropes are cleaned automatically if the parent is no longer alive, so only need to manually destroy it if we are "Stowing" the rope.

in conclusion worst case you have a helper until the boat is destroyed/despawned or someone stows the rope

2020-11-22 19:48 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +        [player] spawn A3A_SR_attachRope;
no, nether would adjustRope, fixed

2020-11-22 20:28 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (!alive _vehicle) then { [_helper, _vehicle] call A3A_SR_cleanHelper };
No, worst case is that you break the rope and then later the boat is despawned. The boat's still alive at the point the rope is broken, so the helper is never removed.

2020-11-22 20:28 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull (_vehicle getVariable ["WinchRope", objNull])) exitWith {false}; //winch deployed
Yeah, misread.

2020-11-22 20:31 UTC, jaj22 commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _rope) exitWith {};
My issue is that it doesn't explicitly set WinchRope to nil in this case, so it's only correct if the boat is destroyed. If there are potential edge cases where the boat isn't destroyed, you should clear WinchRope.

2020-11-22 21:24 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (!alive _vehicle) then { [_helper, _vehicle] call A3A_SR_cleanHelper };
yea missed this one, should be fixed now.
now when player dies or is disconnected from the rope, helper is deleted. helper is also deleted if the vehicle is destroyed when the player has the rope.

2020-11-22 21:24 UTC, HakonRydland commented on A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
> +    if (isNull _rope) exitWith {};
no edge cases as these sets winchRope to nill by adjustRope

2020-11-23 04:31 UTC, jaj22 approved these changes
Looks solid now. As you've tested a decent range of cases it should be good for merging.

2020-11-23 19:40 UTC, Bob-Murphy commented
@HakonRydland  no issue assigned

2020-11-23 21:05 UTC, merged