New jnl
official-antistasi-community/A3-Antistasi pull request #1588
Opened 2020-11-16 19:47 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information: The new logistics system to replace JNL, this system changes JNL base behavior two accommodate for a multitude of different sized cargo without having to redefine any nodes. in addition you can now load weapons alongside regular cargo. the current largest cargo uses 7 cargo node and is the zu-23 static (unable to actually load into anything rn, due to only current vehicle with capacity being vanilla NATO flatbed. in addition to this, the mountable weapons are reenabled, so you can now load and use most statics (if not all) in vehicles as technicals, this includes mobile mortar, mobile AA/AT and HMG
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: preferable dedicated server, use all available options of the system and generally try to break it, its only use will be trough the action added with ``A3A_fnc_logistics_addLoadAction;`` 

********************************************************
Notes: when we get around to doing MIE the only change will be how the nodeInit is done, as then it will be built in templates, then distributed by nodeInit from te server only, in contrast with now where they are run on each client localy.

2020-11-17 07:53 UTC, wurzel0701 reviewed
There are two different inputs for A3A_fnc_logistics_addLoadAction
surrenderAction.sqf
AIVEHinit.sqf
createAIAirplane.sqf
createAIOutpost.sqf
createAISite.sqf
use Object call A3A_....
while
flagAction.sqf
AIVEHinit.sqf
spawnCrate.sqf
use [object] call A3A_...
From the looks of it, the array is the right input, but maybe I am missing something

2020-11-17 07:55 UTC, wurzel0701 commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +	[1, "Logistics nodes not initialized", "fn_logistics_addLoadAction.sqf"] call A3A_fnc_log;
Wouldnt it be better to initialize the vehicle hardpoints instead of aborting?
Or is this not possible?

2020-11-17 07:57 UTC, wurzel0701 commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +	if (({(_X#0) isEqualTo _model } count logistics_weapons) isEqualTo 0) then {_nonSupportedStatic = true};
To not count the whole array, you can do
```logistics_weapons findIf ((_x#0) isEqualTo _model) == -1```
This will return -1 and result in true if nothing is found, however it will abort the search as soon as it finds the first matching element

2020-11-17 08:01 UTC, wurzel0701 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +        if (_actions findIf {(_x#0) isEqualTo _loadText} != -1) exitWith {};
I am not sure how fast sqf is with comparing texts (maybe the just hash it, but you know, BI...

I would add a variable to the object itself, either holding the load action or the load state

2020-11-17 08:05 UTC, wurzel0701 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
> +	[parseText _text] remoteExec ["hint", crew _vehicle]; //parse text dont work with chat
From my experience most vehicles are empty when you load/unload stuff, personally I have never seen that message. A search for nearby vehicles might be a good idea

2020-11-17 11:07 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
> +	[parseText _text] remoteExec ["hint", crew _vehicle]; //parse text dont work with chat
can you expand on the search for nearby vehicles part, as for the hint crew, i definitely have before been in example driver while someone else loads the crate, regardless this is actually one that is virtually untouched from the original, only containing a fix for the chat message being done with parse text, this is the now hint to the crew.

2020-11-17 11:17 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +        if (_actions findIf {(_x#0) isEqualTo _loadText} != -1) exitWith {};
a set/getVariable would be a bit faster, but not drastically, and with how few times this will actually be run relatively i dont find the extra clutter in the players/vehicles variable to be worth it.

2020-11-17 11:18 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +	if (({(_X#0) isEqualTo _model } count logistics_weapons) isEqualTo 0) then {_nonSupportedStatic = true};
done

2020-11-17 11:24 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +	[1, "Logistics nodes not initialized", "fn_logistics_addLoadAction.sqf"] call A3A_fnc_log;
the nodes are defined during initClient currently, when we move to MIE it will be defined in templates/initServer then publicVariabled, in either case they should be defined long before we try to add a action to any object, and for JIP it dosnt need the data yet. i have not encountered a single instance of it having to abort as of yet. however if youd like i recommend looking for the logged line in Cinders server logs to verify, there should be more than enough data there to be certain.

TL;DR it dosnt even actually need that line, it was left in to find out if it ever would actually would fail, which it hasnt afaik.

2020-11-17 17:19 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
> +	[parseText _text] remoteExec ["hint", crew _vehicle]; //parse text dont work with chat
customHint takes precompiled text. If you do this, the client will never see the hint there.

2020-11-17 17:28 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf
> +	[parseText _text] remoteExec ["hint", crew _vehicle]; //parse text dont work with chat
```suggestion
	["logistics_objtMass_owner",parseText _text] remoteExec ["A3A_fnc_customHint", remoteExecutedOwner];
	["logistics_objtMass_crew",parseText _text] remoteExec ["A3A_fnc_customHint", crew _vehicle];
```
you can change the header text, as in this case it is only used as an identifier.

2020-11-17 17:47 UTC, CalebSerafin requested changes
Could `A3-Antistasi/functions/Logistics/adding stuff to the new JNL.docx` have its content moved to a simple text file? It would drastically reduce the file size, and be viewable in all code editors.

2020-11-17 17:54 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_initMountedWeapon.sqf
> +	_weapon removeEventHandler ["Fired", _idRecoil];
These lines are indented with tabs.

2020-11-17 17:59 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_generateNodes.sqf
> +	_newArray pushBack [1, _x, []];
This new file has Ln31 and Ln32 indented with spaces and the rest with tabs.

2020-11-17 18:01 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +
These lines are indented with tabs.

2020-11-17 19:54 UTC, CalebSerafin reviewed
Okay, what I flag was sorted. Converting Tabs to spaces in functions.hpp, I guess it was going to have to happen eventually, current PRs will just need to fix their minor merge conflicts if they removed/renamed a function.

2020-11-17 19:55 UTC, CalebSerafin approved these changes

2020-11-20 16:49 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +    if (logistics_weapons findIf ((_x#0) isEqualTo _model) isEqualTo -1) then {_nonSupportedStatic = true};
Wrong bracket type on the findIf. Does this actually work?

2020-11-20 17:02 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_getVehicleNodes.sqf
> +private _return = -1;
Shouldn't this be an empty array to avoid type errors in the calling function?

2020-11-20 17:16 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +    if (logistics_weapons findIf ((_x#0) isEqualTo _model) isEqualTo -1) then {_nonSupportedStatic = true};
think i forgot to test with loading weapons after the change, should definitely not work, fixed

2020-11-20 17:16 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_getVehicleNodes.sqf
> +private _return = -1;
old leftover from JNL, negative int were used a lot to note invalid something, as for the type errors, where its used theres either been confirmed to have valid nodes or theres a type check following it, see logistics_canLoad ln 68.
so it should be fine, unless i missed something

2020-11-21 15:47 UTC, HakonRydland commented
> There are two different inputs for A3A_fnc_logistics_addLoadAction
> surrenderAction.sqf
> AIVEHinit.sqf
> createAIAirplane.sqf
> createAIOutpost.sqf
> createAISite.sqf
> use Object call A3A_....
> while
> flagAction.sqf
> AIVEHinit.sqf
> spawnCrate.sqf
> use [object] call A3A_...
> From the looks of it, the array is the right input, but maybe I am missing something

overlooked this comment, sry. you are right it should have an array with a object and optionally a string

2020-11-21 15:52 UTC, HakonRydland commented
as a side note, passing a object in place of a array will work fine too as.
[player] params ["_player", "_thisIsNil"];
returns: [player, any]

and
player params ["_player", "_thisIsNil"];
return: [player any]

ie its passed as the first element

2020-11-23 22:46 UTC, Bob-Murphy commented
@HakonRydland merge conflicts

2020-11-28 21:41 UTC, jaj22 commented
Not fully reviewed yet, only did a bit of syntax checking.

2021-01-13 01:15 UTC, Bob-Murphy commented
Please create an issue for that PR or make it part of a project.
Thank you.

2021-01-14 12:29 UTC, HakonRydland commented
> Please create an issue for that PR or make it part of a project.
> Thank you.

issue created

2021-01-17 15:50 UTC, CalebSerafin commented
7 Liner for myself.
* [ ] Indentation & Headers
* [ ] Naming Conventions & Grammar
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic

2021-01-18 13:53 UTC, CalebSerafin requested changes
Okay, everything so far looks pretty solid. There are a few comments below that can be changed before I do the logic part of the review. I decided to save the trees, so instead of writing out my comments as a backup, I made an [Excel Spreadsheet](https://1drv.ms/x/s!AhRKsW_EtNcb2lrWnPAuTtV97Tcs?e=15wQ6B).
***
17- I noticed some error codes, could use macros for those. However, this isn't too necessary as we don't have an enumeration system yet.
***
19- Is it possible to prefix logistics_attachmentOffset, logistics_vehicleHardpoints, logistics_weapons, and logistics_coveredVehicles with `A3A_`?
***
The logic review should come in 1-2 days.

2021-01-18 14:26 UTC, HakonRydland commented on A3-Antistasi/functions/CREATE/fn_createAISite.sqf
>    	_box = CSATAmmoBox createVehicle _markerPos;
done, side note: this function is disconnected

2021-01-18 14:33 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
> +private _bbv = (boundingBoxReal _vehicle select 0 select 1) + ((boundingCenter _vehicle) select 1);
those vowel's are gonna cost you ;)

2021-01-18 14:45 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/fn_logistics_getVehCapacity.sqf
> +    0. <Object> The vehicle you want to know the cargo capacity of
why i like the index of the params in the header, i find its easier to read for potential unexperienced users.

2021-01-18 14:51 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_canLoad.sqf
> +    private _isBlocking = call {
none, i probably was exhausted when writing that :)

2021-01-19 17:20 UTC, CalebSerafin requested changes
Solid code. Comments are mostly optimisation, one array reference possible problem (49).
***
The Excel spreadsheet has been updated to newest comments.

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +        if (_actions findIf {(_x#0) isEqualTo _loadText} != -1) exitWith {};
42- In addition to above
```suggestion
        if (_loadText in _actionNames) exitWith {};
```
This is lightning fast (might be faster than getVariable at 0.8 microseconds). I don't know how SQF implements it in C++.

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +{_actions pushBack (_object actionParams _x)}forEach actionIDs _object;
41- Could simplfy to the following, which might be slightly faster.
```suggestion
private _actionNames = (actionIDs _object) apply {(_object actionParams _x)#0};
```
In rest of code omit `#0`.

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_canLoad.sqf
> +if !(_cargoUnits isEqualTo []) exitWith {-9};
45- This can be optimised to avoid searching after a sign unit has already being found to be blocking the way.
```suggestion
if !(_fullCrew findIf {_x#2 in _seats} isEqualTo -1) exitWith {-9};
```

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_generateHardPoints.sqf
> +};
46- Instead of making a negative diametre and radius, we could use vectorDiff.
```suggestion
private _diameter = 0.8;
private _radius = (_diameter/2);// get some distance from walls
private _plane = _planeStart vectorDiff _planeEnd;

private _nodeArray = [];
private _node = _planeStart vectorDiff [0,_radius,0];//first point
while {(_radius*1.5) < (_plane#1)} do {
    _plane = _plane vectorDiff [0,_diameter,0];
    _nodeArray pushBack _node;
    _node = _node vectorDiff [0,_diameter,0];
};
```

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_generateHardPoints.sqf
> +A3A_Logistics_nodeArray = _newArray;
47- This could be optimised and shortened.
```suggestion
A3A_Logistics_nodeArray = _nodeArray apply {[1, _x, []]};
```

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_initMountedWeapon.sqf
> +}];
51- It might be better if some values were hard-coded into the delegate so that they do not need to be processed every shot fired.
```suggestion
//credits to audiocustoms on youtube (Cup dev) for the concept and CalebSerafin for optimisation.
private _idRecoil = _weapon addEventHandler ["Fired", compile (' 
    params ["_weapon"];
    private _vehicle = attachedTo _weapon;
    private _weaponDir = _weapon weaponDirection currentWeapon _weapon;
    private _appliedForce = (_weaponDir vectorMultiply -' + (str _fireForce) +');
    _vehicle addForce [_appliedForce, ' + (str (_weapon getVariable ["AttachmentOffset", [0,0,0]])) + '];
')];
```

2021-01-19 17:20 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
> +    _weapon
52- This could be shortened.
```suggestion
    A3A_logistics_weapons findIf {_x#0 isEqualTo _model} > -1
```

2021-01-19 17:48 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_getCargoNodeType.sqf
> +    if ((_x#0) isEqualTo _model) exitWith {_size = +(_x#3)};
safety, i never use reference to the data structure to ensure its never modified

2021-01-19 18:04 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_getCargoNodeType.sqf
> +    if ((_x#0) isEqualTo _model) exitWith {_size = +(_x#3)};
Is `A3A_logistics_attachmentOffset#any#3` not a scalar for size? All the common basic types (String, Scalar, Boolean,..probably some more but need to test) always copy the value.

2021-01-19 18:27 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
> +    A3A_logistics_weapons findIf {_x#0 isEqualTo _model} > -1
I think Travis is throwing a hissyfit about this line. It does not need a semi-colon, but maybe add a semi-colon to the end.

2021-01-19 18:29 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
> +    A3A_logistics_weapons findIf {_x#0 isEqualTo _model} > -1
not it apparently

2021-01-19 18:44 UTC, CalebSerafin approved these changes

2021-01-19 20:36 UTC, merged