Multilanguage support
official-antistasi-community/A3-Antistasi pull request #1602
Opened 2020-11-26 08:21 UTC by mimizid

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
>  Multilanguage support:
> 1. Hint (A3A_fnc_customHint \ hintC)
> 2. Actions (addAction)
> 3. Chat (groupChat\sideChat\globalChat)
> 4. cutText
> 5. bis_fnc_dynamicText
> 6. Dialog Menu (only ctrlSetTooltip)
> 7. Missions (A3A_fnc_taskUpdate\BIS_fnc_taskCreate\BIS_fnc_showNotification)
> 8. Markers (except hq, carrier)
> 9. Brifing (headers, removed "format")

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in singleplayer?
2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (added a lot of lines so I could have missed the error)

********************************************************
Notes:
Added multilingual support for everything that was patient enough.

P.S. In the future I will add Russian localization and rebuild Stringtable.xml (there are duplicates)

2020-11-27 11:15 UTC, Bob-Murphy commented
Hi mimizid,
thank you very much for your PRs!
As we currently have a lot of stuff in the pipeline it can take some time to get everything properly reviewed.
For the russian translations, we also will let somebody with russian capabilities check your translations as we have a general 4-eye-principle.
We will certainly use your changes even though we might ask for slight adaptations.
Nevertheless, well done and thank you.

2021-01-11 17:05 UTC, CalebSerafin commented
7 Liner for myself.
* [ ] Indentation
* [ ] Naming Conventions & Spelling
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic

2021-01-11 19:46 UTC, CalebSerafin commented
## The Supreme Progress Chart
* [ ] 1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\briefing.sqf
* [ ] 2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\dialogs.hpp
* [ ] 3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\onPlayerRespawn.sqf
* [ ] 4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\JeroenArsenal\JNG\fn_garage_garageVehicle.sqf
* [ ] 5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\JeroenArsenal\JNL\Actions\fn_logistics_addActionLoad.sqf
* [ ] 6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\JeroenArsenal\Shit Jeroen.sqf
* [ ] 7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\REINF\addToGarrison.sqf
* [ ] 8.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\REINF\controlHCsquad.sqf
* [ ] 9.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\REINF\controlunit.sqf
* [ ] 10.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\REINF\dismissPlayerGroup.sqf
* [ ] 11.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\REINF\dismissSquad.sqf
* [ ] 12.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\Scripts\fn_advancedTowingInit.sqf
* [ ] 13.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_artySupport.sqf
* [ ] 14.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_autoHealFnc.sqf
* [ ] 15.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_autoLoot.sqf
* [ ] 16.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_autoRearm.sqf
* [ ] 17.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_captureX.sqf
* [ ] 18.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_help.sqf
* [ ] 19.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_interrogate.sqf
* [ ] 20.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_liberatePOW.sqf
* [ ] 21.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_liberaterefugee.sqf
* [ ] 22.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_staticAutoT.sqf
* [ ] 23.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_undercoverAI.sqf
* [ ] 24.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\AI\fn_vehicleMarkers.sqf
* [ ] 25.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Ammunition\fn_empty.sqf
* [ ] 26.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Ammunition\fn_transfer.sqf
* [ ] 27.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_FIAradio.sqf
* [ ] 28.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_NATOFT.sqf
* [ ] 29.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_addActionBreachVehicle.sqf
* [ ] 30.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_createOutpostsFIA.sqf
* [ ] 31.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_ejectPvPPlayerIfInvalidVehicle.sqf
* [ ] 32.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_flagaction.sqf
* [ ] 33.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_healAndRepair.sqf
* [ ] 34.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_keys.sqf
* [ ] 35.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_markerChange.sqf
* [ ] 36.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_moveHQ.sqf
* [ ] 37.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_mrkUpdate.sqf
* [ ] 38.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_mrkWIN.sqf
* [ ] 39.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_outpostDialog.sqf
* [ ] 40.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_placementselection.sqf
* [ ] 41.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_rebuildAssets.sqf
* [ ] 42.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_rebuildRadioTower.sqf
* [ ] 43.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_resourcecheckSkipTime.sqf
* [ ] 44.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_sellVehicle.sqf
* [ ] 45.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_singlePlayerBlackScreenWarning.sqf
* [ ] 46.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_startBreachVehicle.sqf
* [ ] 47.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Base\fn_unlockVehicle.sqf
* [ ] 48.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_AIVEHinit.sqf
* [ ] 49.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_createAIcontrols.sqf
* [ ] 50.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_createFIAOutposts2.sqf
* [ ] 51.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_createSDKgarrisons.sqf
* [ ] 52.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_invaderPunish.sqf
* [ ] 53.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_patrolCA.sqf
* [ ] 54.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\CREATE\fn_wavedCA.sqf
* [ ] 55.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Convoy\fn_roadblockFight.sqf
* [ ] 56.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_buyVehicle.sqf
* [ ] 57.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_buyVehicleCiv.sqf
* [ ] 58.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_clearForest.sqf
* [ ] 59.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_dialogHQ.sqf
* [ ] 60.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_fastTravelRadio.sqf
* [ ] 61.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_mineDialog.sqf
* [ ] 62.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_moveHQObject.sqf
* [ ] 63.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_skiptime.sqf
* [ ] 64.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_squadOptions.sqf
* [ ] 65.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_squadRecruit.sqf
* [ ] 66.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Dialogs\fn_unit_recruit.sqf
* [ ] 67.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Garage\fn_attemptPlaceVehicle.sqf
* [ ] 68.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Garage\fn_garage.sqf
* [ ] 69.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Garage\fn_garageVehicle.sqf
* [ ] 70.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Garage\fn_vehPlacementBegin.sqf
* [ ] 71.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Garage\fn_vehPlacementCallbacks.sqf
* [ ] 72.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Intel\fn_searchIntelOnDocument.sqf
* [ ] 73.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Intel\fn_searchIntelOnLeader.sqf
* [ ] 74.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Intel\fn_showIntel.sqf
* [ ] 75.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\LTC\fn_canLoot.sqf
* [ ] 76.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\LTC\fn_canTransfer.sqf
* [ ] 77.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\LTC\fn_initLootToCrate.sqf
* [ ] 78.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\LTC\fn_lootFromContainer.sqf
* [ ] 79.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\LTC\fn_lootToCrate.sqf
* [ ] 80.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\LTC\fn_spawnCrate.sqf
* [ ] 81.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Missions\fn_AS_Official.sqf
* [ ] 82.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Missions\fn_AS_Traitor.sqf
* [ ] 83.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Missions\fn_AS_specOP.sqf
* [ ] 84.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-Antistasi\functions\Missions\fn_CON_Outpost.sqf
* [ ] 85.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A3-An [...]

2021-01-12 17:45 UTC, CalebSerafin requested changes
Okay, I'll submit at this halfway point. Full 69. 
You can read through and respond, but don't push any changes yet.
Bellow are general comments in addition to line-specific comments attached to this review.
***
1. A lot of the keys have `customHint`, `chat`, `notification`, `addAction` etc in them. The issue with this is that their text has nothing to do with these functions, and should probably be named according to its context. EG:

In A3-Antistasi\functions\AI\fn_help.sqf #Ln 32:
```sqf
localize "STR_antistasi_customHint_medical"
```
would make more sense being
```sqf
localize "STR_antistasi_AIHelp_medical"
```

Since this will be a large refactor, do not do it now. Rather wait for the second review and what changes will be done for it. Then after all the small stuff if sorted, I'll give the go-ahead to refactor the keys.
***
2. (Side note, no action required for this PR) With the localisation of text sent via `remoteExec`: the language the clients see will depend on what language the server is set to. This will require some working with functions to make sure everything is localised on the client.
***
3. Please feel free to question my suggestions and reviews. As this is a large number of changes, I could make a mistake or overlook something.
***
The second half of the review should be ready in 1-3 days, but I cannot make any promises.

2021-01-15 15:36 UTC, CalebSerafin requested changes
4. This will be a large one. `stringtable.xml` Keys: `STR_antistasi_customHint_only_comander`,`STR_antistasi_customHint_cargo_no_comander`, `STR_antistasi_customHint_clean_forest_only_comander` all spell `commander` incorrectly.
***
1. Again, please don't do the large refactor now, rather focus on the current small issues. And once those are out of the way, then that can be taken care of.

2021-01-15 15:36 UTC, CalebSerafin commented on A3-Antistasi/functions/REINF/fn_vehStats.sqf
> +	if (_textX != "") then {[localize "STR_antistasi_customHint_vehInfo", format ["%1",_textX]] call A3A_fnc_customHint;};
Above _textX needs to be localised.

2021-01-15 15:36 UTC, CalebSerafin commented on A3-Antistasi/functions/REINF/fn_vehStats.sqf
> +[localize "STR_antistasi_customHint_vehInfo", format ["%1",_textX]] call A3A_fnc_customHint;
above TextX needs to be localised.

2021-01-15 15:36 UTC, CalebSerafin commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +		[localize "STR_antistasi_customHint_undercover", localize "STR_antistasi_customHint_undercover_reported"] call A3A_fnc_customHint;
This key does not exist `STR_antistasi_customHint_undercover_reported`

2021-01-15 15:36 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initClient.sqf
> +	vehicleBox addAction [localize "STR_antistasi_addAction_buyBox", {player call A3A_fnc_spawnCrate},nil,0,false,true,"","true", 4];
Format in price of lootbox incase of balance changes.

2021-02-09 02:53 UTC, Bob-Murphy commented
@mimizid will you do the adjustments?

2021-03-26 15:59 UTC, mimizid commented on A3-Antistasi/briefing.sqf
>  player createDiaryRecord ["Diary",[format [localize "STR_antistasi_journal_entry_header_Default_3"],format [localize "STR_antistasi_journal_entry_text_Default_3",nameInvaders]]];
No. I don't know why I added "format". "format" is only needed in some lines.
It should be:
`player createDiaryRecord ["Diary",[localize "STR_antistasi_journal_entry_header_Default_3",format [localize "STR_antistasi_journal_entry_text_Default_3",nameInvaders]]];
`

2021-03-26 16:17 UTC, mimizid commented on A3-Antistasi/dialogs.hpp
> +			action = "if (player == theBoss) then {if (maxUnits < 200) then {maxUnits = maxUnits + 10; publicVariable ""maxUnits""; [localize ""STR_antistasi_customHint_AI_limiter"", format [localize ""STR_an
Maybe change the keys? To change the limit range.
`maxUnits` and `minUnits` range of maximum and minimum number of units. 
`limitUnits` selected unit limit
or not `Units` but `AI`, so shorter

2021-03-26 16:21 UTC, mimizid commented on A3-Antistasi/dialogs.hpp
> +			action = "if (player == theBoss) then {closeDialog 0;[""create""] spawn A3A_fnc_outpostDialog} else {[localize ""STR_antistasi_customHint_op_rb"", localize ""STR_antistasi_customHint_only_comander
My mistake. It should be: 
`localize ""STR_antistasi_customHint_only_comander""`

2021-03-26 16:26 UTC, mimizid commented on A3-Antistasi/dialogs.hpp
> +			action = "closeDialog 0;if (count groupselectedUnits player > 0) then {nul = [groupselectedUnits player] execVM ""REINF\dismissPlayerGroup.sqf""} else {if (count (hcSelected player) > 0) then {nul
Ok, so it will be clearer what the key is.

2021-03-26 16:40 UTC, mimizid commented on A3-Antistasi/JeroenArsenal/JNG/fn_garage_garageVehicle.sqf
> +[localize "STR_antistasi_customHint_garage", (_name + localize "STR_antistasi_customHint_garage_stored")] call A3A_fnc_customHint;
You can do this, but there is no difference. "A3A_fnc_customHint" transfers words if they don't fit.

2021-03-26 16:41 UTC, mimizid commented on A3-Antistasi/JeroenArsenal/JNG/fn_garage_garageVehicle.sqf
> +[localize "STR_antistasi_customHint_garage", (_name + localize "STR_antistasi_customHint_garage_stored")] call A3A_fnc_customHint;
So it will be better, but can JeroenArsenal not localize so that localization does not ruin with each update? Or add localization? Let it be on the advice of JeroenArsenal

2021-03-26 16:53 UTC, mimizid commented on A3-Antistasi/JeroenArsenal/Shit Jeroen.sqf
> +			[localize "STR_antistasi_customHint_game_options", str (_this select 1)] call A3A_fnc_customHint;
I don't understand what is the difference between `[localize "STR_antistasi_customHint_game_options", str (_this select 1)] `and `[localize 'STR_antistasi_customHint_game_options', str (_this select 1)]`. Explain please.  But the first option `[localize ""STR_antistasi_customHint_game_options"", str (_this select 1)]` is not working

2021-03-26 16:57 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>Auto Heal requires at least one AI soldier in your group</Original>
I think this is excusable. First, I just copied the text. And secondly, I'm Russian. lol

2021-03-26 17:03 UTC, HakonRydland commented on A3-Antistasi/JeroenArsenal/Shit Jeroen.sqf
> +			[localize "STR_antistasi_customHint_game_options", str (_this select 1)] call A3A_fnc_customHint;
its inside of a string so what yours is currently saying is 
```sqf
"localize "STR_.....options", str (....."
```

2021-03-26 17:04 UTC, HakonRydland commented on A3-Antistasi/JeroenArsenal/Shit Jeroen.sqf
> +			[localize "STR_antistasi_customHint_game_options", str (_this select 1)] call A3A_fnc_customHint;
single quotes would make it 
```sqf
"localize 'STR_......options', str (....."
```

2021-03-26 17:05 UTC, HakonRydland commented on A3-Antistasi/JeroenArsenal/Shit Jeroen.sqf
> +			[localize "STR_antistasi_customHint_game_options", str (_this select 1)] call A3A_fnc_customHint;
additional quotes would make it
```sqf
"localize ""STR_.....options"", str (....."
```

2021-03-26 17:06 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>I cannot rearm right now. I'm healing a comrade</Original>
`I am already busy.`
A good idea. There are many lines with a similar meaning. Better to rebuild Stringtable.xml. Repetitive lines. EG: 
why do we need `STR_antistasi_dialogs_hq_button_close_text` if there is `STR_disp_close`

2021-03-26 17:10 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>No source to rearm my primary weapon</Original>
Fixed

2021-03-26 17:10 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>Picking a First Aid Kit</Original>
Fixed

2021-03-26 17:14 UTC, mimizid commented on A3-Antistasi/functions/AI/fn_interrogate.sqf
> +            _unit globalChat localize "STR_antistasi_chat_inter_chanse100";
Fixed

2021-03-26 17:16 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>Статическая автоматическая цель недоступна для минометных отрядов в сетевой игре.</Original>
Fixed

2021-03-26 17:19 UTC, mimizid commented on A3-Antistasi/functions/AI/fn_vehicleMarkers.sqf
> +if ((_text == localize "STR_antistasi_markers_convoy_obj") or (_text == localize "STR_antistasi_markers_veh") or (_text == localize "STR_antistasi_markers_box")) then {_convoy = true};
Returned

2021-03-26 17:22 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
> +        _flag addAction [localize "STR_antistasi_addAction_intelSmall", A3A_fnc_searchIntelOnLeader, nil, 4, true, false, "", "isPlayer _this", 4];
Renamed

2021-03-26 17:23 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
> +        _flag addAction [localize "STR_antistasi_addAction_intelMedium", A3A_fnc_searchIntelOnDocument, nil, 4, true, false, "", "isPlayer _this", 4];
Renamed

2021-03-26 17:23 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_flagaction.sqf
> +        _flag addAction [localize "STR_antistasi_addAction_intelLarge", A3A_fnc_searchIntelOnLaptop, nil, 4, true, false, "", "isPlayer _this", 4];
Renamed

2021-03-26 18:07 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_healAndRepair.sqf
> +		[localize "STR_antistasi_customHint_heal_repair", localize "STR_antistasi_customHint_heal_repair_wait"] call A3A_fnc_customHint;
Or maybe:
```
if ((_time - (boxX getVariable ["lastUsed", -30])) < 30) exitWith { 
	if (hasInterface) then { 
		_timeBox = (-30 + _time - (boxX getVariable "lastUsed")) * -1; 
		[localize "STR_antistasi_customHint_heal_repair", format [localize "STR_antistasi_customHint_heal_repair_wait", _timeBox]] call A3A_fnc_customHint; 
	};
};
```

Will show the remaining time. Will show the remaining time

2021-03-26 18:11 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_mrkWIN.sqf
> +	[localize "STR_antistasi_customHint_capture", localize "STR_antistasi_customHint_capture_wait"] call A3A_fnc_customHint;
Done

2021-03-26 18:18 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
> +if (_resourcesFIA < 5000) exitWith {[localize "STR_antistasi_customHint_rebuild", localize "STR_antistasi_customHint_rebuild_no_money"] call A3A_fnc_customHint;};
Сan add variable `_cost`? 

`_cost = 5000`
`if (_resourcesFIA < _cost) exitWith {[localize "STR_antistasi_customHint_rebuild", format [localize "STR_antistasi_customHint_rebuild_no_money",_cost]] call A3A_fnc_customHint;};`
`[0,- _cost] remoteExec ["A3A_fnc_resourcesFIA",2];`

2021-03-26 18:21 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
> +if (_leave) exitWith {[localize "STR_antistasi_customHint_rebuild", format ["%1",_textX]] call A3A_fnc_customHint;};
Will do. There are a few more non-localized strings

2021-03-26 18:25 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_sellVehicle.sqf
> +if (_veh distance getMarkerPos respawnTeamPlayer > 50) exitWith {[localize "STR_antistasi_customHint_sell_veh", localize "STR_antistasi_customHint_sell_veh_no_flag"] call A3A_fnc_customHint;};
Done

`format [localize "STR_antistasi_customHint_sell_veh_no_flag",50]`

stringtable:

`<Original>Vehicle must be closer than %1 meters to the flag</Original>`

2021-03-26 18:27 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>Чтобы взломать автомобиль, нужно быть инженером!</Original>
Oh...Again I messed up the language?
Done

2021-03-26 18:29 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
> +[localize "STR_antistasi_customHint_breach_veh", localize "STR_antistasi_customHint_breach_veh_wait"] call A3A_fnc_customHint;
Done

2021-03-26 18:31 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>You cannot Fast Travel while enemies are nearby</Original>
Done

2021-03-26 18:31 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +        <Original>You cannot Fast Travel if your vehicles don't have a driver or your vehicles immobile</Original>
Done

2021-03-26 18:33 UTC, mimizid commented on A3-Antistasi/functions/Dialogs/fn_mineDialog.sqf
> +if (_quantity < 5) exitWith {[localize "STR_antistasi_customHint_minefields", localize "STR_antistasi_customHint_minefields_no_mine"] call A3A_fnc_customHint;};
Done

2021-03-26 18:35 UTC, mimizid commented on A3-Antistasi/functions/Dialogs/fn_skiptime.sqf
> +if (_checkX) exitWith {[localize "STR_antistasi_customHint_skipTime", localize "STR_antistasi_customHint_skipTime_radius"] call A3A_fnc_customHint;};
Done

2021-03-26 19:02 UTC, mimizid commented on A3-Antistasi/functions/Garage/fn_garage.sqf
> +if (count garage_vehiclesAvailable == 0) exitWith {hintC localize "STR_antistasi_customHint_garage1", localize "STR_antistasi_customHint_garage2"};
Done

`hintC localize "STR_antistasi_customHint_garage_empty"`

stringtable:

`<Original>The Garage is empty or the vehicles you have are not suitable to recover in the place you are. \n\n Air vehicles need to be recovered near Airport flags</Original>`

2021-03-26 19:10 UTC, mimizid commented on A3-Antistasi/functions/Garage/fn_garage.sqf
> +[_initialType, localize "STR_antistasi_customHint_garage", _extraMessage] call A3A_fnc_vehPlacementBegin;
Done

2021-03-26 19:12 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
> +      <Key ID="STR_antistasi_customHint_unlock_busy"> <!-- TODO str_a3_boot_m03_d01_situation_lac_4 -->
Done

2021-03-26 19:16 UTC, mimizid commented on A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
> +if (player distance _veh > 25) exitWith {[localize "STR_antistasi_customHint_garage", localize "STR_antistasi_customHint_garage_away"] call A3A_fnc_customHint};
Done

2021-03-26 19:28 UTC, mimizid commented on A3-Antistasi/functions/Garage/fn_vehPlacementBegin.sqf
> +				[localize "STR_antistasi_dynamicText_vehPlaced_noPos" + "<t size='0.6'>",0,0,3,0,0,4] spawn bis_fnc_dynamicText;
Done

2021-03-26 19:30 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
> +[[teamPlayer,civilian],"DES",[format [localize "STR_antistasi_mission_vehArmor_text",_nameDest,_displayTime,getText (configFile >> "CfgVehicles" >> (_typeVehX) >> "displayName")],localize "STR_antist
corrected

2021-03-26 19:30 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
> +		["DES",[format [localize "STR_antistasi_mission_vehArmor_text",_nameDest,_displayTime,getText (configFile >> "CfgVehicles" >> (_typeVehX) >> "displayName")],localize "STR_antistasi_mission_vehArmor
corrected

2021-03-26 19:31 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_DES_Vehicle.sqf
> +	["DES",[format [localize "STR_antistasi_mission_vehArmor_text",_nameDest,_displayTime,getText (configFile >> "CfgVehicles" >> (_typeVehX) >> "displayName")],localize "STR_antistasi_mission_vehArmori
corrected

2021-03-26 19:34 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_attackHQ.sqf
> +		["DEF_HQ",[format [localize "STR_antistasi_mission_defend_text2",name petros],format [localize "STR_antistasi_mission_defend_name",name petros],respawnTeamPlayer],_positionX,"SUCCEEDED"] call A3A_f
Done. Then the key `STR_antistasi_mission_defend_text2` can be removed

2021-03-26 19:35 UTC, doommetal commented
Just as a little warning: Everything to do with dialogs will be *gone* after the UI update coming soon™, so it's probably a waste of time to touch any of that.
On the bright side: everything in the UI update will actually have stringtable entries.

2021-03-26 19:36 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"globalChat",localize "STR_antistasi_chat_petros_DestrMission_hint"] remoteExec ["A3A_fnc_commsMP",_requester];
corrected

2021-03-26 19:36 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"globalChat",localize "STR_antistasi_chat_petros_LogMission_hint"] remoteExec ["A3A_fnc_commsMP",_requester];
corrected

2021-03-26 19:37 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"globalChat",localize "STR_antistasi_chat_petros_RescMission_hint"] remoteExec ["A3A_fnc_commsMP",_requester];
corrected

2021-03-26 19:45 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_AssasMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:45 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_DestrMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:45 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_LogMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:45 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_ConqMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:45 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_SupMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:45 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_RescMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:46 UTC, mimizid commented on A3-Antistasi/functions/Missions/fn_missionRequest.sqf
> +				[petros,"hint",localize "STR_antistasi_chat_petros_noConvMission_hint", "Missions"] remoteExec ["A3A_fnc_commsMP",_requester];
Done

2021-03-26 19:47 UTC, mimizid commented on A3-Antistasi/functions/OrgPlayers/fn_donateMoney.sqf
> +if (_resourcesPlayer < 100) exitWith {[localize "STR_antistasi_customHint_donate", localize "STR_antistasi_customHint_donate_no_money"] call A3A_fnc_customHint;};
Done

2021-03-26 19:53 UTC, mimizid commented on A3-Antistasi/functions/OrgPlayers/fn_membersList.sqf
>  _textX = format ["%1<br/>No members:<br/>%2",_textX,_countN];
Done

2021-03-26 19:54 UTC, mimizid commented on A3-Antistasi/functions/OrgPlayers/fn_membersList.sqf
>  _textX = "In Game Members<br/><br/>";
Done

2021-03-26 19:58 UTC, mimizid commented on A3-Antistasi/functions/OrgPlayers/fn_theBossSteal.sqf
> +[localize "STR_antistasi_customHint_money_grab", format [localize "STR_antistasi_customHint_grabed",nameTeamPlayer]] call A3A_fnc_customHint;
Done

2021-03-26 20:04 UTC, mimizid commented on A3-Antistasi/functions/OrgPlayers/fn_theBossToggleEligibility.sqf
>  ["Commander", _text] remoteExec ["A3A_fnc_customHint", _playerX];
Done

2021-03-26 20:07 UTC, mimizid commented on A3-Antistasi/functions/REINF/fn_NATObomb.sqf
> +driver _plane sideChat localize "STR_antistasi_chat_startBomb";
Done

2021-03-26 20:08 UTC, mimizid commented on A3-Antistasi/functions/REINF/fn_addBombRun.sqf
> +if (_veh distance getMarkerPos respawnTeamPlayer > 50) exitWith {[localize "STR_antistasi_customHint_airstrike", localize "STR_antistasi_customHint_airstrike_noFlag"] call A3A_fnc_customHint;};
Done

2021-03-26 20:14 UTC, mimizid commented on A3-Antistasi/functions/REINF/fn_build.sqf
> +if (_leave) exitWith {[localize "STR_antistasi_customHint_build", format ["%1",_textX]] call A3A_fnc_customHint;};
Done

2021-03-26 20:19 UTC, mimizid commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +		[localize "STR_antistasi_customHint_undercover", localize "STR_antistasi_customHint_undercover_reported"] call A3A_fnc_customHint;
added a lost key

2021-03-26 20:22 UTC, mimizid commented on A3-Antistasi/functions/init/fn_initClient.sqf
> +	vehicleBox addAction [localize "STR_antistasi_addAction_buyBox", {player call A3A_fnc_spawnCrate},nil,0,false,true,"","true", 4];
Done

2021-03-26 20:29 UTC, mimizid commented
> Just as a little warning: Everything to do with dialogs will be _gone_ after the UI update coming soon™, so it's probably a waste of time to touch any of that.
> On the bright side: everything in the UI update will actually have stringtable entries.

Then I will not make new changes to the dialogs. Besides what has already been done.

2021-03-26 20:43 UTC, mimizid commented
I will look for more errors. Maybe there is something to localize. I commit on Sunday.

2021-03-27 05:15 UTC, mimizid commented on A3-Antistasi/JeroenArsenal/JNG/fn_garage_garageVehicle.sqf
> +[localize "STR_antistasi_customHint_garage", (_name + localize "STR_antistasi_customHint_garage_stored")] call A3A_fnc_customHint;
Done

2021-03-27 05:40 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
> +if (_leave) exitWith {[localize "STR_antistasi_customHint_rebuild", format ["%1",_textX]] call A3A_fnc_customHint;};
Done

2021-03-27 10:22 UTC, mimizid commented on A3-Antistasi/functions/REINF/fn_vehStats.sqf
> +	if (_textX != "") then {[localize "STR_antistasi_customHint_vehInfo", format ["%1",_textX]] call A3A_fnc_customHint;};
Done

2021-03-27 10:22 UTC, mimizid commented on A3-Antistasi/functions/REINF/fn_vehStats.sqf
> +[localize "STR_antistasi_customHint_vehInfo", format ["%1",_textX]] call A3A_fnc_customHint;
Done

2021-03-27 12:42 UTC, Bob-Murphy commented
What you also need to do is fixing all the merge conflicts and update it to unstable.

2021-03-28 09:06 UTC, mimizid commented on A3-Antistasi/JeroenArsenal/Shit Jeroen.sqf
> +			[localize "STR_antistasi_customHint_game_options", str (_this select 1)] call A3A_fnc_customHint;
Done

2021-03-28 09:08 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_rebuildAssets.sqf
> +if (_resourcesFIA < 5000) exitWith {[localize "STR_antistasi_customHint_rebuild", localize "STR_antistasi_customHint_rebuild_no_money"] call A3A_fnc_customHint;};
Done

2021-03-28 09:19 UTC, mimizid commented on A3-Antistasi/functions/Base/fn_healAndRepair.sqf
> +		[localize "STR_antistasi_customHint_heal_repair", localize "STR_antistasi_customHint_heal_repair_wait"] call A3A_fnc_customHint;
Done. `format`ting

2021-03-28 09:21 UTC, mimizid commented on A3-Antistasi/dialogs.hpp
> +			action = "if (player == theBoss) then {if (maxUnits < 200) then {maxUnits = maxUnits + 10; publicVariable ""maxUnits""; [localize ""STR_antistasi_customHint_AI_limiter"", format [localize ""STR_an
In new versions, this line is not needed.

2021-03-28 09:24 UTC, mimizid commented on A3-Antistasi/dialogs.hpp
> +			action = "if (player == theBoss) then {if (maxUnits > 80) then {maxUnits = maxUnits - 10; publicVariable ""maxUnits""; [localize ""STR_antistasi_customHint_AI_limiter"", format [localize ""STR_ant
In new versions, this line is not needed. I deleted the 
`STR_antistasi_customHint_AI_limiter_80`
`STR_antistasi_customHint_AI_limiter_200`
`STR_antistasi_customHint_AI_limiter_text`
in stringtable

2021-04-02 12:01 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
>          <English>Close</English>
Why are Original and English duplicated in the strintable? Have a specific goal? After all, it is better to use only the Original.

2021-04-03 11:37 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
>          <English>Placeholder</English>
Are placeholders used for a specific purpose?

2021-04-03 11:39 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
>          <Original>Be the Resistance Leader. Fight against a superior enemy in technology, number, assets and vehicles. Use guerrilla tactics in a totally dynamic world, with around 18 sidemissions, e
Are duplicate keys used for a specific purpose?
`STR_antistasi_mission_info_..._description_text` (13 keys)

2021-04-03 11:42 UTC, Lazejun commented on A3-Antistasi/Stringtable.xml
>          <English>Placeholder</English>
Not realy, they are just there to easily swap them out and assign them for future Maps.

2021-04-04 10:28 UTC, Bob-Murphy commented on A3-Antistasi/Stringtable.xml
>          <English>Close</English>
This is to have all the languages covered.
Of course it's technically a dublicate but this way technically we can add in specific slang or else.

2021-04-04 10:29 UTC, Bob-Murphy commented on A3-Antistasi/Stringtable.xml
>          <Original>Be the Resistance Leader. Fight against a superior enemy in technology, number, assets and vehicles. Use guerrilla tactics in a totally dynamic world, with around 18 sidemissions, e
To have the option to create map specific cases. We might use it in the future.

2021-04-06 12:44 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
>          <English>Close</English>
It is, but could it be better to remove <English>? If <English> is missing, the arm will refer to <Original> and there will be no duplicates. The stringtable will be slightly lighter

2021-04-06 12:44 UTC, mimizid commented on A3-Antistasi/Stringtable.xml
>          <English>Placeholder</English>
Maybe it's better to remove them? You can always add.
for example, the placeholder was removed in (5e04d4609cb655dffb08ac0e04dfa7e92f98ad88)

2021-04-07 18:26 UTC, Bob-Murphy commented on A3-Antistasi/Stringtable.xml
>          <English>Close</English>
Please let them in for now. Thank you.

2021-04-07 18:27 UTC, Bob-Murphy commented on A3-Antistasi/Stringtable.xml
>          <English>Placeholder</English>
Please let them in as we already have things in the pipeline to fill them.
Thank you.

2021-08-07 19:02 UTC, Bob-Murphy commented
@mimizid we are currently working on a new UI which will change a lot.
Would you be up to overhauling this PR once it is merged?
Unfortunately we simply have not had the ressources to review it properly and now it does not make sense to merge it anymore with the new UI pending.
Sorry for that and thank you for considering.

2021-08-10 05:28 UTC, mimizid commented
@Bob-Murphy, ok. I will recreate the PR after merging the new interface

2021-08-10 10:03 UTC, Bob-Murphy commented
I will let you know once it's merged as it's not the case yet. Thank you!

2021-08-10 12:31 UTC, closed without merging