Add functions that can spawn vehicle and fill with template crew.
official-antistasi-community/A3-Antistasi pull request #1631
Opened 2020-12-29 09:36 UTC by CalebSerafin

## What type of PR is this.
* Bug
* Change
3. [x] Enhancement

## What has changed and why.
### A3A_fnc_spawnVehicle
* Vehicle spawning takes position and angle in multiple formats.
* Vehicle spawning has features if BIS_fnc_spawnVehicle
* Vehicle spawning can be customised.

### A3A_fnc_spawnVehicleCrew
* Vehicle Crew spawning randomly selects crew from templates if possible.
* Vehicle Crew spawning does not create unnecessary groups
* Vehicle Crew spawning fills up all non-cargo seats.

### A3A_fnc_setPos 
* Set position of object using different coordinate systems.

## Following steps after merge
* Get someone who knows the implementation of the new template system to add that compatibility into the marked locations in source code.
* Modify safeVehicleSpawn to work with all custom angles and position systems, so we can use that instead.
* Integrate were possible into 

## Please specify which Issue this PR Resolves.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1368

## Please verify the following and ensure all checks are completed.

2. [x] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
* Yes

### How can the changes be tested?
Spawn rebel crewed LSV in proximity to the player.
```sqf
["B_T_LSV_01_armed_F",getPos player, 0, resistance, 20] call A3A_fnc_spawnVehicle;
```
Spawn rebel crewed LSV on top roof above player.
```sqf
private _myPos = getPosWorld player;
_myPos = [_myPos#0,_myPos#1,0,"AGLS"];  // Spawn 0m above highest roof above the player.
["B_T_LSV_01_armed_F",_myPos, 0, resistance, 20] call A3A_fnc_spawnVehicle;
```
Spawn rebel crewed ghost-hawk part of your squad at a low turn above player.
```sqf
private _myPosW = getPosWorld player;
private _vectorDirAndUp = [[0.676148,-0.736273,-0.0269321],[-0.571476,-0.547179,0.611565]];
private _vehicle = ["B_Heli_Transport_01_F",[_myPosW,"WORLD"], _vectorDirAndUp, group player, nil, [10,40]] call A3A_fnc_spawnVehicle;
_vehicle enableSimulation false; // For admiring the artwork

// Look and execute at ghost-hawk to release.
cursorObject enableSimulation true;
```

2021-02-09 19:55 UTC, CalebSerafin commented
Okay, I'll delete the last squash commit out of history, thinks I added stuff.

2021-03-16 11:33 UTC, HakonRydland requested changes
mostly good, one change needed and one question

2021-03-16 11:33 UTC, HakonRydland commented on A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf
> +        _vehicle = createVehicle [_className, _position select [0,2], [], 0, _createVehicleSpecial];     // Retry with a vehicle so that a convoy/mission which doesn't check won't error out.
when would retrying creation with an invalid classname ever not fail?

2021-03-16 13:07 UTC, CalebSerafin commented on A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf
> +        _vehicle = createVehicle [_className, _position select [0,2], [], 0, _createVehicleSpecial];     // Retry with a vehicle so that a convoy/mission which doesn't check won't error out.
That should've been a constant stock vehicle. Will fix.

2021-03-16 13:11 UTC, CalebSerafin commented on A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf
> +    ["_aircraftPhysics",[], [ true,[] ]],
Ah, should swap that and add data validation if an empty array is issued.

2021-03-16 20:02 UTC, HakonRydland approved these changes
👍

2021-03-17 09:51 UTC, merged