overhauled napalm particle animation stuff by ArtemisGodfrey
official-antistasi-community/A3-Antistasi pull request #1642
Opened 2021-01-10 14:44 UTC by Bob-Murphy

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Artemis has overhauled the particle effect for the napalm script. Now it looks better and shit.
    

### Please specify which Issue this PR Resolves.
closes #1641 

### Are further changes required?
[x] Yes!
What still needs adaptation for damage and sounds as visible in #1641 

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
look at something and do this
`[getPos cursorObject] remoteExec ["A3A_fnc_napalm"];`
********************************************************
Notes:

2021-01-10 15:16 UTC, CalebSerafin commented
I'll just push directly into this branch.

2021-01-22 22:14 UTC, CalebSerafin commented
@Bob-Murphy Assign someone else to review the new code.

2021-01-23 20:28 UTC, jaj22 requested changes

2021-01-23 20:28 UTC, jaj22 commented on A3-Antistasi/functions/AI/fn_napalmDamage.sqf
> +            clearBackpackCargoGlobal _victim;
Move these into init or final?

2021-01-23 20:28 UTC, jaj22 commented on A3-Antistasi/functions/AI/fn_napalmParticles.sqf
> +private _lightPrimary = "#lightpoint" createVehicleLocal [ _pos#0, _pos#1, _pos#2 + 10];
Is createVehicleLocal definitely the correct way to do particle effects rather than createSimpleObject?

2021-01-23 20:28 UTC, jaj22 commented on A3-Antistasi/functions/AI/fn_napalm.sqf
> +_storageNamespace setVariable ["active",false];
Shouldn't you be clearing out the data here? That's quite a lot of hash data per napalm.

2021-01-23 20:58 UTC, jaj22 approved these changes
Looks ok now.

2021-01-23 21:15 UTC, merged