distance refactoring
official-antistasi-community/A3-Antistasi pull request #1643
Opened 2021-01-11 11:02 UTC by AlexTriada

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [ ] Have you loaded the mission in LAN host?
3. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-01-11 11:27 UTC, HakonRydland commented
fill out what why and how for pr info, and testing steps, these are required
the artwork needs to go, and we require a proper header on new code/changes.

heres an example of our standard header:
/*
Author: Name of Author(s)
Description

Arguments:
    <STRING> The first argument
    <OBJECT> The second argument
    <SCALAR> Float or number in SQF.
    <INTEGER> If the number cannot be a decimal.
    <CODE<STRING,ANY,INTEGER,INTEGER>> Code that returns a string with arguments of any, integer, integer.
    <ARRAY<STRING>> Array of a specific type (string in this case).
    <STRING> String input  | <ARRAY> Array input | <CODE> Code input
    <STRING,ANY> A key-pair as compound type.
    <STRING> Optional String input  | <ARRAY> Optional Array input (default: [“”])
    <BOOL> Optional input (default: true)
    <CODE|STRING> Optional input with synonymous types (default: {true})
    <STRING> Not mandatory input (default: nil)

Return Value:
<BOOL> The return value

Scope: Server,Server/HC,Clients,Any
Environment: Scheduled/unscheduled/Any
Public: Yes/No
Dependencies: 
<STRING> A3A_guerName
<SCALER> LBX_lvl1Price


Example:
["something", player] call A3A_fnc_someExsampleFnc;
*/

2021-01-11 11:30 UTC, AlexTriada commented
> fill out what why and how for pr info, and testing steps, these are required
> the artwork needs to go, and we require a proper header on new code/changes.
> 
> heres an example of our standard header:
> 
> ```
> /*
> Author: Name of Author(s)
> Description
> 
> Arguments:
>     <STRING> The first argument
>     <OBJECT> The second argument
>     <SCALAR> Float or number in SQF.
>     <INTEGER> If the number cannot be a decimal.
>     <CODE<STRING,ANY,INTEGER,INTEGER>> Code that returns a string with arguments of any, integer, integer.
>     <ARRAY<STRING>> Array of a specific type (string in this case).
>     <STRING> String input  | <ARRAY> Array input | <CODE> Code input
>     <STRING,ANY> A key-pair as compound type.
>     <STRING> Optional String input  | <ARRAY> Optional Array input (default: [“”])
>     <BOOL> Optional input (default: true)
>     <CODE|STRING> Optional input with synonymous types (default: {true})
>     <STRING> Not mandatory input (default: nil)
> 
> Return Value:
> <BOOL> The return value
> 
> Scope: Server,Server/HC,Clients,Any
> Environment: Scheduled/unscheduled/Any
> Public: Yes/No
> Dependencies: 
> <STRING> A3A_guerName
> <SCALER> LBX_lvl1Price
> 
> 
> Example:
> ["something", player] call A3A_fnc_someExsampleFnc;
> */
> ```

ok, thank you, i will

2021-01-11 12:07 UTC, AlexTriada commented
https://github.com/official-antistasi-community/A3-Antistasi/blob/15db28d6dcc2f8888e0cb66d34e61ab12e220481/A3-Antistasi/functions/Base/fn_distance.sqf#L155
in this line i find the wrong code

2021-01-11 12:19 UTC, AlexTriada commented
i think this file is play fundamental rule for the spawn markers, so ... you know...

2021-01-12 10:16 UTC, wurzel0701 commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +
This can't stay as Hakon said

Regardless of how beautiful it is

2021-01-12 10:19 UTC, wurzel0701 commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +				{ _x enableSimulationGlobal false; }
enableSimulationGlobal works for SP too, it doesnt have to be selected

2021-01-12 10:36 UTC, wurzel0701 commented
This file is incredible important, so this refactor is really good, maybe even increasing performance on the long run.

However, there are a few things that should be fixed before we test it.

First, please fill out the header (for example add your name and what exactly this file is doing). 

Second, I am not sure if possible to unify them, but please also add your testing methods.

Third, I already added two points which should be fixed before further reviewing to break the file down a bit

2021-01-12 11:35 UTC, HakonRydland requested changes
Over all very good. some small changes and a few style notes.

writing your if statements as
````
if (
    _condA
    || _condB
    && _condC
) then {
    code...
};
```` 
is easier to read and modify.

you have a lot of poorly used space, example your switch statements could be compressed to
```
if (_cond) do {
    code...
};
```
the style comments is not required to be changed but would be appreciated.

again overall very good, fix the minor few things and consider the style changes and it should be good.

2021-01-12 11:35 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
naming conventions; _greenfor, _bluefor, and _opfor should be; _teamplayer, _occupants, and _invader respectively. this is a leftover from the original creator barb and should not persist.

ln461 change it to `_counter > COUNT_CYCLES` and change COUNT_CYCLES to 5.

2021-01-12 11:35 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +Description
Description: Handles the spawned state of locations, scheduling spawning, handling simulation state of garrisons, and marking for de-spawning (de-spawning handled in the spawning code).

2021-01-12 11:35 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +Public: Yes
Public: No.

this code should only be spawned once by the init, and is therefore not for public use

2021-01-12 11:35 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +none
<nil>

2021-01-12 11:35 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +#define NOT_EXIST -1
more harm the good, most know what findIf returns when it fails and it is more work to check what NOT_EXIST is defined as then simply having it say `-1`. in addition its less caracters and one less define, it is also not something that would change.

2021-01-12 11:35 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +#define DESPAWN 2
These for contrast are good defines, makes it easier to read the code and no need to look for what was this defined as

2021-01-12 16:29 UTC, AlexTriada commented
> Over all very good. some small changes and a few style notes.
> 
> writing your if statements as
> 
> ```
> if (
>     _condA
>     || _condB
>     && _condC
> ) then {
>     code...
> };
> ```
> 
> is easier to read and modify.
> 
> you have a lot of poorly used space, example your switch statements could be compressed to
> 
> ```
> if (_cond) do {
>     code...
> };
> ```
> 
> the style comments is not required to be changed but would be appreciated.
> 
> again overall very good, fix the minor few things and consider the style changes and it should be good.

`if (cond1) then {
      code...
} else {
      if (cond2) then {
            code...
      };
};
`
- this equally what switch doing, that more complex to understand and to view

2021-01-12 23:51 UTC, AlexTriada commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
I have a suggestion to call _guerillas instead of _teamplayer, _teamplayer is not exactly an accurate name for resistance fighters

2021-01-13 00:12 UTC, SonorousMeerkat commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
> I have a suggestion to call _guerillas instead of _teamplayer, _teamplayer is not exactly an accurate name for resistance fighters, and in PVP mode this is not wright sense, and so we will have
> 
> * _occupants,
> * _invaders,
> * _guerrillas

I can see why you'd think so, but I think teamplayer is perfectly descriptive as that always refers to the player's side.

2021-01-13 00:15 UTC, AlexTriada commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
yes but no, in pvp player's side is not only teamplayer

2021-01-13 00:17 UTC, AlexTriada commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
and then, this is such a small thing, it changes in the entire project in a couple of clicks

2021-01-13 00:19 UTC, AlexTriada commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
and I only suggested as long as in this file they are called _teamplayer

2021-01-13 00:24 UTC, Bob-Murphy commented on A3-Antistasi/functions/Base/fn_distance.sqf
> +		} forEach _spawners;
As teamplayer is not only used on it's own but also in variables like `staticCrewTeamPlayer` and in total is appearing 873 times in 195 files in one way or another and considering that we currently have a few large projects touching a ton of files, a change like this certainly should not be applied as part of a larger PR and should be done on it's own either before or after a publication as then there won't be many large projects open.
Therefore, for now please stick to what we already have regarding the siderelated variable names.
Thank you.

2021-01-13 00:35 UTC, AlexTriada commented
> you have a lot of poorly used space, example your switch statements could be compressed to
> 
> ```
> if (_cond) do {
>     code...
> };
> ```

EXAMPLE:

if (condition1) then {
	code1
} else {
	if (condition2) then {
		code2
	} else {
		if (condition3) then {
			code3
		} else {
			if (condition4) then {
				code4
			} else {
				if (condition5) then {
					code5
				} else {
					if (condition6) then {
						code6
					} else {
						if (condition7) then {
							code7
						};
					};
				};
			};
		};	
	};
};

// equally to 

switch (true) do {
	case (condition1): {code1};
	case (condition2): {code2};
	case (condition3): {code3};
	case (condition4): {code4};
	case (condition5): {code5};
	case (condition6): {code6};
	case (condition7): {code7};
};
```

2021-01-13 00:45 UTC, AlexTriada commented
> Over all very good. some small changes and a few style notes.

I did everything

2021-01-13 13:46 UTC, HakonRydland commented
one last thing that needs changing, tabs to spaces, 4 spaces pr tab.

sidenote: you seam to missunderstand my comment about wasting space, it was about unnecessary use of new line.
```
if (cond)
do
{
    code
}
```
instead of
```
if (cond) do {
    code
}
```
but as i said i wont require it, just prefer it

2021-01-13 13:51 UTC, AlexTriada commented
> one last thing that needs changing, tabs to spaces, 4 spaces pr tab.
ok no problem
> sidenote: you seam to missunderstand my comment about wasting space, it was about unnecessary use of new line.
are we saving paper? as for me, so more readable

2021-01-13 15:36 UTC, AlexTriada commented
I've always used this style before, and in the end I abandoned it, it sacrifices readability too much in favor of compactness.

2021-01-13 15:51 UTC, HakonRydland approved these changes
all the community standards are now met, code is a lot more readable then the old horror show. should be good to merge once @wurzel0701 gives his thumbs up too.

2021-01-15 08:46 UTC, wurzel0701 approved these changes

2021-01-15 08:48 UTC, merged