Revert aggro improvements
official-antistasi-community/A3-Antistasi pull request #1732
Opened 2021-02-24 06:49 UTC by wurzel0701

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Currently the most aggressive faction wins the map as their attacks are way more frequent to fight the player advancing. This however leads to the more fought faction (mostly Occupants) to stop the other faction (mostly Invaders).

Now there is a chance for the attacked faction to defend the attack and counter attack the attacking force, dependent on aggro ratio between them. Lower aggro increases chance of winning attacks/defending attacks.

In the end the faction which is mostly inactive, should take over the map quickly until they are actively fighting the rebels and therefor get active.

### Please specify which Issue this PR Resolves.
None opened

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in singleplayer?
2. [X] Have you loaded the mission in LAN host?
3. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
```
[[50, 60], [0, 0]] spawn A3A_fnc_prestige;
[] spawn 
{
    while {true} do 
    {
        [Occupants] spawn A3A_fnc_rebelAttack;
        sleep 50;
        [Invaders] spawn A3A_fnc_rebelAttack;
        sleep 50;
    };
};
``` 

Execute as server and watch what is happening

2021-02-24 06:50 UTC, wurzel0701 commented
This is the replacement PR for #1553

2021-02-26 18:42 UTC, jaj22 requested changes

2021-02-26 18:42 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    [_soldiers,_side,_marker,0] remoteExec ["A3A_fnc_garrisonUpdate",2];
Can we cap this to somewhere near marker capacity? Overshooting by half a squad is fine, but currently it can stack 7*8 troops on a tiny marker. Calc for marker soldier capacity is `[_marker] call A3A_fnc_garrisonSize`.

2021-02-26 18:42 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    _targetPoints = _targetPoints + (10 * (count _garrison) + (50 * (count _nearbyStatics)));
Unmentioned change but probably a good one. It was too obsessed with garrison size before, and this should cut down the cross-island gov vs inv attacks.

2021-02-26 18:42 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +		+ (tierWar / 5);
I assume this is an adjustment to counter the reduction in _attackPoints due to the change in the garrison size calc? Seems fair enough.

2021-02-26 18:42 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    };
I think these were supposed to go below this scope. Currently the carriers are only being added for gameMode 1.

2021-03-03 12:15 UTC, wurzel0701 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    };
Good catch, but them below the scope

2021-03-03 12:17 UTC, wurzel0701 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    _targetPoints = _targetPoints + (10 * (count _garrison) + (50 * (count _nearbyStatics)));
Sorry, forgot to mention it, yeah it should consider closer  but more garrisoned positions first now

2021-03-03 12:18 UTC, wurzel0701 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    [_soldiers,_side,_marker,0] remoteExec ["A3A_fnc_garrisonUpdate",2];
I am not a big fan of that marker size anyways, makes no sense to have an important outposts only have a few troops cause its marker is not allowed to touch some roads

2021-03-03 12:20 UTC, wurzel0701 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +		+ (tierWar / 5);
Partly also from feedback from the server, might need more adjustment

2021-03-05 04:40 UTC, jaj22 commented on A3-Antistasi/functions/Base/fn_rebelAttack.sqf
> +    [_soldiers,_side,_marker,0] remoteExec ["A3A_fnc_garrisonUpdate",2];
UPSMON uses the marker size as a patrol/placement limit, so if the marker is small then it jams the troops into a tiny area. This will look ridiculous in some cases. Also, the troop count variation between simulated-capture and other cases will look like a bug.

The correct approach given the current system would be to expand the markers if you want more troops on them. Some of them are far too small at the moment.

2021-03-05 04:41 UTC, jaj22 approved these changes
Approved because the remaining issue isn't new and isn't blocking.

2021-03-12 01:31 UTC, merged