New Garage
official-antistasi-community/A3-Antistasi pull request #1735
Opened 2021-02-26 15:01 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    The new garage system

### Please specify which Issue this PR Resolves.
Project Garage 2.0

### Please verify the following and ensure all checks are completed.

~~1. [ ] Have you loaded the mission in singleplayer?~~ Not supported
2. [x] Have you loaded the mission in LAN host?
3. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: just use it, good luck breaking shit

********************************************************
Notes: 
Testing to ensure that stability of system, includes but not limited to:
- Save not fucking up
- state preservation not fucking up
- core garage systems not fucking up
- adding/ removing from garage not fucking up
- refining "feedback" to players if necessary
- probably more but i cant think of any

2021-02-26 15:04 UTC, HakonRydland commented
Travis build failure is a false positive

2021-02-26 22:26 UTC, HakonRydland commented
Note: large scale stress test raveled no issues with network traffic, garage remained responsive as if by single user (visually)

2021-03-29 17:31 UTC, eXCoreX commented
I guess squashing commits is desired.

2021-03-29 17:39 UTC, HakonRydland commented
> I guess squashing commits is desired.

we dont recommend merging anything but master, as unstable and or other branches based of it can be broken, therefore you should wait for for official release, and definitely wait for this to be merged into unstable if you want to risk broken stuff.

2021-03-29 17:46 UTC, eXCoreX commented
> > I guess squashing commits is desired.
> 
> we dont recommend merging anything but master, as unstable and or other branches based of it can be broken, therefore you should wait for for official release, and definitely wait for this to be merged into unstable if you want to risk broken stuff.

I was trying to say that there are a lot of commits and squashing them could make it easier to review. It's only my guess though, and English is not my native language, so sorry if it was unclear.

2021-03-29 17:48 UTC, HakonRydland commented
> > > I guess squashing commits is desired.
> > 
> > 
> > we dont recommend merging anything but master, as unstable and or other branches based of it can be broken, therefore you should wait for for official release, and definitely wait for this to be merged into unstable if you want to risk broken stuff.
> 
> I was trying to say that there are a lot of commits and squashing them could make it easier to review. It's only my guess though, and English is not my native language, so sorry if it was unclear.

we always squash merge pr's

2021-03-29 17:49 UTC, Bob-Murphy commented
This is a WIP branch and as Hakon said, it will be squashed when merged into unstable.

2021-05-14 18:50 UTC, CalebSerafin commented
* [ ] Indentation & Headers
* [ ] Naming Conventions & Grammar
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic
  * [ ] Function
  * [ ] Edgecases
  * [ ] Compaction
  * [ ] Optimisation

2021-05-15 17:28 UTC, CalebSerafin requested changes
Indentation and Header comments are complete. Other comments will be submitted in the future. This was done to streamline the review and response rather than having one long stairway to heaven of text.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf
> +
1. Does not include _player and _client params.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_genVehUID.sqf
> ++HR_GRG_UID
2. Unnessary, SQF does not pass pointers of Any, Boolean, Code, Scalar, String, Text

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_getCatIndex.sqf
> +if ( !isClass (configFile >> "CfgVehicles" >> _class) ) exitWith { [0, "Invalid Input: " + _class, _filename] call HR_GRG_fnc_log };
3. This does not return a scalar.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_requestVehicle.sqf
> +if (_UID isEqualTo "") exitWith {};
4. May not always return boolean.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_toggleLock.sqf
> +    Public: [Yes/No]
5. Scope, Enviroment, Public are undefined.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Extras/fn_findMount.sqf
> +
6. Player object argument is not stated. Please provide mote information for Requesting or releasing enum.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Extras/fn_switchTexture.sqf
> +if (_index isEqualTo -1) exitWith {};
7. May return nil instead of a boolean.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Extras/fn_toggleAnim.sqf
> +if (_index isEqualTo -1) exitWith {};
8. May return nil instead of a boolean.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/Pylons/fn_getPylonTurret.sqf
> + *
9. Scope, Enviroment are undefined.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/StatePreservation/fn_getDamage.sqf
> +            <Int> Repair cargo
10. Global Damage and Repair Cargo are not strictly integers as they range between 0 and 1 inclusively.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/StatePreservation/fn_setDamage.sqf
> +            <Int> Repair cargo
11. Global Damage and Repair Cargo are not strictly integers as they range between 0 and 1 inclusively.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/config.inc
> +/*
12. This should be an SQF function that is set to auto init. Then isNil checks will not be need.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/fn_addVehicle.sqf
> +params [ ["_vehicle", objNull, [objNull]], ["_client", 2, [0]], ["_lockUID", ""], ["_player", objNull, [objNull]] ];
13. Player object argument is not stated in header.

2021-05-15 17:28 UTC, CalebSerafin commented on A3-Antistasi/Garage/fn_callbackHandler.sqf
> +    Public: Yes/No
14. Scope, Enviroment, Public are undefined.

2021-05-26 11:56 UTC, HakonRydland commented on A3-Antistasi/Garage/Pylons/fn_getPylonTurret.sqf
> + *
added, left header otherwise unchanged as this is mostly ace code

2021-05-26 12:01 UTC, HakonRydland commented on A3-Antistasi/Garage/config.inc
> +/*
cant say i agree, as auto init runs on every client. and while the values are broadcasted to clients, id as a design choice want these only set on server, along with any other important variables

2021-05-26 12:11 UTC, HakonRydland commented on A3-Antistasi/Garage/config.inc
> +/*
as an additional note, publicVariable JIP happens before init.sqf, and while im not 100% sure when the mission script with auto init run, im fairly certain its after init.sqf

2021-06-06 16:53 UTC, CalebSerafin commented on A3-Antistasi/Garage/config.inc
> +/*
https://community.bistudio.com/wiki/Initialization_Order
You can slap an isServer check in your pre-inits as well.

2021-06-08 20:38 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
> +    private _mPos = [(_bb#0#0) - 0.3, (_vehicle worldToModel getPos _cargo)#1, _bb#0#2];
15. What does the - 0.3 do. Why 0.3?

2021-06-08 20:38 UTC, CalebSerafin commented on A3-Antistasi/functions/Save/fn_savePlayer.sqf
> +    Info_4("Saved player %1: %2 rank, %3 money, %4 vehicles", _playerId, rank _playerUnit, _totalMoney, "old garage removed");
16. Replacing the garage count with text will break auto graphing anyway. Might aswell downgrade to Info_3.

2021-06-08 20:38 UTC, CalebSerafin commented on A3-Antistasi/functions/Save/fn_savePlayer.sqf
> +	private _garage = [];
17. _garage is unused.

2021-06-08 20:39 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_addUser.sqf
> +if !(_client isEqualType 0) exitWith {false};
18. All the checks are quite cheap. In the success scenario, all of them would be run and return true. Therefore they could be combined.

2021-06-08 20:39 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_addUser.sqf
> +if (isNil "HR_GRG_Users") then {HR_GRG_Users = []};
19. It does not return any value. Neither true or false. This will cause all if statements to act as if they were false down the line.

2021-06-08 20:41 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_broadcast.sqf
> +    _x publicVariableClient "HR_GRG_Event";
20. What is the advantage of publicVariable over remoteExec? For remoteExec you can directly provide an array of clientIDs, it will remove the need for receiving and sending functions.

2021-06-08 20:41 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +params [ ["_class", "", [""]], ["_mounts", [], [[]]], ["_pylons", [], [[]]], "_state", ["_useGRGPool", true, [true]], ["_callBack", ""] ];
21. The params could be made multiline so it is easier to differentiate each param.

2021-06-08 20:41 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +RB_KeyPause = time;
22. RB_KeyPause was not refactored from RedBlood to HakonRydland.

2021-06-08 20:41 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +HR_GRG_fnc_execForGarageUsers = {
23. HR_GRG_fnc_execForGarageUsers should be made it's own function from a file. Then it could be directly remoteExec-ed and not sent over the network.

2021-06-08 20:41 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +HR_GRG_Mounts_ = _mounts; //HR_GRG_Mounts is used in garage internaly
24. Instead of adding an underscore to HR_GRG_Mounts, it would be more noticiable adding another word in the name.

2021-06-08 20:42 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +    HR_GRG_KeyQ = nil;
25. naming of HR_GRG_KeyQ is inconsistent with camalCase. IE: HR_GRG_keyHint.

2021-06-08 20:42 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +    HR_GRG_dispMounts pushBack [_static, _nodeOffset vectorAdd (_offsetAndDir#0), _offsetAndDir#1, _x ];
26. I can't figure out what is going on here. I might guess it's for placing the vehicle with half of its size used for spacing. Code comments would be greatly appreciated.

2021-06-08 20:43 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_genVehUID.sqf
> +HR_GRG_UID = HR_GRG_UID + 1 % 10000000;
28. The order of operations means that modulo will operate on 1 before adding the UID. Also, 1e7 is quicker to read. ie: `(HR_GRG_UID + 1) % 1e7`.

2021-06-08 20:43 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_genVehUID.sqf
> +HR_GRG_UID
29. You don't need to positive the scalar (There is no copy operation, they are always copied)

2021-06-08 20:43 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_onLoad.sqf
> +if (isNil "HR_GRG_Init") then {remoteExecCall ["HR_GRG_fnc_initServer",2]};
30. This does not wait for initServer to finish. If such a case comes up, this will motor-along and other clients could fire initServer until a response returns.

2021-06-08 20:44 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_onLoad.sqf
> +waitUntil {!isNil "HR_GRG_Vehicles"};//wait for server response
31. HR_GRG_Vehicles is never nilled, so if someone opens the garage again, it will not wait for the server response. Is this intended?

2021-06-08 20:44 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_onLoad.sqf
> +FIX_LINE_NUMBERS()
32. There is no need to re-include the same file again. All macros in this function will be processed based on the includes at the file top. There is also no use of logMacros in that function.

2021-06-08 20:45 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_onUnload.sqf
> +"HR_GRG_Vehicles" addPublicVariableEventHandler {};
33. Did you test that you can clear the PublicVarable event handlers. Looking at the docs it would indicate that it would just keep adding more.

2021-06-08 20:45 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_onUnload.sqf
> +private _code = {
34. Why is this not a permanently defined function?

2021-06-08 20:46 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_removeUser.sqf
> +if (isNil "HR_GRG_Users") exitWith {false};
35. All the checks are quite cheap. In the success scenario, all of them would be run and return true. Therefore they could be combined.

2021-06-08 20:46 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf
> +private _exit = { [true] remoteExecCall ["HR_GRG_fnc_toggleConfirmBttn", _client] };
36. Since exit is always the only thing called in exitWith, you could simplify some code. The false return could be inside _exit. And exit can be inlined right after exitWith: `if (true) exitWith _exit;`

2021-06-08 20:46 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_selectionChange.sqf
> +HR_GRG_SelectedVehicles params ["_cat", ""];
37. Not sure if params with one variable and no validation is more appropriate than select in this context. `private _cat = HR_GRG_SelectedVehicles#0`

2021-06-08 20:55 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_genVehUID.sqf
> +HR_GRG_UID
Weird, there does not appear to be a plus. Maybe I hallucinated.

2021-06-08 21:23 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
> +    private _mPos = [(_bb#0#0) - 0.3, (_vehicle worldToModel getPos _cargo)#1, _bb#0#2];
offset slightly further to the left, 0.3 was picked after testing to be safe from bad placement and none excessive

2021-06-08 21:38 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_addUser.sqf
> +if (isNil "HR_GRG_Users") then {HR_GRG_Users = []};
its just defining the list, did you misread, or am i misunderstanding

2021-06-08 22:15 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_onLoad.sqf
> +FIX_LINE_NUMBERS()
IDDs etc are also in defines.inc, but yes you are right

2021-06-08 22:17 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_onUnload.sqf
> +"HR_GRG_Vehicles" addPublicVariableEventHandler {};
its been a while, but im 99% certain i did test and confirm it can only have one EH tied to a variable on each client at a time. ie this would clear the EH

2021-06-09 05:47 UTC, CalebSerafin commented on A3-Antistasi/Garage/Core/fn_addUser.sqf
> +if (isNil "HR_GRG_Users") then {HR_GRG_Users = []};
Oh sorry, I misread then for exitWith.

2021-06-09 05:50 UTC, CalebSerafin commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
> +    private _mPos = [(_bb#0#0) - 0.3, (_vehicle worldToModel getPos _cargo)#1, _bb#0#2];
Could you add a comment to the code for this one?

2021-06-09 13:40 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_onUnload.sqf
> +"HR_GRG_Vehicles" addPublicVariableEventHandler {};
ok re tested and can confirm it does clear it

2021-06-09 13:42 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
> +    private _mPos = [(_bb#0#0) - 0.3, (_vehicle worldToModel getPos _cargo)#1, _bb#0#2];
done

2021-06-19 15:52 UTC, CalebSerafin requested changes
Minor changes for 3 notifications. After that, it should be good to go. 🎆

2021-06-19 15:52 UTC, CalebSerafin commented on A3-Antistasi/Garage/Extras/fn_findMount.sqf
> +private _failed = { [localize "STR_HR_GRG_Feedback_requestMount_Denied"] remoteExec ["Hint", _owner]; [true] remoteExecCall ["HR_GRG_fnc_toggleConfirmBttn", _owner]; false };
38. For use in Antistasi, you will need to switch from `hint` to `a3a_fnc_customHint`, otherwise, the message may be hidden in the same or a near frame. You already have a hint function, could use that.

2021-06-19 15:52 UTC, CalebSerafin commented on A3-Antistasi/Garage/Extras/fn_reloadMounts.sqf
> +hintSilent "";
39. In customHint currently there is no public method to dismiss a particular notification. The messages are stored in `A3A_customHint_MSGs` with structure: [<STRING>headerText,<TEXT>structuredText,<BOOL>isSilent], it will not change in the future. So the best would be to write all notifications with the same Header, this will overwrite the previous message.

2021-06-19 15:52 UTC, CalebSerafin commented on A3-Antistasi/Garage/Extras/fn_requestMount.sqf
> +if (_nodes isEqualType 0) exitWith { hint localize "STR_HR_GRG_Feedback_requestMount_Denied" };
40. Similar to point 38, customHint will be required to make sure that it's visible.

2021-06-19 16:36 UTC, HakonRydland commented on A3-Antistasi/Garage/Extras/fn_reloadMounts.sqf
> +hintSilent "";
leftover from early build before logistics was modified to not show hint messages on instant loading, i will remove it

2021-06-25 22:13 UTC, CalebSerafin approved these changes
Cool, all the problems have been solved.
A small thing with dismissing hints may remain, but that best requires an addition for customHint (And it probably wont matter as they overwrite each other.)
Good to merge ✨🎆

2021-06-25 22:22 UTC, merged