fn_placementselection Refactor
official-antistasi-community/A3-Antistasi pull request #1764
Opened 2021-03-05 16:52 UTC by Toakan

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
Information:

- Refactored `fn_placementselection` to utilise switch statement rather than busy IF blocks. This should make it easier to capture / add future cases of restriction to HQ deployment.
- Removed some duplicated IF Blocks.
- Moved EXITWITH when VISIBLEMAP returned true to switch block. I believe this was stopping the HQ creation earlier than needed in some cases. Possibly relates to #1763.
- Added some standard logging.

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
*Test 1*
- Load the a Fresh game, 
- Attempt to meet each criteria currently in the switch block.
    - Close Map without choosing a place
    - Try choosing a location within Enemy Hotzone
    - Try choosing a location near enemy forces
    - Try choosing a location in water
    - Try choosing a location off map.

*Test 2*
- Kill Petros
- Attempt all checks again.
    - *NOTE* You cannot escape the Map when Petros has been killed.

********************************************************
Notes:

I think it would be worth adding a minimum distance check from previous HQ location, this should prevent players just continuously using the same spot which can be a form of briefing if users are being hit by QRFs / Mortars.

2021-03-08 08:32 UTC, HakonRydland approved these changes
looks good, on minor note

2021-03-08 08:32 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_placementselection.sqf
> +		case (!_positionIsInvalid && (_positionClicked findIf { (_x < 0) || (_x > worldSize)} != -1)):
dont need to check that ``_positionClicked`` is not true, as switch exits out of the scope when one of the cases is true

2021-03-08 11:35 UTC, Toakan commented on A3-Antistasi/functions/Base/fn_placementselection.sqf
> +		case (!_positionIsInvalid && (_positionClicked findIf { (_x < 0) || (_x > worldSize)} != -1)):
This isn't checking for `!(_positionClicked)`, it's checking to see if it's been clicked out of the map bounds?

2021-03-08 12:25 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_placementselection.sqf
> +		case (!_positionIsInvalid && (_positionClicked findIf { (_x < 0) || (_x > worldSize)} != -1)):
Typo as i wrote the comment in a bit of a haste, meant ``_positionIsInvalid``, this is because it would always be false if the condition is evaluated, in addition you could also remove the ``_positionIsInvalid = false`` in not visible map case, as its set before the switch statement to false, making the presumption the position is valid

2021-03-08 13:40 UTC, Toakan commented
Reminder:
Remove unneeded _positionIsInvalid check.
Check Tab indentation...

2021-04-03 22:45 UTC, Bob-Murphy commented
merge conflicts

2021-04-08 22:48 UTC, Toakan commented
Merge issue should now be sorted.

2021-04-10 13:56 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_placementselection.sqf
> +				ServerError("HQ Placement chosen, setting up.");
was info

2021-04-10 13:56 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_placementselection.sqf
> +	ServerInfo("Petros is dead, Setting new HQ Location.");
was debug

2021-04-10 14:01 UTC, HakonRydland commented
the comment from 8. march is stil unresolved and the log level alterations need to be "justified"

2021-04-10 14:08 UTC, HakonRydland requested changes
- ln 24: info was debug, why?
- ln 88: error was info, why?
- ln 60: remove unnecessary ``_positionIsInvalid = false``
- ln 68: remove unnecessary ``!_positionIsInvalid`` always true if case reached
becomes ``case (surfaceIsWater _positionClicked):```
- ln 74: remove unnecessary ``!_positionIsInvalid`` allways true if case reached
becomes ``case (_positionClicked findIf { (_x < 0) || (_x > worldSize)} != -1):``

2021-04-10 14:10 UTC, HakonRydland commented
a reason why not doing so and or why this was done is all that is needed, but i want this answered before merge

2021-08-05 21:18 UTC, Bob-Murphy commented
Hakon taking over due to inactivity.

2022-10-15 12:34 UTC, Bob-Murphy commented
dead

2022-10-15 12:34 UTC, closed without merging