Doom go undercover split
official-antistasi-community/A3-Antistasi pull request #1818
Opened 2021-03-28 12:33 UTC by wurzel0701

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Split the goUndercover file into a canGoUndercover and goUndercover file, cleaned up the files and added the new headers. The functionality is the same, but the hints are now clear on what you doing wrong.

### Please specify which Issue this PR Resolves.
closes #1791

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: Play around with the undercover system, try to get and lose undercover as often as possible in all possible situations

********************************************************
Notes: I couldnt test all cases here, but the ones I tested were good, more testing required.

2021-03-29 13:19 UTC, doommetal commented
Did a quick test of just the goUndercover part now and seems to do exactly what's needed for the UI. 👍

2021-03-30 14:04 UTC, CalebSerafin commented
* [ ] Indentation & Headers
* [ ] Naming Conventions & Grammar
* [ ] Macros
* [ ] Param & Call
* [ ] Global Variables
* [ ] Local Variables
* [ ] Logic
  * [ ] Function
  * [ ] Edgecases
  * [ ] Compaction
  * [ ] Optimisation

2021-03-30 20:04 UTC, CalebSerafin requested changes
Okay, first, hats off for listing all the global variables in the header. That saved me tonnes of time in checking. There are some bugs, most are code readability and quality.

I'll only look at optimization after changes.

2021-03-31 05:51 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +	["Undercover", "You cannot go Undercover while you are controlling AI"] call A3A_fnc_customHint;
Fixed, finally found a way for atom to show them to me, should be fine now

2021-03-31 05:52 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +    Checks if the player is able to go undercover
Copy pasted and forgot to change...

2021-03-31 05:53 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +Environment: Any
Right, fixed

2021-03-31 05:53 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +    <ARRAY> reportedVehs
Deleted

2021-03-31 05:54 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +    <BOOL> hasACE
Fixed, never threw an error for me tho

2021-03-31 05:54 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +private _changeState = "";
Gone now

2021-03-31 05:56 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +_result = [];
Fixed, also fixed a logical bug based on it (which might shows up later in the list)

2021-03-31 05:57 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +        ["Undercover", "You cannot stay Undercover while showing:<br/><br/>A weapon is visible<br/>Wearing a vest<br/>Wearing a helmet<br/>Wearing NVGs<br/>Wearing a mil uniform<br/><br/>The enemy ad
Nope, if you are here, canGoUndercover passed already with you being able to, but you reequipted something. I could try to call it here again, but that seems a bit unnecessary.

2021-03-31 05:57 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                    [_x, false] remoteExec["setCaptive"];
There was something that it was not fast enough or something, thats why it was done that way. It can be changed after investigating that, but thats not part of this PR

2021-03-31 05:59 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +    }
Done

2021-03-31 05:59 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +        {
No it cannot, even if you are completely undercover this would exit the check loop, then break undercover

2021-03-31 06:00 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                if (((position player nearObjects["SatchelCharge_Remote_Ammo", 5]) select 0) mineDetectedBy Occupants) then
Feature change, not part of this PR

2021-03-31 06:01 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                };
Nope, without that setting it back to false you would be able to pass every airfield, outpost and roadblock once you passed one successful once

2021-03-31 06:01 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                    {
Its not, see 13.

2021-03-31 06:02 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                        };
It is, see 13.

2021-03-31 06:02 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                        }
Once is the text for getting to close to an enemy military location, the other one is getting recognised by a roadblock, it cannot be merged

2021-03-31 06:03 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +            if ((primaryWeapon player != "") || (secondaryWeapon player != "") || (handgunWeapon player != "") || (vest player != "") || (getNumber(configfile >> "CfgWeapons" >> headgear player >> "I
I would say the outer one improves readability. Its just personal preferences here, so I leave it untouched

2021-03-31 06:05 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                if (side _healingTarget != civilian && {_healingTarget isKindOf "Man"}) then
Done

2021-03-31 06:05 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +            if ((primaryWeapon player != "") || (secondaryWeapon player != "") || (handgunWeapon player != "") || (vest player != "") || (getNumber(configfile >> "CfgWeapons" >> headgear player >> "I
Done

2021-03-31 06:05 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +            if (dateToNumber date < _compromised) then
Done

2021-03-31 06:06 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +            if (!(_vehType in undercoverVehicles)) then
Nope, that would break the entire script, see above

2021-03-31 06:08 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +            if (_veh in reportedVehs) then
Done

2021-03-31 06:08 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +
Done

2021-03-31 06:10 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                        if ({((side _x == Invaders) || (side _x == Occupants)) && ((_x knowsAbout player > 1.4) or(_x distance player < 350))} count allUnits > 0) then
Done, the condition for failure are quite harsh tho, somebody might wanna have a second look here

2021-03-31 06:11 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                        if (_base in airportsX || _onDetectionMarker || random 100 < _aggro) then
No, that would break the logic

2021-03-31 06:11 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +                {
Double post :D

2021-03-31 06:13 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +	["Undercover", "You cannot go Undercover while you are controlling AI"] call A3A_fnc_customHint;
I am against that, that would require alot of code in goUndercover that is already needed in canGoUndercover and therefor would be duplicated

2021-03-31 06:15 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +private _secureBases = airportsX + outposts + seaports + _roadblocks;
I dont like how this would cause an allocation of these every frame the player is driving on a random road, i take the maybe unnecessary memory allocation over alot of repeated necessary ones.

2021-03-31 06:16 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +private _compromised = player getVariable ["compromised", 0];
Done

2021-03-31 06:16 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +    _result = [false, "Spotted by enemies"];
The bug I talked about above, already fixed

2021-03-31 06:17 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +        ["Undercover", "You have been reported in the last 30 minutes therefore you cannot go Undercover"] call A3A_fnc_customHint;
Feature change, not part of this PR

2021-03-31 06:17 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +        ["Undercover", "You have been reported in the last 30 minutes therefore you cannot go Undercover"] call A3A_fnc_customHint;
Relatively complicated for nearly no gain too, I guess players dont wait till they can go undercover again and just hit the box

2021-03-31 06:18 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +    };
This makes no sense? In the end it would let you go undercover after throwing a message that you cant

2021-03-31 06:19 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +if ((player distance2D getMarkerPos _base < _size * 2) && (!(sidesX getVariable [_base, sideUnknown] == teamPlayer))) exitWith
Legacy code, not sure why the 2* is in there
Changed the other thing

2021-03-31 06:25 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +    };
Can you not heal people in vehicles with ACE? Then it is needed outside the if construct

2021-03-31 06:28 UTC, wurzel0701 commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
>  };
Added macros, log line and display line, so players will notice if it happens and hopefully send us a rpt

2021-04-03 11:37 UTC, CalebSerafin commented on A3-Antistasi/functions/Undercover/fn_canGoUndercover.sqf
> +    };
Ah sorry, should of been set false, not true. It has been edited.

2021-04-03 12:23 UTC, CalebSerafin requested changes
Okay, I attempted to benchmark the while loop in goUndercoverfunction. From the cases where the player is already undercover, or not undercover, it runs between `23 ns` and `20 ns` which is good as it only runs every second. A3A_fnc_canGoUndercover runs at `185ms`. However, this is fine as it should only be run intermittently when the user clicks go under cover or when his cursor enters the button to show hover text.

So after this bug is sorted and if you decide to add the above suggestion to shorten the code, then it should be good to go.

2021-04-03 12:23 UTC, CalebSerafin commented on A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
> +        if (dateToNumber date < _compromised) exitWith
I missed this in the first review, ths first commit removed the compromised definitions. However, this one appears to have been left behind.
```suggestion
        if (dateToNumber date < (player getVariable ["compromised", 0])) exitWith
```

2021-04-03 17:52 UTC, CalebSerafin approved these changes
Cool, those bugs have been fixed, and it should work if Doom's UI system (As long as he doesn't run the check code on each frame for the button hover).

2021-05-01 15:53 UTC, merged