Street Artist Navigation Grid Editor
official-antistasi-community/A3-Antistasi pull request #1900
Opened 2021-05-02 22:45 UTC by CalebSerafin

## What type of PR is this.
* Bug
* Change
* [x] Enhancement

### What have you changed and why?
Information:
    Added an editor.
    Some unhandled expectations thrown.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
* No
* [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-05-03 07:36 UTC, Bob-Murphy approved these changes
I confirm usability. Everything works as expected

2021-05-03 18:18 UTC, Lazejun approved these changes
I was not able to recreate Errors/Issues i ran into on earlier versions.

Even during a short amount of testing on 2 Seperate Maps with Edited NavGrids i didn't see any issues.

So should be good 🤷‍♂️

2021-05-15 16:26 UTC, Bob-Murphy commented
Is here anything new that I can test?

2021-05-15 17:15 UTC, CalebSerafin commented
@Bob-Murphy
> Is here anything new that I can test?
Not at the moment, busy implementing some of the node connection requirements. As a result the editor is currently not fully capable/functional.

2021-06-10 14:26 UTC, HakonRydland requested changes
okay this is a review of individual functions primarilly, and does not look at the bigger picture, but rather that the functions are acomplishing its declaired task returns what its supposed to and has no errors etc. an assumption that any functions called will behave as expected by the calling function is made.

a big picture review is to be done looking at the system as a whole where primarily i will be looking for unnececeties, unused functions, incorrect use of functions etc.

So far i have found no large issues, and the review contains mostly small changes or sugguestions to improve the code or its readability.

2021-06-10 14:26 UTC, HakonRydland commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_posRegionHM_allAdjacent.sqf
> +
could add a nice visual aid here
```sugguestion
1|2|3
4|P|5
6|7|8
```
butt probably can ignore as its simple enough

2021-06-10 15:17 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridDraw/fn_NG_draw_dot.sqf
> +    _name setMarkerColor _colour;
It's provisioning if I decide to add multiplayer map editing.

2021-06-10 15:20 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridDraw/fn_NG_draw_main.sqf
> +if (isNil {
Guarantees that the code inside will be executed as one block without suspension. This is used for variable or operation locks.

2021-06-10 15:23 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridGen/getStats.sqf
> +[] spawn {
Its more of a probe tool. So what ever it returns is the new standard. The source code is left there in case I want to re adapt it for something else.

2021-06-10 15:24 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridGen/specification tolerences.md
> +John Jordan — 21May04 at 21:59
I should probably clean it up into bullet points.
I'll leave the specification in the source code as it's far easier to find and update.

2021-06-10 15:42 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_click_modeConnect.sqf
> +    A3A_NGSA_UI_marker1_name setMarkerPos A3A_NGSA_UI_marker1_pos; // Broadcasts marker attributes here
Provision for multiplayer map editing

2021-06-10 15:43 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_canAddPos.sqf
> +assert (A3A_NG_const_positionInaccuracy < 100); // This is the minimum distance returned by adjacent navRegions.
Quick 1 liner way to test condition and throw an error. Could probably be removed as a map would need to be about a million kilometres wide to get that inaccuracy.

2021-06-10 15:45 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_action_changeTool.sqf
> +    <ANY> undefined.
The undefined return is to inform that the consistency of the output should not be relied upon. As in an update the internal workings may be changed which inadvertently changes what could of been returned.

2021-06-10 15:46 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_action_changeColours.sqf
> +private _selectorText = ["Normal","Normal &amp; Offroad","Island","Island &amp; Dead-ends"];   // Use a special space for the underlining to work.
I'm not sure I understand. Could you provide a code example?

2021-06-10 15:46 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_action_autoRefresh.sqf
> +    <ANY> undefined.
The undefined return is to inform that the consistency of the output should not be relied upon. As in an update the internal workings may be changed which inadvertently changes what could of been returned.

2021-06-10 15:48 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridGen/fn_NG_init.sqf
> +    _this apply {_a=+_x; reverse _a, _a};
Comma?

2021-06-10 15:49 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridDraw/fn_NG_draw_islands.sqf
> +    <ANY> undefined.
The undefined return is to inform that the consistency of the output should not be relied upon. As in an update the internal workings may be changed which inadvertently changes what could of been returned.

2021-06-10 16:32 UTC, HakonRydland commented
> Comma? 

should be semicolon, guessing typo

2021-06-10 16:34 UTC, HakonRydland commented on Tools/NavGridPP/functions/NavGridDraw/fn_NG_draw_islands.sqf
> +    <ANY> undefined.
good enough for me

2021-06-10 16:39 UTC, HakonRydland commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_action_changeColours.sqf
> +private _selectorText = ["Normal","Normal &amp; Offroad","Island","Island &amp; Dead-ends"];   // Use a special space for the underlining to work.
nevermind, i had a brain fart and missed youd stil be displaying the others just not highlighted

2021-06-10 16:45 UTC, HakonRydland commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_canAddPos.sqf
> +assert (A3A_NG_const_positionInaccuracy < 100); // This is the minimum distance returned by adjacent navRegions.
i feel a regular logged error and hint would still be better, as this is a one of use of assert not seen elsewhere in navgrid. but ill leave it to you

2021-06-10 17:19 UTC, CalebSerafin commented on Tools/NavGridPP/functions/NavGridGen/fn_NG_init.sqf
> +    _this apply {_a=+_x; reverse _a, _a};
Oh, now I see the typo. I'm surprised it didn't produce any noticeable problems.

2021-06-12 20:06 UTC, HakonRydland commented
okay so the big picture review found nothing of significant, hovever i want aswers regarding three disconnected files left over.
Disconnected Files:
- fn_NG_check_coneExists.sqf
- fn_NG_check_oneWays.sqf
- fn_NGSA_EH_rem.sqf

the EH_rem im guessing is for debug, the two other im guessing is leftover of a refactor(s)?

2021-06-12 20:11 UTC, HakonRydland commented
okay i can't see anything else, once all comments are addressed and changes committed this can be approved and merged

2021-06-14 08:42 UTC, Bob-Murphy commented on Tools/NavGridPP/functions/NavGridGen/specification tolerences.md
> +John Jordan — 21May04 at 21:59
type in file name
tolerences --> tolerances

2021-06-19 16:36 UTC, CalebSerafin commented on Tools/NavGridPP/Please Read Me.md
>  You can re-run this command as much as you want, everytime it will delete the old markers and redraw new. (But please wait for the last one to finish otherwise bad things will happen.)<br/>
They probably will not need or bother to tweak them. Tested the Editor on all 5 UI sizes and its current size is appropriate. And now the different colour/display schemes in the Editor supersede this functionality anyway. Therefore I will remove it which will shorten the `Please Read Me` as well.

2021-06-19 16:46 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_EH_add.sqf
> +[localNamespace,"A3A_NGPP","MissionEH_eachFrame_ID",_missionEH_eachFrame_ID] call Col_fnc_nestLoc_set;
Not needed anymore so I'll remove it as well.

2021-06-19 17:20 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_click_modeConnect.sqf
> +    <BOOLEAN> _shift
Moved the global key check to onMouseClick, since all will rely on those instead.

2021-06-19 18:17 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_hover_modeBrush.sqf
> +    Removes a _roadStruct reference from posRegions
lol, all of these must have been copied from another function and I never noticed. 😅

2021-06-19 19:08 UTC, CalebSerafin commented on Tools/NavGridPP/functions/StreetArtist/fn_NGSA_EH_add.sqf
> +_gameWindow displayAddEventHandler ["MouseButtonDblClick", {
Probably not. But I couldn't find a way to block double click regardless of gameWindow, map window, map control and displayEH, controlEH combinations. So I'll remove it completely as it's ineffective. (Pretty sure like one of them worked before Arma 3 version 2.04 🤔)

2021-06-19 20:10 UTC, HakonRydland approved these changes
Everything looks good now

2021-06-20 23:31 UTC, CalebSerafin commented
Should do with a test to confirm that the changes did not do a funny.

2021-06-21 13:08 UTC, HakonRydland commented
> Should do with a test to confirm that the changes did not do a funny.

okay found an issue, drawing is not fully blocked, only on first draw attempt (when holding ctrl down with multiple mouse presses)

2021-06-21 13:22 UTC, HakonRydland commented
everything else seems to be working fine

2021-06-21 13:35 UTC, CalebSerafin commented
As far as I could test the following clicks are not blockable. Don't know why. If in the future someone finds a way I will jump to add it.

2021-06-21 13:40 UTC, CalebSerafin commented
> it clears the fact ctrl is pressed and therefore prevents it from blocking drawing, think it could be fixed by checking for the EH argument for ctrl in `fn_NGSA_onKeyDown.sqf`, and if it was unreliable then check both maybe?

Hmm, yes. I could probably block all cases where shift, alt, ctrl is pressed on keyDown. Mouse down can still getaway on the second press though.

2021-06-21 14:20 UTC, HakonRydland commented
last commit solved the two raised issues.

as a side note, the drawing solution was deletion after creation, as we were unable to find a way to reliably prevent drawing in the first place, this is something that can be improved upon if someone would like, but is not a necessity for the merger of this PR

2021-06-24 07:56 UTC, Bob-Murphy approved these changes
Tested the system on the map Kujari and it worked wonderful.
Big thumbs up, merging it shortly.

2021-06-25 20:59 UTC, merged