Add new param to scale the time limits for tasks
official-antistasi-community/A3-Antistasi pull request #1965
Opened 2021-05-29 00:08 UTC by ralreegorganon

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?

Many of the mission time limits are essentially unachievable on Cam Lao Nam when playing with the VN DLC, particularly with a smaller player count. There is some precedence for explicitly scaling the time limits based on loaded content, as seen here:
https://github.com/official-antistasi-community/A3-Antistasi/blob/dc7e93be3718f7dbd5edb768b388819687991812/A3-Antistasi/functions/Missions/fn_AS_Official.sqf#L16
but it seemed like this could be more flexible and more easily adjusted to taste with a parameterized multiplier rather than hardcoding a specific multiplier for specific optional content.

I've added this param and set it up with 1x (existing value as default), 2x, 3x, 4x and 8x multipliers. This seemed to give a good spread of options for the various missions, resulting in times as seen below. No modifications to the actual previously defined times have been made for this--it's simply applying a global modifier to them.

| mission               | 1x (std, difficult) | 2x         | 3x         | 4x         | 8x         |
| --------------------- | ------------------- | ---------- | ---------- | ---------- | ---------- |
| A3A_fnc_AS_Official   | 15, 30              | 30, 60     | 45, 90     | 60, 120    | 120, 240   |
| A3A_fnc_AS_Traitor    | 30, 60              | 60, 120    | 90, 180    | 120, 240   | 240, 480   |
| A3A_fnc_AS_SpecOP     | 60, 120             | 120, 240   | 180, 360   | 240, 480   | 480, 960   |
| A3A_fnc_CON_Outpost   | 30, 90              | 60, 180    | 90, 270    | 120, 360   | 240, 720   |
| A3A_fnc_DES_Vehicle   | 30, 120             | 60, 240    | 90, 360    | 120, 480   | 240, 960   |
| A3A_fnc_DES_Heli      | 120                 | 240        | 360        | 480        | 960        |
| A3A_fnc_DES_antenna   | 30, 120             | 60, 240    | 90, 360    | 120, 480   | 240, 960   |
| A3A_fnc_LOG_Ammo      | 30, 60              | 60, 120    | 90, 180    | 120, 240   | 240, 480   |
| A3A_fnc_LOG_Bank      | 60, 120             | 120, 240   | 180, 360   | 240, 480   | 480, 960   |
| A3A_fnc_LOG_Salvage   | 30, 60              | 60, 120    | 90, 180    | 120, 240   | 240, 480   |
| A3A_fnc_LOG_Supplies  | 30, 60              | 60, 120    | 90, 180    | 120, 240   | 240, 480   |
| A3A_fnc_RES_Refugees  | 30, 60              | 60, 120    | 90, 180    | 120, 240   | 240, 480   |
| A3A_fnc_RES_Prisoners | 30, 120             | 60, 240    | 90, 360    | 120, 480   | 240, 960   |
| A3A_fnc_convoy        | 0 or 5-10           | 0 or 10-20 | 0 or 15-30 | 0 or 20-40 | 0 or 40-80 |

### Please specify which Issue this PR Resolves.

N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?

Set the modifier (or leave as default) and request missions from Petros. Verify the times fall within the expected ranges given the game state and selected parameters.

2021-05-29 09:12 UTC, Bob-Murphy commented
Good idea.
Nevertheless, we maybe can scale down the choices a bit. Especially the *8 is kinda too much in my personal opinion.
Also, I don't think that at least the convoy and rescue missions should not have that massive times.
Will talk about it with a few other devs.

2021-05-29 16:16 UTC, ralreegorganon commented
> Nevertheless, we maybe can scale down the choices a bit. Especially the *8 is kinda too much in my personal opinion.

I don't have a particular attachment to the values and was just trying to provide a range, so I've struck 8x from the list.

> Also, I don't think that at least the convoy and rescue missions should not have that massive times.

The convoy mission is actually one of the ones that prompted me to look into this in the first place. We spawned a convoy mission from our HQ as noted here, and it gave us 5 minutes, when it would depart from the noted convoy start heading towards the noted convoy end (with most everything in between us hostile):

![image](https://user-images.githubusercontent.com/11464/120076883-41e14400-c054-11eb-960f-dddd70521192.png)

With the road network and vehicle options in the VN CDLC, it was pretty much impossible. 

I do see the convoy mission is being reworked in #1917 and that may help some, given it notes that it will make the following changes:
* Target selection uses much closer targets so you don't have to drive 8km to reach the convoy.
* Source selection prefers medium distances to allow more intercept options.
* Convoy units spawn immediately but have a 5-20 minute travel delay.

We didn't run into an impossible rescue yet, but in general I wasn't trying to make any judgements on the amount of time provided and more was looking at it as the base values at 1x being the designed gameplay experience, with the multiplier being just a pressure release valve when those times don't work for the given set of players or content. In our case, we're playing Cam Lao Nam with only the SOG gear and vehicles, with 3 or 4 players, who like methodical play. A majority of the missions have just ended up being a mad rush to transit the map, turning what could be fun missions into a bit of a comedy show.

![image](https://user-images.githubusercontent.com/11464/120077138-5bcf5680-c055-11eb-966c-1d63a19b0375.png)

2021-06-01 12:11 UTC, Bob-Murphy commented
Solid feedback, I like that.
I certainly see the issue here.
Maybe we can think about adding a map specific multiplier but for that we should do some other stuff before that, but that would be my topic, not one for you.
Thank you so far.

2021-06-08 21:00 UTC, CalebSerafin commented
I like the idea of a general time scalar. It can allow players to be more casual or turn up the heat and act on the moment.

2021-06-28 12:39 UTC, HakonRydland requested changes
idea is ok i guess, but execution could be refined

2021-06-28 12:39 UTC, HakonRydland commented on A3-Antistasi/functions/Missions/fn_AS_Official.sqf
>  if (A3A_hasIFA) then {_timeLimit = _timeLimit * 2};
this could be better
```suggestion
_timeLimit = 15 * taskTimerMultiplier * (2 * ({_x} count [A3A_hasIFA, _difficultX]));
```
the formula is `Base timer * glob modifier * 2 per true other boosters` (currently the boosters are only difficultX and ww2)

2021-06-28 20:59 UTC, ralreegorganon commented on A3-Antistasi/functions/Missions/fn_AS_Official.sqf
>  if (A3A_hasIFA) then {_timeLimit = _timeLimit * 2};
Don't disagree that the equations could be further refactored. I purposefully tried to change as little as possible here, and to change every one of them in the same way, rather than refactoring all of the time limit calculations, in hopes of an easy review and integration. If I was going to refactor them, I'd prefer to push more of it data driven rather than having scalars littered all over the place anyway. 

At this point I've already made the change in my local fork for play, and I don't see much interest here for having this available, so maybe the need is unique to my playgroup.

2021-06-28 21:00 UTC, ralreegorganon commented
This needs a rebase after the convoy updates, and there doesn't seem to be much interest in the idea in general so I'll just keep my local patch.

2021-06-28 21:00 UTC, closed without merging

2021-06-28 21:59 UTC, Bob-Murphy commented
@ralreegorganon I am slightly confused on why you closed the PR.
It think that the idea is a good one which gives options to adjust especially for single players as well as smaller communities and you received feedback on how to improve it.
Please don't take long answer times or such as "not much interest" but please keep in mind that we are also only working on Antistasi in our free time and we are working on other stuff/issues/topics ourselves.

2021-06-28 23:37 UTC, ralreegorganon commented
@Bob-Murphy I'm not concerned about long answer times, I've got a long history of contributing to and maintaining busy open source projects and am no stranger to having things wait and need to rebased and reworked, and have certainly had my turn inflicting that on others. That's not a problem in the least.

I disagree that @HakonRydland's feedback is much of an improvement--if they would look at all the existing tasks being modified here, they are not always having their durations doubled (sometimes it's tripled, sometimes it's quadrupled) and so the formula proposed as an improvement is not actually applicable for all cases, is just churn at best, and mostly seems like bikeshedding. 

If the directive from the maintainers here is to go refactor all the time calculations for these tasks, I don't disagree that's a useful goal and the whole thing could probably benefit from a more data driven and holistic approach that can be shared by the tasks rather than the way they've accumulated constants and multipliers in a more ad hoc fashion... but that's not something I have the time for right now, and taking on something more invasive like that was never my goal with this PR to begin with--I had a need, made the change to my fork so I could play with it, and figured I couldn't have been the first person to have that problem and thus sent the patch upstream.

As it stands, it needs to be rebased to accommodate the convoy changes that were just merged yesterday. I simply don't and won't have the time to review those and adjust accordingly for awhile. I basically closed this because the alternative is that it sits open for an indefinite time and someone thinks I'm doing something with it rather than just making the change themselves--the actual changes (unless someone refactors all the equations and/or takes a different approach) are so trivial that there's nothing really special about this PR.

If I get more free time and something like this isn't integrated by then, I may take another swing at it--I just don't want anyone waiting on me.

2021-06-28 23:45 UTC, Bob-Murphy commented
Thank you very much for the additional answer.
I myself don't have that deep knowledge about the code as that's not my job within the team so I can't say anything towards that.
What I fully understand on the other hand are personal time constraints, setting priorities on other topics than Antistasi and seeing certain tasks out of scope for what you initially intended.
Luckily the changes won't be deleted (I love GitHub for that) and I hope that either we or you will revisit that topic.

So the only thing left is me saying Thank you for contributing, even if it didn't get merged, and all of success with your other projects :)

2021-06-28 23:49 UTC, HakonRydland commented
I fully understand that, and admittedly didnt take a close look at all the multipliers that were in all the missions, mainly as the missions are extremely likely to receive a major rework if not fully removed in favor of other missions in the *relative* short future.

Regardless thank you for the PR.