Add Signal Smoke Grenades / FlagMarkers / Update Equipment
official-antistasi-community/A3-Antistasi pull request #1969
Opened 2021-05-30 15:19 UTC by Lazejun

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Added SignalSmokeGrenades to Templates and gave them to Squadleader,
Removed Colored smoke from Normal Smoke grenades and move them to SignalSmokeGrenades.

Added new AFRF Gear from #1882 to Arid, slight changes to the Temperate Template.

Added FlagMarkerType to Rebell Factions, this was already done for VN, but not for the other Factions.
Changed FIA and Napas Flagtexture to the FIA Flag.

Selector:
Changed Log Message to Template instead of Templates,
Added a Case for Worldname Altis in Vanilla to use the AAF Template as Occupants.

AAF Template:
Added a SniperRifle for the Militia Sniper, this was missed and would have left him with just his Pistol.

Nato Arid Template:
Changed one wrong Scope to the Normal Variant,
Changed one Pistol to the Tan Variant.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Play against AFRF and look at their Shiny new Gear,
As SignalSmokes are only given to SLs you could spawn some and look in their Inventory:
```sqf
//Some OCC Militia Units
[group player, "loadouts_occ_military_SquadLeader", getpos (player)] call A3A_fnc_createUnit;
[group player, "loadouts_occ_military_Rifleman", getpos (player)] call A3A_fnc_createUnit;
[group player, "loadouts_occ_military_Medic", getpos (player)] call A3A_fnc_createUnit;
[group player, "loadouts_occ_military_Engineer", getpos (player)] call A3A_fnc_createUnit;

//This is for your Own Safety
group player setCombatMode "BLUE";
group player setBehaviourStrong "CARELESS";
{
_x disableAI "TARGET"; 
_x disableAI "AUTOTARGET";
_x setspeaker "novoice";
_x stop true;
_x setCaptive true;
} forEach units group player;
```
********************************************************
Notes:

2021-06-04 01:40 UTC, jaj22 requested changes
Just the shotgun consistency thing really. I'll miss the random smoke colours but they were a bit silly.

2021-06-04 01:40 UTC, jaj22 commented on A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
> +_policeLoadoutData setVariable ["shotgun", [
Should probably be `shotguns`, for consistency. All the other vars are plural.

2021-06-04 01:40 UTC, jaj22 commented on A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
> +_militaryLoadoutData setVariable ["GLvests", ["rhs_6b45_grn"]];
I feel like players are gonna be complaining about invincible russians, but whatever.

2021-06-05 17:51 UTC, Lazejun commented on A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf
> +_policeLoadoutData setVariable ["shotgun", [
Updated All to shotguns

2021-06-05 19:28 UTC, jaj22 approved these changes

2021-06-08 10:31 UTC, merged