2.5.0 preliminary changelog
official-antistasi-community/A3-Antistasi pull request #2030
Opened 2021-08-04 13:06 UTC by Bob-Murphy

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-08-04 13:24 UTC, CalebSerafin commented on changelog.txt
> +  - fully localised garage hints
Did we add many translations for the garage text, or did add localisation keys for all of the garage text?

2021-08-04 13:33 UTC, Bob-Murphy commented on changelog.txt
> +  - fully localised garage hints
keys are added, no translations. I'll clarify that.

2021-08-04 15:02 UTC, HakonRydland requested changes

2021-08-04 15:02 UTC, HakonRydland commented on changelog.txt
> +
should mention the license of the new garage and SA

2021-08-04 16:24 UTC, Bob-Murphy commented on changelog.txt
> +  - fully localised garage hints (no translations added yet)
done

2021-08-04 16:24 UTC, Bob-Murphy commented on changelog.txt
> +
done

2021-08-04 16:30 UTC, HakonRydland approved these changes

2021-08-05 21:38 UTC, CalebSerafin approved these changes
Looks good

2021-08-07 11:03 UTC, merged