Toggle top information string visibility while opening/closing garage
official-antistasi-community/A3-Antistasi pull request #2041
Opened 2021-08-08 13:12 UTC by igorkis-scrts

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Since top string basically has no use inside the garage menu, i think that it should be hidden while player interacting with the garage menu. Also, top string intersects garage UI controls.

Before:
![b](https://user-images.githubusercontent.com/6746043/128633077-db9da726-2cc2-42f3-8e20-5e6bb0117ff5.jpg)

After:
![a](https://user-images.githubusercontent.com/6746043/128633081-4d375106-ac13-4d25-86c8-610c0e325c6b.jpg)

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
- Open and close new garage at any friendly flagpole or red vehicle box.
********************************************************
Notes:

2021-08-09 17:37 UTC, HakonRydland commented
this would work, but im thinking that it maybe should be expanded to be more safe with other functions calling the toggle in the future.
maybe a registre with the system disabling the hud and its state being passed as parameters...
and also allow for the hud toggle to be made togglable permanently by the user?

also @doommetal are you doing anything with this for the UI rework, the concept is def good so if not then consider looking at this before merging the UI rework.

Example:
- Functions
  - disableInfoBar: handles registering the systems wanting to disable the UI and removing them from the list
  - updateInfoBarShown: checks if it should hide/show the bar based on the registra.

disableInfoBar:
```sqf
params [["_systemName",""], ["_state",false,[false]]];

if (_isNil "A3A_InfoBarRegistre") then {A3A_InfoBarRegistre = createHashMap};
if (_state) then {
    A3A_InfoBarRegistre set [_systemName, _state];
} else {
    A3A_InfoBarRegistre deleteAt _systemName;
};
call A3A_fnc_updateInfoBarShown;
```
updateInfoBarShown:
```sqf
if (isNil "A3A_InfoBarRegistre") exitWith {};
private _state = if (count A3A_InfoBarRegistre isEqualTo 0) then {true} else {false};

private _display = uiNameSpace getVariable "H8erHUD";
private _control = _display displayCtrl 1001;
_control ctrlShow _state;
```

2021-08-09 18:03 UTC, HakonRydland commented
as for garage implementing the feature, it should not be done directly in the core files, but in an event raised by the core files, for load the existing onOpenEvent would be the one to use, see config.inc
a equivalent onCloseEvent could be added too for toggling it back on

2021-08-10 16:29 UTC, HakonRydland requested changes

2021-08-10 16:29 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_onLoad.sqf
> +
Move to event in config.inc

2021-08-10 16:29 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_onUnload.sqf
> +
add onClose event and add this to it in config.inc

2021-08-10 17:18 UTC, igorkis-scrts commented on A3-Antistasi/Garage/Core/fn_onLoad.sqf
> +
Fixed in 4f9f6951def8b9f480cde547adacc5c04df3df81

2021-08-10 17:18 UTC, igorkis-scrts commented on A3-Antistasi/Garage/Core/fn_onUnload.sqf
> +
Fixed in 4f9f6951def8b9f480cde547adacc5c04df3df81

2021-08-10 17:24 UTC, igorkis-scrts commented
About changes you suggested above - it is great idea, but i think that it should happen after UI rewrite, as this suggested code will be heavily modified or straight up removed, making PR irrelevant.

2021-08-10 17:36 UTC, HakonRydland commented
> About changes you suggested above - it is great idea, but i think that it should happen after UI rewrite, as this suggested code will be heavily modified or straight up removed, making PR irrelevant.

the top bar wouldnt be touched by the rework, talked with doom the suggested approach would be fine as the new ui toggle top bar functionality would just call the function

2021-08-10 18:47 UTC, igorkis-scrts commented
Implemented it, also as a side gig (and to test new system) implemented the ability to toggle info bar visibility via keyboard in the  usual gameplay.

2021-08-10 18:55 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +#define KEY_INSERT 210
we should use the DIK codes in the define see https://community.bistudio.com/wiki/DIK_KeyCodes
also recommend scroll lock instead of insert as that is a actually useless key

2021-08-10 18:57 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +
also tabs -> spaces ( we use 4 spaces for each tab indentation)

2021-08-10 18:59 UTC, igorkis-scrts commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +#define KEY_INSERT 210
I think that scroll lock will not fit as it is not present on all keyboards (especially on laptop ones). Maybe HOME button will fit?

2021-08-10 19:01 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +#define KEY_INSERT 210
yea maybe, for now

2021-08-10 19:01 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +#define KEY_INSERT 210
also to clarify i meant use the includes of the defines

2021-08-10 19:04 UTC, HakonRydland commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +#define KEY_INSERT 210
and apparently theres some ace conflicts with just home, so we should do alt + home

2021-08-10 19:14 UTC, igorkis-scrts commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +#define KEY_INSERT 210
Fixed in 42d2126763025384ac3a36b6a2f9d5f7efa3b246

2021-08-10 19:14 UTC, igorkis-scrts commented on A3-Antistasi/functions/Base/fn_keys.sqf
> +
Fixed in 42d2126763025384ac3a36b6a2f9d5f7efa3b246

2021-08-10 20:16 UTC, igorkis-scrts commented
whoops, brb

2021-08-10 20:20 UTC, igorkis-scrts commented
fixed

2021-08-10 20:27 UTC, HakonRydland approved these changes
should be fine now

2021-08-10 20:30 UTC, CalebSerafin commented
Is the key-bind written somewhere in the wiki or does it come up in a tool-tip? How will players discover it?

2021-08-10 20:34 UTC, HakonRydland commented
> Is the key-bind written somewhere in the wiki or does it come up in a tool-tip? How will players discover it?

its a secret ;)
serious now its likely to be replaced by UI before next release, could add it to the diary entries. think theres one for the earplugs, not that anyone actually reads those

2021-08-10 20:35 UTC, CalebSerafin commented
Okay 👍 We can integrate it with other buttons (and maybe other new key-binds)

2021-08-10 20:36 UTC, CalebSerafin commented
I'm creating an issue to document this problem.

2021-08-11 21:42 UTC, merged