made custom JIP keys for Logistics system
official-antistasi-community/A3-Antistasi pull request #2078
Opened 2021-08-22 12:43 UTC by HakonRydland

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information: due to object based jip keys overwriting each other some actions on statics were being blocked from being added for jip clients,
this fix adds a custom jip key and null object handling to the logistics system as a band aid as currently the only actions that ***we know*** are conflicting are the logistics and garrison static manning actions.
in the future we might want to consider other possibilities to prevent this from happening again.

### Please specify which Issue this PR Resolves.
closes #2072 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-08-22 13:34 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +    remoteExec ["", 0, _jipKey]; //clear custom JIP
Wiki quotes the syntax for this as simply:
`remoteExec ["", _jipKey]`

However, as addAction is client-executed and logically this needs to be executed on the server, it's unclear what the syntax would be. I don't know if you tested whether this works or you have better info. Otherwise I'll poke around with it on my local DS.

2021-08-22 13:42 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +    remoteExec ["", 0, _jipKey]; //clear custom JIP
no i made a assumption based on the syntax of remoteExec that apparently was wrong, corrected

2021-08-22 14:34 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +    remoteExec ["", 0, _jipKey]; //clear custom JIP
Do you know if it works when executed on a client though? Wiki doesn't hint either way.

2021-08-22 15:16 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +    remoteExec ["", 0, _jipKey]; //clear custom JIP
havent tested it no, but as i didnt see anything about it on the wiki i assume it handle managing the list, including on what machine to modify the list on

2021-08-22 16:52 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf
> +    remoteExec ["", 0, _jipKey]; //clear custom JIP
Such optimism :P

I tested though and it does actually work. I guess it makes sense given that you can add entries to the JIP queue with remoteExecs from clients, so logically it should know how to remove them too.

2021-08-22 17:13 UTC, jaj22 commented
I think the addWeaponAction remoteExec in logistics_load also needs the same treatment, although it's a less common case (load, unload, reconnect, no static actions).

If I'm reading it right, the unload case was an internal JIP conflict? If you loaded a surrender crate onto a quadbike, you would then lose the JIP that enabled loading the quadbike onto a transport. I don't suppose anyone noticed that one.

2021-08-22 17:26 UTC, HakonRydland commented
good catch fixed

2021-08-22 19:05 UTC, jaj22 requested changes
Extra stuff:

1. The two toggleLock remoteExecs in logistics_unload are also squashing JIPs. I think the easy fix for these is to simply remove the JIP from them, as the lock commands are local argument global effect anyway, so locks on any vehicle will persist for joining players anyway.

2. removeWeaponAction is removing the wrong JIP.

2021-08-22 19:05 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf
> +private _jipObject = toArray str _vehicle;
_vehicle should be _object

2021-08-22 19:47 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
> +_jipKey = "A3A_Logistics_" + _action + "_" + toString _jipObject;
the lock needs to stay due to inconsistent behavior that was found when it was implemented. updated (add/Remove)WeaponAction and toggle lock with custom keys and proper clearing

2021-08-23 01:08 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
> +_objStringCargo = toString _objStringCargo;
On these, why not `str _cargo splitString ":" joinString ""`? I think the only output difference is that it removes all colons rather than just the first, but that doesn't seem like a bad thing. Not 100% sure why you're removing the colon anyway.

2021-08-23 02:09 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
> +_objStringCargo = toString _objStringCargo;
objects strings contain one colon, for JIP keys when its a string and it finds a colon it thinks it is a net id, this will therefore break the JIP of the remote execution if its left in.
as for the alternate way, im not sure which would be more performant, both methodes creates an array of equal lenght, but they would be rather close i would think. i suppose the alternate way is more compact

2021-08-23 02:31 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
> +_objStringCargo = toString _objStringCargo;
Perf is 0.0044 for the long version and 0.0027 for the splitstring/joinstring with a loot crate here.  Mostly suggested it for the compactness though.

2021-08-23 02:35 UTC, HakonRydland commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf
> +_objStringCargo = toString _objStringCargo;
👍 ill make the changes

2021-08-23 02:38 UTC, jaj22 commented on A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf
> +params [["_vehicle", objnull, [objNull]], ["_cargo", objnull, [objNull]], , ["_jipKey", "", [""]]];
Extra blank parameter before the jipKey here.

2021-08-23 02:56 UTC, jaj22 approved these changes
Gave it a final test run on DS+client, everything seems to work.

2021-08-25 16:35 UTC, merged