removed random selection for construction
official-antistasi-community/A3-Antistasi pull request #2094
Opened 2021-08-26 21:45 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Changed the random selection process to no longer existing. I got rid of it. The player will now know what they are constructing instead of finding out that they can only build tree logs barricades. I changed the initial build from 60 seconds to 45, and Added a check for a toolkit in the player inventory. The check decreases the time required to build structures. 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-09-14 22:08 UTC, CalebSerafin requested changes
Pretty good addition and simplification. Just a few comments.

2021-09-14 22:08 UTC, CalebSerafin commented on A3-Antistasi/functions/REINF/fn_buildCreateVehicleCallback.sqf
>  	build_time = build_time / 2;
To make it more noticeable that this is a global variable, it could be refactored to `A3A_build_time`. From my search, there are 5 references in `build` and 5 in `buildCreateVehicleCallback`.

2021-09-14 22:08 UTC, CalebSerafin commented on A3-Antistasi/functions/REINF/fn_build.sqf
> +		_classX = "Land_Bunker_01_tall_F";
This will be a cool change that allows the rebels to gain a verticle view without playing head-stacking. Rebels will no longer be able to play turrets on top, but that's fine as it did not make the turrets any more effective.

2021-09-14 22:08 UTC, CalebSerafin commented on A3-Antistasi/functions/REINF/fn_build.sqf
> +build_time = 45;
To make the code more explicit, we could set the build time to 45 in the "ST" case. Because in all other cases it is over-written. It does not need to be defined in this parent scope because it is a global variable.

2021-09-23 07:08 UTC, killerswin2 commented on A3-Antistasi/functions/REINF/fn_build.sqf
> +build_time = 45;
Simulations are enabled when loading buildings from save.

2021-09-29 01:40 UTC, CalebSerafin approved these changes
Good 👍

2021-10-12 11:29 UTC, merged