Made HC squads vehicle placement use the garage placement
official-antistasi-community/A3-Antistasi pull request #2108
Opened 2021-08-29 21:40 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
- Reworked confirmPlacement to be easier to use externaly;
also removed some unnecessary statements.
- altered confirmPlacement and callbackHandler to accept external arguments.
- added a new case for addFIAsquadHC to callbackHandler
- made addFIAsquadHC use garage placement.

### Please specify which Issue this PR Resolves.
closes #2073 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-08-30 16:20 UTC, jaj22 commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +    6. <Bool>   use garage vehicle pool for placement (optional: default true)
This defaults to false now, right.

2021-08-30 16:50 UTC, HakonRydland commented on A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf
> +    6. <Bool>   use garage vehicle pool for placement (optional: default true)
yes forgot to update header

2021-08-30 17:20 UTC, jaj22 commented on A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf
> +["B_G_Van_01_transport_F", "SquadVehicle", _groupX] call HR_GRG_fnc_confirmPlacement;
This code only used `B_G_Van_01_transport_F` as a proxy vehicle for findEmptyPosition, possibly because it works even less well for other vehicles. Should be passing `_typeVehX` here instead.

2021-08-30 17:24 UTC, Lazejun reviewed
The problem with using Garage Placement now is that it will allow you to Place any of the Vehicles anywhere any time when buying them.

Just to show, i am pretty far from my HQ.
![107410_20210830191815_1](https://user-images.githubusercontent.com/57111907/131379326-f94f8110-31a8-4510-8567-9dc114fafa95.png)

2021-08-30 17:32 UTC, HakonRydland commented
yea not sure how to deal with that

2021-08-30 17:38 UTC, Lazejun commented
If i read the issue correct, this should probably include all HC Vehicles.

Currently its only the Groups with the "Hey would you like a Vehicle to that" Pop up.

2021-09-05 16:59 UTC, Lazejun reviewed
Placement seems fine, Units get in their Vehicles after placement.

This is probably Dead code, especially as we have an AT Car for RHS
https://github.com/official-antistasi-community/A3-Antistasi/blob/da45de01debae1efe20bdbec1a07b20cb68fb9eb/A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf#L19-L23

There might be possible confusion with the near HQ Check as its only triggered upon pressing any the Buttons on the Squads, while the You dont have a Radio check triggers when pressing the Recruit button.
https://github.com/official-antistasi-community/A3-Antistasi/blob/14d1505a278e0b198fa79962436c400f50766796/A3-Antistasi/functions/Dialogs/fn_squadRecruit.sqf#L2

2021-09-05 18:23 UTC, Lazejun commented on Map-Templates/Antistasi-Altis.Altis/mission.sqm
>  	};
This sneaking in 👀

2021-09-05 18:38 UTC, HakonRydland commented on Map-Templates/Antistasi-Altis.Altis/mission.sqm
>  	};
damned symlink and quick commits 😄

2021-09-06 19:34 UTC, Lazejun approved these changes
Doesent seem to Catch fire,

Placement near HQ (50 meters) is manual Placement,
further away is auto placement, which seems to work most of the time.

2021-09-07 13:55 UTC, jaj22 requested changes
The auto-placement method can be pretty bad even without explosions, because findEmptyPosition searches near the center first, which is generally not where you want HC squads to park their vehicles.

Unfortunately findEmptyPosition [20, 70, _vehtype] doesn't work for some reason. A quick-ish workaround would be something like this:

```
_searchCenter = (markerPos "Synd_HQ") getPos [40, random 360];
_pos = _searchCenter findEmptyPosition [0, 30, _vehType];
```

However, note that findEmptyPosition can and does fail, so it needs some kind of fallback placement, or an error/refund case.

**Edit:** Fixed missing _searchCenter on second line.

2021-09-11 13:52 UTC, jaj22 approved these changes

2021-09-14 14:52 UTC, merged