Quick rework of punishment attacks
official-antistasi-community/A3-Antistasi pull request #2119
Opened 2021-09-02 16:33 UTC by jaj22

### What type of PR is this.
1. [X] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Ended up rewriting most of the punishment function:
- Punishment attacks no longer sent against occupant-controlled towns.
- Player scaling added to delay time and attacker vehicle count.
- Improved vehicle choice and maxUnits control, ensure 2+ transports.
- Defender ("civilian") count non-linearised, splits to groups of 4.
- Removed civInit from defenders, so that they shoot and don't affect aggro.
- Use combat landing in preference to fastrope, remove slow landing.
- Simplified termination conditions.
- Results only adjust support of nearby cities.

Plus some fixes to how destroyed cities are handled:
- Destroyed cities are now coloured black on the map.
- Destroyed cities are now invader-side, to prevent some weird spawning.
- Destroyed cities no longer switch side, provide rebel HR or resources.

Review notes:
The resourceCheck changes are just a reorder and an early breakout for destroyed cities.

### Please specify which Issue this PR Resolves.
closes #2117
Probably some older stuff too.

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Haven't tested invaders with transport planes yet.

### How can the changes be tested?
Example for an Altis start. You'll need to flip a suitable city to rebel first:
```
_town = "Molos";
[-100,100,_town,false] spawn A3A_fnc_citySupportChange;
sidesX setVariable [_town,teamPlayer,true]; 
_mrkD = format ["Dum%1",_town]; 
_mrkD setMarkerColor colorTeamPlayer; 
garrison setVariable [_town,[],true];
[_town, "airport_2"] spawn A3A_fnc_invaderPunish;
```
Watch in Zeus. You probably want to set a higher war tier first so that Invaders can actually shoot straight-ish, otherwise it'll take a while.

Note that the start delay is ~10 mins for a single player, so you may want to reduce that for testing.

2021-09-02 23:19 UTC, jaj22 commented
Clarification: The start delay is the `sleep (60*5 / _playerScale)`, not the `_minMissionTime = 600`.

2021-09-03 16:57 UTC, HakonRydland requested changes
code looks mostly good

2021-09-03 16:57 UTC, HakonRydland commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +    if (not(_typeAirVehicle in _invaderAirTransport)) then {
probably faster to check if its in `_invaderAttackHelis`

2021-09-03 16:57 UTC, HakonRydland commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +        private _mineX = createMine ["APERSMine",_posDestination,[],_size];
we have mines defined in templates `minefieldAPERS`

2021-09-03 17:08 UTC, Lazejun commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +            [_civ, selectRandom (unlockedmachineguns + unlockedshotguns + Unlockedrifles + unlockedsmgs), 5, 0] call BIS_fnc_addWeapon;
In theory might not be a problem/will rarely happen, but with Rebell Templates that only have "Sniperrifles" as starting gear the Machinegun case will spawn unarmed Civs

2021-09-03 17:14 UTC, Lazejun approved these changes
Timeout for Low Playercount etc. is a nice idea, hopefully people won't assume something broke because nothing spawned yet.

Hakon already mentioned the Mines.

Civs do a pretty good Job at defending themself, and they even have a Higher skill than INV Units on Low War levels, helps with surviveability.

During my Test some Groups used SAD and Hold waypoints which seems ok too.

Seems like a good improvement overall.

Notes for the Rabbit hole:
Due to Attack Helicopters using SAD Waypoints and them being spawners, they might spawn nearby Outposts, engage those and spawn more Outposts on each strave run they do.

2021-09-03 19:46 UTC, jaj22 commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +        private _mineX = createMine ["APERSMine",_posDestination,[],_size];
Yeah, but they don't work for save/load at the moment, do they? loadStat has a fixed list of vanilla mines for the ammo-to-vehicle translation. Need to deal with that properly at some point but until then I'm inclined to leave it kind-of-working, at least for minefields that should be permanent.

2021-09-03 19:47 UTC, jaj22 commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +    if (not(_typeAirVehicle in _invaderAirTransport)) then {
Could do. I don't think I'm going to have a change of heart anytime soon and bring back the useless aircraft.

2021-09-03 19:49 UTC, jaj22 commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +            [_civ, selectRandom (unlockedmachineguns + unlockedshotguns + Unlockedrifles + unlockedsmgs), 5, 0] call BIS_fnc_addWeapon;
I'll switch it to my randomRifle function that has better fallbacks.

2021-09-03 19:56 UTC, jaj22 commented
> Due to Attack Helicopters using SAD Waypoints and them being spawners, they might spawn nearby Outposts, engage those and spawn more Outposts on each strave run they do.

Yeah, it happens. Ideally the attack target selection shouldn't be attacking locations that are closely defended by outposts, and SAD behaviour absolutely sucks for attack-support purposes so we should have our own AI routine for it, but that's all future work.

2021-09-04 07:57 UTC, HakonRydland commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +        private _mineX = createMine ["APERSMine",_posDestination,[],_size];
easy fix, move away from createmine and you dont need the mine vehicle class -> `createVehicle [_typeMine_, _posMine, [], 0, "CAN_COLLIDE"]`

2021-09-04 14:32 UTC, jaj22 commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +        private _mineX = createMine ["APERSMine",_posDestination,[],_size];
Neat, that actually works. Shows up in allMines rather than vehicles, still blows up when you stand on it.

Still kinda out of scope but it's simple enough that I may as well throw it in.

2021-09-04 17:05 UTC, jaj22 commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +        private _mineX = createMine ["APERSMine",_posDestination,[],_size];
Potential problem. I think the current code is effectively dumping anything that isn't in its conversion list (createMine just throws config errors on CfgAmmo classes), while with createVehicle everything will work. Therefore UXOs could balloon the save file and potentially cause in-game perf problems over time.

I'll cap the mine saving to ~500 random mines.

2021-09-04 18:31 UTC, jaj22 commented
Minefield rabbit hole stuff:
- invaderPunish now uses mines from the faction template.
- Loaded mines now work for all mine types rather than a fixed list.
- Saved mines randomly culled down to ~500 to prevent ballooning.

Minor review tweaks;
- Flipped the attack heli vs transport branch.
- Simplified civ weapons to plain random from unlocks.

2021-09-04 18:38 UTC, HakonRydland approved these changes
Looks good

2021-09-14 14:59 UTC, merged

2022-03-11 05:56 UTC, Rowantrek commented on A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
> +private _playerScale = (8 + count (allPlayers - entities "HeadlessClient_F")) / 17;
It would be best practice to use the A3A_fnc_getPlayerScale for this - unless there is a specific reason for not calling to it. Just a small change note.