Fix cheap rebel AA trucks
official-antistasi-community/A3-Antistasi pull request #2151
Opened 2021-09-27 02:43 UTC by jaj22

### What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Both constructed and single-vehicle AA trucks were being underpriced on purchase due to not calculating truck + static AA costs as the other code did. This PR fixes this for both cases with a horrible hack.    

### Please specify which Issue this PR Resolves.
closes #2150

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

2021-09-29 22:51 UTC, jaj22 commented
Found a bunch more pricing bugs, don't merge yet.

2021-10-01 16:38 UTC, HakonRydland requested changes
one small change and a clerification

2021-10-01 16:38 UTC, HakonRydland commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			_resourcesFIA = _resourcesFIA + ([typeOf _x] call A3A_fnc_vehiclePrice);
would likely tose a lot of errors in the rpt for undefined vehicle prices (should fix vehiclePrice)

2021-10-01 16:38 UTC, HakonRydland commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			if (!isNull (assignedVehicle _x) and {isNull attachedTo (assignedVehicle _x)}) then
blocking quads loaded, correct?

2021-10-01 17:14 UTC, jaj22 commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			if (!isNull (assignedVehicle _x) and {isNull attachedTo (assignedVehicle _x)}) then
Issue was that the AA launchers on the vanilla AA truck were being counted twice: Once from the assigned list and once from the attached objects. Apparently deleteVehicle is not instant.

2021-10-01 17:17 UTC, jaj22 commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			_resourcesFIA = _resourcesFIA + ([typeOf _x] call A3A_fnc_vehiclePrice);
I figured that function just returned zero, but yeah. The whole vehicle value/price system needs a rework but I'll just check vehFIA for the moment.

If people attach random stuff to HC vehicles then that's their problem if it gets deleted without a refund, I guess.

2021-10-01 17:17 UTC, HakonRydland commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			if (!isNull (assignedVehicle _x) and {isNull attachedTo (assignedVehicle _x)}) then
oh yea (delete vehicle takes a frame i think to clear references, but despawn is instantly i think

2021-10-01 17:19 UTC, HakonRydland commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			_resourcesFIA = _resourcesFIA + ([typeOf _x] call A3A_fnc_vehiclePrice);
i mean could just get rid of the error, or change it to verbose

2021-10-01 17:39 UTC, jaj22 commented on A3-Antistasi/REINF/dismissSquad.sqf
> +			_resourcesFIA = _resourcesFIA + ([typeOf _x] call A3A_fnc_vehiclePrice);
Hmm. I assume the point of an error there is that you're not supposed to call the function when something doesn't have a valid price. Would need to go through all the uses before changing it.

In dismissSquad we only want to refund FIA stuff anyway. Any leftover objects get dropped on the floor, which is fine.

2021-10-01 17:41 UTC, jaj22 commented
Changed to only attempt attached-vehicle refunds if they're in vehFIA. Anything else is left alone (or dumped on the ground, if the parent object is deleted).

2021-10-01 17:42 UTC, HakonRydland approved these changes

2021-10-02 08:07 UTC, merged