Fix rare case when player rank wouldn't save correctly when dead
official-antistasi-community/A3-Antistasi pull request #2159
Opened 2021-10-04 15:19 UTC by jaj22

### What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
`rank _playerUnit` returns empty string on dead players after respawning, which is possible on save if timed precisely. Switched to using the mirrored rankX variable on the player unit, which should always return a real rank.

### Please specify which Issue this PR Resolves.
closes #1285

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

2021-10-17 21:18 UTC, CalebSerafin requested changes
This is a good change.
There might still be a delay is because on clientside onPlayerRespawn script is responsible for transferring `"rankX"`, and saving happens serverside. Therefore, there may still be a ~100-400ms gap due to the scheduler and lower net-priority of setVaraible. 

https://github.com/official-antistasi-community/A3-Antistasi/blob/c847afd20c52a9967de491abf21bbf6ba3310c81/A3-Antistasi/onPlayerRespawn.sqf#L41

https://github.com/official-antistasi-community/A3-Antistasi/blob/c847afd20c52a9967de491abf21bbf6ba3310c81/A3-Antistasi/onPlayerRespawn.sqf#L59

However, the default variable will cover up well as most players will not notice rank.

I suggest adding an error log if the player's rank cannot be found when saving. This is so we can see if it still occurs.

2021-10-17 22:52 UTC, jaj22 commented
Wait, now I don't understand how this works at all, because as far as I can tell, the variable canSave is never set on respawned units...

Logically you'd just set that after the other params are transferred, but then it doesn't appear to be set at all.

2021-10-18 02:08 UTC, jaj22 commented
Oh god, all player unit variables get *transferred* on respawn.

Gonna need to figure out which end this happens at.

2022-10-15 12:35 UTC, Bob-Murphy commented
dead

2022-10-15 12:35 UTC, closed without merging

2022-10-15 15:17 UTC, jaj22 commented
Hmm. Actually still need to sort this out, although it may get merged into the init/setup PR. Should have some research time soon.

2022-10-15 22:02 UTC, jaj22 commented
Ok, investigated the respawn timings. Turns out that the unit vars are copied to the new unit before either onPlayerRespawn or the Respawn missionEventHandler are called, so the fix was valid. I'll reimplement the changes in #2488

Further, the client respawn handlers are called a couple of frames before the server respawn handlers, which suggests that the client has responsibility for the process. I did run into one case where the vars hadn't been copied to the server at the point that the player unit changed on ths server, so that may cause occasional issues. Should be rare though, and non-critical because it doesn't save the player data if canSave or moneyX are missing.