To mod
official-antistasi-community/A3-Antistasi pull request #2184
Opened 2021-10-30 18:59 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Antistasi the mod!!!

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

TBD -> Build instruction
       |-> Live editing setup
       |-> Server testing

********************************************************
Notes: i will get around to the testing instructions 😁 promise!!!

2021-10-30 19:00 UTC, killerswin2 commented
Oh no

2021-11-21 17:03 UTC, CalebSerafin approved these changes
Okay, nothing suspicious. A3 Antistasi and other CTI missions are already full of back doors, so if one was snuck in here it wouldn't make much difference.

2022-01-10 16:59 UTC, CalebSerafin requested changes
Some improvements.

2022-01-10 16:59 UTC, CalebSerafin commented on A3A/addons/core/Includes/script_mod.hpp
> +    #define AUTHORS "Antistasi Dev Team, Håkon Rydland"
Either Inherit from AUTHOR or define it in some standalone file so it's easy to locate and update.

2022-01-11 07:16 UTC, HakonRydland commented on A3A/addons/core/Includes/script_mod.hpp
> +    #define AUTHORS "Antistasi Dev Team, Håkon Rydland"
This would be the falback if no author is defined, souch defines would be placed in the component hpp of each addon

2022-01-11 12:35 UTC, CalebSerafin commented
After merge, update the following to use the ARG_x() macros
```
A3-Antistasi/functions/AI/fn_artySupport.sqf Ln 260
A3-Antistasi/functions/Missions/fn_convoy.sqf Ln 286
A3-Antistasi/functions/init/fn_initServer.sqf Ln 87
```

2022-01-11 16:07 UTC, HakonRydland commented
> Note for later: After merge, update the following to use the ARG_x() macros
> 
> ```
> A3-Antistasi/functions/AI/fn_artySupport.sqf Ln 260
> A3-Antistasi/functions/Missions/fn_convoy.sqf Ln 286
> A3-Antistasi/functions/init/fn_initServer.sqf Ln 87
> ```

Correction updated to use macros `ARR_n(E1, ...En)` as ARG is recursive select (ARG_3(A,B,C) == ((A) select (B)) select (C))

2022-01-22 19:17 UTC, killerswin2 approved these changes

2022-01-22 21:29 UTC, merged