KeyCache-Garbage Collector
official-antistasi-community/A3-Antistasi pull request #2186
Opened 2021-11-01 20:57 UTC by CalebSerafin

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
* Added Garbage Collection Component of KeyCache.

### But What is KeyCache???
* KeyCache's goal is to reduce data sent over a network.
* It can achieve this by replacing commonly used identifiers with a shortID.
* However, this technology can be used to create translation tables for any data.
* Translations can go stale and expire, this is preferable for a DNS-like implementation where the server holds all translations, and the client only needs to use a translation for a short period.
* KeyCache is intended to be used as middleware before and after remoteExecution. Therefore, it cannot be directly called from another machine. Only the server can directly update translations on clients.
* The parent code must handle the propagation of translations.
* The most critical part of expiring translations is the garbage collector. Therefore, this PR will add that component.

### Tell us about this Garbage Collector
* This garbage collector finds stale translations and deletes them.
* A concurrent generational garbage collector was implemented. 
* Generational GCs are based on life's tough truth that most objects die young. See <https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#generations> for a description.
* All new items are added to generation 0. If it not stale on this pass, it is promoted to generation 1.
* Generation 1 checks items at a slower pace. If items survive this pass, they are promoted to generation 2.
* Generation 2 checks items at an even slower pace. Items are not promoted past this point.

### Please verify the following and ensure all checks are completed.

 [x] Have you loaded the mission in LAN host?
* Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
* Yes

### What do I need to review?
* You don't need to review the fields under `/Tests/`
* All functions that have text content need a review
* CfgRemoteExec can use a review as well.

### How can the changes be tested?
Steps: 
```sqf
/*
Run in order.
Make sure that the previous test finishes before starting next.
If the previous test failed, it's likely that the following will too.
*/

// Recommended
call compileScript ["functions\Utility\KeyCache\Tests\unitTest_garbageCollector_basicPromotion.sqf"];
call compileScript ["functions\Utility\KeyCache\Tests\unitTest_garbageCollector_timedPromotion.sqf"];
call compileScript ["functions\Utility\KeyCache\Tests\unitTest_garbageCollector_basicDeletion.sqf"];
// Will take ≈10 minutes. Game will still run at 60fps.
call compileScript ["functions\Utility\KeyCache\Tests\unitTest_garbageCollector_shortFpsStressTest.sqf"];
```

2021-11-01 21:06 UTC, CalebSerafin commented
# Long Stress Test Data
69 Million items were registered for GC. As they were being added, an equilibrium of ≈300 thousand soon-to-be GCed items formed. 
> Note: Arrays can't handle more than 10 million, and integers in scalars can't handle more than 16 million.

The GC uses buckets per generation to avoid array overfilling.
Raw data is available to the Offical Dev Team on its Discord.
![Imgur](https://imgur.com/jGww8Uq.jpg)

The naive analysis might be that GC caused those lag-dips.
However, the GC is constantly scanning, promoting, and deleting items as noted by the equilibrium.
The total amount of non-deleted objects becomes reduced proportionally to the frame rate.
Therefore, the reduced framerate slowed down the stress-test script.
**Therefore, It can be concluded that the GC outperformed the stress-test script.**

2021-11-03 05:18 UTC, killerswin2 commented
5 empty files? Are they used in later versions, needed for something else, or holdover files?

2021-11-03 05:39 UTC, killerswin2 requested changes

2021-11-03 05:39 UTC, killerswin2 commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_init.sqf
> +// Recommended to init preJIP.
No header

2021-11-03 05:39 UTC, killerswin2 commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_garbageCollector.sqf
> +    private _currentBucket = _allBuckets deleteAt 0;
Critical section? Mutex maybe?

2021-11-03 05:39 UTC, killerswin2 commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_garbageCollector.sqf
> +            _keyCache_DB deleteAt _x;  /*__inc_deleted;*/
Critical section?

2021-11-03 05:50 UTC, CalebSerafin commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_garbageCollector.sqf
> +    private _currentBucket = _allBuckets deleteAt 0;
Delete is an atomic operation.

2021-11-03 05:50 UTC, CalebSerafin commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_garbageCollector.sqf
> +            _keyCache_DB deleteAt _x;  /*__inc_deleted;*/
Yes, it is critical.

2021-11-03 05:55 UTC, CalebSerafin commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_init.sqf
> +// Recommended to init preJIP.
Resolved 👍

2021-11-03 05:57 UTC, killerswin2 approved these changes
Noice

2021-11-06 17:06 UTC, HakonRydland requested changes
mostly good, dont really like the empty functions, should be added rn or when you actually want to implement the functionality

2021-11-06 17:06 UTC, HakonRydland commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_startGarbageCollectors.sqf
> +FIX_LINE_NUMBERS()
double use of FIX_LINE_NUMBERS is unnecesary, as its inteaded to correct the line number to in file number after includes

2021-11-06 17:44 UTC, CalebSerafin commented on A3-Antistasi/functions/Utility/KeyCache/fn_keyCache_startGarbageCollectors.sqf
> +FIX_LINE_NUMBERS()
The compiled line number will change depending on the macro's if-statement.

2021-11-06 17:46 UTC, CalebSerafin commented on A3-Antistasi/functions/Utility/KeyCache/config.hpp
> +#define __keyCache_unitTestMode
Fixed.

2021-11-06 17:48 UTC, CalebSerafin commented
The function files have been put there and registered to `functions.hpp` and `CfgRemoteExec.hpp` in one swoop. Next change they will be filled.

2021-11-06 17:56 UTC, HakonRydland approved these changes

2021-11-07 14:14 UTC, merged