Fuel
official-antistasi-community/A3-Antistasi pull request #2187
Opened 2021-11-04 13:08 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Made vehicle fuel spawns cap and random. Added three containers to buy fuel. Added nodes for vehicles to load vehicles.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-11-05 15:43 UTC, CalebSerafin requested changes
There are just a few quick to resolve points. Otherwise, it's good 👍.

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/Garage/fn_callbackHandler.sqf
> +                _vehicle setFuel random [0.05, 0.125, 0.20];
So for rebel vehicles, they may be buying the vehicle with the last of there cash. So I did some testing in vanilla to see if I could get from Oerocastro to Sytra with 5% fuel. 
1. First attempt with offroad, failed. 
2. Second attempt I went at max speed and turned the engine off on flat and donwhills. Made it with 0.57%
3. Thrist attempted I tried it with a quadbike with smaller fuel tank (more consumption) and had to use even more tricks like driving diagonally on hills and accerating then turning engine off. Made it with 1.06%
4. This time on Cam Lao Nam I drove the PAVN Z157 Truck from Thud Ridge to Phao Noi (~5km driving distance). Using careful driving, it made it there with 0.53% left. However, most of the map is far from fuel.

Most players will not know the fuel workings of Arma 3. Even worse, they may think that a slow to moderate speed is most effieciant. However, Arma 3 bills your fuel usage based soley on the engine being on.
So I recommend bumping the minium to 10%. The bias can stay the same or be lower. The main point is that the worse case scenerio should still be workable.

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions/UtilityItems/fn_spawnItem.sqf
> +    [player, ["object", 2], 65, [['A3A_fnc_initMovableObject', 0]]] call A3A_fnc_spawnLight;
The example's function name should be updated.

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions/UtilityItems/fn_spawnItem.sqf
> +private _lastTimePurchase = _unit getVariable["LightCooldown",time];
The lock's name mismatches the new function name.
Maybe `A3A_spawnItem_cooldown`, `A3A_spawnItemCooldown`, `A3A_spawnItem`

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions/UtilityItems/fn_spawnItem.sqf
> +private _resourceFIA = player getVariable ["moneyX", 0];
Since we don't need to use the global variable, we could just call it `_money`, because that is simple and describes it well.

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions/UtilityItems/fn_spawnItem.sqf
> +if (_position isEqualTo []) then {_position = getPos _unit};
An offset of 1 to 3 metres should be added. Otherwise the failure case will result in squashing the player.
`_position = getPos _unit vectorAdd [2,0,0]`

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions/UtilityItems/fn_spawnItem.sqf
> +_item allowDamage false;
It might be good to explicidy write in the function description that damage is disabled. Since a developer quickly using this function may not notice.

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions/UtilityItems/fn_spawnItem.sqf
> +            [_item] remoteExec [_func_name, clientOwner];
Since it's not actually **remote** execution, you could write it as:
```sqf
[_item] spawn (missionNamespace getVariable _func_name);
```
However, I'm not sure if the function expects `remoteExecutedOwner` to return anything useful.

2021-11-05 15:43 UTC, CalebSerafin commented on A3-Antistasi/functions.hpp
> +        class spawnItem {};
Besides spawning the item, this function does involve UI elements and a money transaction. The name spawnItem does not sound like it touches those layers.
I would recommend calling it `buyItem` or something with a similar sounding intent.

2021-11-21 17:11 UTC, CalebSerafin approved these changes
Changes are Good 👍

2021-12-05 13:31 UTC, HakonRydland requested changes
a few things

2021-12-05 13:31 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_buyItem.sqf
> +private _money = player getVariable ["moneyX", 0];
need to ensure only run where there is a player (`hasInterface`)
also should make sure its running unscheduled with (`casSuspend`)

2021-12-05 13:31 UTC, HakonRydland commented on A3-Antistasi/functions/init/fn_initClient.sqf
> +vehicleBox addAction ["Buy Huron Container for 1000€", {[player, ['vehicleFuelSource', 1], 1000, [['A3A_fnc_logistics_addLoadAction', 1]]] call A3A_fnc_buyItem},nil,0,false,true,"","true",4];
grabs vehicle from template, but hardcoded name, may not be correct if someone assigns a different fuel source(s) in the templates, instead you should get the display name from the vehicle config and pass in the class name directly..., also should have a check if the template supports the fuel source, i.e. if someone decides to only add a jerry can but no fuel tank then the action should not be there.

example:
```sqf
FactionGet(reb,"vehicleFuelSource") params [["_fuelCan","",[""]], ["_fuelTank","",[""]]];
if (isClass (congifFile/"CfgVehicles"/_fuelCan) then {
    private _dispName = getText (configFile/"CfgVehicles"/_fuelSources#0/"displayName");
    /*add action here with formated text adding the displayname into the string, preferably as a stringtable entry, passing in classname instead of the template lookup*/
    /*also the callbacks could be a simple "isGlobal" bool for clearity, unless you plan on expanding with other functionallity later, and if so, then local should be default and not `1`*/
};
```

if you wanted you could also expand this with template defined pricing, by having the price next to the entry like so
example:
```sqf
["vehicleFuelSource", [
    [classname, price],
    [classname, price]
]] call _fnc_saveToTemplate;
```
also maybe split this to `vehicleFuelCan` and `vehicleFuelTank` as it would be less error prone, making it 
```sqf
["vehicleFuelCan", [classname, price]] call _fnc_saveToTemplate;
["vehicleFuelTank", [classname, price]] call _fnc_saveToTemplate;
```

2021-12-05 13:31 UTC, HakonRydland commented on A3-Antistasi/Garage/fn_addVehicle.sqf
> +    [_vehicle getVariable ['A3A_itemPrice', 0]] remoteExec ["A3A_fnc_resourcesPlayer", _client]; // later make this a function call for percentage of fuel remaining
do you mean reduce refund price to the percentage remaining fuel, if so, yes do that... now
as we do support ace, you need to make it ace compatible. and tie the reduction to a `A3A_isFuelContainer` variable on the object, so it wont fuck over none fuel items being refunded.
maybe a `getRefundPrice` function?

2021-12-05 18:57 UTC, killerswin2 commented on A3-Antistasi/Garage/fn_addVehicle.sqf
> +    [_vehicle getVariable ['A3A_itemPrice', 0]] remoteExec ["A3A_fnc_resourcesPlayer", _client]; // later make this a function call for percentage of fuel remaining
it's already created, just not in this pr. The project is split into multiple pr.

2021-12-06 19:44 UTC, HakonRydland approved these changes
Looks good now

2022-01-07 21:30 UTC, merged