Cup templates Us
official-antistasi-community/A3-Antistasi pull request #2199
Opened 2021-11-20 19:41 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2021-11-20 20:21 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
> +	["CUP_smg_MP5A5","","","CUP_optic_CompM2_low",["CUP_30Rnd_Subsonic_9x19_MP5","CUP_30Rnd_Red_Tracer_9x19_MP5"],[],""],
why would the Police get SD ammo,

besides lower MV (If Ace) it probably behaves the same, its just weird

2021-11-20 20:21 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
> +	["CUP_srifle_M24_wdl","","","CUP_optic_LeupoldMk4_20x40_LRT",["CUP_5Rnd_762x51_M24","CUP_5Rnd_762x51_M24"],[],"bipod_01_F_blk"]
If its the same Magazine entering it once will be enough.

2021-11-20 20:24 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
> +_loadoutData set ["antiInfantryGrenades", []];
probably skipped a line here

2021-11-20 20:25 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
> +_loadoutData set ["antiInfantryGrenades", []];
yeah that got flipped

2021-11-20 20:28 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
> +["vehiclesPlanesCAS",["CUP_B_A10_DYN_USA"]] call _fnc_saveToTemplate;
These need to be added here, yes it's a mess
https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Base/fn_setPlaneLoadout.sqf

2021-11-20 20:29 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
> +["vehiclesPlanesCAS",["CUP_B_A10_DYN_USA"]] call _fnc_saveToTemplate;
the planes?

2021-11-20 20:29 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
> +_loadoutData set ["antiInfantryGrenades", []];
fixed

2021-11-20 20:33 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
> +["vehiclesPlanesCAS",["CUP_B_A10_DYN_USA"]] call _fnc_saveToTemplate;
Yes, github thought it would be funny to include boats on that marking.

2021-11-22 19:54 UTC, Lazejun requested changes
Why would you reupload a Flag that exist in CUP itself?

@CUP Weapons\addons\cup_baseconfigs.pbo\Data\Flags\flag_cdf.co.paa

-------> "\CUP\BaseConfigs\CUP_BaseConfigs\data\Flags\flag_cdf_co.paa";

at best keep it all lower case as checks for Flagtexure will return lowercase only

-------> "cup\baseconfigs\cup_baseconfigs\data\flags\flag_cdf_co.paa"

if that one wouldn't have existed you could have used the Chernarus Flag.

Most of the times Flagtextures can be found in CfgFactionClasses

configFile >> "CfgFactionClasses" >> "CUP_B_CDF"

flag = "\CUP\BaseConfigs\CUP_BaseConfigs\data\Flags\flag_chernarus_co.paa";

2021-11-23 17:34 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
> +["flagMarkerType", "Fraction_CUP_CDF"] call _fnc_saveToTemplate; 		//this line determines the flag marker type -- Example: ["flagMarkerType", "flag_NATO"] - ENTER ONLY ONE OPTION
Faction_CUP_CDF

2021-11-23 17:42 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
> +["flagMarkerType", "Fraction_CUP_CDF"] call _fnc_saveToTemplate; 		//this line determines the flag marker type -- Example: ["flagMarkerType", "flag_NATO"] - ENTER ONLY ONE OPTION
It's already that.... are you on the wrong commit?

2021-11-23 17:46 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["staticAT",["CUP_B_RBS70_ACR"]] call _fnc_saveToTemplate;
The RBs 70 is AA

2021-11-23 19:21 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
> +["flagMarkerType", "Fraction_CUP_CDF"] call _fnc_saveToTemplate; 		//this line determines the flag marker type -- Example: ["flagMarkerType", "flag_NATO"] - ENTER ONLY ONE OPTION
oh

2021-11-25 22:32 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +	["CUP_launch_RPG7V", "", "", "cup_optic_pgo7v3", ["CUP_OG7_M", "CUP_PG7VR_M"], [], ""],
Mixing Vanilla and CUP Ammo,

Maaws gets almost only Vanilla Ammo.

2021-11-25 22:42 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["minefieldAT", ["ATMine"]] call _fnc_saveToTemplate;
There are no CUP AP Mines but there are 2 AT Variants:

"CUP_Mine" ------> AT 15 AT Mine, US Mine

"CUP_MineE" -----> TM46 AT Mine, Soviet Mine

2021-11-25 22:49 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesIFVs",["CUP_B_BMP2_CZ_Des"]] call _fnc_saveToTemplate;
thats unused.

2021-11-25 22:53 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesIFVs",["CUP_B_BMP2_CZ_Des"]] call _fnc_saveToTemplate;
what? Can't tell from git

2021-11-25 22:54 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesIFVs",["CUP_B_BMP2_CZ_Des"]] call _fnc_saveToTemplate;
vehiclesIFVs and LightAPC are unused

2021-11-25 22:55 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesIFVs",["CUP_B_BMP2_CZ_Des"]] call _fnc_saveToTemplate;
move to apc then?

2021-11-25 22:55 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesIFVs",["CUP_B_BMP2_CZ_Des"]] call _fnc_saveToTemplate;
ofcourse

2021-11-25 23:01 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesMilitiaCars",["CUP_B_LR_Transport_CZ_D"]] call _fnc_saveToTemplate;
At best Militia and Military Vehicles should be unique Classes so they will be Crewed correctly.

Militia Light Armed are used for Roadblocks, these are all arrays since MoveToTemplates, you can use more than one if suitable, just avoid GL Variants for that one.

2021-11-25 23:03 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesMilitiaCars",["CUP_B_LR_Transport_CZ_D"]] call _fnc_saveToTemplate;
??? It's an mg?

2021-11-25 23:06 UTC, Bob-Murphy commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesMilitiaCars",["CUP_B_LR_Transport_CZ_D"]] call _fnc_saveToTemplate;
Laze said "You can use multiple, but do not use GL variants".
Not "this is a GL variant, don't use it".

2021-11-25 23:07 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +["vehiclesMilitiaCars",["CUP_B_LR_Transport_CZ_D"]] call _fnc_saveToTemplate;
oh

2021-11-28 13:15 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +	["CUP_launch_RPG7V", "", "", "cup_optic_pgo7v3", ["CUP_OG7_M", "CUP_PG7VR_M"], [], ""],
Instead of Removing Vanilla ammo you replaced CUP Ammo with Vanilla ammo

2021-11-28 13:43 UTC, killerswin2 commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf
> +	["CUP_launch_RPG7V", "", "", "cup_optic_pgo7v3", ["CUP_OG7_M", "CUP_PG7VR_M"], [], ""],
Well mean you didn't say I can't use it lol

2021-11-28 15:17 UTC, Lazejun requested changes
As you disabled Maintainers to Commit to the PR and the list is way to long to tell you,
There is a PR to the Branch to make it Useable, Fix all Syntax Errors etc. Apply Flagtextures Tabs to Spaces etc.

If you request a Review have it atleast useable so it can actually be tested,

2021-11-28 16:52 UTC, killerswin2 commented
merged PR

2021-12-03 22:40 UTC, killerswin2 commented
Todo list for Bluefor templates
----------------- Template Changes Need -------------------------
- [] Update templates to use 3CB_AI_AAF.sqf style 
- [] Remove weapon colors, all weapons should be black
- [] Check and or remove magnified optics from units that don't need it ( ONLY SL and Maybe Marksman/Sniper get Magnified Scopes )
- [] Check ammo type in all weapons is correct ( No Vanilla Mags )

2021-12-16 01:57 UTC, killerswin2 commented
-------------------------------------------- R E S T O F T E M P L A T E S --------------------------------------------

- [ ] CUP_AI_AFRF_Arid.sqf
- [ ] CUP_AI_AFRF_Temperate.sqf
- [ ] CUP_AI_ChDKZ_Temperate.sqf
- [ ] CUP_AI_RAS_Temperate.sqf
- [ ] CUP_AI_SLA_Temperate.sqf
- [ ] CUP_AI_TA_Arid.sqf
- [ ] CUP_BW_AI_BW_Arid.sqf
- [ ] CUP_BW_AI_BW_Temperate.sqf
- [ ] CUP_BW_Logistics_Nodes.sqf
- [ ] CUP_Logistics_Nodes.sqf
- [ ] CUP_Civ_Arid.sqf
- [ ] Cup_Civ_Temperate.sqf
- [ ] CUP_Reb_NPC_Temperate.sqf
- [ ] CUP_Reb_TKL_Arid,sqf

2021-12-27 06:32 UTC, killerswin2 commented
I think that I got all of it, I'm sure there is something that I missed that will come up in review.

2022-01-06 18:39 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf
> +    ["CUP_B_D30_CDF",["CUP_30Rnd_122mmHE_D30_M","CUP_30Rnd_122mmWP_D30_M","CUP_30Rnd_122mmILLUM_D30_M"]]
Illum rounds usually can't hurt people

2022-01-06 18:42 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_SLA_Temperate.sqf
> +["vehiclesGunBoats",["O_Boat_Armed_01_hmg_F"]] call _fnc_saveToTemplate;
There is probably a better replacement than the Vanilla 2035 Boats

2022-01-06 18:44 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_TA_Arid.sqf
> +["name", ""] call _fnc_saveToTemplate;
You lost the Names

2022-01-06 18:46 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf
> +["vehiclesHelisTransport",["CUP_B_UH60M_US","CUP_B_UH60M_FFV_US","CUP_B_UH60M_Unarmed_US","CUP_B_UH60M_Unarmed_FFV_US","CUP_B_MV22_USMC_RAMPGUN"]] call _fnc_saveToTemplate;
"CUP_B_MV22_USMC_RAMPGUN" is not a Helicopter.

2022-01-06 18:52 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_Civ.sqf
> +    "CUP_U_C_Priest_01",
"CUP_U_C_Priest_01",

might want to remove it before Bob rips you a new one

2022-01-06 19:00 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_Logistics_Nodes.sqf
> +["\CUP\Weapons\CUP_Weapons_StaticWeapons\ZU23\CUP_zu23.p3d",				[0,0,0],    [0,0,0],   4, 	    1000],
I doubt that most of those Weapons are "2s" and "4s",

Especially as they are usually the same Size as variants in other mods https://github.com/official-antistasi-community/A3-Antistasi/blob/2366dbe293e142fb968af9a6e2107a3fcbfcf6a6/A3-Antistasi/Templates/Templates/RHS/RHS_Logistics_Nodes.sqf#L229-L244

MG Gunner Clipping might happen,
The Zu23 is usually pretty Wide and wont fit most Vehicles,
The Tripod of the FIM92 is usually to Wide and might not fit most "4s".

2022-01-06 19:01 UTC, Lazejun commented on A3-Antistasi/Templates/Templates/CUP/CUP_Logistics_Nodes.sqf
> +    ["\CUP\WheeledVehicles\CUP_WheeledVehicles_T810\CUP_t810_vp2.p3d",[
Please respect the Format.
Using the Model itself instead of Class to Model is fine but the rest isn't

https://github.com/official-antistasi-community/A3-Antistasi/blob/2366dbe293e142fb968af9a6e2107a3fcbfcf6a6/A3-Antistasi/Templates/Templates/RHS/RHS_Logistics_Nodes.sqf#L186-L194

2022-01-06 19:18 UTC, Lazejun reviewed
For some Reason you have decleared War on Spaces,

https://github.com/official-antistasi-community/A3-Antistasi/blob/b20645f4848742224a2d3aa58513c1a1f2f172e2/A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf#L20-L22
```sqf
["vehiclesBasic", ["B_Quadbike_01_F"]]
```
there is a lot of random use of Spaces like 
```Sqf
["word", "word","word"]
```

--------> A Space after each comma for example

https://github.com/official-antistasi-community/A3-Antistasi/blob/b20645f4848742224a2d3aa58513c1a1f2f172e2/A3-Antistasi/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf#L181

```Sqf
 ["CUP_arifle_CZ805_A2", "CUP_muzzle_snds_M16", "", "CUP_optic_ACOG2", ["CUP_30Rnd_TE1_Red_Tracer_556x45_CZ805"], [], ""], 
 ```
 
 And Faction Names, for some Reason you are calling
the Royal Army Corp of Sahrani (RACS) just RAS and
Takistani Army has the Acronym TKA and it should probably be that too.

2022-01-22 13:12 UTC, Lazejun requested changes
I did say Spawn all Units and look at them, some of these Mistakes are very Obvious.

AFRF Arid:
![107410_20220122135018_1](https://user-images.githubusercontent.com/57111907/150639238-7ec4ae15-f014-4ddc-85a9-bbabbb7919fd.png)

![107410_20220122135031_1](https://user-images.githubusercontent.com/57111907/150639236-da866fed-a7fa-4e27-a383-36131c145984.png)
ACR Temperate:
![107410_20220122135850_1](https://user-images.githubusercontent.com/57111907/150639518-ae30b130-7464-42f8-8d8e-7825df1df850.png)
![107410_20220122135842_1](https://user-images.githubusercontent.com/57111907/150639522-21ccc185-7fd3-4afe-ae72-92ddefc79bf6.png)
BAF Temperate:
![107410_20220122140137_1](https://user-images.githubusercontent.com/57111907/150639595-eba5d119-a366-44ad-bdf8-d5356a931526.png)
USMC Temperate:
![107410_20220122141025_1](https://user-images.githubusercontent.com/57111907/150639815-dec070b1-f1f7-46cf-aac5-4a31b97a3d6d.png)
![107410_20220122141021_1](https://user-images.githubusercontent.com/57111907/150639816-f07ae515-68f4-4c12-a066-86e4320d3a45.png)
CDF Temperate SF:
![107410_20220122141141_1](https://user-images.githubusercontent.com/57111907/150639846-cf837aa6-96e9-4789-9dd1-423d543ab6dc.png)

I think thats enough, there is a lot more

2022-01-30 19:41 UTC, killerswin2 commented
:( rebase errors, human errors, and merge errors. :(

2022-01-30 19:41 UTC, closed without merging