Update fn_initServer.sqf to properly invoke Info_2
official-antistasi-community/A3-Antistasi pull request #2205
Opened 2021-12-17 18:51 UTC by Zarickan

Info_2 is defined with 3 parameters, but in this case it is passed (unintentially) 4 arguments, this means that the macro will instead be expanded to nothing.

Related documentation can be found on the [wiki](https://community.bistudio.com/wiki/PreProcessor_Commands), relevant part is under __Arguments__.

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### Please verify the following and ensure all checks are completed.
1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-01-06 11:26 UTC, Bob-Murphy commented
Hi Zarickan,
thank you for the PR and sorry for the delay.
Somebody of our team will look at this shortly.
Cheers

2022-01-06 11:37 UTC, killerswin2 requested changes
All good changes, just keep the sqf files clear from preprocessor macro defines

2022-01-06 11:37 UTC, killerswin2 commented on A3-Antistasi/functions/AI/fn_artySupport.sqf
> +#define ARTILLERY_ERROR_INFORMATION [_positionTel, ((getArtilleryAmmo [(_artyArrayDef1 select 0)]) select 0)]
I'm okay with this being a define, but move it to an hpp file. lets keep the sqf files free from macro defines.

2022-01-06 11:37 UTC, killerswin2 commented on A3-Antistasi/functions/Missions/fn_convoy.sqf
> +#define CONVOY_MISSION_STATUS_ARRAY ["lost", "won"]
Again move to a hpp

2022-01-06 11:37 UTC, killerswin2 commented on A3-Antistasi/functions/init/fn_initServer.sqf
> +#define MODE_ARRAY ["SP","MP"]
hpp file, please

2022-01-06 19:01 UTC, CalebSerafin commented
For those array cases, we could pull a page out of CBA and ACE.

in `A3-Antistasi\Includes` we could create a file called `generalMacro.hpp` or something else that sounds appropriate.

We include it in common.hpp

Then we can pillage https://github.com/CBATeam/CBA_A3/blob/876b9b2f6afa7f609d58955333078531a33f9836/addons/main/script_macros_common.hpp#L1066-L1084

After that, we can use to to inline arrays like so:
```cpp
INFO_1("Test : %1", [ARR("false","true")] select true)
```

2022-01-08 18:51 UTC, HakonRydland commented
Those macros will be a part of move to mod, in `script_macros_common.hpp`

2022-01-08 19:03 UTC, CalebSerafin commented
Move to mod is not happing yet, so this will be a suitable solution for now :)

2022-01-10 21:40 UTC, CalebSerafin approved these changes
After moving to mod we can weed out these special cases that needed their own array macro.
For now, it isn't too much of a war crime leaving it as is.

2022-01-11 00:58 UTC, killerswin2 approved these changes
we will change to a hpp once mod to move it complete

2022-01-11 12:35 UTC, merged