Fuel part2
official-antistasi-community/A3-Antistasi pull request #2207
Opened 2022-01-08 19:34 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ x ] Change
3. [ x ] Enhancement

### What have you changed and why?
Information:
    added second part of fuel part 2

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-01-09 18:46 UTC, HakonRydland requested changes
a few things

2022-01-09 18:46 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
> +    <number>
percentile remaining fuel 0 -> 1

2022-01-09 18:46 UTC, HakonRydland commented on A3-Antistasi/Garage/fn_addVehicle.sqf
> +        [floor (([_vehicle] call A3A_fnc_remainingFuel) * (_vehicle getVariable ['A3A_itemPrice', 0]))] remoteExec ["A3A_fnc_resourcesPlayer", _client];
`floor (([_vehicle] call A3A_fnc_remainingFuel)` will result in either 0 or one, did you test this?

2022-01-09 18:46 UTC, HakonRydland commented on A3-Antistasi/functions/init/fn_initZones.sqf
> +private _fuelStationTypes = ["Land_Fuelstation_Feed_F", "Land_fs_feed_F", "Land_FuelStation_01_pump_F", "Land_FuelStation_01_pump_malevil_F", "Land_FuelStation_03_pump_F", "Land_FuelStation_02_pump_F
cant remember where initZones is run, im assuming its server due to the publicVariables further down, if so then this is fine

2022-01-09 18:46 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
> +	(_vehicle getVariable ["ace_refuel_currentFuelCargo"] / getNumber (_vehCfg >> "ace_refuel_fuelCargo"));
add a safeguard against zero divisor

2022-01-09 18:51 UTC, killerswin2 commented on A3-Antistasi/Garage/fn_addVehicle.sqf
> +        [floor (([_vehicle] call A3A_fnc_remainingFuel) * (_vehicle getVariable ['A3A_itemPrice', 0]))] remoteExec ["A3A_fnc_resourcesPlayer", _client];
I did test it floors the price

2022-01-09 18:52 UTC, killerswin2 commented on A3-Antistasi/functions/init/fn_initZones.sqf
> +private _fuelStationTypes = ["Land_Fuelstation_Feed_F", "Land_fs_feed_F", "Land_FuelStation_01_pump_F", "Land_FuelStation_01_pump_malevil_F", "Land_FuelStation_03_pump_F", "Land_FuelStation_02_pump_F
It's server

2022-01-09 19:35 UTC, HakonRydland requested changes
last bit

2022-01-09 19:35 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
> +private _vehType = if (_vehicle isEqualType objNull) then {typeOf _vehicle} else {_vehicle};
will only be typeOf objNull due to the params, could exit with 0 if null, but the other cases should handle null fine

2022-01-09 19:35 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
> +private _vehCfg = configFile/"CfgVehicles"/_vehType;
in line above line as typeOf objNull == ""

2022-01-09 19:35 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
> +    private _ace_refuel_cargo = getNumber (_vehCfg >> "ace_refuel_fuelCargo");
semantics but i would have named it something like _vehicleMaxFuel for clarity as those unfamiliar with ace refuel might not know what ace_refuel_fuelCargo actually refers to

2022-01-09 19:35 UTC, HakonRydland commented on A3-Antistasi/functions/UtilityItems/fn_remainingFuel.sqf
> +    if(_ace_refuel_cargo == 0) exitwith {};
`exitWith {0}` we expect a number return and a nil return would create an error in user code (or require extra safeguards on user side)

2022-01-09 22:27 UTC, HakonRydland approved these changes
looks good now

2022-01-09 23:32 UTC, CalebSerafin requested changes
Comments about saving system and fuel station classnames.

2022-01-09 23:32 UTC, CalebSerafin commented on A3-Antistasi/functions/Save/fn_loadStat.sqf
> +        };
The saved array should be keyPairs of <2D position, fuelLeft>. So if more fuel stations are added or removed due to the type-matching or objects placed in the SQM, the list will not get shifted and scrambled.

2022-01-09 23:32 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initZones.sqf
> +private _fuelStationTypes = ["Land_Fuelstation_Feed_F", "Land_fs_feed_F", "Land_FuelStation_01_pump_F", "Land_FuelStation_01_pump_malevil_F", "Land_FuelStation_03_pump_F", "Land_FuelStation_02_pump_F
Pull a list from the template system Defaults or Map Information. Different mods may still be combined, but at least the list will reside somewhere where someone will see it and update it.

2022-01-09 23:32 UTC, CalebSerafin commented on A3-Antistasi/functions/init/fn_initZones.sqf
> +private _fuelStationTypes = ["Land_Fuelstation_Feed_F", "Land_fs_feed_F", "Land_FuelStation_01_pump_F", "Land_FuelStation_01_pump_malevil_F", "Land_FuelStation_03_pump_F", "Land_FuelStation_02_pump_F
And add CUP Terrain and friends.

2022-01-10 05:20 UTC, HakonRydland commented on A3-Antistasi/functions/init/fn_initZones.sqf
> +private _fuelStationTypes = ["Land_Fuelstation_Feed_F", "Land_fs_feed_F", "Land_FuelStation_01_pump_F", "Land_FuelStation_01_pump_malevil_F", "Land_FuelStation_03_pump_F", "Land_FuelStation_02_pump_F
not in template system defaults as it has nothing to do with factions, having the list of locations defined in map information file is a good idea though.
leaving in a default stations getter as a fallback would reduce the work load though, as most currently supported map uses vanilla fuel stations

2022-01-10 11:24 UTC, CalebSerafin requested changes
Okay, good changes, just a couple of improvements.

2022-01-10 11:24 UTC, CalebSerafin commented on A3-Antistasi/functions/Save/fn_loadStat.sqf
> +            private _fuelStation = nearestObjects [A3A_fuelAmountleftArray # _i # 0, [A3A_fuelAmountleftArray # _i # 2], 1] select 0;
You need to catch the case where a fuel station is missing.
It might be possible to just forgo storing the type of fuel station and use the set list from generation.
```suggestion
            private _nearFuelStations = nearestObjects [A3A_fuelAmountleftArray # _i # 0, fuelStationTypes, 1];
            if (count _nearFuelStations == 0) then { continue };
            private _fuelStation = _nearFuelStations#0;
```

2022-01-10 11:24 UTC, CalebSerafin commented on A3-Antistasi/functions/Save/fn_saveLoop.sqf
> +		_fuelAmountleftArray pushback _keyPairsFuel;
May not need to store the type.

2022-01-10 11:28 UTC, CalebSerafin commented
@HakonRydland Could you look at how the fuel stations are loaded from map data? I think you have more expertise in this case.

2022-01-10 19:46 UTC, HakonRydland commented
> @HakonRydland Could you look at how the fuel stations are loaded from map data? I think you have more expertise in this case. 

Map data loading looks correct.

2022-01-10 21:39 UTC, CalebSerafin approved these changes
Changes Good.

2022-01-10 21:41 UTC, merged