Garage improvements
official-antistasi-community/A3-Antistasi pull request #2214
Opened 2022-01-16 22:22 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    - Added synergy with fuel scarcity with actual fuel consumption on un-garage (vanilla still practically still has unlimited fuel due to vanilla fuel truck configs).
    - Added long time requested QOL changes #2138 #2006 
    - Added alphabetical sorting to the vehicle lists
    - Fixed a type causing an error in capacity check code

### Please specify which Issue this PR Resolves.
closes #2138 #2006 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-01-17 05:17 UTC, killerswin2 requested changes

2022-01-17 05:17 UTC, killerswin2 commented on A3-Antistasi/Garage/Refuel/fn_reciveStateUpdate.sqf
> +params ["_vUID","_stateIndex", "_state"];
Missing your defines here.

2022-01-17 05:17 UTC, killerswin2 commented on A3-Antistasi/Garage/Refuel/fn_refuelVehicleFromSources.sqf
> +if (_sourceEmptied) then { [1] call HR_GRG_fnc_declairSources; };
misspelling HR_GRG_fnc_declairSources -> HR_GRG_fnc_declareSources

2022-01-17 05:17 UTC, killerswin2 commented on A3-Antistasi/Garage/Extras/fn_reloadExtras.sqf
> +private _avgDmg = 1 - (HR_GRG_previewVehState#1#0);
the states, could be abstracted to some define?

2022-01-17 05:17 UTC, killerswin2 commented on A3-Antistasi/Garage/Refuel/fn_refuelVehicleFromSources.sqf
> +    private _fuelData = _sourceData#4#0; //vehicle data >> statePreservation data >> Fuel data
#define statedata 4
#define fuelState 0
#define aceFuelCargo 2 
#define fuelCargo 0
#define vehFuel 0
or ignore do to dm talk

2022-01-17 12:42 UTC, CalebSerafin commented on A3-Antistasi/Garage/Refuel/fn_refuelVehicleFromSources.sqf
> +    private _fuelData = _sourceData#4#0; //vehicle data >> statePreservation data >> Fuel data
So I've personally become laxed on the magic array indices. The reason is that SQF has not compiled structures or classes where property names can be used. hashMaps can be an unnecessary overhead for being a small container. Although, for arrays 4 or longer I do generally use Macros to name indices. But it is a good suggestion.

2022-01-17 13:13 UTC, CalebSerafin reviewed
Yeah, I think killer caught all the critical points.

2022-01-17 22:10 UTC, HakonRydland commented on A3-Antistasi/Garage/Refuel/fn_refuelVehicleFromSources.sqf
> +    private _fuelData = _sourceData#4#0; //vehicle data >> statePreservation data >> Fuel data
i feel the comments are good enough

2022-01-17 22:12 UTC, HakonRydland commented on A3-Antistasi/Garage/Extras/fn_reloadExtras.sqf
> +private _avgDmg = 1 - (HR_GRG_previewVehState#1#0);
comments should help future readers easily understand

2022-01-17 22:13 UTC, HakonRydland commented on A3-Antistasi/Garage/Refuel/fn_reciveStateUpdate.sqf
> +params ["_vUID","_stateIndex", "_state"];
comment explains the "magic numbers"

2022-01-18 00:44 UTC, killerswin2 approved these changes
Good on my end, now Frost.

2022-01-21 11:50 UTC, merged