Khe Sanh port
official-antistasi-community/A3-Antistasi pull request #2224
Opened 2022-01-22 19:47 UTC by Bob-Murphy

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-01-22 20:13 UTC, killerswin2 approved these changes

2022-01-22 20:13 UTC, killerswin2 commented on Map-Templates/Antistasi-Khe-Sanh.vn_khe_sanh/Map/vn_khe_sanhInfo.sqf
> +		private _blacklistIndex = [];
no blacklist, standard is to nil, but okay

2022-01-22 21:20 UTC, Lazejun commented on Map-Templates/Antistasi-Khe-Sanh.vn_khe_sanh/mission.sqm
> +							angle=62.260929;
```suggestion
							angle=0;
```

2022-01-22 21:22 UTC, Lazejun commented on Map-Templates/Antistasi-Khe-Sanh.vn_khe_sanh/mission.sqm
> +							angle=62.260929;
```suggestion
							angle=0;
```

2022-02-13 21:49 UTC, Lazejun requested changes
![grafik](https://user-images.githubusercontent.com/57111907/153776504-aab5c008-4cb1-4594-8968-0c142dffa54a.png)

"airport_2" we either remove the wall infront of the Planes or tell SGD to turn around the Hangars

2022-05-07 14:35 UTC, Bob-Murphy commented
Implemented all changes into `map-overhaul` branch.
Hence this PR will be closed.

2022-05-07 14:35 UTC, closed without merging