New cup templates
official-antistasi-community/A3-Antistasi pull request #2239
Opened 2022-02-01 17:20 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    redo of the templates, can build mod to test, need help on that.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-02-05 23:15 UTC, Lazejun requested changes
"B_Kitbag_khk" Does not exist in Arma.

>>> Entry: "mineAT" | Invalid classname: CUP_MineE | Classname should be from config CfgMagazines       ------> "CUP_MineE_M"

Bad Casing CUP_optic_pgo7v3 should be "CUP_optic_PGO7V3"
Bad case on classname: CUP_optic_eotech553_black, expected: CUP_optic_Eotech553_Black
Bad case on classname: CUP_optic_compm2_low, expected: CUP_optic_CompM2_low
Bad case on classname: CUP_optic_elcan_specterdr_black, expected: CUP_optic_Elcan_SpecterDR_black

There is a lot more, all can be found in the RPTs

2022-02-19 13:23 UTC, Lazejun reviewed
Fixed MissileATlauncher as that was never given to any Loadout,
Moved M47 to MissileATLaunchers as its Guided AT,
Fixed the lightATLaunchers and ATLauncher confusion ----> lightATLaunchers  is single use.
CDF:
Removed 75 round Magazines from non MG Loadouts/Weapons as that will just overfill loadouts resulting in 0 Ammo.
Added the same Vanilla item filtering as RHS has.
Fixed Weapon Categories for AT/AA Launchers,
Swaped Vanilla NVGs for a CUP Variant
Added Smaw with Spotting rounds
Added CDF and AFRF Winter, all Vehicle that are not availible in White/Winter will be the same as Temperate.

2022-02-22 18:11 UTC, Bob-Murphy requested changes

2022-02-22 18:11 UTC, Bob-Murphy commented on A3A/addons/core/Templates/fn_detector.sqf
> +A3A_hasBWMOD = false;
remove CUP unrelated content

2022-02-22 18:11 UTC, Bob-Murphy commented on A3A/addons/core/Templates/fn_detector.sqf
> +A3A_hasTornado = false;
remove CUP unrelated content

2022-02-22 18:11 UTC, Bob-Murphy commented on A3A/addons/core/Templates/fn_detector.sqf
> +//Project Tornado Dectection
remove CUP unrelated content

2022-02-22 18:11 UTC, Bob-Murphy commented on A3A/addons/core/Templates/fn_detector.sqf
> +// BWMOD Detection
remove CUP unrelated content

2022-02-22 21:07 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
> +["vehiclesIFVs", ["CUP_I_FENNEK_GMG_ION", "CUP_I_MATV_HMG_ION", "CUP_I_FENNEK_HMG_ION", "CUP_I_MATV_GMG_ION"]] call _fnc_saveToTemplate;				//this line determines IFVs
Uses the unused categories

2022-02-22 21:08 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
> +    ["CUP_launch_Mk153Mod0_blk", "", "", "CUP_optic_smaw_scope", ["CUP_SMAW_HEAA_M", "CUP_SMAW_HEDP_M"], [], ""],
Doesent include the Spotting rounds

2022-02-22 21:14 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
> +_loadoutData set ["missileATLaunchers", ["CUP_launch_Javelin", "", "", "", ["CUP_Javelin_M"], [], ""]];
missileATLaunchers is not even given do anyone

2022-02-22 21:15 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
> +_militiaLoadoutData set ["ATLaunchers", []];
Militia gets no AT.

2022-02-22 21:38 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
> +    ["CUP_launch_Mk153Mod0_blk", "", "", "CUP_optic_smaw_scope", ["CUP_SMAW_HEAA_M", "CUP_SMAW_HEDP_M"], [], ""],
Spotting Rounds are a secondary Magazine, not a Primary.

2022-02-22 22:19 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
> +["CUP_smg_BallisticShield_MP7", "", "", "", ["CUP_40Rnd_46x30_MP7", "CUP_40Rnd_46x30_MP7_Green_Tracer"], [], ""]
Not very useful to give the only Shield that can crash your Game

2022-02-22 22:29 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
> +    ["launcher", 2] call _fnc_addMagazines;
https://github.com/killerswin2/A3-Antistasi/blob/cd8e9647833f61ed6d2ef1273dcebb100c22d822/A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf#L633

2022-03-06 23:47 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
> +    ["launcher", 2] call _fnc_addMagazines;
resolved in [a1afc4f](https://github.com/official-antistasi-community/A3-Antistasi/pull/2239/commits/a1afc4fc934e46385b37b2d7f8aa96ed2054652b)

2022-03-06 23:47 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf
> +["CUP_smg_BallisticShield_MP7", "", "", "", ["CUP_40Rnd_46x30_MP7", "CUP_40Rnd_46x30_MP7_Green_Tracer"], [], ""]
resolved in [a1afc4f](https://github.com/official-antistasi-community/A3-Antistasi/pull/2239/commits/a1afc4fc934e46385b37b2d7f8aa96ed2054652b)

2022-03-08 13:54 UTC, killerswin2 commented
update cup templates to new ace style. ( for me to remember )

2022-03-10 11:31 UTC, killerswin2 commented
update tk -> remove mc
update SLA -> remove mc
update RACS -> remove mc
update AFRF -> remove mc

2022-03-14 21:27 UTC, Lazejun approved these changes
Just approving so Merge is not blocked,

This should be seen as WIP,

It may change depending on Community Feedback etc.

A full review will follow at some point.

2022-03-14 21:30 UTC, Bob-Murphy approved these changes
what laze said

2022-03-14 21:33 UTC, merged