moved anti keybinds from eh to built in keybind introduced in arma3 v…
official-antistasi-community/A3-Antistasi pull request #2247
Opened 2022-02-12 13:52 UTC by HakonRydland

…2.06

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    since arma 3 v2.06 and the move to mod, we are now able to have custom keybinds similare to vanilla keybinds of arma, this pr removes the old key eh and replaces them with the new native keybind system.
    per https://community.bistudio.com/wiki/Arma_3:_Modded_Keybinding

### Please specify which Issue this PR Resolves.
closes #1760

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
1) load into mission
2) test keybinds
3) open configure -> controls -> antistasi
and modify the keybinds there
4) test with new keybinds
5) reset keybinds to default
7) check that you cant place vehicles while battleMenu is open (only thing blocked currently)
6) modify keybind, unload mod, launch, the relaunch with mod loaded again, then check keybinds stored properly

********************************************************
Notes:

2022-02-12 13:56 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>You've turned off top information bar. To enable it, press </Original>
We can't simply delete the button and leave half a sentence.

2022-02-12 13:56 UTC, HakonRydland commented on A3A/addons/core/Stringtable.xml
> +        <Original>You've turned off top information bar. To enable it, press </Original>
constructed from localized string + button name

2022-02-12 13:57 UTC, HakonRydland commented on A3A/addons/core/Stringtable.xml
> +        <Original>You've turned off top information bar. To enable it, press </Original>
although i havent tried with unbound key, but this hint would never be shown while the key is unbound

2022-02-12 14:01 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>You've turned off top information bar. To enable it, press </Original>
I got it. I'm used to having all information in the string and not being it partially code and added to the A3A_fnc_customHint at a different place.
Makes sense.

2022-02-12 14:18 UTC, Bob-Murphy commented
Is there a reason you left in `A3A/addons/core/functions/Base/fn_keys.sqf` as well as commented out references to it?

2022-02-12 14:34 UTC, Bob-Murphy requested changes
Typos

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/config.cpp
> +
unnecessary empty line?

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgUserActions.hpp
> +        displayName = "Toggle ear pluggs";
it's `plugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgUserActions.hpp
> +        tooltip = "Toggle use of ear pluggs (no effect when using ace)";
it's `plugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgUserActions.hpp
> +    class GVAR(earPluggs) {
it's `earPlugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgUserActions.hpp
> +        onActivate = ACTION(earPluggs);
it's `earPlugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/UserActionGroups.hpp
> +            QGVAR(earPluggs)
it's `earPlugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/UserActionsConflictGroups.hpp
> +            QGVAR(earPluggs)
it's `earPlugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/fn_keyActions.sqf
> +    case QGVAR(earPluggs): {
it's `earPlugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp
> +            GVAR(earPluggs)[] = {DIK_END};
it's `earPlugs`

2022-02-12 14:34 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgUserActions.hpp
> +        tooltip = "Toggle visability of Antistasis information bar at the top of the screen";
it's `visibility`

2022-02-12 14:49 UTC, HakonRydland commented on A3A/addons/core/config.cpp
> +
its to separate grouped includes, defines.hpp is required for dialogs.hpp

2022-02-13 12:28 UTC, Bob-Murphy commented on A3A/addons/core/keybinds/CfgUserActions.hpp
> +        onActivate = ACTION(earplugs);
I think the P must be uppercase?

2022-02-13 12:39 UTC, Bob-Murphy approved these changes
I reviewed the P.
I approve the P.

2022-02-13 15:07 UTC, CalebSerafin requested changes
Okay, the change is quite good.
The only blocking change is that the stringtable entries should use formating entities like %1. More info in that issue.

2022-02-13 15:47 UTC, merged