Fuel Fixes
official-antistasi-community/A3-Antistasi pull request #2251
Opened 2022-02-13 22:15 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
replaces #2216 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-02-14 06:49 UTC, Bob-Murphy requested changes
Please add `Land_vn_usaf_fueltank_75_01` in the mapInfo of Cam Lao Nam as that was part of the old PR.

2022-02-14 06:49 UTC, Bob-Murphy commented on A3A/addons/core/functions/init/fn_initZones.sqf
> +		[_x, 250] call ace_refuel_fnc_setFuel; // only call on fuels that are not blacklisted and first zone init.
It was 2500 in the old PR. Is the change on purpose?

2022-02-14 18:16 UTC, CalebSerafin requested changes
Mostly good. Some minor improvements.

2022-02-14 18:16 UTC, CalebSerafin commented on A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
> +    [0,(-_price)] remoteExec ["A3A_fnc_resourcesFIA",2];
The has neough money check does not cover the being commander.
Two checks will need to happen, incase the faction has no money but the commander has enough.
Also, most of the function uses `_unit`, so that should be used. HOWEVER, `A3A_fnc_resourcesPlayer` is used, which must be local. So should `player` should be used everywhere?
```sqf
// ...
//check to make sure that the player is not spamming
private _lastTimePurchase = _unit getVariable["A3A_spawnItem_cooldown",time];
if (_lastTimePurchase > time) exitwith {["Item Purchase", format ["You already bought one, wait %1 seconds before you can buy another.", ceil (_lastTimePurchase - time)]] call A3A_fnc_customHint;};


// Try deduct funds from the player or faction.
private _notEnoughMoney = isNil {
    // Imagine how slick it would be if tryTake was a method.
    if (player == theBoss && { (IDKGetFactionMoneyOrSomething) >= _price }) exitWith {
        [0, -_price] remoteExec ["A3A_fnc_resourcesFIA",2];
        false
    };
    if ((player getVariable ["moneyX", 0]) >= _price) exitWith {
        [-_price] call A3A_fnc_resourcesPlayer;
        false
    };
    nil
};
if (_notEnoughMoney) exitWith { ["Item Purchase", "You can't afford this Item."] call A3A_fnc_customHint };

// At this point money deduction was successful
_unit setVariable["A3A_spawnItem_cooldown", time + 15];

//spawn the Item
// ...
```

2022-02-14 18:16 UTC, CalebSerafin commented on A3A/addons/core/functions/Base/fn_sellVehicle.sqf
> +if (_typeX in [FactionGet(reb,"vehicleFuelDrum"), FactionGet(reb,"vehicleFuelTank")]
Indentation is a little weird
```suggestion
if (_typeX in [FactionGet(reb,"vehicleFuelDrum"), FactionGet(reb,"vehicleFuelTank")] 
    && _veh getVariable ['A3A_canGarage', false]
) exitwith {
    floor ([_veh] call A3A_fnc_remainingFuel * (_veh getVariable ['A3A_itemPrice', 0]));
};
```

2022-02-14 23:56 UTC, CalebSerafin approved these changes
Looks good to me.

2022-02-14 23:56 UTC, CalebSerafin commented on A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
> +private _insufficientFunds = isNil {
`_noMoneyNoProblems` does not adequately describe what the variable holds.
What does it mean if it's true? What does it mean if it's false?

2022-02-14 23:57 UTC, killerswin2 commented on A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
> +private _insufficientFunds = isNil {
Yes

2022-02-14 23:58 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initZones.sqf
> +		[_x, 250] call ace_refuel_fnc_setFuel; // only call on fuels that are not blacklisted and first zone init.
Yes, some maps have too many fuel stations, some have too many.

2022-02-15 00:34 UTC, Bob-Murphy approved these changes

2022-02-15 00:37 UTC, Bob-Murphy commented
Does this issue close #2213 ?
If so, please link it properly. It was mentioned in the old PR.

2022-02-15 01:32 UTC, killerswin2 commented
Done

2022-02-15 10:52 UTC, merged