Hr events
official-antistasi-community/A3-Antistasi pull request #2254
Opened 2022-02-14 17:36 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Final part of 3rd party support:
    This part adds the event system to antistasi whit one example usage of event trigger, with this we could allow 3rd party mods to extend (in this case) AIVehInit to add functionality to the gamemode

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:  
- add an event listener like so 
```sqf
["AIVehInit", "test", {systemChat str _this}] call A3A_Events_fnc_addEventListener;
```
- now test it by buying a vehicle
- then remove one like so and retest
```sqf
["AIVehInit", "test"] call A3A_Events_fnc_removeEventListener;
```

- Then add two more and remove all for AIVehInit like so (test before and after removing)
```sqf
["AIVehInit", "test1", {systemChat "1"}] call A3A_Events_fnc_addEventListener;
["AIVehInit", "test2", {systemChat "2"}] call A3A_Events_fnc_addEventListener;

["AIVehInit"] call A3A_Events_fnc_removeAllEventListeners;
```

- Finally trigger a false event like so
```sqf
["AIVehInit", [player, side group player]] call A3A_Events_fnc_triggerEvent;
```
********************************************************
Notes:
This only adds the framework and an example event, there would need to be added a lot more events before it would be of substantial use to 3rd party developers.

2022-02-18 10:41 UTC, Bob-Murphy commented
Is this ready for review?

2022-02-18 10:52 UTC, HakonRydland commented
Yes, core mechanics can be reviewed, still need to decide and create all the hooks, but that can be done at a later point

2022-02-18 10:54 UTC, Bob-Murphy requested changes
typos and such

2022-07-09 18:27 UTC, killerswin2 approved these changes
LGTM, pray for events

2022-07-09 18:55 UTC, Bob-Murphy requested changes
DNLGTM

2022-07-09 18:55 UTC, Bob-Murphy commented on A3A/addons/Events/Events.hpp
> +                description = "Vehicle being initilized";
initialized

2022-07-09 18:55 UTC, Bob-Murphy commented on A3A/addons/Events/Events.hpp
> +                description = "Unit being initilized";
initialized

2022-07-09 18:55 UTC, Bob-Murphy commented on A3A/addons/Events/Events.hpp
> +                description = "civ vehicle being initilized";
initialized

2022-07-09 18:55 UTC, Bob-Murphy commented on A3A/addons/Events/Events.hpp
> +                description = "Unit being initilized";
initialized

2022-07-09 18:59 UTC, HakonRydland commented on A3A/addons/Events/Events.hpp
> +                description = "Unit being initilized";
me no english

2022-07-09 19:44 UTC, Bob-Murphy approved these changes
GNTM

2022-07-30 22:56 UTC, merged