Doom UI Buy Vehicle Menu
official-antistasi-community/A3-Antistasi pull request #2259
Opened 2022-02-16 21:38 UTC by CalebSerafin

## What type of PR is this.
* Bug
* Change
* [x] Enhancement

### What have you changed and why?
* Added a Params switch to opt-in to Development UI Preview
* When in preview UI. Buy Menu will be the new one.
* This should replace all buy menus.
* UI no longer scales by UI scale. This ensures that it's the same size on all displays. This has to be done because sub-elements scale according to the parents. Therefore, it becomes unreadable if small. and off-screen if large.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
* [x] No
* Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Open game.
Go to the vehicle buy menu.
Go to outpost buy menu.

2022-02-16 22:07 UTC, CalebSerafin commented
Tested on 3CB BAF & Factions to ensure the templates are pulled correctly.

2022-02-17 13:19 UTC, CalebSerafin commented
Okay, that should be all the new changes.

2022-02-17 16:08 UTC, HakonRydland requested changes
Buy boat should be consilidated into the new menu

2022-02-17 16:08 UTC, HakonRydland commented on A3A/addons/GUI/dialogues/defines.hpp
> +#define REFLECT(Text) Text
These two first onec are unused, do you have a plan for them?
last one is a dupe as they already have QUOTE defined in config.cpp with script_component.hpp include

2022-02-18 09:29 UTC, CalebSerafin commented on A3A/addons/GUI/dialogues/controls.hpp
> +    rowHeight = "4.32 * (1 / (getResolution select 3)) * pixelGridNoUIScale * 0.5";
UI no longer scales by UI scale. This ensures that it's the same size on all displays. This has to be done because sub-elements scale according to the parents. Therefore, it becomes unreadable if small. and off-screen if large.

2022-02-18 09:29 UTC, CalebSerafin commented on A3A/addons/GUI/dialogues/defines.hpp
> +#define REFLECT(Text) Text
It was used to replace the pound symbol used for select. However, that's no longer needed as there is no macro involved now.

2022-02-18 09:31 UTC, CalebSerafin commented on A3A/addons/GUI/dialogues/controls.hpp
> +    rowHeight = "4.32 * (1 / (getResolution select 3)) * pixelGridNoUIScale * 0.5";
A major change would be required to allow scaling.

2022-02-18 09:38 UTC, CalebSerafin commented on A3A/addons/GUI/dialogues/defines.hpp
> +#define REFLECT(Text) Text
But they may likely be used in the future.

2022-02-18 10:37 UTC, Bob-Murphy commented
Seems broken.
I tried it, switched on `A3A_GUIDevPreview`, loaded in and got slapped by this one.

`Warning Message: Resource A3A_BuyVehicleDialog not found`

2022-02-18 10:57 UTC, CalebSerafin commented
@Bob-Murphy You need to add it to your arma build settings.

2022-02-18 11:22 UTC, Bob-Murphy commented
lines intended?
![ArmA 3 Screenshot 2022 02 18 - 12 20 44 72](https://user-images.githubusercontent.com/50651578/154673298-efca7a0e-1e52-4e9e-9204-a6b270aa29cd.png)

2022-02-18 11:23 UTC, CalebSerafin commented
> lines intended?
That's got nothing to do with me.
I assume that change was intended as many players on the test server thought it was useful to see where their vehicle fits.

2022-02-18 11:24 UTC, Bob-Murphy commented
@HakonRydland ?

2022-02-18 11:26 UTC, Bob-Murphy commented
Other than that, UI works wonderful, mouse-over are working as intended.

2022-02-18 11:37 UTC, Bob-Murphy requested changes
Please remove the block with `<KeyID="STR_antistasi_dialogs_main_hc_fire_mission_position_start_label">` in line 581.
It's a dublicate and already is in line 517.
That popped up in the RPT.

2022-02-18 12:42 UTC, CalebSerafin commented
Okay, the placeholder for editor preview was added.
And the duplicate string table entry was fixed.

2022-02-18 14:28 UTC, HakonRydland commented
> @HakonRydland ?

an acidentall enabling of debug rendering, no idea why it was never brought up before, will make a pr to fix it

2022-02-18 21:28 UTC, HakonRydland approved these changes
all good now

2022-02-18 21:28 UTC, HakonRydland commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> -        _flag addAction ["Buy Boat", {[FactionGet(reb,"vehicleBoat")] spawn A3A_fnc_addFIAVeh},nil,0,false,true,"","(isPlayer _this) and (_this == _this getVariable ['owner',objNull])",4]
not exactly how i would have done it, but its fine

2022-02-19 11:06 UTC, Bob-Murphy approved these changes

2022-02-19 11:10 UTC, merged