Task framework
official-antistasi-community/A3-Antistasi pull request #2275
Opened 2022-03-03 19:06 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    New task framework (WIP)

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

- 03.March
System design open for major changes to correct shortcomings
Only a test task exists and the old task should be converted over to act as a temporary source of tasks until new task can be written (new task will be a resource heavy process)

2022-03-03 19:14 UTC, Bob-Murphy requested changes
typos

2022-03-03 19:14 UTC, Bob-Murphy commented on A3A/addons/Tasks/Core/fn_getSettings.sqf
> +    [QGVAR(TaskLingerTime), "SLIDER", ["Task linger time", "Time in minutes a task remains in the task list after compleation"], ["Antistasi","Tasks"], [1, 15, 3, 0], true, {
completion

2022-03-03 19:14 UTC, Bob-Murphy commented on A3A/addons/Tasks/Core/fn_getSettings.sqf
> +    [QGVAR(MaxTestMissions), "SLIDER", ["Max test missions", "maximum amount of test missions that can be active at the same time"], ["Antistasi","Tasks"], [0, 10, 3, 0], true, {
maximum --> Maximum

2022-03-03 19:14 UTC, Bob-Murphy commented on A3A/addons/Tasks/Core/fn_requestTask.sqf
> +        if (_chain isEqualTo "") then { Error_1("Missconfigured task %1, lacking name of chain", _x); continueWith false; };
Misconfigured

2022-03-03 19:14 UTC, Bob-Murphy commented on A3A/addons/Tasks/Core/fn_requestTask.sqf
> +            Debug_1("%1 Chain not at the required stage for task %2 | Current: %3 | Required: %4", _chain, _x, _stage, _requiredStage);
chain lowercase as not start of sentence

2022-03-07 23:01 UTC, killerswin2 requested changes

2022-03-07 23:03 UTC, killerswin2 commented
I don't understand why you are making tasks a separate pbo. The task are deep ingrained into core, so why not place in core?

2022-03-07 23:05 UTC, killerswin2 requested changes

2022-03-07 23:05 UTC, killerswin2 commented on A3A/addons/core/functions/Save/fn_loadStat.sqf
> +    "countCA", "attackCountdownInvaders", "testingTimerIsActive", "version", "HR_Garage","A3A_fuelAmountleftArray", QEGVAR(Tasks,ActiveTasks)
no macros in loadStat please

2022-03-07 23:07 UTC, killerswin2 requested changes

2022-03-07 23:07 UTC, killerswin2 commented on A3A/addons/Tasks/Tasks/fn_testTask.sqf
> +_this set ["Constructor", { // Type: code | Required | Constructor to run at start of task
what are we doing here?

2022-03-08 05:13 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_getSettings.sqf
> +        GVAR(Settings) set ["TaskLingerTime",round _this * 60];
seconds

2022-03-08 05:14 UTC, HakonRydland commented on A3A/addons/core/functions/Save/fn_loadStat.sqf
> +    "countCA", "attackCountdownInvaders", "testingTimerIsActive", "version", "HR_Garage","A3A_fuelAmountleftArray", QEGVAR(Tasks,ActiveTasks)
theres no reson not to use macros

2022-03-08 05:15 UTC, HakonRydland commented on A3A/addons/Tasks/Tasks/fn_testTask.sqf
> +_this set ["Constructor", { // Type: code | Required | Constructor to run at start of task
how is this a change request?

2022-03-08 05:15 UTC, killerswin2 commented on A3A/addons/Tasks/Tasks/fn_testTask.sqf
> +_this set ["Constructor", { // Type: code | Required | Constructor to run at start of task
yeah dismiss the review

2022-04-02 16:09 UTC, killerswin2 requested changes

2022-04-02 16:09 UTC, killerswin2 commented on A3A/addons/Tasks/Params/LegacyParams/fn_AS_specOP_p.sqf
> +private _controlsX = [controlsX] FUNC(nearHostileMarkers);
call FUNC(nearHostileMarkers);

2022-04-02 16:09 UTC, killerswin2 commented on A3A/addons/Tasks/Params/LegacyParams/fn_AS_specOP_p.sqf
> +private _nearbyFriendlyMarkers = FUNC(nearFriendlyMarkers);
call FUNC(nearFriendlyMarkers);

2022-04-02 16:23 UTC, killerswin2 requested changes

2022-04-02 16:23 UTC, killerswin2 commented on A3A/addons/Tasks/Core/fn_getSettings.sqf
> +if (isClass (configfile >> "CBA_Extended_EventHandlers")) then {
we should make this A3A_hasCBA

2022-04-02 16:23 UTC, killerswin2 commented on A3A/addons/Tasks/Core/fn_getSettings.sqf
> +if (isClass (configfile >> "CBA_Extended_EventHandlers")) then {
more than one place to use this

2022-04-02 16:38 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_getSettings.sqf
> +if (isClass (configfile >> "CBA_Extended_EventHandlers")) then {
this check (or similar check) would be needed anytime we have a cba dependent optional feature

2022-04-02 16:39 UTC, HakonRydland commented on A3A/addons/Tasks/Params/LegacyParams/fn_AS_specOP_p.sqf
> +private _controlsX = [controlsX] FUNC(nearHostileMarkers);
good catch

2022-04-03 20:15 UTC, Lazejun commented on A3A/addons/Tasks/Params/LegacyParams/fn_AS_Officail_p.sqf
> +private _possibleMarkers = [citiesX] call FUNC(nearHostileMarkers);
You kinda mixed Official and the Traitor Mission.

Traitor was Towns,
Official was Airbases.

I dont think its a bad idea to move them to Towns, just weird since the Goal was to port the old ones

2022-04-03 20:23 UTC, Lazejun commented on A3A/addons/Tasks/Params/LegacyParams/fn_AS_Officail_p.sqf
> +private _possibleMarkers = [citiesX] call FUNC(nearHostileMarkers);
Also very good filename type

"fn_AS_Officail_p.sqf" should have been "fn_AS_Official_p.sqf"

2022-07-03 08:18 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_genTaskID.sqf
> +GVAR(TaskID) = GVAR(TaskID) + 1;
missions can have more than one of each category or even same mission, as long as the setting for max tasks of the type is not blocking it, example: we would not want multiple defend petros missions running at the same time, default will be 1 per cat

2022-07-03 08:25 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_genTaskID.sqf
> +GVAR(TaskID) = GVAR(TaskID) + 1;
renaming has also been done

2022-07-04 15:57 UTC, jaj22 commented on A3A/addons/Tasks/Core/fn_requestTask.sqf
> +    private _cfg = TASK_CFG/(_taskTypes#0);
Typo? I don't see a TASK_CFG.

2022-07-04 16:05 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_requestTask.sqf
> +    private _cfg = TASK_CFG/(_taskTypes#0);
ln8

2022-07-04 16:14 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_requestTask.sqf
> +    private _cfg = TASK_CFG/(_taskTypes#0);
ah now i see it, corrected

2022-07-04 17:04 UTC, jaj22 commented on A3A/addons/Tasks/Core/fn_runTask.sqf
> +    _taskHM set ["__CurrentStage", (_taskHM get "__CurrentStage") +1]; //increment stage count (for saving/loading)
Wouldn't this cause currentStage to be saved as 2 when a task is saved during its first stage?

2022-07-04 17:59 UTC, HakonRydland commented on A3A/addons/Tasks/Core/fn_runTask.sqf
> +    _taskHM set ["__CurrentStage", (_taskHM get "__CurrentStage") +1]; //increment stage count (for saving/loading)
good catch, moved to after stage condition is meet

2023-03-18 01:05 UTC, rautamiekka commented on A3A/addons/Tasks/Params/LegacyParams/fn_LOG_Ammo_p.sqf
> +	_Markers
```suggestion
	_Markers select {(getMarkerPos _x distance2D getMarkerPos respawnTeamPlayer < distanceMission) && (sidesX getVariable [_x,sideUnknown] != teamPlayer)}
```
No need to save privately if you immediately return.

2023-03-18 01:05 UTC, rautamiekka commented on A3A/addons/Tasks/Params/LegacyParams/fn_LOG_Ammo_p.sqf
> +_possibleMarkers = [ outposts] call _findIfNearAndHostile;
```suggestion
_possibleMarkers = [outposts] call _findIfNearAndHostile;
```

2023-03-18 01:05 UTC, rautamiekka commented on A3A/addons/Tasks/Params/LegacyParams/fn_LOG_Ammo_p.sqf
> +if ( _possibleMarkers isEqualTo []) exitWith {false};
```suggestion
if (_possibleMarkers isEqualTo []) exitWith {false};
```

2023-03-18 01:06 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +private _timeLimit = if (_this get "_isDifficult") then {30} else {60};
```suggestion
private _timeLimit = [60, 30] select (_this get "_isDifficult");
```

2023-03-18 01:09 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +	Note: the task sets all feedback to players automaticly based on the info in the task hm passed to the task
```suggestion
	Note: the task sets all feedback to players automatically based on the info in the task hm passed to the task
```

2023-03-18 01:09 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +	the modifyable values are:
```suggestion
	the modifiable values are:
```

2023-03-18 01:16 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +			private _side = _this get "_side";
```suggestion
			private _bonus = [1, 2] select (_this get "_isDifficult");
			private _positionX = (_this get "destination");
			private _markerX = (_this get "marker");
			private _side = (_this get "_side");
```
The last for consistency, otherwise the parens ain't needed.

2023-03-18 01:18 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +				[-10*_bonus,theBoss] call A3A_fnc_playerScoreAdd;
```suggestion
			if ((_this get "state") isNotEqualTo "SUCCEEDED") then
			{
				[-10 * _bonus,theBoss] call A3A_fnc_playerScoreAdd;
```
For consistency.

2023-03-18 01:18 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Supplies.sqf
> +            private _positionX =(_this get "destination");
```suggestion
            private _positionX = (_this get "destination");
```
For consistency.

2023-03-18 01:19 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Supplies.sqf
> +			    [-15*_bonus,15*_bonus,_positionX] remoteExec ["A3A_fnc_citySupportChange",2];
```suggestion
			    [-15 * _bonus,15 * _bonus,_positionX] remoteExec ["A3A_fnc_citySupportChange",2];
```
For consistency.

2023-03-18 08:21 UTC, HakonRydland commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +private _timeLimit = if (_this get "_isDifficult") then {30} else {60};
select is slower than an if statement

2023-03-18 15:10 UTC, rautamiekka commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +private _timeLimit = if (_this get "_isDifficult") then {30} else {60};
Weird, you'd think there would be no point in the feature in such case.

2023-03-19 02:14 UTC, killerswin2 commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_AS_Official.sqf
> +            [leader _group, _this get "marker", "SAFE", "SPAWNED", "NOVEH", "NOFOLLOW"] execVM EQPATHTOFOLDER(core,scripts\UPSMON.sqf);
```suggestion
            [leader _group, _this get "marker", "SAFE", "SPAWNED", "NOVEH", "NOFOLLOW"] spawn UPSMON_fnc_UPSMON;
```

2023-03-19 02:15 UTC, killerswin2 commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_AS_Official.sqf
> +            [leader _group, _this get "marker", "SAFE", "SPAWNED", "NOVEH", "NOFOLLOW"] execVM EQPATHTOFOLDER(core,scripts\UPSMON.sqf);
need to update to after upsmon move

2023-03-22 17:48 UTC, Bob-Murphy requested changes
as noted

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +				[petros,"hint",(localize "STR_antistasi_LTasks_LOG_Ammo_destroyed_description"), "Logistics Mission"] remoteExec ["A3A_fnc_commsMP",[teamPlayer,civilian]];
"Logistics Mission"
Please localize

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +				[petros,"hint",(localize "STR_antistasi_LTasks_LOG_Ammo_captured"), "Logistics Mission"] remoteExec ["A3A_fnc_commsMP",[teamPlayer,civilian]];
"Logistics Mission"
Please localize

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Ammo.sqf
> +					["TaskFailed", ["", format ["Ammotruck Stolen in an %1",(_vehicle getVariable ["ammoTruckLocation", ""])]]] remoteExec ["BIS_fnc_showNotification",_owningSide];
"Ammotruck Stolen in an %1"
Please localize

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/Tasks/LegacyTasks/fn_LOG_Supplies.sqf
> +                [petros,"hint",(localize "STR_antistasi_LTasks_LOG_Supplies_supplies_delivered"), "Logistics Mission"] remoteExec ["A3A_fnc_commsMP",[teamPlayer,civilian]];
"Logistics Mission"
Please localize

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/stringtable.xml
> +        <Original>We have spotted a %1 SpecOp team patrolling around a %2. Ambush them and we will have one less problem. Do this before %3. Be careful, they are tough boys.</Original>
Just double-checking, does it makes to have the `a` before the %2?
It is stating something like "ourpost, airport, resource" or for example a city name?
Maybe `around the` would be more fitting as for `outpost/airport` it would be `an outpost / an airfield`.

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/stringtable.xml
> +        <Original>A %1 would be a fine addition to our cause. Go there and capture it before %2.</Original>
Same here, what exactly is the location name? Does the `A` make sense?

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/stringtable.xml
> +        <Original>A %1 is disturbing our operations in the area. Go there and capture it before %2.</Original>
Same as above

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/stringtable.xml
> +        <Original>%1 population is in need of supplies. We may improve our relationship with that city if we are the ones who provide them. I have placed a crate with supplies near our HQ. Deliver th
You mention `city center` but we mostly deliver to villages.
Maybe something like `Deliver the crate to the center of %1` makes more sense.

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/stringtable.xml
> +        <Original>Keep distributing supplies for %1 more seconds.</Original>
You are not actively distributing the supplies but more guarding them.
`Keep guarding the supplies for %1 more seconds.`

2023-03-22 17:48 UTC, Bob-Murphy commented on A3A/addons/Tasks/stringtable.xml
> +        <Original>We've spotted an Ammotruck in an %1. Go there and destroy or steal it before %2.%2.</Original>
duplication of `%2`?

2025-11-10 17:33 UTC, Tiny-DM commented
An expanded version of the task state machine was added in #3667. It is finally time to close another historical piece.

2025-11-10 17:33 UTC, closed without merging