UtilityItems - Prevent players from carrying objects into vehicles.
official-antistasi-community/A3-Antistasi pull request #2284
Opened 2022-03-08 03:54 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Added an event handler to the play when holding an movable item. Once trigger the item is moved away from the vehicle to stop damage.

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-03-14 13:26 UTC, jaj22 requested changes
Flagged some clear errors. I'm working on the basis that this PR is a quick fix, and there's a glorious longer-term plan to bring all the object-carrying code together and rewrite it.

2022-03-14 13:26 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
> +        _unit removeEventHandler ['GetIn', _thisEventHandler];
Wrong event handler.

2022-03-14 13:26 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
> +    _item enableSimulationGlobal false; // prevent killing players with item
enableSimulationGlobal must be executed on the server.

2022-03-14 13:26 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
> +        private _pos = [_unit, 1, 10, 3, 0, 20, 0] call BIS_fnc_findSafePos;
IIRC BIS_fnc_findSafePos only checks for terrain objects, not entities, so this is probably disastrous. If you want a quick solution then setVehiclePosition with "NONE" is a better bet.

2022-03-14 13:55 UTC, killerswin2 commented
Yeah, later I plan to kill some of Hakon's carry code and unify them

2022-03-14 20:44 UTC, killerswin2 commented
ready for round two!

2022-03-15 15:53 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_remainingFuel.sqf
> +	( _currentFuelCargo / _vehicleMaxFuel);
Formatting: Tab not space, plus random bonus space after the bracket.

2022-03-16 15:58 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
> +        if (isNil _objectCarrying) exitwith {_player removeEventHandler ["GetInMan", _thisEventHandler]};
Should be `if (isNil "_objectCarrying")`

2022-03-16 16:00 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
> +        if (isNil _objectCarrying) exitwith {_player removeEventHandler ["GetInMan", _thisEventHandler]};
Also _unit rather than _player.

2022-03-19 17:35 UTC, jaj22 approved these changes
Probably works :P

2022-03-20 23:40 UTC, Bob-Murphy commented
You wrote that you want to "unify the code" but at the same time you removed forced walk because "as the intent is use this around base".

So, if you want to unify the code and removed the forced walk in the end everything would have removed "forced walk"?

In general I don't see the reason to remove it, especially when it enabled players to run around with items in the hands like damn idiots knocking other players left and right.

2022-03-21 00:39 UTC, killerswin2 commented
Bob, discussion of adding or removal of force walk can come at a later date when I merge both carrying code.

2022-03-21 01:28 UTC, Bob-Murphy commented
I'm this case I'll leave it labeled as "not now" so it doesn't get merged before you are done with Hakons code.

2022-03-21 03:28 UTC, killerswin2 commented
No, merge it. Hakon's carry loot box code is outside of this scope for the pr.

2022-03-21 08:49 UTC, Bob-Murphy requested changes
Please re-enable forceWalk.

2022-03-21 11:41 UTC, killerswin2 commented
No

2022-03-21 12:59 UTC, Bob-Murphy approved these changes
Topic has been discussed on discord.
Good for now.

2022-03-21 13:02 UTC, merged