No-unlocks support for rebel AI equipping
official-antistasi-community/A3-Antistasi pull request #2305
Opened 2022-03-24 19:14 UTC by jaj22

### What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
We need a new method of picking rebel AI equipment after removing unlocks. I've decided that the best method is to base AI equipment on the arsenal contents but generate new items. This is relatively simple (actually taking items from the arsenal is complex and expensive, especially with garrisons) and should have low exploit potential and no significant player count balance problems.

Processing the arsenal for each unit recruited is still too expensive, so this PR rewrites the rebel AI equipping code to use server-generated weighted lists. Some details:
- Generates weighted arrays on server every 10mins, transmits to clients as required.
- Weight based on arsenal contents. Typically 10 items min chance, 50 max.
- Item usage is also capped by available magazines/bullets.
- Refund value halved to reduce effectiveness of exploits.
- Still works correctly with unlocks enabled.

General improvements to rebel AI equipping:
- Improved use of NV, grenades, explosives and launchers.
- Optics are now weapon-appropriate.
- Magazines are now added by weight instead of count.

General improvements to automatic item categorisation:
- equipmentClassToCategories now caches for fast subsequent use.
- Disposable launcher support added.
- Optic categorization added.
- Explosive charge detection added.
- Moved smoke grenade, flashlight and thermal detection to equipmentClassToCategories.
- Simplified and fixed missile launcher support.
- Fixed some broken CUP stuff in categoryOverrides.

Misc:
- Fixed incorrect CUP template dependency.

The only regression at the moment is that missile launchers will no longer be used even if the unlocks are enabled. The plan is to add AT/AA missile launcher rebel infantry types which should be much more expensive to buy, but this requires additional entries added to each rebel template, and some UI work.

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

This is insufficiently tested. I've run the categorization code on RHS and CUP, but not VN or BAF yet. The rebel equipping code should be somewhat solid if the categorization works, although if weapons exist without a default magazine then that may trip up some config calls.

### How can the changes be tested?
A3A_rebelGear is the hashmap containing all the gear lists, so that's worth looking at before spamming soldiers.

2022-03-24 21:17 UTC, killerswin2 requested changes

2022-03-24 21:17 UTC, killerswin2 commented on A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf
> +            _pool = A3A_rebelGear get "Shotguns" + A3A_rebelGear get "SniperRifles";
(A3A_rebelGear get "Shotguns") + (A3A_rebelGear get "SniperRifles");

2022-03-24 21:42 UTC, Lazejun commented on A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
> +_rebelGear set ["UnarmoredVests", _uvests];          // not a category name, but whatever
Thats actually very Ironic with the Comment.

You could just rename the CivivilianVests to UnarmoredVests

https://github.com/official-antistasi-community/A3-Antistasi/blob/4f9923ed8b8908c32877b5ac19acbb73c2358e4a/A3A/addons/core/functions/Ammunition/fn_equipmentSort.sqf#L50-L55

https://github.com/official-antistasi-community/A3-Antistasi/blob/4f9923ed8b8908c32877b5ac19acbb73c2358e4a/A3A/addons/core/functions/Ammunition/fn_loot.sqf#L63


22:36:08 Error in expression < get "UnarmoredVests") };
_unit addVest _vest;

private _backpack = selectRandom>
22:36:08   Error position: <_vest;

private _backpack = selectRandom>
22:36:08   Error Undefined variable in expression: _vest
22:36:08 File x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf..., line 64
22:36:08  ➥ Context: 	[] L28 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L29 (x\A3A\addons\core\functions\REINF\fn_FIAinit.sqf)
	[] L76 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)
	[] L81 (x\A3A\addons\core\functions\REINF\fn_equipRebel.sqf)

2022-03-24 22:12 UTC, Lazejun commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +        if (_maxzoom >= 0.0625 ) exitWith { _categories pushBack "OpticsMid" };        // su230 etc
As Configs are fun Optics mid might have a few funny entries or lacks some so they end up in OpticsLong

CUP RCO's are 0.623 and end up in Long.

We could try rounding up the Numbers so "Draw the Line" between Close, Mid and Long at like 1 to 2X, 2 to 6X (MG Optic in RHS, the SU260) and 6 and higher are Long.

Some Ace Code below, they round up.

https://github.com/acemod/ACE3/blob/d1353713198720fda42a134d6d1a6e23e4c4d4c2/addons/arsenal/functions/fnc_statTextStatement_scopeMag.sqf#L16-L26

2022-03-25 14:21 UTC, jaj22 commented
Fixed everything else that turned up but didn't change the CivilianVests/UnarmoredVests naming yet. I guess "CivilianVests" is kinda weird given that we block undercover for them. 

A lot of the VN categoryOverrides look wrong so I'll check that later.

2022-03-25 14:24 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
> +_rebelGear set ["UnarmoredVests", _uvests];          // not a category name, but whatever
The error there is unrelated to the naming. generateRebelGear failed to complete due to bugging out on bad magazines, and the vests are the first thing used (by Petros).

Not sure which way to go with the naming. rebelGear doesn't have to match category names anyway, they were just convenient. I'll flip it one way or the other before merge though.

2022-03-26 14:26 UTC, jaj22 commented
- Reworked the optic detection to use the ranging capability, so now it picks up the DMS and PSO-1 as long range. All the VN optics count as long range, which is fine.
- Switched UnarmoredVests to CivilianVests for consistency.
- Fixed the VN weapon category overrides. It needs a lot of them.
- Fixed rebel AIs not using disposable launchers (everything needs a magazine).

2022-03-26 17:34 UTC, jaj22 commented
Turns out there was a second way to cause the petros vest problem. arsenal_addItem (as used by unlockEquipment) updated every machine with a remoteExecCall, so it was possible for generateRebelGear to run before all the equipment had actually been added to the arsenal. I fixed arsenal_addItem so that it updates the server immediately when run locally.

Also checked the categories with CUP. Optics & launchers seem fine at least, so I think that's all the modsets tested.

2022-03-26 22:28 UTC, Lazejun commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +            if (getNumber (_x >> "opticsZoomMin") < 0.2) exitWith {
I think this causes way more Issue than the Previous version:
RHS (It's all 4 RHSDev variants as i wanted to look at new stuff, should not affect most config Values)
![107410_20220326232013_1](https://user-images.githubusercontent.com/57111907/160258879-faaf0608-df4b-4c2d-8bfa-1a71f371a219.png)
RHS Scope lists
[Scopes.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/8356461/Scopes.txt)
Vanilla with Ace and Zen
[ScopesVanilla.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/8356466/ScopesVanilla.txt)
![107410_20220326232645_1](https://user-images.githubusercontent.com/57111907/160259046-98e680b4-f1b6-47a4-803a-e0d9878ecda4.png)

2022-03-27 00:12 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +            if (getNumber (_x >> "opticsZoomMin") < 0.2) exitWith {
Oh lol, the ACE compats actually remove the value I was using to identify ranging (discreteDistance), I guess because that was the only way to disable vanilla ranging. I'll have to add a check for the ACE ranging value as well.

Curious about the Russian optics (1P29 and some PSO-1s) that still have discreteDistance. I guess they use vanilla ranging even with ACE?

2022-03-27 00:35 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +            if (getNumber (_x >> "opticsZoomMin") < 0.2) exitWith {
Oh yeah, apparently all the PGO_7V variants are compatible with various AKs. Not sure if we want to fight that. Stat-wise they're a valid mid-range optic and they seem to use the standard Russian scope attachment. I'm guessing that the ak/pkp/asval versions are even marked for those weapons. AIs won't care about the markings anyway.

2022-03-27 14:41 UTC, Lazejun commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +            if (getNumber (_x >> "opticsZoomMin") < 0.2) exitWith {
It's a bit better with:
[3b27e89](https://github.com/official-antistasi-community/A3-Antistasi/pull/2305/commits/3b27e89c222c6a1bba01ace251eaa58934bee605)

But annyoingly still weird in some Cases for RHS:
[Scopes.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/8357839/Scopes.txt)
Like the Common RHS ACOGs end up in Long.

**I would say fuck it,
It's as good as we can get it so that should be fine now.**
```sqf
["rhsusf_acc_ELCAN",
"rhsusf_acc_ELCAN_ard",
"rhsusf_acc_ACOG",
"rhsusf_acc_ACOG_wd",
"rhsusf_acc_ACOG_d",
"rhsusf_acc_ACOG2",
"rhsusf_acc_ACOG3",
"rhsusf_acc_ACOG_USMC",
"rhsusf_acc_ACOG2_USMC",
"rhsusf_acc_ACOG3_USMC",
"rhsusf_acc_ACOG_RMR"];
```
CUP With Ace looks pretty OK
[ScopesCUP.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/8357852/ScopesCUP.txt)
And Vanilla looks pretty fine
[ScopesVanilla.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/8357866/ScopesVanilla.txt)

2022-03-27 14:58 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +            if (getNumber (_x >> "opticsZoomMin") < 0.2) exitWith {
Ah yeah, RHS ACOG defines all the ACE scope ranging params with zeros for some reason. Can workaround that easily enough, hopefully without breaking anything else. ELCAN just looks like a busted config (scope zoom is wrong, ACE ranging on marked scope) so I'm not bothered if that slips through.

2022-03-27 15:07 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
> +            if (getNumber (_x >> "opticsZoomMin") < 0.2) exitWith {
Double-checked ACE code. If force turrets is disabled and the vertical adjustment value doesn't exist then the default is 0, or no ranging. So checking >0 for vertical adjustment should be correct.

2022-03-27 15:16 UTC, Lazejun commented
Had a look how AI Picks Equipment with No Unlocks, that seems to work pretty nice.

The only funny thing i saw while looking at it, is that the "ADR DLC" P90s are "Rifles"

```sqf
"SMG_03_TR_black",
"SMG_03_TR_camo",
"SMG_03_TR_khaki",
"SMG_03_TR_hex",
"SMG_03C_TR_black",
"SMG_03C_TR_camo",
"SMG_03C_TR_khaki",
"SMG_03C_TR_hex",
"SMG_03_black",
"SMG_03_camo",
"SMG_03_khaki",
"SMG_03_hex",
"SMG_03C_black",
"SMG_03C_camo",
"SMG_03C_khaki",
"SMG_03C_hex",
```

And as it seems we kinda forget to stay up to date when Arma Updated for Contact etc.
Marksman Variant of LDFs AR, Classed as Rifles
```sqf
"arifle_MSBS65_Mark_F",
"arifle_MSBS65_Mark_black_F",
"arifle_MSBS65_Mark_sand_F",
"arifle_MSBS65_Mark_camo_F",
```
Probably not worth to change but these are Underbarrel Shotgun variants Classed as Just Rifles
```sqf
"arifle_MSBS65_UBS_F",
"arifle_MSBS65_UBS_black_F",
"arifle_MSBS65_UBS_sand_F",
"arifle_MSBS65_UBS_camo_F"
```
RPKs are Classed as Rifles but could be Machineguns
```sqf
"arifle_RPK12_F",
"arifle_RPK12_lush_F",
"arifle_RPK12_arid_F",
```

2022-03-27 17:09 UTC, jaj22 commented
Odd thing about the P90 is that the ammo performance is pretty close to the vanilla 5.45 rounds, and possibly better than the RHS M855 and some RHS 5.45s, so it might not be the worst weapon for a rifleman to carry around. On the other hand it is a light weapon, so good for medics.

I'm not a fan of adding rifles to the sniper list just because they have a long barrel, but apparently in ACE compats these 6.5mm weapons get different cartridges. However, it's barely better than the stock 6.5mm (1.1 caliber vs 1.0, both have 10 hit), so still miserable as marksman ammo. Think I'll keep those in rifles.

The GL code could give ammunition to the underbarrel shotguns (and that 50cal specops underbarrel from Apex), but we wouldn't want them used instead of real grenade launchers, so it'd need an extra keyword. Probably not worth it because AIs likely wouldn't know what to do with them.

RPKs should be MachineGuns, yeah.

2022-03-27 17:34 UTC, Lazejun approved these changes
Should be fine now

2022-04-10 13:26 UTC, merged