Add Faces and Speakers to Templates
official-antistasi-community/A3-Antistasi pull request #2316
Opened 2022-04-02 20:55 UTC by Lazejun

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Added Faces and Voices (Speaker) to Templates,
removed Identities and its use in the Code, replaced it with BIS_fnc_setIdentity,
Added a Check for ace_noradio_enabled, if its disabled, Players get Faction fitting Speakers applied.
(This sets "AceNoVoice" as Speaker on Respawn).
### Please specify which Issue this PR Resolves.
only half of #1914 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
TP around spawn Units etc.
If you manually Spawn units they need NatoInit/FiaInit called onto them.
```sqf
//All Loadouts with 15 meters in between with NatoInit 
_returnpos = getpos (player); 
_westGrp = createGroup west; 
_eastGrp = createGroup east; 
 
//SF 
[_westGrp, "loadouts_occ_SF_SquadLeader", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_Rifleman", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_Medic", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_Engineer", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_ExplosivesExpert", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_Grenadier", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_LAT", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_AT", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_AA", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_MachineGunner", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_Marksman", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_SF_Sniper", getpos (player)] call A3A_fnc_createUnit; 
 
player setPos (getPos player vectorAdd [15,0,0]); 
//Military 
[_westGrp, "loadouts_occ_military_SquadLeader", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_Rifleman", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_Medic", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_Engineer", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_ExplosivesExpert", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_Grenadier", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_LAT", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_AT", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_AA", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_MachineGunner", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_Marksman", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_military_Sniper", getpos (player)] call A3A_fnc_createUnit; 
 
player setPos (getPos player vectorAdd [15,0,0]); 
//Militia 
[_westGrp, "loadouts_occ_militia_SquadLeader", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_Rifleman", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_Medic", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_Engineer", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_ExplosivesExpert", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_Grenadier", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_LAT", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_AT", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_AA", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_MachineGunner", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_Marksman", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_militia_Sniper", getpos (player)] call A3A_fnc_createUnit; 
 
player setPos (getPos player vectorAdd [15,0,0]); 
//Other Loadouts 
[_westGrp, "loadouts_occ_police_SquadLeader", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_police_Standard", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_other_Official", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_other_Traitor", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_other_Crew", getpos (player)] call A3A_fnc_createUnit;  
[_westGrp, "loadouts_occ_other_Pilot", getpos (player)] call A3A_fnc_createUnit; 
 
player setpos _returnpos; 
 
player setPos (getPos player vectorAdd [0,10,0]); 
 
//SF  
[_eastGrp, "loadouts_inv_SF_SquadLeader", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_Rifleman", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_Medic", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_Engineer", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_ExplosivesExpert", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_Grenadier", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_LAT", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_AT", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_AA", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_MachineGunner", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_Marksman", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_SF_Sniper", getpos (player)] call A3A_fnc_createUnit;  
  
player setPos (getPos player vectorAdd [15,0,0]);  
//Military  
[_eastGrp, "loadouts_inv_military_SquadLeader", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_Rifleman", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_Medic", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_Engineer", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_ExplosivesExpert", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_Grenadier", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_LAT", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_AT", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_AA", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_MachineGunner", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_Marksman", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_military_Sniper", getpos (player)] call A3A_fnc_createUnit;  
  
player setPos (getPos player vectorAdd [15,0,0]);  
//Militia  
[_eastGrp, "loadouts_inv_militia_SquadLeader", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_Rifleman", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_Medic", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_Engineer", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_ExplosivesExpert", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_Grenadier", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_LAT", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_AT", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_inv_militia_AA", getpos (player)] call A3A_fnc_createUnit;   
[_eastGrp, "loadouts_i [...]

2022-04-05 14:22 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
> +    if (isNil "_voices") then {_voices = selectRandom (_faction get "voices")};
General cleanup of code duplication here: You could pull the regular faces/voices out front, and then just do:
``
private _face = selectRandom (_faction getOrDefault ["milFaces", _regularFaces]);
private _voice = selectRandom (_faction getOrDefault ["milVoices", _regularVoices]); 
```
Cleaned up other code issues there:
- Face/voice naming. It's a single thing after the selectRandom.
- Lack of private qualifier on face/voice.
- Some double spaces.

Private qualifiers are the only important thing here though.

`_unit getVariable "unitType"` should also be pulled out front, because otherwise SQF is dumb enough to re-evaluate it on each case.

2022-04-05 14:32 UTC, jaj22 requested changes
Looks reasonable other than some minor code issues in NATOinit. Abusing group-side switching and predefined class identities may have been slightly faster but this is one fairly short remoteExec per unit, and has more flexibility and resistance to mod bugs.

2022-04-05 14:33 UTC, jaj22 commented
Actually it might make more sense to put the identity code in createUnit rather than NATOinit.

2022-04-05 14:34 UTC, Lazejun commented on A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
> +    if (isNil "_voices") then {_voices = selectRandom (_faction get "voices")};
Oh yeah 😅

2022-04-05 17:57 UTC, Lazejun commented
> Actually it might make more sense to put the identity code in createUnit rather than NATOinit.

Probably, but i avoided cause i thought it was supposed to be high speed so i didnt want to slow it down with my Spaghetti :D

If you think it would be better i could move it over.

2022-04-05 20:54 UTC, Lazejun commented
Updated it, it didnt catch fire so far, so thats good.

I think i did it like you Suggested it, if not just tell me

2022-04-10 13:12 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
> +private _voice = selectRandom (_faction get "voices");
A rare case where it's better to do `private ["_face", "_voice"];`. The values here won't be used.

2022-04-10 13:15 UTC, Lazejun commented on A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
> +private _voice = selectRandom (_faction get "voices");
Done

2022-04-10 13:33 UTC, jaj22 approved these changes
I think I'm fine with this. Ideally createUnit should be setting voice/face (it's working with unit types which should in theory provide all the required information), but this works and the main thing is get the data into the templates.

2022-04-10 15:29 UTC, merged