Update french translations
official-antistasi-community/A3-Antistasi pull request #2347
Opened 2022-05-05 13:19 UTC by zayfix

Hello ! I'm back after almost [2 years](https://github.com/official-antistasi-community/A3-Antistasi/pull/1109) for more french translations !

By the way i just wanted to say you guys are doing an amazing job !

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information: Updated french translations.
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
- Load up Antistasi with the game language set to French.

********************************************************
Notes: N/A

2022-05-07 14:37 UTC, Bob-Murphy commented
Hey, welcome back and thank you for the commit.
I'll see to get it integrated.

2022-05-07 15:00 UTC, Bob-Murphy requested changes

2022-05-12 14:45 UTC, Eli-Porter requested changes

2022-05-12 14:45 UTC, Eli-Porter commented on A3A/addons/core/Stringtable.xml
> +        <French>Player and Money Interaction</French>
Change it to either "Interaction du Joueur et de l'Argent" or "Interaction Joueur et Argent"

2022-06-10 07:17 UTC, Bob-Murphy commented
Sorry for the delay.
Thank you Eli for checking and Thank you Zayfix for the changes.
I try to get my build bipeline up (new computer) so I can test and confirm it working this weekend.

2022-06-29 19:14 UTC, Bob-Murphy approved these changes
Läuft

2022-06-29 19:16 UTC, merged

2022-06-29 19:17 UTC, Bob-Murphy commented
@zayfix I finally got time to check it and it's good and merged for next update.
Thank you!