Emeny near changes
official-antistasi-community/A3-Antistasi pull request #2381
Opened 2022-06-17 16:17 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Parameterized the value for enemyNearCheck. This allows for player to choose the distance of the check. AKA, lower values easy checks. This PR makes are references to enemyNearCheck consistent, no more 500 meters for one check and 300 for another.
    

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-06-29 02:51 UTC, jaj22 commented
While knocking the 500m checks down to 300m is probably a good idea, I'm not too sure about parameterization, especially to the point of letting people disable the checks entirely. I'd say the bigger problem with the checks is which units count for them, with checks frequently blocked by oblivious 2-man garrison patrols or QRF remnants that should have retreated hours ago.

One approach is to consider target knowledge to identify units which are actually engaged with units near the flag (as in the garage check in addVehicle, not covered here), but that will have performance issues in the future due to non-local target knowledge checks.

Something that might work well is only counting spawner units and enemy markers: Retreating troops no longer count as spawners, and they should all be flagged correctly in #2383. Enemy markers are actually more of a technical problem because there's no mechanism to fetch near markers at the moment. But this should achieve the goal of blocking when there's significant enemy action in the vicinity, and not otherwise.

Another related thing I want to try is blocking the use of flag facilities at a location until it's been held for a specific time. Might need some tweaks to make the loot crates more manageable though.

2022-06-29 18:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +//_distanceX = 500; dead code now
If you have dead code like this, please remove it.
Let's not repeat mistakes from the past and collect more and more dead code.

2022-06-29 18:16 UTC, killerswin2 commented
@Bob-Murphy The forum was posted in the member's chat. Would you like to extended it out more?

2022-06-29 18:20 UTC, Bob-Murphy commented
> @Bob-Murphy The forum was posted in the member's chat. Would you like it to be extended it out more?

Only posting a questionnaire in the members chat is basically catering only a certain audience aka people that mostly play with blob squads on our servers and have no stategic approach at all.
In this case it's not needed to extend it out. It's very clear that players in general prefer it adjustable without getting more data and also based on countless comments regarding that in the help channel and such over the time.
Nevertheless, only because people say that they would like to have 100m distance or no check at all does not answer the question on if that option even would make sense gameplay wise.
Hence my comment above regarding range and default value adjustment.

2022-08-14 21:52 UTC, jaj22 requested changes
Minor stuff, otherwise looks solid.

2022-08-14 21:52 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +	if ([getPos player] call A3A_fnc_enemyNearCheck) then {
Should be anything except getPos (getPosATL is fine here) due to the unnecessary performance overhead. Doesn't really matter here but we need to start setting an example :P

2022-08-14 21:52 UTC, jaj22 commented on A3A/addons/Garage/Public/fn_addVehicle.sqf
> +if ([_player] call A3A_fnc_enemyNearCheck) exitWith {["STR_HR_GRG_Feedback_addVehicle_enemiesNear"] remoteExec ["HR_GRG_fnc_Hint", _client]; false };
This one's a bit odd because the new enemyNearCheck is much closer to the garage's enemiesEngaging check than the enemiesNear check. It's an interesting question of whether the hard <100 check is worth keeping or causes more problems (eg with logic/AI-unit enemies and those stuck in rocks or underground) than it solves.

My inclination would be to replace both garage checks with the new code for consistency and see how it goes.

2022-08-14 21:52 UTC, jaj22 commented on A3A/addons/maps/MissionDescription/params.hpp
> +        texts[] = {"Load from save (Default: 300)", "0", "100", "200", "300", "400", "500"};
I wouldn't personally give them the zero option because it removes some fundamental game mechanics. You could have enemies right next to the flag and spawn garrison on top of them, for example. There is a school of thought for allowing people to break their own game, but having the parameter feels like encouragement. They can always force the var persistently with the command line if they really want to.

Even 300m is much more generous than the old 300m, due to the COMBAT behaviour check.

2022-08-14 21:57 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_enemyNearCheck.sqf
> +    trys to carry an object to a place
Not that I bother reading comments but this one is a copypaste bug.

2022-08-14 22:00 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_enemyNearCheck.sqf
>  _return
Oh yeah, this stuff is kinda clumsy. Can dump the return var and just do:

`_nearEnemies isNotEqualTo [];`

2022-08-14 22:22 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +	if ([getPos player] call A3A_fnc_enemyNearCheck) then {
yeah, I don't need the pos. Inarray can take an object

2022-08-14 23:00 UTC, jaj22 approved these changes
Looks good now.

2022-08-21 17:37 UTC, merged