Initial version of attack/support rework
official-antistasi-community/A3-Antistasi pull request #2383
Opened 2022-06-18 17:24 UTC by jaj22

### What type of PR is this.
1. [X] Fail project

### What have you changed and why?
This is a general rework of all enemy supports and attacks to draw from limited resource pools. Key files and systems:

#### Resource pools
Enemy resources are split into two types, "attack" and "defence". Units generated as part of an attack or support are paid for up-front and have their "A3A_resPool" variable set accordingly. If despawned in good condition, they are partially refunded. Mission units have A3A_resPool set to "legacy" and are free to spawn (as they're effectively ambient units with no particular task), and paid for equally from both pools on destruction. Garrison units are paid for on creation and not refunded on despawn for obvious reasons. Attack and defence resources are saved, and updated appropriately on save: Pre-paid units are refunded according to damage level.

Attack and defence pools are used differently. An attack is launched once an enemy faction hits >0 attack resources, typically leaving that faction with a large negative value, which is slowly increased back to zero before the next attack can be launched. Defence resources typically have a positive buffer which is used up as reinforcements and supports are generated.

#### AggressionUpdateLoop
This file (basically a 60-second loop) is now responsible for updating all the balance variables, incrementing the four resource pools and launching attacks. Descriptions of balance variables:

- A3A_activePlayerCount is a count of all active players. Activity is determined by a simple client-side getDir check.
- A3A_balancePlayerScale is the general amount-of-stuff coefficient, normalized to 1 with 6 players at tier 6.
- A3A_balanceVehicleCost is a rough average resource cost of a single attack vehicle + cargo (if any) at the current war tier.
- A3A_balanceResourceRate is the resources of each type typically gained by a faction every 10 minutes, currently just balancePlayerScale * balanceVehicleCost. The defence cap is currently at 10*A3A_balanceResourceRate.
- A3A_enemyBalanceMul is a parameter (default 10, because params don't do FP) that multiplies A3A_balancePlayerScale to make the game generally harder or easier.
- A3A_enemyAttackMul is a parameter that multiplies attack resource rate to make attacks faster or slower.
- A3A_invaderAttackMul and A3A_invaderDefenceMul are temporary multipliers applied to invader resource gain rates. These aren't currently parameterized.

ResourceCheck (the 10-minute loop) still has most of its former responsibilities, although it now runs with any active players (not necessarily a commander), and no longer generates supply convoys against flipped towns (now the responsibility of chooseAttack).

#### Support system
This is the call/response system rather than the limited-knowledge system, as I got it mostly working first. Might be replaced in the future as limited-knowledge does have advantages. Key files:

- initSupports set up various arrays and hashmaps used by the support system, including marker values and static support type data. They're all documented there, so I won't repeat it here.

- maxDefenceSpend determines how many resources can be spent against a particular target or marker. It takes account of the importance of the location (based on nearby friendly and enemy markers), aggregate threat (based on live friendly garrisons and enemy troops nearby, plus recent casualties taken), available resources, and support resources already spent against that target/area.

- requestSupport takes dumb support requests against targets (typically from callForSupport or airspaceControl), uses maxDefenceSpend to decide how many resources to spend, and then chooses a support type dependening on base types (area, troops, target) already called nearby. It also uses the SUP_*Available functions to generate weights for each support based on target type and other support-specific factors. There is a similar but simpler function (requestArtillery) used to choose artillery type supports for attacks. requestSupport always uses the defence pool.

- createSupport is a worker function to force-create a support of a specific type. It will use already-active supports by preference, if they don't currently have a target.

Each support typically has an availability function (actually returns a weight now, could be renamed), a creation function (intended to be called by createSupport, and so returns fairly quickly), and a persistently spawned routine that manages the support while active. Multi-target supports update the A3A_activeSupports array to indicate readiness and completion.

All working supports from the previous system have been preserved except for Gunship and the orbital laser, which need updating to new systems.

Individual supports have been heavily refactored and in some cases rewritten. Some common trends:
- Event handlers for damage response have been generalised and moved to AIVehInit.
- Support marker creation and maintenance is now offloaded to showInterceptedSupportCall.
- Multitarget supports now only store one target at once. This avoids problems where the support system would overstack a support with targets it was never likely to engage.

The CAS support had a major overhaul, rewriting the pre-run loop to a semi-proper state engine and converting CASRun to an onEachFrame handler so that it behaves properly under moderate script load.

callForSupport is now only triggered by damage, not spotting. Unconsciousness triggers have been cleaned up to call AIReactOnKill more consistently with and without ACE. These triggers also add to the recentDamage arrays on the server, to improve the decision making of maxDefenceSpend.

Marker recapture counterattacks now use maxDefenceSpend to calculate how large a counterattack to send. If the capture was a hard fight with multiple supports called, or the flag was reflipped shortly after a counterattack was cleared, it's likely that nothing further will be sent.
 
#### QRF and attack vehicle spawning
QRFs, counterattacks (singleAttack), major attacks, punishments and HQ attacks have all been rewritten to use the same code paths for spawning and vehicle/troop behaviour. 

Vehicle choice is based on splitting vehicles into transport (contains cargo units) and support types. Any attack force must contain at least one transport vehicle, typically more than half. Only attack helis are generated as air supports. CAS and ASF must be called separately.

Land forces are spawned using the vehicle spawn places system, patched up so that it mostly works. **Maps without sufficient vehicle spawn places defined will need them added, otherwise land vehicles will be minimal.** Air vehicles are restricted to spawning at airfields or the carrier marker.

Various changes to previous QRF/singleAttack vehicle behaviour:
- Ground vehicles now have their waypoints culled much more heavily, improving travel speed and preventing some weird cowardly behaviour of unarmed transports.
- Crew in weapon-less ground transport vehicles now leave with the cargo units.
- Attack helis are less inclined to give you a free shot on approach, and will not hover once they run out of targets.
- Paradrop method has been substantially improved. Perf should be better and drop height should be more consistent. Aims further from the target but may miss.
- combatLanding now lands further away from the target and gets the troops out more reliably, but needs more work (onEachFrame usage, persisting after landing).

#### Attack choice system
Once a faction has positive attack resources, it will call chooseAttack to launch an attack. Target selection is handled with findAttackTargets, which weights potential attacks depending on target value and threat. Main differences:

- Lower-rated attacks can be chosen, using the weight as a probability.
- Attacks against rebel targets outside mission distance are now permitted, although chance is reduced.
- Danger of flying over othe [...]

2022-06-18 20:57 UTC, killerswin2 requested changes
Just some stuff I saw. Happy that the annoying incoming missile event is being killed.

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_addRecentDamage.sqf
> +#include "..\..\script_component.hpp"
Missing Header

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Save/fn_loadServer.sqf
> +//  ["countCA"] call A3A_fnc_getStatVariable;
Keeping Or Is This Dead?

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Save/fn_loadServer.sqf
> +//	["idlebases"] call A3A_fnc_getStatVariable;
Dead?

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initZones.sqf
> +markersX = airportsX + outposts + resourcesX + factories + seaports + controlsX + ["Synd_HQ"];
git funnies

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +//Max units we aim to spawn in. Unused now.
plans to use? Saved for backwards compat?

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
> +
missing Header

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
> +	if (A3A_lastPlayerDir != _oldDir) then {
we should account for distance changes, someone could walk in a straight line be counted as afk.

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Supports/fn_SUP_artilleryAvailable.sqf
> +#include "..\..\script_component.hpp"
Missing Header

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Supports/fn_SUP_artilleryAvailable.sqf
> +// TODO: move these existence checks to initSupports?
Sure, or Compile assets

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Supports/fn_SUP_artillery.sqf
> +Info_3("Artillery support %1 against %2 will be carried out by a %3 with %4 mags", _supportName, _target, _vehType, _shellType);
Info_4, 4 variables

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf
> +
Missing Header

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Supports/fn_SUP_QRFLandAvailable.sqf
> +// later maybe. Only consider target for the moment.
yes, players probably have a stockpile of aa and manpads.

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/Supports/fn_SUP_QRFAirAvailable.sqf
> +
Missing Header

2022-06-18 20:57 UTC, killerswin2 commented on A3A/addons/core/functions/AI/fn_attackHeli.sqf
> +
Missing Header

2022-06-18 21:01 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
> +	if (A3A_lastPlayerDir != _oldDir) then {
If they don't change heading for 20 seconds while walking forwards then I'm pretty sure it's their cat on the keyboard, so this is fine.

What I really should do though is not count players as AFK if they're in a moving vehicle. Otherwise it's gonna bounce around when players are being driven to a target.

2022-06-19 13:36 UTC, Lazejun requested changes

2022-06-19 13:36 UTC, Lazejun commented on A3A/addons/core/CfgFunctions.hpp
>              class findNearestGoodRoad {};
(Just doing it here cause Git didnt allow me to point at the right line)

This function doesent exist anymore
https://github.com/official-antistasi-community/A3-Antistasi/blob/62739ebc1db87430d0ef5255d693b699ece8393c/A3A/addons/core/CfgFunctions.hpp#L264
This function doesent exist anymore
https://github.com/official-antistasi-community/A3-Antistasi/blob/62739ebc1db87430d0ef5255d693b699ece8393c/A3A/addons/core/CfgFunctions.hpp#L166

This one was renamed to fn_enemyUnitKilledEH
https://github.com/official-antistasi-community/A3-Antistasi/blob/62739ebc1db87430d0ef5255d693b699ece8393c/A3A/addons/core/CfgFunctions.hpp#L52

2022-07-30 17:04 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +//Max units we aim to spawn in. Unused now.
It's still modified in both UIs and used in some currently-disabled code, so the var itself (defined in initParams) stays for now.

2022-07-30 17:08 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_QRFLandAvailable.sqf
> +// later maybe. Only consider target for the moment.
Decided that there's little value in making these functions smart, and it's better to make them fast given that it has to call all of them each time there's a support request. Target-only consideration makes a lot of sense in practice because request targets are proportionally likely to be the units/vehicles currently inflicting the damage.

2022-07-30 17:08 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initZones.sqf
> +markersX = airportsX + outposts + resourcesX + factories + seaports + controlsX + ["Synd_HQ"];
Possibly I started changing that code and then mis-reverted it. Whatever.

2022-07-30 17:17 UTC, jaj22 commented on A3A/addons/core/functions/Save/fn_loadServer.sqf
> +//	["idlebases"] call A3A_fnc_getStatVariable;
This one in particular will stay, because I'm still in two minds as to whether to use it more. The others are very dead.

2022-07-30 17:20 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_artilleryAvailable.sqf
> +// TODO: move these existence checks to initSupports?
Because I allowed direct (speculative) use of createSupport, it's not currently possible to remove all these checks. Might reconsider later.

2022-08-12 20:32 UTC, jaj22 commented
Getting pretty close to done. Remaining test/cleanup:
- At least syntax-check all the templates.
- More synthetic testing of findAttackTargets changes.
- Sort out template verification for vehicleAttributes.

2022-09-09 14:05 UTC, Bob-Murphy reviewed
Went through all the stuff and marked the ones where I have some questions and to check ToDos marked by you, just to check them off. I also didn't mark every ToDo, just so you know.
In addition to that I saw that there are some headers not completely set up or fully missing. Hence I'd like you to go through the files and clean up the headers a bit. The ones I marked are exemplary.

Other than that nothing special jumped into my eye. No typos, no obvious wrong content in texts.

2022-09-09 14:14 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_combatLanding.sqf
> +// Dirty hack to stop the heli lurching around near the ground
Depends how badly it works on DS/HC at low FPS really. Didn't have any reports so it's probably fine.

combatLanding needs a rewrite in general which is quite tempting but would probably take a day or two.

2022-09-09 14:15 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_enemyGarrison.sqf
> +// TODO: err, this sometimes makes the troops walk miles away?
It's actually replaced by the shitty patrol code below it, which works much better. Guess I can delete this stuff now.

2022-09-09 14:16 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_addEnemyResources.sqf
> +// Probably not for decision code (always runs on server), but might be needed for intel?
Nah, fixed intel to run on server, so it doesn't need publishing.

2022-09-09 23:42 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
> +// TODO: Could add an extra timed "petros surrender" condition if there are too many enemies near him
Probably not, too much testing time required. I'll leave that one hanging because it may turn out to be necessary.

2022-09-09 23:56 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +    // TODO: Might need to constrain this with the strike list so that you don't get multiple supports sent against one aircraft
Current requestSupport prevents more than one TARGET-type support being launched against a single target within 20 minutes, so the TODO is redundant at the moment. It becomes more important if that's too easy, and you need 2+ aircraft to kill a player.

2022-09-10 00:03 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_callForSupport.sqf
> +// TODO: this breaks differential leader skills. Maybe fix.
Ugh, may as well. Probably doesn't need testing...

2022-09-10 00:04 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf
> +// TODO: Sort out the spawn positions API or don't use it
No, that's a major follow-up project.

2022-09-10 00:05 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
> +// TODO: move this to chooseAttack?
Nah, that's one's a long-standing structural issue that's a pain to address. It's not important as long as the major attack routines are completely stable :P

2022-09-10 00:08 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
> +        // This is bullshit really
One does not fix bullshit. It's out of scope really, but we could do with a quick money/HR balance pass fairly soon to smooth out the worst stuff.

2022-09-10 00:09 UTC, jaj22 commented on A3A/addons/core/functions/Pathfinding/fn_findNavDistance.sqf
> +// TODO: subtract start->nav and end->nav from distance? Or fancier?
Nah, doesn't matter for the current use cases, but the note should remain.

2022-09-10 00:09 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
> +        // TODO: better evasion mechanics?
No.

2022-09-10 00:11 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_QRFAirAvailable.sqf
> +// TODO: Rework vehicle type system to handle this shit better
I did the more urgent half of the vehicle type system, but it'll probably need redesigning from scratch at some point. Not now though.

2022-09-10 00:13 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +    // TODO: should we consider aircraft type here?
No. We'll have to see if the anti-air stuff needs more complexity or not once people are using it. I don't personally fly aircraft in Arma so it's hard to tell what's balanced.

2022-09-10 00:13 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
> +        _enemyStr = _enemyStr + ([10, 30] select isPlayer _x);          // TODO: parameterize player multiplier
Nope, leaving that one hanging. Probably not important enough for the complexity.

2022-09-10 00:14 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_showInterceptedSetupCall.sqf
> +// TODO: add source/setup position?
Nah, possible future work thing.

2022-09-10 20:15 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_paradrop.sqf
> +    // TODO: check this against reinf code
Actually completely forgot to sort out reinforcement and patrol behaviour for low air factions and the pathfinding changes. So that took some work.

2022-09-10 20:26 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
> +    // TODO: maybe add incidence factor so we can use it for any approach angle?
Nah, not worth the testing given that it's currently using fixed-ish incidence anyway. I'll leave the TODO because it needs the reminder that it's missing that feature.

2022-09-11 05:00 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_initSupports.sqf
> +// TODO: Define separate hashmap per side, pre-check for existence of vehicle supports?
Done in [#4430c4d](https://github.com/official-antistasi-community/A3-Antistasi/pull/2383/commits/4430c4df26fde7d2b10ba778c3666ec1742156ee). Seems to hang together.

2022-09-13 21:48 UTC, killerswin2 approved these changes

2022-09-16 00:57 UTC, merged