GUI PLACER HAKON
official-antistasi-community/A3-Antistasi pull request #2384
Opened 2022-06-21 20:26 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-10-29 12:53 UTC, Bob-Murphy commented
@killerswin2 could you please add screenshots? That'd be nice.
Cheers

2022-10-29 19:20 UTC, killerswin2 commented
![image](https://user-images.githubusercontent.com/8095345/198849108-8b46ecd4-bd28-4b05-831e-766731faa570.png)

2022-10-29 19:54 UTC, killerswin2 commented
https://youtu.be/R9kkguX32XY

2022-12-24 11:32 UTC, CalebSerafin commented
Yeah, this is pretty cool. I back the idea and the look of it. Has this been discussed in a meeting before, what are other people's thoughts?

2022-12-24 17:10 UTC, killerswin2 commented
We have had informal meetings about it, but we haven't sat down and discussed this in a meeting yet.

2023-02-15 12:29 UTC, CalebSerafin requested changes
Is did a quick skim, so I might have missed some things. But there are some comments.

2023-02-15 12:29 UTC, CalebSerafin commented on A3A/addons/core/functions/UtilityItems/fn_placeBuilderObjects.sqf
> +		if (_className isEqualTo "Flag_AAF_F") then {
This feels rather hard-coded. Is it always valid or is there a way to detect variations of flag.

2023-02-15 12:29 UTC, CalebSerafin commented on A3A/addons/core/functions/UtilityItems/fn_placeBuilderObjects.sqf
> +		publicVariable "A3A_notBuiltObjectList";
We could limit the amount of "planned" constructions to minimise the potential of updating huge lists. Maybe 50 objects?

2023-02-15 12:29 UTC, CalebSerafin commented on A3A/addons/core/functions/UtilityItems/fn_teamLeaderRTSPlacer.sqf
> +		if (_insufficientFunds) exitwith {[localize "STR_antistasi_teamleader_placer_title", localize "STR_antistasi_teamleader_placer_insufficient_funds"] call A3A_fnc_customHint};
This is executing on the client, only the server should consider insufficient funds. You'll need to fight with an SQF callback to update the UI on the client (rip other languages async await compiler sugar).

2023-02-15 12:29 UTC, CalebSerafin commented on A3A/addons/core/functions/UtilityItems/fn_teamLeaderRTSPlacer.sqf
> +	};
User keybind configuration via CBA options soon™?

2023-02-15 18:09 UTC, killerswin2 commented on A3A/addons/core/functions/UtilityItems/fn_placeBuilderObjects.sqf
> +		if (_className isEqualTo "Flag_AAF_F") then {
currently the only flag defined is that one. I could make check that rebel flag instead

2023-02-15 18:10 UTC, killerswin2 commented on A3A/addons/core/functions/UtilityItems/fn_placeBuilderObjects.sqf
> +		publicVariable "A3A_notBuiltObjectList";
Yes, there will be a limit. Either based on resource allocation or just a hard limit on placement.

2023-02-15 18:13 UTC, killerswin2 commented on A3A/addons/core/functions/UtilityItems/fn_teamLeaderRTSPlacer.sqf
> +	};
Yes

2023-04-14 22:37 UTC, killerswin2 commented
maybe one day

2023-08-06 00:33 UTC, jaj22 requested changes
Ok, need the following things before I read this again:
1. Port to unstable. Save/load and utility item stuff needs switching over.
2. Sort out the indentation in teamLeaderRTSPlacerDialog.sqf.

2023-08-06 01:22 UTC, jaj22 commented
Actually I guess I should do the port myself. It was my broken shit in the end :P

2023-08-06 02:06 UTC, killerswin2 commented
I can actually push my commits

2023-08-06 02:07 UTC, killerswin2 commented
That will save the time some stuff

2023-08-06 02:08 UTC, jaj22 commented
Feel free. I haven't started yet.

2023-08-06 21:12 UTC, jaj22 commented
So what features does the placer function here have that we couldn't or wouldn't want to jam into the garage placement function?

2023-10-07 01:22 UTC, jaj22 commented on A3A/addons/core/functions/UtilityItems/fn_placeBuilderObjects.sqf
> +		if (_className isEqualTo A3A_faction_reb get "flag") then {
Notes for self: Precedence error.

2023-10-07 01:22 UTC, jaj22 commented on A3A/addons/core/functions/Save/fn_loadStat.sqf
> +                    veh setVariable ["price", _state, true];
Notes for self: Missing underscore.

2023-10-10 00:14 UTC, jaj22 commented
Perf issues:
1. Every awaiting-construction object generates an EachFrame icon-draw handler on every player that renders regardless of distance. Should be converted to a single handler installed by initClient that renders any *nearby* awaiting-construction buildings. Can probably get away with a publicVariable array there because there likely won't be many awaiting-construction buildings at once.
2. Every awaiting-construction object has two very large addAction global remoteExecs. These can be easily reduced by remoteExec'ing a client-side function to add those actions instead.
3. Every constructed building is added to staticsToSave. Would be mitigated by the garrison rework, but I don't think there's any reason to access this list globally for buildings, so the straightforward solution for now is to move them into a separate server-side array.
4. Every constructed building has a global removal addAction remoteExec. This is potentially an awful lot of JIP remoteExec for a rarely used action, as the building count could easily be in the hundreds. Could instead have a client-side cursorObject checker: If you look at a deconstructible building then it adds the action, client-side.

2023-10-10 18:15 UTC, killerswin2 commented
On 1. That each frame handler should only be on engineers that need to see what to build.

2023-10-10 18:56 UTC, jaj22 commented
> On 1. the each-frame handler should only be on engineers who need to see what to build.

Slightly worried about players gaining unit traits later, but I'll roll with it for now.

2023-10-11 19:28 UTC, jaj22 commented
Ok, organisation/perf stuff done and working. Also added a semi-temporary GC and save filter to clear out buildings that aren't in rebel garrisons. Currently it also clears down to mission distance so there shouldn't be a risk of long-term object bloating.

Some interface issues that need to be cleaned up:
- No display of remaining funds.
- "Can't afford" hint doesn't show on top of placer UI.
- Placer UI cancel (c) doesn't do anything.
- Garage refund gives you the full 100 back.
- Plank objects not sized relative to final construction.
- Placer box object needs a stringtabled name.
- Need a second larger placer box object.
- A couple of placer-init warnings are not stringtabled yet.

2023-10-12 03:22 UTC, jaj22 commented
Added server-side locking for reasonable protection against money exploits involving two players using the same builder box or refunding a box that's in use.

Also from the to-do list:
- Now displays remaining funds in box in title bar.
- Garage refund now gives the correct amount.
- Found a decent class for the larger placer box.
- Stringtabled names for placer boxes.

Remaining:
- Better sizing of plank objects.
- Improve prices (larger bunkers are too cheap).
- Hints into the stringtable.
- Look into the cancel (or remove it). 
- Sort out logistics nodes for construction boxes.

2023-10-12 09:24 UTC, Bob-Murphy commented
Feedback & Observations:

1. if you start building something and run away, you continue building even when the round thingy ain't visible on distance
2. `Snap to Surface` ain't working and magically let's the buildings fly away
3. `E` for clockwise rotation and `R` for counter-clockwise rotation seems weird. In the other systems we have `Q` for rotating left aka counter-clockwise and `E` for right aka clockwise.

![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/50651578/bf404f58-b86b-4ed2-bb18-2f257edaaf77)

4. when there are 0 credits in the building placer, the box stays but is useless. is that intended?

2023-10-12 16:28 UTC, jaj22 commented
Duh, reason for not using Q is that it's what the camera uses for up.

2023-10-13 02:45 UTC, jaj22 commented
Added functionality to cancel and repair buildings within the placer UI (so people finally have an expensive way to rebuild the towers they carelessly destroyed). Plays around with the keys a bit.

2023-10-14 01:36 UTC, jaj22 commented
Bunch more fixes/improvements done. Remaining stuff that I recall:
1. Check/expand the CUP & VN buildings.
2. Stringtables.
3. Construction box logistics nodes.

2023-10-14 14:55 UTC, jaj22 approved these changes

2023-10-15 03:09 UTC, jaj22 commented
Done construction box nodes and buildable objects for all maps (SPE is kinda thin, couldn't find much). Should be functionally complete now, just needs some extra stringtabling and more testing. Not sure I'll have any more time though.

2023-10-15 03:35 UTC, killerswin2 commented
I can do the string table stuff

2023-10-15 03:37 UTC, killerswin2 commented
We can do the pro-gamer move of testing on "Testing Tuesday"™️

2023-10-15 03:58 UTC, jaj22 commented
> I can do the string table stuff

Yeah feel free. I might have an hour or two available tomorrow but I'd rather spend it testing.

2023-10-16 10:19 UTC, Bob-Murphy requested changes

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
> +		_textCtrl ctrlSetText format ["T: Repair for %1 €", _price];
stringtable?

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
> +		_textCtrl ctrlSetText format ["C: Cancel %1", getText (configof _intersectObj >> "displayName")];
stringtable?

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
> +    [localize "STR_A3A_Unit_Traits_title", format [localize "STR_A3A_Unit_Traits_selected_trait", _this]] call A3A_fnc_customHint;
Please revert, covered in #2970

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
> +        "Carry object",
I'll deal with stringtable based on #2970

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
> +        "Rotate object",
I'll deal with stringtable based on #2970

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
> +        "Building Placer",
I'll deal with stringtable based on #2970

2023-10-16 10:19 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +    <Container name="Unit_Traits">
Please revert Unit Triats strings as it's covered in #2970

2023-10-16 14:11 UTC, jaj22 commented on A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
> +		_textCtrl ctrlSetText format ["T: Repair for %1 €", _price];
I put these in the wrong place. I'll move them into the display UI stuff where the other related strings are.

2023-10-16 19:44 UTC, jaj22 commented
Ok, that should be everything done.

2023-10-16 20:32 UTC, Bob-Murphy approved these changes
lgtm

2023-10-16 20:35 UTC, merged