Facewear support for AI loadouts
official-antistasi-community/A3-Antistasi pull request #2395
Opened 2022-06-28 23:23 UTC by UltimateFlash15

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
This pull request adds the ability for AI to randomly select from facewear items to wear specified in their template (e.g. goggles, glasses, bandanas, custom mod items like beards, etc.).

![image](https://user-images.githubusercontent.com/92134872/176320127-6be9fe66-2dd4-4e1c-9636-ba2219f641a3.png)

This has been something requested occasionally by other community members on the Discord server, and I personally wanted to add this functionality myself as well after I started playing around with faction templates. Essentially, its overall purpose is adding more variety with AI appearance.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
The AAF and FIA factions are setup with facewear. By spawning any FIA units (except for Petros), or by travelling to an area with AAF units, you can observe the randomized facewear on the AI.

********************************************************
Notes:
The AAF template file includes extra details with setting up facewear. 

There is a weight modifier that affects how likely the chances of any facewear being equipped are compared to having no facewear equipped. This way, you can adjust the look of a faction even further (e.g. having facewear less likely to be equipped on a conventional military, having a bandana always be equipped for an SF unit, etc.).

2022-06-28 23:36 UTC, killerswin2 requested changes

2022-06-28 23:36 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +/* Facewear array:
move this comment to the rebel example file

2022-06-28 23:36 UTC, killerswin2 commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_setFacewear.sqf
> + * Author: Spoffy
Spoffy didn't write this. Update the header

2022-06-28 23:36 UTC, killerswin2 commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_setFacewear.sqf
> +	_facewear
fix this to be one line not three.

2022-06-28 23:37 UTC, killerswin2 commented
@UltimateFlash15 thanks for the PR

2022-06-28 23:49 UTC, UltimateFlash15 commented
@killerswin2 Resolved all your issues, thanks for the heads up! Feel free to let me know of anything else if needed.

2022-06-29 00:04 UTC, killerswin2 commented
@UltimateFlash15 we are gonna have to wait for the templates maintainer (Laze) for his decision now.

2022-06-29 03:23 UTC, killerswin2 requested changes

2022-06-29 03:23 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +/* Facewear array:
My apologies I didn't tell you the right file. move this comment to the examples here https://github.com/official-antistasi-community/A3-Antistasi/tree/unstable/A3A/addons/core/Templates/Templates/%23Examples

2022-06-29 03:34 UTC, UltimateFlash15 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +/* Facewear array:
All good. Should I just add it to FactionExample.sqf, or also add it to RebelExample.sqf and CivillianExample.sqf?

2022-06-29 03:39 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +/* Facewear array:
right now just add it to rebel and faction

2022-06-29 04:47 UTC, Lazejun requested changes

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
> +    ["facewear"] call _fnc_setHelmet;
A good amount of Tomfoolery

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
> +0.5 = All facewear options, including having no facewear, have an equal chance of being selected.
Documentation comments dont belong in Example Templates, they were recently cleaned up as all People just copy them when copying the Example.

Put it in the PRs description or on the Github Wiki.

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
> +0.5 = All facewear options, including having no facewear, have an equal chance of being selected.
Documentation comments dont belong in Example Templates, they were recently cleaned up as all People just copy them when copying the Example.

Put it in the PRs description or on the Github Wiki.

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    ["facewear"] call _fnc_setFacewear;
Thats not a camelCase like the rest.

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/functions/REINF/fn_equipRebel.sqf
> +	// Resize data table to add "none/unequipped" option, and add corresponding weight to it.
Why is the Weighet Array even needed?
This can be done in the Templates themself

```sqf
[selectRandom ["variable1", 1, "variable2", 2]] call _fnc_setFacewear;
//Could even do a they get nothing chance
[selectRandom ["variable1", 1, "variable2", 2, "nothing", 0.5]] call _fnc_setFacewear;
```

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _weightsArray = [0]; // 0 here so that _selectFacewearWeight variable in the array has no weight and doesn't get selected as a facewear
Same here
Why is the Weighet Array even needed?
This can be done in the Templates themself

```sqf
[selectRandom ["variable1", 1, "variable2", 2]] call _fnc_setFacewear;
//Could even do a they get nothing chance
[selectRandom ["variable1", 1, "variable2", 2, "nothing", 0.5]] call _fnc_setFacewear;
```

2022-06-29 04:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +["facewear", [0.5,
Thats the wrong Method for Loadouts.

This is specificly for Rebel Player Uniforms and EquipRebel function

```sqf
_loadoutData set ["faceWear", [1, "G_Tactical_Clear", "G_Tactical_Black", "G_Combat", "G_Shades_Black", "G_Shades_Blue", "G_Shades_Green", "G_Shades_Red", "G_Aviator", "G_Spectacles", "G_Spectacles_Tinted", "G_Sport_BlackWhite", "G_Sport_Blackyellow", "G_Sport_Greenblack", "G_Sport_Checkered", "G_Sport_Red", "G_Squares", "G_Squares_Tinted", "G_Lowprofile"]];

private _squadLeaderTemplate = {
    ["uniforms"] call _fnc_setUniform;
    ["faceWear"] call _fnc_setFacewear;

    ["items_medical_standard"] call _fnc_addItemSet;
    ["items_miscEssentials"] call _fnc_addItemSet;

    ["maps"] call _fnc_addMap;
    ["watches"] call _fnc_addWatch;
    ["compasses"] call _fnc_addCompass;
    ["binoculars"] call _fnc_addBinoculars;
};

private _riflemanTemplate = {
    ["uniforms"] call _fnc_setUniform;
    ["faceWear"] call _fnc_setFacewear;
    ```

2022-06-29 06:18 UTC, UltimateFlash15 commented on A3A/addons/core/functions/REINF/fn_equipRebel.sqf
> +	// Resize data table to add "none/unequipped" option, and add corresponding weight to it.
Originally did it for the sake of simplification to setup, but yeah in hindsight people editing this in the first place should also be able figure out the selectRandomWeighted API themselves. Has been changed.

2022-06-29 06:19 UTC, UltimateFlash15 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    ["facewear"] call _fnc_setFacewear;
I'm unsure if any changes actually need to be made here, "facewear" is one word.

2022-06-29 07:09 UTC, Lazejun requested changes

2022-06-29 07:09 UTC, Lazejun commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
This is not necessary, you can just use "" for nothing, you could use a Variable that is just "" with a selectRandom it can all be handled in the Templates.

2022-06-29 07:11 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    ["facewear"] call _fnc_setFacewear;
Yeah right 😅

2022-06-29 17:51 UTC, Lazejun requested changes
And Classname Validation.
https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3A/addons/core/functions/Templates/Verification/fn_TV_verifyLoadout.sqf#L246

2022-06-29 17:56 UTC, UltimateFlash15 commented
> As this is purely cosmetic, wouldn't it make sense to also have the chance to not have any facewear?

There already is, in the facewear arrays there is a value for blank quotation marks that act as the empty option

2022-06-29 18:06 UTC, UltimateFlash15 commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
Alrighty, I see what you mean. Just to be clear, if I go the classes route, would there basically just be one facewear item in the array for each facewear class? (Aside from varying with extra loadout sets for SF and the like)

2022-06-29 18:10 UTC, Lazejun commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
No, the Variable names are not fixed, call them whatever you want, add as many as you want if it achives what you want in terms of looks, hence the Example with 3 Variables.

LoadoutData is used by EVERYONE, the Specific Datas like Crew, SF, Military, Militia, Police only by them.
Also Specific Data overwrite LoadoutData.

There are Multiple method that you can use, the one above is just an Example if you want to use "Categories" and weight them for example.

2022-06-29 18:10 UTC, Lazejun commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
You are limited by how much you want to write down in that sense.

2022-06-29 18:13 UTC, HakonRydland commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
disregard the concern, on a closer look this doesn't appear to be the case

2022-06-29 18:33 UTC, UltimateFlash15 commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
To be more clear on what I meant, could I do something like this for each facewear type?

```lua
_loadoutData set ["Glasses", ["Some_funny_Glasses, Some_funny_Glasses2, Some_funny_Glasses3"]];

_loadoutData set ["Facemask", ["aFunnyBandana, aFunnyBandana2"]];
```

Or should I just have one per facewear type?

```lua
_loadoutData set ["Glasses", ["Some_funny_Glasses"]];

_loadoutData set ["Facemask", ["aFunnyBandana"]];
```

2022-06-29 18:36 UTC, Lazejun commented on A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf
> +	private _facewear = selectRandomWeighted _data;
Yes it can use Multiple Classes in an Array.

2022-06-29 19:11 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
> +_loadoutData set ["facemask", []];
Keep the Examples simple with just facewear, people can take inspiration/examples from other Templates etc.

Or the Documentation on the Github Wiki whenever i come around to do that, its the same as with any other entry/Category --------> You can always add more if it's needed todo what you wanted todo.
Example Templates should just be the basic/Minimum needed.

2022-06-29 19:23 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf
> +    [selectRandomWeighted ["facewear", 1]] call _fnc_setFacewear;
["facewear"] call _fnc_setFacewear;

2022-06-29 19:49 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    [selectRandomWeighted [[], 2, "glasses", 1, "goggles", 0.5]] call _fnc_setFacewear;
Using a 2 for "No Glasses" is pretty high, barely any AI gets Facewear

2022-06-29 20:07 UTC, Lazejun approved these changes
that works a bit better, yeah should be fine

2022-07-08 21:20 UTC, Bob-Murphy commented
> Awesome, if you want to change anything else template wise of course feel free to do so

It seems like we don't need anything from you on this PR.
But what you could do is adding facewear to additional templates and create a new PR.
That'd be appreciated.

Other than that Thank you for the PR!

2022-07-08 21:22 UTC, Bob-Murphy commented
@killerswin2 please set review to "approved" as you marked it "ready to merge".
Your last review with requested changes is blocking the merge.

2022-07-08 21:29 UTC, killerswin2 commented
Huh, thought laze's reviews was golden

2022-07-08 21:30 UTC, killerswin2 approved these changes

2022-07-08 21:32 UTC, Bob-Murphy commented
It was. But when somebody requested changes at an earlier point he has to re-review it.
I technically could just dismiss the review, but I rather have it checked by the person who made it than overwriting it.

2022-07-08 21:32 UTC, merged