added logging of debug code execution with name and UID
official-antistasi-community/A3-Antistasi pull request #2403
Opened 2022-07-10 00:10 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Now logs debug console executions with the users in game name and UID, this includes logging the target: local, server, global, this allows server owners to track what code has been run on their servers to help track hackers, but also keeps a record of debug code run that may have caused a bug etc.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-07-10 11:50 UTC, Lazejun approved these changes
From a User side it seems to work.

Might come in handy when we have People in help channels saying Commands would not work when they used them wrong.

2022-07-15 17:14 UTC, jaj22 requested changes

2022-07-15 17:14 UTC, jaj22 commented on A3A/addons/JeroenArsenal/JND/fn_debugv2.sqf
> +                        if !(
This `!` shouldn't be here. It's currently causing it to log only devs for "All non-devs" and log no-one for "All".

2022-07-15 17:14 UTC, jaj22 commented on A3A/addons/JeroenArsenal/JND/fn_debugv2.sqf
> +    if !(
Also this `!`.

2022-07-15 17:14 UTC, jaj22 commented on A3A/addons/JeroenArsenal/JND/fn_debugv2.sqf
> +    ];
This doesn't respond to changes in the A3A_logDebugConsole var after init. If this is intentional then it should also apply to the other section, which does respond to later changes. Make them consistent either way.

2022-07-15 17:14 UTC, jaj22 commented on A3A/addons/maps/MissionDescription/params.hpp
> +        texts[] = {"Load from save (Default: All none-dev)", "None", "All none-dev", "All"};
Should be "All non-dev" rather than "All none-dev".

2022-07-15 21:29 UTC, jaj22 approved these changes

2022-07-30 22:55 UTC, merged