WIP: Template and Integration GM
official-antistasi-community/A3-Antistasi pull request #2427
Opened 2022-08-04 13:43 UTC by targetingsnake

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x ] Enhancement

### What have you changed and why?
Information:
    created a template for GM, i would like to see GM within antistasi

### Please specify which Issue this PR Resolves.
none

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x ] Yes (Please provide further detail below.)

unknown balance of assests

### How can the changes be tested?
Steps: 

play Antistasi with GM template

********************************************************
Notes:

2022-08-04 13:55 UTC, Bob-Murphy requested changes
Thank you for the PR Draft.

That's just what I noticed when quickly glancing over it.
I guess there will be more feedback coming from Laze.

2022-08-04 13:55 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
> +["spawnMarkerName", "NATO Support Corridor"] call _fnc_saveToTemplate;
Please revert this change.
1. it's not a GM template but an RHS template
2. the change in itself is incorrect.

2022-08-04 13:55 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +//Each element is: [model name, [nodes]]
Looks like you more or less copied a different log-node sqf.
I don't see a single GM vehicle being defined properly.

2022-08-04 14:01 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
> +["spawnMarkerName", "NATO Support Corridor"] call _fnc_saveToTemplate;
was an accident, will do

2022-08-04 14:02 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +//Each element is: [model name, [nodes]]
not done yet, still WIP (also NVA is currently still a copy of CSAT)

made a copy of vanilla template to have a wroking template to test stuff

2022-08-04 14:19 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
> +["spawnMarkerName", "NATO Support Corridor"] call _fnc_saveToTemplate;
change has been reverted

2022-08-04 14:19 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +//Each element is: [model name, [nodes]]
file now empty until i'm at that point

2022-08-04 15:59 UTC, Lazejun requested changes

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["vehiclesIFVs", ["gm_ge_army_marder1a2", "gm_ge_army_marder1a1a", "gm_ge_army_marder1a1plus", "gm_dk_army_m113a2dk"]] call _fnc_saveToTemplate;                //this line determines IFVs
Unused

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["vehiclesLightAPCs", ["gm_ge_army_m113a1g_apc", "gm_ge_army_m113a1g_command", "gm_ge_army_fuchsa0_command", "gm_dk_army_m113a1dk_command"]] call _fnc_saveToTemplate;            //this line determine
Unused

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["magazines", createHashMapFromArray [
It makes no Sense giving AI Non Lethal Ammo, they dont know what they are firing, they only know its supposed to hurt Players.

Smoke doesent hurt Players.

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["sfVoices", ["gm_voice_male_deu_01","gm_voice_male_deu_02","gm_voice_male_deu_03","gm_voice_male_deu_04"]] call _fnc_saveToTemplate;
Why should SF be any different, the same Voices are used Above.

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +"gm_WhiteHead_14_camo_01", "gm_WhiteHead_14_camo_02", "gm_WhiteHead_15_camo_01", "gm_WhiteHead_15_camo_02",
Police with Camo Faces is pretty weird

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_pzf84_oli", "", "", "gm_feroz2x17_pzf84_blk", ["gm_1Rnd_84x245mm_ILLUM_DM16_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM32_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM22_carlgustaf", "gm_1Rnd_84x245mm_h
Also thats missusing the Category.

Winter, Desert, Olive it makes sense to stick to ONE Color not all depending on what Terrain is going to be used.

weird way of using the Magazine Arrays.

It will pick from the Array thats correct but giving 5 Magazines when the Loadout gets 3 doesent seems like the best solution, especially if one Rocket is just a Flare.

missileATLaunchers get 3 Magazines https://github.com/official-antistasi-community/A3-Antistasi/blob/29fe9a0b5f5c163641226e3278a24f191e993cb5/A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf#L599

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["Hvests", ["gm_ge_vest_armor_90_machinegunner_flk", "gm_ge_vest_armor_90_medic_flk"]];
Using Variables that are Hand tailored for Vanilla as they dont have Class Specific Vests doesent make sense in a Modset when there are Class Specific Vests.

For Example: https://github.com/official-antistasi-community/A3-Antistasi/blob/29fe9a0b5f5c163641226e3278a24f191e993cb5/A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf#L177

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_hk69a1_blk", "", "", "", ["1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareGreen_F"
Same as Above with the Launchers, this doesent realy make sense

https://github.com/official-antistasi-community/A3-Antistasi/blob/29fe9a0b5f5c163641226e3278a24f191e993cb5/A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf#L480

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +private _vehicleAA = "";
Instead of Copying Vanilla, use the Example Templates and use a Finished Template as Cheat Sheet, so you dont copy over Vanilla/DLC Specific Stuff that makes no sense here.

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +    [selectRandomWeighted [[], 1.25, "glasses", 1, "goggles", 0.75, "facemask", 1]] call _fnc_setFacewear;
Same as Above.

2022-08-04 15:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["vehiclesCargoTrucks", ["gm_ge_army_kat1_454_cargo", "gm_ge_army_u1300l_container", "gm_ge_army_kat1_452_container", "gm_ge_army_kat1_451_container"]] call _fnc_saveToTemplate;
A Truck with a Container is not a Cargo Truck, it cannot fit anything anymore so its the opposite of a Cargo Truck

2022-08-04 16:30 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["magazines", createHashMapFromArray [
smoke also exists in vanilla template (looked there a bit for inspiration but will remove it then)

2022-08-04 16:31 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["Hvests", ["gm_ge_vest_armor_90_machinegunner_flk", "gm_ge_vest_armor_90_medic_flk"]];
will do so

2022-08-04 16:32 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["magazines", createHashMapFromArray [
Thats not smoke
https://github.com/official-antistasi-community/A3-Antistasi/blob/1dc2c665751c2fa3434a3af741cb64193f831732/A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf#L48-L49

2022-08-04 16:33 UTC, killerswin2 requested changes

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates.hpp
> +        priorityOcc = 7;
Unsung was "given" the priority of 7 change it to 8 for the time being. Unless this get's merged in before unsung

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["staticMortars", ["B_Mortar_01_F"]] call _fnc_saveToTemplate;
is there not a CDLC mortar?

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_p2a1_launcher_blk""", "", "", ["gm_1Rnd_2650mm_potato_dm11"], [], ""]
remove the potato

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_loadoutData set ["lightATLaunchers", [
if your adding only one "item" make it a single line.
if your adding more than one, each additional line should be indented by 4 spaces
end with the braces on newline.
https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arid.sqf#L97-L102

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_pilotLoadoutData set ["uniforms", ["gm_ge_pol_uniform_pilot_grn", "gm_ge_pol_uniform_pilot_rolled_grn", "gm_ge_army_uniform_pilot_oli", "gm_ge_army_uniform_pilot_rolled_oli", ]];
```suggestion
_pilotLoadoutData set ["uniforms", ["gm_ge_pol_uniform_pilot_grn",  "gm_ge_army_uniform_pilot_oli" ]];
```

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_crewLoadoutData set ["helmets", ["gm_ge_headgear_headset_crew_oli", "gm_ge_headgear_crewhat_80_blk", "gm_ge_headgear_beret_crew_red_antiair", "gm_ge_headgear_beret_crew_blk_antitank", "gm_ge_headgea
cut the amount of helmets in half.

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_pilotLoadoutData set ["vests", ["gm_ge_vest_90_crew_flk", "gm_ge_army_vest_80_bag", "gm_ge_army_vest_80_crew", "gm_dk_army_vest_54_crew"]];
pick one vest that looks good on both uniforms.

2022-08-04 16:33 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_sfLoadoutData set ["SMGs", [
check the sf smg muzzles. Try to add suppressors, even vanilla ones.

2022-08-08 20:55 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_sfLoadoutData set ["SMGs", [
some smgs have inbuild supressors (MP5-SD) others are deleted out of the SF-template

2022-08-08 20:57 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["vehiclesIFVs", ["gm_ge_army_marder1a2", "gm_ge_army_marder1a1a", "gm_ge_army_marder1a1plus", "gm_dk_army_m113a2dk"]] call _fnc_saveToTemplate;                //this line determines IFVs
all now in apcs

2022-08-08 20:57 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["vehiclesLightAPCs", ["gm_ge_army_m113a1g_apc", "gm_ge_army_m113a1g_command", "gm_ge_army_fuchsa0_command", "gm_dk_army_m113a1dk_command"]] call _fnc_saveToTemplate;            //this line determine
all now in apcs

2022-08-08 20:57 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["magazines", createHashMapFromArray [
smoke removed

2022-08-08 20:58 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["sfVoices", ["gm_voice_male_deu_01","gm_voice_male_deu_02","gm_voice_male_deu_03","gm_voice_male_deu_04"]] call _fnc_saveToTemplate;
has different voices now

2022-08-08 21:00 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +"gm_WhiteHead_14_camo_01", "gm_WhiteHead_14_camo_02", "gm_WhiteHead_15_camo_01", "gm_WhiteHead_15_camo_02",
has been changed, police now has normal faces

2022-08-08 21:07 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_pzf84_oli", "", "", "gm_feroz2x17_pzf84_blk", ["gm_1Rnd_84x245mm_ILLUM_DM16_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM32_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM22_carlgustaf", "gm_1Rnd_84x245mm_h
double entries removed, ilumination removed;

note: no documentation on these arrays, template guide only findable for version 2.5.3

2022-08-08 21:10 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_hk69a1_blk", "", "", "", ["1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareGreen_F"
smoke, ilum and double entries removed

2022-08-08 21:11 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["vehiclesCargoTrucks", ["gm_ge_army_kat1_454_cargo", "gm_ge_army_u1300l_container", "gm_ge_army_kat1_452_container", "gm_ge_army_kat1_451_container"]] call _fnc_saveToTemplate;
the name is container, but they are ingame as flatbeds, no container on top of them

2022-08-08 21:12 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["staticMortars", ["B_Mortar_01_F"]] call _fnc_saveToTemplate;
no there is none

2022-08-08 21:12 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_p2a1_launcher_blk""", "", "", ["gm_1Rnd_2650mm_potato_dm11"], [], ""]
done

2022-08-08 21:13 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_pilotLoadoutData set ["uniforms", ["gm_ge_pol_uniform_pilot_grn", "gm_ge_pol_uniform_pilot_rolled_grn", "gm_ge_army_uniform_pilot_oli", "gm_ge_army_uniform_pilot_rolled_oli", ]];
removed 2 uniforms (both police)

2022-08-08 21:14 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_pilotLoadoutData set ["vests", ["gm_ge_vest_90_crew_flk", "gm_ge_army_vest_80_bag", "gm_ge_army_vest_80_crew", "gm_dk_army_vest_54_crew"]];
done

2022-08-09 19:51 UTC, killerswin2 requested changes

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_u1300l_container",
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_kat1_454_cargo",
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_kat1_451_container",
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_kat1_452_container",
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_u1300l_container_civ",
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_weapons\gm_machineguns\gm_mg3\gm_mg3_aatripod",			[0, -1, 1.45],      [0,0,0],    3,      100],
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +    ["\gm\gm_weapons\gm_machineguns\gm_mg3\gm_mg3_aatripod",
needs the p3d file extension

2022-08-09 19:51 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +];
Yeah these should have a p3d file extension

2022-08-09 20:05 UTC, Lazejun requested changes

2022-08-09 20:06 UTC, HakonRydland commented
as you resolve issues raised in this pr please close their related comments to make it easier to keep track of what's left and what can be reviewed again

2022-08-09 20:08 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +        priorityOcc = 7;
It would not matter, both will be Merge conflicts as they are on the same Linies.

2022-08-09 20:15 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["sfVoices", ["gm_voice_male_deu_01","gm_voice_male_deu_02","gm_voice_male_deu_03","gm_voice_male_deu_04"]] call _fnc_saveToTemplate;
They are all German either way, why would there be a reason to split them?

The only good use would be they actually speak a different Language, which was the Case on the Vanilla Template where you took it from.

2022-08-10 13:06 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["sfVoices", ["gm_voice_male_deu_01","gm_voice_male_deu_02","gm_voice_male_deu_03","gm_voice_male_deu_04"]] call _fnc_saveToTemplate;
have now the same

2022-08-10 13:09 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_pzf84_oli", "", "", "gm_feroz2x17_pzf84_blk", ["gm_1Rnd_84x245mm_ILLUM_DM16_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM32_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM22_carlgustaf", "gm_1Rnd_84x245mm_h
desert and winter weapons removed

2022-08-10 13:23 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_pzf84_oli", "", "", "gm_feroz2x17_pzf84_blk", ["gm_1Rnd_84x245mm_ILLUM_DM16_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM32_carlgustaf", "gm_1Rnd_84x245mm_heat_t_DM22_carlgustaf", "gm_1Rnd_84x245mm_h
double magazines in arrays removed

2022-08-10 13:24 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["gm_hk69a1_blk", "", "", "", ["1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "1Rnd_HE_Grenade_shell", "UGL_FlareGreen_F"
double entries removed

2022-08-10 13:24 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["Hvests", ["gm_ge_vest_armor_90_machinegunner_flk", "gm_ge_vest_armor_90_medic_flk"]];
done

2022-08-10 13:25 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates.hpp
> +        priorityOcc = 7;
changed to 8, so please decide what you want there

2022-08-10 13:26 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_crewLoadoutData set ["helmets", ["gm_ge_headgear_headset_crew_oli", "gm_ge_headgear_crewhat_80_blk", "gm_ge_headgear_beret_crew_red_antiair", "gm_ge_headgear_beret_crew_blk_antitank", "gm_ge_headgea
done

2022-08-10 13:27 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	["\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_u1300l_container",
wrote to hakon if i should trust his function or add the p3d extension, he replied that i should trust the function and this is a mod /cdlc maker failure

2022-08-10 13:34 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +["vehiclesTanks", ["gm_gc_army_pt76b", "gm_gc_army_t55", "gm_gc_army_t55a", "gm_gc_army_t55ak", "gm_gc_army_t55am2", "gm_gc_army_t55am2b", "gm_pl_army_pt76b",
removed (beside ot64a

2022-08-10 13:37 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +            "gm_40Rnd_mlrs_122mm_he_9m22u",
done

2022-08-10 14:14 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +["spawnMarkerName", "warsaw pact support Corridor"] call _fnc_saveToTemplate;
changed

2022-08-10 18:02 UTC, Lazejun commented
> 



> as you resolve issues raised in this pr please ~close~ resolve their related comments to make it easier to keep track of what's left and what can be reviewed again

Eh its the other way around.

It makes sense for the Reviewer to mark them as Resolved, when they are seen as done, not the other Person.

As right now i have to open all Comments to find stuff.

2022-08-10 18:03 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +        priorityOcc = 7;
It does not matter it will be a Merge conflict either way.

The one that gets merged first gets the lower Number.

2022-08-10 18:43 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates.hpp
> +        priorityOcc = 7;
okay i would leave it on 8 if that's fine

issue resolved?

2022-08-10 19:27 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Logistics_Nodes.sqf
> +	]
ural occupied seats missing

2022-09-16 08:24 UTC, Bob-Murphy approved these changes
lgtm

2022-09-16 08:26 UTC, Bob-Murphy commented
Merge conflicts because of Unsung - make sure you add both and not overwrite the one with the other

2022-09-16 13:15 UTC, Lazejun commented
> > Merge conflicts because of Unsung - make sure you add both and not overwrite the one with the other
> 
> i don't think i can merge, i con't have write right's on this Repository

Just merge Unstable onto your branch, the you get slapped with the Resolve these conflicts if you use GitHub desktop

2022-09-16 14:07 UTC, targetingsnake commented
just a reminder to myself: need to define vehiclesLightAPCs, vehiclesIFVs and vehiclesHelisLightAttack

2022-09-18 19:57 UTC, Lazejun commented
Have you checked Item Categories yet ? https://github.com/official-antistasi-community/A3-Antistasi/blob/master/A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf

Check AllRifles, AllSniperRifles, AllMachineguns, AllAA and so on for Weapons and that they are Categoriesed properly.

as Example see : https://github.com/official-antistasi-community/A3-Antistasi/blob/3696f65e585a1cdfa83640ac89acce3b865228a5/A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf#L130-L137

In General Item filtering, that will be a lot harder and more annyoing as you are going for Coldwar-ish and CUP adds a lot of Modern Times stuff.

https://github.com/official-antistasi-community/A3-Antistasi/blob/master/A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf

2022-09-22 17:19 UTC, killerswin2 commented on A3A/addons/core/functions/Utility/fn_getItemListFromDLC.sqf
> +License: MIT License, Copyright (c) 2019 Barbolani & The Official AntiStasi Community
you can remove the Copyright

2022-09-22 17:22 UTC, targetingsnake commented on A3A/addons/core/functions/Utility/fn_getItemListFromDLC.sqf
> +License: MIT License, Copyright (c) 2019 Barbolani & The Official AntiStasi Community
is now removed

2022-09-22 17:22 UTC, killerswin2 commented on A3A/addons/core/Templates/fn_detector.sqf
> +if (allowDLCGlobMob && isClass (configFile >> "CfgPatches" >> "gm_weapons_items")) then {A3A_hasGM = true; Info("GM Detected");};
Since GM now has cup stuff, you need to check that A3A_hasCUP is true in the expression

2022-09-22 17:25 UTC, targetingsnake commented on A3A/addons/core/Templates/fn_detector.sqf
> +if (allowDLCGlobMob && isClass (configFile >> "CfgPatches" >> "gm_weapons_items")) then {A3A_hasGM = true; Info("GM Detected");};
done

2022-09-22 17:27 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
Hmmm... that's alot of different ammo. If we are using this calibre in different loadout sections, it would be wise to remove intersections. A.K.A. pick one ammo to give sf then give the rest to military/milita

2022-09-22 17:28 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
That's more of a nit pick, but I think we only give for mags of primary as a default.

2022-09-22 17:30 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
if you have all those different ammo types, you should add the ["primary", 4] call _fnc_addAdditionalMuzzleMagazines so that rifleman actually get the other ammo.

2022-09-22 17:32 UTC, killerswin2 reviewed
just some small nit picks, overall structure is good

2022-09-22 17:37 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
It hands out ammo by simply cycling the arrays, IIRC. These guys will end up with one of each magazine, which is... weird at best, and will work poorly with no-unlocks because there won't be a large quantity of any magazine. As a general rule, rifles should be at worst 50/50 between two different mags, and only SF and militia should vary ammunition with the same weapons.

2022-09-22 17:39 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
I think _addAdditionalMuzzleMagazines is just for weapons with multiple muzzles, like grenade launchers.

2022-09-22 17:40 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
there are rifle grenades in the list so i think they count as grenade launcher, i'll add that for this reason (DM22 HEAT)

2022-09-22 17:42 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
is now changed

2022-09-22 17:47 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
will reduce to 3 ammo types according to what the definition of those are:

1x bullet hard core (german name: hartbleikern)
1x bullet softcore (german: weichbleikern)
1x tracers ( orange for rest)

For SF:
1x hard core bullet
1x AP
1x tracers (red)

that's fine?

2022-09-22 17:47 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
In which direction? If you do want riflemen to get the rifle grenades then you'd need to addAdditionalMuzzleMagazines here, but as not all of the rifles have a secondary muzzle you'd need to test that the function doesn't break in that case. I don't think we do that anywhere else.

2022-09-22 17:49 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
If that's a realistic loadout then fair enough. I'll settle for three mags.

2022-09-22 17:50 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
ah sorry adopted because so it get's harder with each step and it's 50/50 so

2022-09-22 18:02 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "acc_pointer_IR", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_DM111_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A2_g3_blk", "gm
should be fixed

2022-09-22 18:19 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
torwards what killerswin suggested, but also i'm now testing that it works or if it throws errors

2022-09-22 18:33 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["primary", 6] call _fnc_addMagazines;
@jaj22 seems to work, also not every SL has a grenadelauncher in his loadout but it is used there as well

2022-09-22 19:08 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["staticAA", ["B_static_AA_F"]] call _fnc_saveToTemplate;
static AA, mortars and amphibious vics are still vanilla

2022-09-22 19:28 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +["staticAA", ["B_static_AA_F"]] call _fnc_saveToTemplate;
changed

2022-09-25 07:53 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["voices", ["Male01GRE", "Male02GRE", "Male03GRE", "Male04GRE", "Male05GRE", "Male06GRE"]] call _fnc_saveToTemplate;
Do you want Greek People here or was this Forgotten?

2022-09-25 07:53 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +["faces", ["GreekHead_A3_02", "GreekHead_A3_03", "GreekHead_A3_04", "GreekHead_A3_05", "GreekHead_A3_06",
Do you want Greek People here or was this Forgotten?

2022-09-25 11:04 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["voices", ["Male01GRE", "Male02GRE", "Male03GRE", "Male04GRE", "Male05GRE", "Male06GRE"]] call _fnc_saveToTemplate;
i think that was forgotten, but also GM has only two white faces without any paint, so i just might change the voices.

2022-09-25 11:04 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +["faces", ["GreekHead_A3_02", "GreekHead_A3_03", "GreekHead_A3_04", "GreekHead_A3_05", "GreekHead_A3_06",
i think that was forgotten, but also GM has only two white faces without any paint, so i just might change the voices.

2022-09-25 12:00 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["voices", ["Male01GRE", "Male02GRE", "Male03GRE", "Male04GRE", "Male05GRE", "Male06GRE"]] call _fnc_saveToTemplate;
changed

2022-09-25 12:00 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +["faces", ["GreekHead_A3_02", "GreekHead_A3_03", "GreekHead_A3_04", "GreekHead_A3_05", "GreekHead_A3_06",
changed

2022-10-03 10:42 UTC, Lazejun requested changes

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["srifle_LRR_F", "", "", "optic_SOS", [], [], ""],
As you need CUP anyway you could Whitelist specific Weapons and their Ammo aswell as needed Attachments to Replace these Weapons with Stuff that would be appropiate.

Like the M40 or other older Sniper Rifles that fit the spot.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
> +["gm_svd_wud",["SniperRifles","Weapons"]]	];
For forgot 2 GrenadeLaunchers
"gm_hk69a1_blk","gm_pallad_d_brn"

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
> +	private _blacklist = ["gm_g36a1_blk", "gm_g36a1_des", "gm_g36e_blk", "gm_p2a1_launcher_blk"];
You ban G36s but give them to BW SF?

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["gm_g3a3_blk", "", "", "", ["gm_20Rnd_762x51mm_B_DM41_g3_blk", "gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk"], ["gm_1rnd_67mm_heat_dm22a1_g3"], ""],
"gm_1rnd_67mm_heat_dm22a1_g3" is not a Secondary Muzzle Magazine.

There is no 2. Muzzle, there is no Additional Fire mode, its just loaded like any Primary Magazine with just one Round.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["binoculars", ["Laserdesignator_03"]];
If you think it makes sense to give this Future Equipment for gameplay Purposes it can stay.

But i dont think there are many things that can benefit from it, besides being a Rangefinder that needs Batteries.
The only Vehicles that benefit from it might be CUP Vehicles that can lock onto the Laser.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["backpacks", ["gm_ge_army_backpack_90_flk", "gm_dk_army_backpack_73_oli", "gm_ge_army_backpack_80_oli"]];
"gm_ge_army_backpack_80_oli" looks out of Place.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["gm_pm_blk", "", "muzzle_snds_L", "gm_8Rnd_9x18mm_B_pst_pm_blk", [], [], ""]
Funny typo,
"gm_8Rnd_9x18mm_B_pst_pm_blk" is not an Optic, its a Magazine

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["srifle_GM6_ghex_F", "", "optic_Arco", "", ["5Rnd_127x108_Mag", "5Rnd_127x108_APDS_Mag"], [], ""],
Same here, either give Marksman Rifles with Cooler stuff or Replace with fitting stuff from CUP

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["gm_pm_blk", "", "", "gm_8Rnd_9x18mm_B_pst_pm_blk", [], [], ""]
Funny Typo,
"gm_8Rnd_9x18mm_B_pst_pm_blk" is a Magazine not an Optic.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["srifle_GM6_ghex_F", "", "optic_LRPS_ghex_F", "", ["5Rnd_127x108_Mag", "5Rnd_127x108_APDS_Mag"], [], ""],
Same here, either give Marksman Rifles with Cooler stuff or Replace with fitting stuff from CUP

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["srifle_GM6_ghex_F", "", "optic_LRPS_ghex_F", "", ["5Rnd_127x108_Mag", "5Rnd_127x108_APDS_Mag"], [], ""],
Same here, either give Marksman Rifles with Cooler stuff or Replace with fitting stuff from CUP

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +"gm_mp2a1_blk","gm_pm63_blk",
"gm_mp2a1_blk","gm_pm63_blk"
Can be replaced with Whitelisted Bolt Action Rifles/Shotguns from CUP, i know GM doesent have them but SMGs against Ai that has no Body Armor makes early game way to Easy.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +"gm_p1_blk","gm_pm_blk",
Could add the Funny Flare Pistol + some Ammo the The starting Items, can be helpful at night as GM has almost no Weapons that can hold a Flashlight and NVGs are not a thing in GM either.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +"acc_flashlight","acc_flashlight_smg_01","acc_flashlight_pistol"];
"acc_flashlight","acc_flashlight_smg_01","acc_flashlight_pistol" these are pointless, the only GM Weapons that can hold a Flashlight are the Railed G3s

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["staticMortar", "I_G_Mortar_01_F"] call _fnc_saveToTemplate;
"I_G_Mortar_01_F"
Can be replaced with CUP assets.

2022-10-03 10:42 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["mineAT", ["gm_minestatic_at_dm21", "gm_minestatic_at_dm1233"]] call _fnc_saveToTemplate;
"mineAT", "mineAPERS" are Magazines.

Its mostly horrible Legacy stuff that Barrely works, the Plan is/was to Replace them with just a Demand of Money instead of Arsenal Items.

2022-10-03 13:15 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_sfLoadoutData set ["uniforms", ["gm_xx_uniform_soldier_bdu_nogloves_80_wdl", "gm_xx_uniform_soldier_bdu_80_wdl", "gm_xx_uniform_soldier_bdu_rolled_80_wdl"]];
changed

2022-10-03 13:15 UTC, targetingsnake commented on A3A/addons/core/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf
> +	private _blacklist = ["gm_g36a1_blk", "gm_g36a1_des", "gm_g36e_blk", "gm_p2a1_launcher_blk"];
removed from loudout

2022-10-03 13:19 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["backpacks", ["gm_ge_army_backpack_90_flk", "gm_dk_army_backpack_73_oli", "gm_ge_army_backpack_80_oli"]];
changed

2022-10-03 13:25 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
fixed now still have armor but now in bdu woodland (as i supose them to have armor as they are sf)

2022-10-03 13:28 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_militaryLoadoutData set ["binoculars", ["Laserdesignator_03"]];
changed to simple rangefinder as i think it would improve players gameplay if they can measure distances

2022-10-03 13:29 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +]];
changed

2022-10-03 13:36 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["srifle_LRR_camo_F", "", "", "optic_LRPS", [], [], ""],
will give them g22 from cup, was introduced 1997 so still 90s

2022-10-03 13:36 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +    ["srifle_LRR_F", "", "", "optic_SOS", [], [], ""],
same as with SF but without silencer

2022-10-03 13:41 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
Usually its the opposite, Light Gear, lighter or no Armor for Mobility compared to heavy Bulky Gear and heavy armor.

2022-10-03 13:43 UTC, targetingsnake commented on A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
> +["gm_svd_wud",["SniperRifles","Weapons"]]	];
changed

2022-10-03 13:45 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["gm_pm_blk", "", "muzzle_snds_L", "gm_8Rnd_9x18mm_B_pst_pm_blk", [], [], ""]
changed

2022-10-03 13:45 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["gm_pm_blk", "", "", "gm_8Rnd_9x18mm_B_pst_pm_blk", [], [], ""]
changed

2022-10-03 13:49 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["srifle_GM6_ghex_F", "", "optic_Arco", "", ["5Rnd_127x108_Mag", "5Rnd_127x108_APDS_Mag"], [], ""],
army of gdr seems only to had the mosin as bolt action sniper rifle

2022-10-03 13:49 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
> +    ["srifle_GM6_ghex_F", "", "optic_LRPS_ghex_F", "", ["5Rnd_127x108_Mag", "5Rnd_127x108_APDS_Mag"], [], ""],
same as milita

2022-10-03 13:51 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
ah okay, i should change that then i guess

2022-10-03 13:55 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +"acc_flashlight","acc_flashlight_smg_01","acc_flashlight_pistol"];
some should have the railed G3 so i would leave that in, but i also can remove it

2022-10-03 14:03 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +"gm_mp2a1_blk","gm_pm63_blk",
removed them used cup bolt actions (mosin, Lee enfield and Remington 700)

2022-10-03 14:06 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["staticMortar", "I_G_Mortar_01_F"] call _fnc_saveToTemplate;
added mortar from russians

2022-10-03 14:07 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +["mineAT", ["gm_minestatic_at_dm21", "gm_minestatic_at_dm1233"]] call _fnc_saveToTemplate;
changed

2022-10-03 14:12 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
> +"gm_p1_blk","gm_pm_blk",
added, also think good idea also for night

2022-10-03 14:24 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
now fixed, they now have the suspender gear, like the ones the mod itself has on its SF units (also militia units have the same but i don't think that's a big issue)

2022-10-03 14:27 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
I dunno. For balance purposes it's better if they have body armor, because it makes a huge difference to their capability in both vanilla and ACE with stock settings. You could argue that they're normally being dropped straight into a hot zone, so they'd switch from their usual sneaky-scout setup. Losing the helmet is fine though.

2022-10-03 14:29 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
i would mention it in the PR so when we test the template we can change that if SF is too easy?

2022-10-03 14:39 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
We know what it does. If units lack body armour then they fall over with one rifle shot with vanilla medical. Vanilla NATO specops were unarmoured before 2.4 and they were stupidly easy to kill. We gave them plate carriers somewhere in the template rework, although I'm not sure whose decision that was.

2022-10-03 14:46 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +private _sfLoadoutData = _loadoutData call _fnc_copyLoadoutData; // touch and shit breaks
okay i revert now again to fitting plate carries @Lazejun @jaj22

2022-10-03 14:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +        "gm_ge_army_uniform_pilot_rolled_sar",
Whats the point of giving random Pilot Uniforms to Civilians?

        "gm_ge_army_uniform_pilot_sar",
        "gm_ge_army_uniform_pilot_rolled_sar",

2022-10-03 14:58 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +        "gm_ge_army_uniform_pilot_rolled_sar",
that's the overalls from search and rescue, completely orange, i will remove them

2022-10-03 14:59 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +        "gm_ge_army_uniform_pilot_rolled_sar",
changed

2022-10-03 15:12 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_sfLoadoutData set ["uniforms", ["gm_xx_uniform_soldier_bdu_nogloves_80_wdl", "gm_xx_uniform_soldier_bdu_80_wdl", "gm_xx_uniform_soldier_bdu_rolled_80_wdl"]];
You lost the Army

2022-10-03 15:19 UTC, targetingsnake commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_sfLoadoutData set ["uniforms", ["gm_xx_uniform_soldier_bdu_nogloves_80_wdl", "gm_xx_uniform_soldier_bdu_80_wdl", "gm_xx_uniform_soldier_bdu_rolled_80_wdl"]];
fixed typo, also these variants are not displayed ingame O.o

2022-10-03 15:23 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
> +_sfLoadoutData set ["uniforms", ["gm_xx_uniform_soldier_bdu_nogloves_80_wdl", "gm_xx_uniform_soldier_bdu_80_wdl", "gm_xx_uniform_soldier_bdu_rolled_80_wdl"]];
A lot of things are not visible in the editor and such and can only be accessed via code.
It's done by setting `scope=1` in the config.

2022-10-16 17:04 UTC, Bob-Murphy commented
@killerswin2 @Lazejun please re-review
Thank you

2022-10-16 17:46 UTC, targetingsnake commented
> Have you checked Item Categories yet ?

so far yes

2022-10-17 20:14 UTC, Lazejun requested changes

2022-10-17 20:14 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf
> +_civHats = ["gm_ge_headgear_winterhat_80_oli", "gm_ge_headgear_hat_beanie_blk"];
Are you happy with Civs only wearing 2 funny hats?

Its all they get.

2022-10-17 20:25 UTC, merged