fixed issue with everyone being considered admin on lh (garage)
official-antistasi-community/A3-Antistasi pull request #2430
Opened 2022-08-10 20:47 UTC by HakonRydland

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    on lh it always returned true for cmdClient calls on the server( where its mostly used as most checks that need it are server side) this made everyone able to act as admin/commander on a lh session

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-08-12 18:33 UTC, jaj22 commented
Is there a good reason that this isn't a function that returns a boolean yes/no for whether the user is allowed to override? That's how it's being used at the moment, and it'd make it a lot easier to read if it was written like that.

2022-08-21 17:35 UTC, Bob-Murphy requested changes

2022-08-21 17:35 UTC, Bob-Murphy commented on A3A/addons/Garage/Public/config.inc
> +    if ((isServer && hasInterface && _this isEqualTo player) || {admin owner _this > 0}) then {_this} else {theBoss}; //LAN Host or admin on DS or commander
Please adapt to bool check as discussed on discord

2022-09-17 05:42 UTC, Bob-Murphy commented
@jaj22 please new technical review for change to boolean

2022-09-17 05:43 UTC, Bob-Murphy approved these changes
LGTM - no typos found

2022-09-17 17:53 UTC, jaj22 approved these changes
Looks good.

2022-09-18 11:40 UTC, merged