Fix high command FT and garrison annoyances
official-antistasi-community/A3-Antistasi pull request #2434
Opened 2022-08-14 16:37 UTC by jaj22

## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Changed HC fast travel and HC garrison to directly turn off the commanding menu and override the map click. The fast travel was using a command bar on/off method before which caused the BIS HC functions to throw script errors, while the garrison function wasn't turning off the commanding menu at all, so you needed an additional map click.

Also fixed a couple of things from #2165:
- Prevented closing the map after high command fast travel completion.
- Prevented tow ropes on personal vehicle from blocking squad fast travel.

### Please specify which Issue this PR Resolves.
partially fixes #2165 plus some other stuff that may not have an issue.

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

2022-08-21 17:08 UTC, Bob-Murphy requested changes

2022-08-21 17:08 UTC, Bob-Murphy commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
>  _esHC = false;
Could you please change all `_esHC` to `_isHC`?
It's a leftover spanish variable as it seems.

2022-08-21 17:58 UTC, jaj22 commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
>  _esHC = false;
I could, but it makes it very hard to tell what's been (genuinely) changed in the PR, as `_esHC` is spammed over a dozen lines, some of them very long. Probably best to leave it until it gets rewritten for the new UI.

2022-08-21 17:59 UTC, Bob-Murphy commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
>  _esHC = false;
valid argument

2022-09-09 12:07 UTC, Bob-Murphy approved these changes
lgtm

2022-09-09 13:21 UTC, CalebSerafin approved these changes
Some good changes. I see that Tow ropes are now checked as nil rather than object null. I guess that works as well or better.
Good, disable of other map click event handlers when clicking for FT.
Better checks for closing map while in HC.

2022-09-09 13:22 UTC, merged