Template cohesion
official-antistasi-community/A3-Antistasi pull request #2446
Opened 2022-08-31 23:46 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    oh boi. This Changes alot. 
    1) moves all templated related functionality to a new addon.
    2) a lot documentation, just about every function now has documentation.
    3) templates no longer have unit type definitions, those were moved to one function
    4) loading templates now has an event, allowing 3rd party mods to get the hashmap before loadout creation.
    5) templates now allow have facewear instead of just one vanilla templates.
    6) verification of templates now use the new compatableItems and magazines 
    7) fixed a the vanilla templates trying to add a optic to a rail slot instead of an optic slot.
    8) verification now checks what type of item you are trying you add if it fails.
    9) fixed casing in some cup templates
    10) fixed bad optic names in baf cup templates
    11) fixed adding a rpg mag in a m72
    12) private functions now are prefixed if they weren't
    13) template folder that holds the templates now is named modsets, like addons
    
    Why all these changes, started for testing documentation they decided to make the templates a little cleaner and more dry.
    This is the first step in allowing templates to be json as now we don't need to have loadout generation code in templates.
    There is probably something I missed in explaining but that should be it. Test with every modset. 

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-09-01 04:13 UTC, Lazejun requested changes
Don't add Facewear unless you do it properly.

Dont use the horrible existing example as a base.

2022-09-01 04:21 UTC, Lazejun commented on A3A/addons/Templates/Templates/Modsets/IFA/IFA_AI_POL_Arid.sqf
> +["spawnMarkerName", ""] call _fnc_saveToTemplate;
Just delete these dead files

2022-09-01 15:46 UTC, HakonRydland requested changes
wont speak to much on this, but i do see one concern, at a glance the rest looks fine but as its mostly template data im leaving that for laze, rest of changes is mostly just moving stuff around, seeing as its a rather big and isolated system im fine with this becoming its own addon

2022-09-01 15:46 UTC, HakonRydland commented on A3A/addons/Templates/functions/Templates/functionTemplates.sqf
> +    _templatesToGenerate pushBack [_prefix, _unitTypes, "sfLoadoutData"];
adding the templates to list of templates should be accessible to the template so they can change stuff, the base unit template can remain where it is as then you could just duplicate and overwrite it, i dont believe this is to much boiler plate to leave in

2022-10-02 22:01 UTC, killerswin2 commented
this pr has been broken up into new prs

2022-10-02 22:01 UTC, closed without merging