Extra message for New Garage
official-antistasi-community/A3-Antistasi pull request #2453
Opened 2022-09-17 13:06 UTC by igorkis-scrts

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Old, pre-2.5.0-garage had the ability to show some extra messages during vehicle placement process. This PR implements same thing for Hakon's Garage too.
This might be useful in some non-general use cases: some additional hints, guidances or simply vehicle price can be shown to player.

![image](https://user-images.githubusercontent.com/6746043/190858138-64661d15-0376-471d-b41e-b8fe47ecf0ff.png)

 
### Please specify which Issue this PR Resolves.
-

### Please verify the following and ensure all checks are completed.
-

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
For example, fn_addFIAVeh.sqf:
```sqf
private _extraMessage = format ["Buying vehicle for $%1.", vehiclePurchase_cost];

[_typeVehX, "BUYFIA", [], nil, nil, nil, false, _extraMessage] call HR_GRG_fnc_confirmPlacement;
```

2022-09-17 13:53 UTC, HakonRydland requested changes

2022-09-17 13:53 UTC, HakonRydland commented on A3A/addons/Garage/Core/fn_confirmPlacement.sqf
>  HR_GRG_placing = true;
this blocker check is required, add it back in

2022-09-17 13:53 UTC, HakonRydland commented on A3A/addons/Garage/Core/fn_confirmPlacement.sqf
> +                format ["%1%2", HR_GRG_CP_extraText, localize "STR_HR_GRG_Feedback_CP_Rotation"]
add the linebreak here, it should not be the responsibility of the user to add it

2022-09-17 13:53 UTC, HakonRydland commented on A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
> +private _extraMessage =	format ["Buying vehicle for $%1.<br/>", vehiclePurchase_cost];
reminder to remove the linebrak from here

2022-09-17 17:50 UTC, igorkis-scrts commented on A3A/addons/Garage/Core/fn_confirmPlacement.sqf
>  HR_GRG_placing = true;
Whoops
Fixed in [commit](901c137ff212c6a66c62ebbf6ad2bb17803c03b0)

2022-09-17 17:50 UTC, igorkis-scrts commented on A3A/addons/Garage/Core/fn_confirmPlacement.sqf
> +                format ["%1%2", HR_GRG_CP_extraText, localize "STR_HR_GRG_Feedback_CP_Rotation"]
Fixed in [commit](901c137ff212c6a66c62ebbf6ad2bb17803c03b0)

2022-09-17 17:50 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
> +private _extraMessage =	format ["Buying vehicle for $%1.<br/>", vehiclePurchase_cost];
Fixed in [commit](901c137ff212c6a66c62ebbf6ad2bb17803c03b0)

2022-09-17 17:51 UTC, HakonRydland approved these changes

2022-09-17 20:06 UTC, Bob-Murphy approved these changes
lgtm

2022-09-17 20:07 UTC, merged

2022-09-18 09:13 UTC, igorkis-scrts commented
It's a little bit late as PR already merged, but - make sure that the extra message's structured text has at least the same size as the rest.
I've noticed today that font of extra message is bigger than the rest of the hint, so it needs to be properly formatted. This could be done either in message or automatically applied in string concatenation. 

For example:
1.
```xml
<Original>&lt;t size='0.6'&gt;Select vehicle position.&lt;br/&gt;Price: %1%2&lt;/t&gt;</Original>
```
2. 
```sqf
format ["<t size='0.6'>%</t><br/>%2", HR_GRG_CP_extraText, localize "STR_HR_GRG_Feedback_CP_Rotation"]
```