Compatible magazines in jna
official-antistasi-community/A3-Antistasi pull request #2472
Opened 2022-09-29 19:09 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
   Make JNA USE COMMANDS AGAIN. Makes the arsenal mag search use the compatibleMagazines command.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-10-02 04:28 UTC, jaj22 commented
Did you check what compatibleMagazines returns for the buggy RHS magazine wells? Will need to do a toLower conversion in the vehicle arsenal one if it doesn't correct the casing.

2022-10-02 19:17 UTC, jaj22 commented
Ok, looks like `compatibleMagazines` does a built-in case correction (equivalent of `configName (configFile/"CfgMagazines"/_x)`) so this should be fine with the broken RHS stuff.

2022-10-02 19:18 UTC, jaj22 approved these changes

2022-10-03 08:58 UTC, Lazejun requested changes
Normal Arsenal seems to show all Magazines correctly
Compatible Ammo for 3CB BAF Vehicles in the Vehicle Arsenal still works,
Vehicle Arsenal for Weapon Magazines doesent work anymore.

To Test: Take a Vehicle, Put a Weapon Inside, Open the Magazine Tab.
It should show you the Magazines for each Weapon in the Vehicle inventory.

```sqf
10:56:01 Error in expression <t select _x;
{
_usableMagazines append (compatibleMagazines _x);
} forEach _weap>
10:56:01   Error position: <compatibleMagazines _x);
} forEach _weap>
10:56:01   Error Type Number, expected String
10:56:01 File \x\A3A\addons\JeroenArsenal\JNA\fn_vehicleArsenal.sqf [JN_fnc_vehicleArsenal]..., line 1623
10:56:01  ➥ Context: 	[] L1 ()
	[] L1384 (\x\A3A\addons\JeroenArsenal\JNA\fn_vehicleArsenal.sqf [JN_fnc_vehicleArsenal])
	[] L1615 (\x\A3A\addons\JeroenArsenal\JNA\fn_vehicleArsenal.sqf [JN_fnc_vehicleArsenal])
	[] L1625 (\x\A3A\addons\JeroenArsenal\JNA\fn_vehicleArsenal.sqf [JN_fnc_vehicleArsenal])
	[] L1624 (\x\A3A\addons\JeroenArsenal\JNA\fn_vehicleArsenal.sqf [JN_fnc_vehicleArsenal])
	[] L1623 (\x\A3A\addons\JeroenArsenal\JNA\fn_vehicleArsenal.sqf [JN_fnc_vehicleArsenal])

```

2022-10-12 18:39 UTC, jaj22 requested changes

2022-10-12 18:39 UTC, jaj22 commented on A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
> +				_usableMagazines append (compatibleMagazines _x);
Still doesn't work because you dropped the toLower, and the later check is lower-case only. In theory we can remove that restriction if the vehicle magazines code is case-corrected, or otherwise guaranteed to return classes with the correct case, but that's going to need more work and a lot of checking either way.

2022-10-12 18:39 UTC, jaj22 commented on A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf
> +				_usableMagazines append (compatibleMagazines _x);
Ah FFS, highlighted the wrong code chunk. Was supposed to be the vehicle arsenal part.

2022-10-14 04:16 UTC, jaj22 commented
This works, but you also lost the pushBackUnique. This matters for the case where you have multiple weapons in a vehicle which use the same ammo, so _usableMagazines ends up with a bunch of duplicate entries which are then tested against every magazine in the arsenal. Probably best to just do `_usableMagazines arrayIntersect _usableMagazines` to filter it down.

2022-10-15 01:47 UTC, killerswin2 commented
> This works, but you also lost the pushBackUnique. This matters for the case where you have multiple weapons in a vehicle which use the same ammo, so _usableMagazines ends up with a bunch of duplicate entries which are then tested against every magazine in the arsenal. Probably best to just do `_usableMagazines arrayIntersect _usableMagazines` to filter it down.

resolved in [d12218b](https://github.com/official-antistasi-community/A3-Antistasi/pull/2472/commits/d12218b3f05456fb20b423812cd49a5aa704b355)

2022-10-15 11:57 UTC, Lazejun approved these changes

2022-10-15 16:21 UTC, jaj22 approved these changes

2022-10-15 22:24 UTC, merged