Discord rich presence
official-antistasi-community/A3-Antistasi pull request #2473
Opened 2022-09-30 13:32 UTC by targetingsnake

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Adds discord rich presence to A3 Antistasi. Currently this branch is only a proof of concept.
   Bob mentioned it would be nice to have a discord integration for antistasi. i build this for is to test and to have a proof of concept. With this extentsion it is possible to display the briefing name and role description in discord. also it displays the current playercount and the max playercount when the current user has connected (will be made repating in a future commit). Also it displays if the player charackter is dead or unconsicous. Furthermore it also displays kills, death and assists of the player.

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

testing needed under linux (extension should not be triggered/ .dll not be searched)
testing for 32 bit systems is required (i don't have one)
Eventually write extension in C++ to make it loadable under linux as client.

### How can the changes be tested?
Steps: 

1. build Antistasi mods with the tools you use
2. copy the .dll files and the lib folder from A3A/ to your folder where the mod is build in
3. start discord (if discord is not started nothing will happen)
4. for a full experience start arma with ace and cba (but will also work withput)
5. select a Multiplayer mission you wanna play
6. look into your discord state and kill a few enemies / respawn
********************************************************
Notes:

2022-10-09 20:11 UTC, CalebSerafin commented
Hello, I have seen the notification and will be looking at this soon.

2022-10-10 09:37 UTC, targetingsnake commented
we already wrote on discord

2023-02-15 11:29 UTC, CalebSerafin commented
@targetingsnake I see git is misidentifying changes. Give me a list of files and directories of the actual changes you made and I can rebase the branch on unstable for you (If desired.).

2023-02-15 11:30 UTC, Bob-Murphy commented
No need.
The rich presence will be separated into a different repo as a optional mod.
This here will be closed soon.

2023-02-15 12:03 UTC, CalebSerafin requested changes
The code is nice and clean. Some suggestions.

Regarding logging, you should use some sort of central login system.
You can define a macro conditionally if antistasi is not loaded, or else create a shim that logs via antistasi's standard logging macros. See [__has_include](https://community.bistudio.com/wiki/PreProcessor_Commands#has_include)

2023-03-25 20:01 UTC, Bob-Murphy commented
Moved to separate repo

2023-03-25 20:01 UTC, closed without merging