Buy item GUI
official-antistasi-community/A3-Antistasi pull request #2476
Opened 2022-10-03 03:04 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    adds a GUI for buy utility items and loot boxes. Allows for use to add more items for purchase.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-10-03 03:05 UTC, killerswin2 commented
![Screenshot 2022-10-02 214808](https://user-images.githubusercontent.com/8095345/193494543-81076f98-05b9-4e6d-9369-00bf8632b60c.png)

2022-10-03 08:27 UTC, Lazejun commented
Pretty neat, probably super annyoing todo since Arma UI Fun.

More informations to the individual Items, the MaxLoad of the LTC Crate, amount of Fuel in the Fuel Containers etc.
Maybe even Node Size so people would know what Vehicles could transport it.
This could be helpful if we add more Options so Players would know what they are getting for their Money.

2022-10-03 20:07 UTC, HakonRydland requested changes
alot of good stuff, some minor changes needed

2022-10-03 20:07 UTC, HakonRydland commented on A3A/addons/GUI/dialogues/buyItemDialog.hpp
> +
```cpp
class A3A_BuyItemDialog : A3A_BuyVehicleDialog {
    idd = A3A_IDD_BUYITEMDIALOG;
    onLoad = "[""onLoad""] spawn A3A_fnc_buyItemDialog";
}
```
note that if these two menus remain unerged then you wont even need uniqe idc's for the controls as the other menu would not ever exist at the same time, we also dont use only idc for control retival but do it through the display, so no fear of conflicts

2022-10-15 02:26 UTC, killerswin2 commented
![Screenshot 2022-10-03 181402](https://user-images.githubusercontent.com/8095345/195964758-18902c34-08ed-4a3f-98bf-f6b3cd2e33d2.png)
![Screenshot 2022-10-03 181316](https://user-images.githubusercontent.com/8095345/195964764-aa9fb790-6911-457c-8735-1f65ab09cd9f.png)
![Screenshot 2022-10-03 181412](https://user-images.githubusercontent.com/8095345/195964767-0cb74b3c-4292-453c-9f66-58dfdfad7ec5.png)
![Screenshot 2022-10-03 181421](https://user-images.githubusercontent.com/8095345/195964772-1e072ebe-635a-4cf6-a085-3f3fdea84a75.png)

2022-10-15 11:14 UTC, Bob-Murphy requested changes

2022-10-15 11:14 UTC, Bob-Murphy commented on A3A/addons/GUI/Stringtable.xml
> +                <Original>The Commander may only buy this item.</Original>
--> "Only the Commander may buy this item"

2022-10-15 11:14 UTC, Bob-Murphy commented on A3A/addons/GUI/Stringtable.xml
> +                <Original>This item can loot items</Original>
--> "This item can collect loot" sounds somewhat better than using 2x items

2022-10-23 17:51 UTC, HakonRydland approved these changes
one small mistake, but as initLootToCrate has doubling safeguards its fairly inexpensive and everything else looks ok

2022-10-23 17:51 UTC, HakonRydland commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +		call A3A_fnc_initLootToCrate;
initLootToCrate called twice

2022-10-23 17:54 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +		call A3A_fnc_initLootToCrate;
Also dropObject called twice (doesn't matter, but unnecessary) and tab spacing in what's now a 4-spaced file.

2022-10-23 18:05 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +		call A3A_fnc_initLootToCrate;
oof, bad merge

2022-10-23 18:10 UTC, killerswin2 commented
okay removed double calls, and fixed tabs. Tabs should be spaces.

2023-01-11 18:33 UTC, Bob-Murphy commented
Price of the light 10€ - substracted money 25€
all other prices are correct

2023-01-11 18:39 UTC, Bob-Murphy approved these changes
lgtm

2023-01-11 20:44 UTC, merged