Setup GUI + init rework
official-antistasi-community/A3-Antistasi pull request #2488
Opened 2022-10-10 22:06 UTC by jaj22

### What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
This PR adds a setup GUI to select and manipulate saved games, select factions and change parameters. This required a major init rework, with some overdue refactors carried out along the way.

Functionality is largely complete, but I need to fill out a lot of doc headers and do more faction-specific equipment testing. Backing up your profile vars files is strongly recommended although I didn't break them for a while.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [X] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Stuff not adequately tested yet:
- Loot list generation.
- Any factions except vanilla, RHS and 3CBF.
- Campaign completion flagging.
- Probably other stuff I forgot.

2022-10-10 23:11 UTC, killerswin2 commented on A3A/addons/core/Templates/fn_detector.sqf
> -//KAT medical detection
I'm confused on why you removed this. Was it replaced some where that I didn't see?

2022-10-11 00:36 UTC, jaj22 commented on A3A/addons/core/Templates/fn_detector.sqf
> -//KAT medical detection
Yeah, it's moved back a step to initVarCommon. Detector and selector aren't currently called, just left in for reference. I'll probably kill them before release.

2022-10-11 17:10 UTC, killerswin2 requested changes
Part 1 of review

2022-10-11 17:10 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates.hpp
>      };
UNS got removed somehow

2022-10-11 17:10 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +A3A_hasCUP = isClass (configFile >> "cfgPatches" >> "CUP_BaseConfigs");
the verfication is approved Bob just needs to merge it in. You can remove this if you want when he merges in the update.

2022-10-11 17:10 UTC, killerswin2 commented on A3A/addons/core/Templates/fn_detector.sqf
>  //TCGM_BikeBackpack Detection
honestly I would just kill this file if we aren't going to use it.

2022-10-11 17:10 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
> +    A3A_balancePlayerScale = A3A_balancePlayerScale * (A3A_enemyBalanceMul / 10);
feel like there changes are out side the scope of the pr. Do they need to be merged in now for a bugfix? Or just minor changes?

2022-10-11 17:10 UTC, killerswin2 commented on A3A/addons/core/functions/ModsAndDLC/fn_getModOfConfigClass.sqf
> +	_return = tolower getText (_config >> "DLC");
you lowercase the command...... toLower

2022-10-11 17:53 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
> +    A3A_balancePlayerScale = A3A_balancePlayerScale * (A3A_enemyBalanceMul / 10);
Within scope because it was a pain making fractions work with the UI, which is probably why the parameters screen didn't support it in the first place. Had a choice between making the UI even less readable or adding these. Switched a few times.

Was simpler to do the div 10 with initParams because it only required a one-way translation.

2022-10-11 17:57 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf
> +    };
I don't see how. At best you'd need a forEach for the index, at which point it's saving exactly one line of code by using a BIS function.

2022-10-11 18:08 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf
> +    A3A_balancePlayerScale = A3A_balancePlayerScale * (A3A_enemyBalanceMul / 10);
cool

2022-10-11 18:09 UTC, killerswin2 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf
> +    };
yeah, we just need better scripting cmds

2022-10-11 18:14 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +        private _nearMarker = [markersX - controlsX, _posClicked] call BIS_fnc_nearestPosition;
Not seeing anything beneficial there. The visiblemap change isn't relevant here because the "current" HQ location is always valid.

2022-10-11 18:16 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +        if (_posClicked findIf { (_x < 0) || (_x > worldSize) } != -1) then {
Missed an exitWith here though. Not tested because you can't hit the case on either Altis or Malden due to the water check triggering first.

2022-10-11 18:18 UTC, killerswin2 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +        private _nearMarker = [markersX - controlsX, _posClicked] call BIS_fnc_nearestPosition;
ah, then it is time to kill #1764

2022-10-11 18:22 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
> +
There's already one in onLoad in setupDialog.sqf. The only way you'd call the tab functions without triggering that first is by external calls, which really aren't supported.

2022-10-11 18:23 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +A3A_hasCUP = isClass (configFile >> "cfgPatches" >> "CUP_BaseConfigs");
Yeah, the more of these I can kill, the better. One day I'll purge all the hasIFA references.

2022-10-11 18:27 UTC, jaj22 commented on A3A/addons/core/functions/ModsAndDLC/fn_getModOfConfigClass.sqf
> +	_return = tolower getText (_config >> "DLC");
Removed, discovered why it was there (BIS can't even keep their own DLC casing consistent), added it back in with different case :P

2022-10-11 21:47 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf
> +            _x set ["mapStr", _prettyMapHM getOrDefault [_x get "map", _x get "map"]];
I thought that line was more readable than the next one, but whatever :P

2022-10-11 21:48 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf
> +        switch (_selectedTab) do
Turns out `ctrlShow true` toggles all the child controls to true, so the update call needs to come after the ctrlShow loop. I shortened the function a bit though.

2022-10-11 21:51 UTC, jaj22 commented on A3A/addons/GUI/dialogues/setupDialog.hpp
> +            onLoad = "['onLoad'] spawn A3A_fnc_setupLoadgameTab";
Yep that worked.

2022-10-11 21:51 UTC, jaj22 commented on A3A/addons/core/Templates/Templates.hpp
>      };
Unsung now added and working, even found a logo.

2022-10-11 23:00 UTC, Bob-Murphy commented
Tried creating a new save. Vanilla only, two different CSAT as enemy. This popped up.
![image](https://user-images.githubusercontent.com/50651578/195213546-89ee6881-29fc-41b5-a31f-c9de950e8791.png)

2022-10-12 00:12 UTC, jaj22 commented
Missed a bunch of vanilla factions that I didn't know existed. Not entirely sure what they are. Would be helpful if something can sanity check:

CSAT_Enoch: Temperate camo, should force Contact DLC enabled.
CSAT_Apex: Tropical camo, should force Apex DLC enabled.
NATO_Apex: Tropical camo, should force Apex DLC enabled.

2022-10-12 04:44 UTC, jaj22 commented
Ok, I fixed up the template file for the new vanilla factions (turns out that they were added since I forked the setup UI stuff). However the forceDLC attributes are guesswork, as I don't know whether any DLC-locked gear or vehicles is actually present in these factions.

2022-10-15 11:43 UTC, Bob-Murphy requested changes
I think I got all missing strings for the GUI and important information.
There are quite a few more customHints in some files you touched but that would be out ot scope.

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf
> +        ];
add the following for new maps in map overhaul:
,["chernarus_autumn", "Chernarus (A)"]
,["vn_khe_sanh", "Khe Sanh"]

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
> +        private _str = format ["Really delete game with ID %1 on %2?", _saveData get "gameID", _saveData get "mapStr"];
stringify

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupFactionsTab.sqf
> +            private _msg = "Couldn't load factions from save:";
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +            ["HQ Position", "Selected position cannot be near enemy zones."] call A3A_fnc_customHint;
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +            ["HQ Position", "Selected position cannot be in water."] call A3A_fnc_customHint;
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +            ["HQ Position", "Selected position cannot be outside the map."] call A3A_fnc_customHint;
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
> +        _confirmText = _confirmText + endl + format ["%1 occupants and %2 invaders?", _occName, _invName];
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
> +                _confirmText = format ["Load game with ID %1, ", _oldSave get "gameID"];
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
> +                _confirmText = format ["Copy game with ID %1, ", _oldSave get "gameID"];
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
> +            _confirmText = "Create new game with ";
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/core/functions/Save/fn_saveLoop.sqf
> +["Persistent Save","Starting persistent save..."] remoteExecCall ["A3A_fnc_customHint",0,false];
stringify?

2022-10-15 11:43 UTC, Bob-Murphy commented on A3A/addons/core/functions/init/fn_startGame.sqf
> +    ["Server Information", "Waiting for background init to complete"] remoteExec ["A3A_fnc_customHint", 0];
stringify?

2022-10-15 11:45 UTC, Bob-Murphy commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +A3A_hasCUP = isClass (configFile >> "cfgPatches" >> "CUP_BaseConfigs");
#2466 is merged

2022-10-16 17:41 UTC, HakonRydland approved these changes
alright from a quick read and testing im ok with merger, while i have some disagreement about design choices for the underlying data and how its handled its simpler and functions perfectly fine... if any changes are wanted by the team it can be done later, as souch this is good to merge

2022-10-16 17:41 UTC, HakonRydland commented on A3A/addons/core/Templates/AddonVics.hpp
> +        path = QPATHTOFOLDER(Templates\AddonVics\);
the `\` at the end should  really be moved to processing, but it can wait til a later date

2022-10-16 17:41 UTC, HakonRydland commented on A3A/addons/core/Templates/Templates.hpp
> +        camo[] = {"temperate","tropical"};
ok so camo is actually suited for climates xyz...

2022-10-16 19:04 UTC, jaj22 commented on A3A/addons/core/Templates/Templates.hpp
> +        camo[] = {"temperate","tropical"};
Can change to climate[]. Makes more sense given that it's not necessarily the actual camo for the troops.

2022-10-16 19:05 UTC, jaj22 commented on A3A/addons/core/Templates/AddonVics.hpp
> +        path = QPATHTOFOLDER(Templates\AddonVics\);
Nah, I'll probably do it. At one point it saved some messy string processing but now it's just two short lines that get slightly longer.

2022-10-17 01:17 UTC, jaj22 commented on A3A/addons/GUI/functions/SetupGUI/fn_setupHQPosDialog.sqf
> +            ["HQ Position", "Selected position cannot be in water."] call A3A_fnc_customHint;
I'll do the HQ position and server information ones, but not the confirm dialog text, because it's really bad and needs a rewrite anyway. Adding stringtable functionality there will just make it harder to replace.

2022-10-17 05:03 UTC, jaj22 commented
Changes:
- Added old fix for missing rank on save when dead.
- Fixed ammobox inventory undercover removal, probably.
- Moved joining backslashes in base paths to code.
- Changed camo[] to climate[] in templates.
- Added localization for HQ position dialog hints.
- Added localization for server information hints.
- Added new maps to name translation.

Things to do:
- Fix bug where params aren't always reset when they should be.
- Dig up and merge Bob's map texture changes (they move to a different file here, better to merge now).
- More testing.

2022-10-17 09:07 UTC, Bob-Murphy commented
init changes for map textures - already merged into unstable
https://github.com/official-antistasi-community/A3-Antistasi/pull/2452/files#diff-772a7d9b258c3c78599acd6dfe21a1d1d175ee3c5d182d0d72494e9753eb8081

2022-10-20 04:20 UTC, jaj22 commented
Turns out CUP still had large quantities of non-rifles in the rifle category, so I sorted that. Probably.

2022-10-21 02:29 UTC, jaj22 commented
Faction testing list: 
- ~~Check that all CUP factions load without errors.~~
- ~~Check that all vanilla factions load without errors.~~
- ~~Check that all GM factions load without errors.~~
- Check that all Unsung factions load without errors.
- Check that all VN factions load without errors.
- Check that all RHS factions load without errors.
- Check that all 3CBF factions load without errors.
- Check that all 3CB BAF factions load without errors.

2022-10-22 17:56 UTC, Bob-Murphy approved these changes
lgtm

2022-10-22 18:01 UTC, killerswin2 approved these changes

2022-10-22 18:20 UTC, merged