Vehicle Box restoration
official-antistasi-community/A3-Antistasi pull request #2505
Opened 2022-10-29 10:05 UTC by igorkis-scrts

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Vehicle box should check ammo/fuel/repair sources and repairs/refuels/rearms vehicles around, almost like it was before 2.5.0. This should reduce some tediousness of putting vehicles in garage and getting them.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
1. Put ammo/fuel/repair truck into garage.
2. Press "Restore nearby units" action on vehicle box.
3. Vehicles around red vehicle box should be refueled/rearmed/repaired. 

********************************************************

2022-10-29 10:25 UTC, Lazejun requested changes
Thats just an Infinite Ammo, Fuel and Spart Parts source now

2022-10-29 10:29 UTC, Bob-Murphy commented
I think that for Ammo and Repair it would be fine as it checks if there is the correct vehicle in the garage.
For fuel it's a different topic because of the fuel scarcity.

2022-10-29 10:33 UTC, igorkis-scrts commented
It seems that fuel source and current fuel scarcity game mechanic contradict each other, so I guess the only way to resolve it is to remove fuel source, so fuel trucks will just provide immense amount of fuel instead of making it infinite (btw, same mechanics could be applied to ammo and "repair" resource, but it does not exist yet).

2022-10-29 10:38 UTC, Lazejun commented
> I think that for Ammo and Repair it would be fine as it checks if there is the correct vehicle in the garage. For fuel it's a different topic because of the fuel scarcity.

We have all the Code to Save the State of the Vehicle and Return it, Ammo, Damage etc. from Garage to Saving and loading a save.

It makes it kind of pointless.

+ This adds the "Yeah hit the box" rearm meme from Pilots going 500 KPH with maximum altitude of 150 meters.
Same as Repair, Refuel by anything thats still moving/flying that is slightly Damaged or loosing fuel.

2022-10-29 10:38 UTC, HakonRydland commented
The sources are not unlimited and is handler differently between ace and vanilla

2022-10-29 10:38 UTC, Bob-Murphy commented
As mentioned in discord, I don't know from the top of my head at which stage we are in the fuel-scarcity topic.
Of course the most logical would be to have really limited fuel but that also would need the ability to only partially fill fuel tanks of vehicles and such instead only `fill` and `don't fill`.
From what I recall we are at an intermediate point where we implemented the first half of the system so people get somewhat used to the fuel scarcity and we reserve the option to implement the second step at a later point.
Hence the contradiction with the fuel source in the garage and the fuel scarcity.

2022-10-29 10:39 UTC, Bob-Murphy commented
> * This adds the "Yeah hit the box" rearm meme from Pilots going 500 KPH with maximum altitude of 150 meters.
>   Same as Repair, Refuel by anything thats still moving/flying that is slightly Damaged or loosing fuel.

Fuck, I completely forgot about that meme.

2022-10-29 10:45 UTC, igorkis-scrts commented
> The sources are not unlimited and is handled differently between ace and vanilla

But at this moment it just checks if `HR_GRG_Sources` has anything and set's boolean to true? This will be changed, I guess?

```sqf
switch _source do {
    case AmmoSource: { HR_GRG_hasAmmoSource = !((HR_GRG_Sources#0) isEqualTo []); publicVariable "HR_GRG_hasAmmoSource" };
    case FuelSource: { HR_GRG_hasFuelSource = !((HR_GRG_Sources#1) isEqualTo []); publicVariable "HR_GRG_hasFuelSource" };
    case RepairSource: { HR_GRG_hasRepairSource = !((HR_GRG_Sources#2) isEqualTo []); publicVariable "HR_GRG_hasRepairSource" };
    default { Info_1("Invalid source type: %1", _source) };
};
```

2022-10-29 10:48 UTC, igorkis-scrts commented
Also, it seems that full fuel scarcity will require to disable vanilla refuel functionality, as it will be easily exploitable by capturing fuel truck and not putting it into garage.

2022-10-29 10:58 UTC, HakonRydland commented
We don't overwrite fuel functionality we add support for them, in vanilla that means virtually infinite source, in ace the vanilla fuel system is disabled and we follow their system, I am out atm but I will find the correct way to do it for you

2022-11-01 15:18 UTC, HakonRydland commented
for fuel you can simply call `HR_GRG_fnc_refuelVehicleFromSources` with the vehicle as parameter, preferably with a delay inbetween to reduce broadcast spam, this keeps fuel preservation in place, could also write a function to allow refueling from other fuel sources around hq, but that functionality is not in place yet, and arguably is not needed/wanted.

repair never had any other conditions and we could argue the same for ammo, although ace does some shit with ammo we just dont have real support for it (CSW)

2022-11-03 04:51 UTC, HakonRydland commented
after some internal discussions i think it would be best to add a few constraints on this, mainly that vehicles are still and preferably off (need to check that vehicles that dont have an engine to turn off is considered as engine off) for repair, refuel and rearm of vehicles

2022-11-08 03:18 UTC, jaj22 commented
I don't know what sort of engine-less vehicles you're thinking of, but this note from isEngineOn suggests that idea is a no-go:
`isEngineOn returns true for static objects without an engine`

An easy but slightly strict/annoying option is to swap the side check for `isNull group _x` and change the text to specify empty vehicles. Then even Bob should be happy and we can throw it into 3.0.

2022-11-08 11:23 UTC, igorkis-scrts commented
I guess this will be needed to prevent in-air restoration for helicopters and planes (btw, Plus will retain it, as, in my opinion, it's a somewhat fun undocumented "catch the plane flyby" interaction between players).
I'm experimenting with checking `isEngineOn` in pair with simulation and config check (it seems that statics have `tankx` simulation type with `maxspeed = 0` config value), as forcing players to get out from vehicles is a bit excessive and it should be avoided if possible. If this will not work out, I guess there is no other way than `isNull group _x`.

2022-11-08 12:02 UTC, HakonRydland commented
Yes, statics and other land vehicle can retain their current functionality, but air vehicles shoul have additional restrains laid upon them.

Think `(typeof _veh isEqualTo "Air") &&`

2022-11-08 19:13 UTC, igorkis-scrts commented
more or less done

2022-11-12 06:01 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
> +    {((typeof _x isEqualTo "Air" && !(isEngineOn _x)) || !(typeof _x isEqualTo "Air"))
Shouldn't that be isKindOf?

`!(_x isKindOf "Air" && isEngineOn _x)` should work if the goal is just to prevent air vehicles rearming in mid-air.

2022-11-12 10:04 UTC, HakonRydland commented on A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
> +    {((typeof _x isEqualTo "Air" && !(isEngineOn _x)) || !(typeof _x isEqualTo "Air"))
yes it should

2022-11-12 10:10 UTC, Lazejun commented on A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
> +    {((typeof _x isEqualTo "Air" && !(isEngineOn _x)) || !(typeof _x isEqualTo "Air"))
let's just hope people don't figure out to Toggle if their engines mid flight to cheese 🧀🧀

2022-11-12 10:43 UTC, HakonRydland commented on A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
> +    {((typeof _x isEqualTo "Air" && !(isEngineOn _x)) || !(typeof _x isEqualTo "Air"))
then best check speed is slow too, like bellow 10 is probably good enough, in general probably faste check to just do that, and it makes sense to not speed by when refueling...

2022-11-16 14:42 UTC, HakonRydland commented on A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
> +    {!(_x isKindOf "Air" && speed _x > 10)
make this simply
```
{speed _x < 10
```
also the lazy evaluations dont have to be nested iirc

2022-11-16 15:05 UTC, igorkis-scrts commented on A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
> +    {!(_x isKindOf "Air" && speed _x > 10)
fixed

> also the lazy evaluations dont have to be nested iirc


They don't have to , but nested one is the fastest:
```sqf
["true  || { false  || {false}}", nil, 100000] call BIS_fnc_codePerformance;	// 0.00080 ms
["true  ||  {false} || {false} ", nil, 100000] call BIS_fnc_codePerformance;	// 0.00105 ms
["false ||   false  ||  false  ", nil, 100000] call BIS_fnc_codePerformance;	// 0.00123 ms
["true  ||   false  ||  false  ", nil, 100000] call BIS_fnc_codePerformance;	// 0.00128 ms
["false ||  {false} || {false} ", nil, 100000] call BIS_fnc_codePerformance;	// 0.00200 ms
```

2022-11-18 22:53 UTC, Lazejun approved these changes
Should be fine now, Also Merge conflict apparently

2022-11-20 20:17 UTC, igorkis-scrts commented
Conflicts have been resolved.

2022-12-07 07:41 UTC, Bob-Murphy commented
![image](https://user-images.githubusercontent.com/50651578/206117692-64d061b4-fd60-4e3e-8687-1649d1134869.png)
Looks fine and only shows the points when they apply. In this case all trucks are in the garage.

2022-12-07 07:49 UTC, merged