initial move to config based logi nodes
official-antistasi-community/A3-Antistasi pull request #2511
Opened 2022-10-30 14:23 UTC by HakonRydland

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-10-30 14:43 UTC, HakonRydland commented
john i know you did some improvements to functionally a short while ago, could you have a look and verify that nothing was lost, old files are still in so its a bit easier to check between them

2022-10-31 01:11 UTC, targetingsnake commented on A3A/addons/Logistics/Cargo/GM.hpp
> +class gm_gm_weapons_gm_launchers_gm_milan_gm_milan_launcher_tripod : TRIPLES(ADDON,Cargo,Base)
blacklisted vehicles are missing on milan, spg, and fagot

2022-11-04 18:13 UTC, HakonRydland commented on A3A/addons/Logistics/Cargo/GM.hpp
> +class gm_gm_weapons_gm_launchers_gm_milan_gm_milan_launcher_tripod : TRIPLES(ADDON,Cargo,Base)
i had forgotten to amend my tools for weapon blacklists, tool has been corrected and blacklists added back inn.

2022-11-05 16:41 UTC, killerswin2 approved these changes
If this breaks, blame Hakon. LGTM

2022-11-05 19:42 UTC, jaj22 requested changes

2022-11-05 19:42 UTC, jaj22 commented on A3A/addons/Logistics/Private/fn_load.sqf
> +private _yStart = _bbVehicle + _bbCargo - 0.1;
Lost changes from #2418, should be:
```
private _bbVehicle = (boundingBoxReal _vehicle select 0 select 1);
private _bbCargo = (boundingBoxReal _cargo select 0 select 1);
private _yStart = _bbVehicle + _bbCargo;
```

2022-11-05 19:42 UTC, jaj22 commented on A3A/addons/Logistics/Private/fn_unload.sqf
> +    private _yEnd = _bbv + _bbc - 0.1;
Lost changes from #2418. Was changed to:
```
    private _bbv = (boundingBoxReal _vehicle select 0 select 1);
    private _bbc = (boundingBoxReal _cargo select 0 select 1);
    private _yEnd = _bbv + _bbc;
```
The original code with boundingCenter looks correct, but Arma seems to recenter the bounding box on loading (at least for vehicles), such that the X and Y components of getPosATL are the same as _veh getPosWorld [0,0,0]. This leaves boundingCenter as a weird orphan, causing an incorrect offset where it's non-zero. See the vanilla HEMTT for an extreme example.

I'm not sure Arma does this for every model. I vaguely recall boundingCenter still being meaningful for buildings.

I should probably have kept the -0.1 though, just in case the bounding box of the vehicle is actually tight.

2022-11-07 05:19 UTC, jaj22 commented on A3A/addons/Logistics/Private/fn_tryLoad.sqf
> +private _vehicles = (nearestObjects [_cargo,["Car","Ship"], 10]) - [_cargo];
Wasn't there a change here recently to allow loading into some helis? Can't remember which modset it was implemented for. @Lazejun would know.

2022-11-07 05:21 UTC, Lazejun commented on A3A/addons/Logistics/Private/fn_tryLoad.sqf
> +private _vehicles = (nearestObjects [_cargo,["Car","Ship"], 10]) - [_cargo];
Yes unsung,
We also lost Tank

2022-11-07 20:51 UTC, jaj22 commented on A3A/addons/Logistics/Private/fn_canLoad.sqf
> +)) exitWith {-6}; //conscious man
Bringing back vanilla unconscious loading? Does this actually work?

2022-11-07 20:56 UTC, HakonRydland commented on A3A/addons/Logistics/Private/fn_canLoad.sqf
> +)) exitWith {-6}; //conscious man
it is still a thing and works for antistasi medical, although not grate (not it was never removed in the first place, see logistics_canLoad)

2022-11-08 06:26 UTC, jaj22 requested changes

2022-11-08 06:26 UTC, jaj22 commented on A3A/addons/Logistics/Dev/fn_convertCargoToNew.sqf
> +        ["", endl + "    isWeapon = 1;" + endl + "    blackList[] = {" + _blackListText + "}"] select (-1 != _weaponsIndex),
Apparently this needs to add the trailing semicolon.

2022-11-08 06:26 UTC, jaj22 commented on A3A/addons/Logistics/Cargo/GM.hpp
> +    blackList[] = {"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_kat1_452_container","\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_kat1_451_container","\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm
Tested locally and it's breaking on every blacklist entry: Turns out Arma config only cares about the semicolons that SQF doesn't care about.

2022-11-08 07:05 UTC, jaj22 commented
Fixed the semicolons and what looks like a porting bug in the unload function.

Tested some basic functionality on DS but not blacklists yet, as vanilla doesn't have any easy blacklist tests. I noticed it's not deleting loot crates when garaging a vehicle but it looks like that's not related to logistics functionality.

2022-11-08 18:39 UTC, jaj22 approved these changes
Should be good now.

2022-11-08 20:17 UTC, merged