Regero Map Port 2, We Fixed the ROADS
official-antistasi-community/A3-Antistasi pull request #2519
Opened 2022-11-02 04:32 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
 Added support for the Antistasi Mission on the Kingdom of Regero map by IceBreakr https://steamcommunity.com/sharedfiles/filedetails/?id=2278254320
Added Placeholder pictures for the port until better ones can be acquired. (<- that's for bob to get)
A redo of  #2195, this time Killer now knows what happened with the roads!

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-11-03 11:29 UTC, Bob-Murphy requested changes
You added a description.ext for Regero, but that contains the Chernarus Summer information.
You changed the Chernarus Summer description.ext over to Regero text.

Please reset the Chernarus Summer file and adapt the Regero one.

Please remove adding yourself to the debug console. I can add you, but that's the wrong way.

2023-07-22 03:57 UTC, jaj22 commented
Browsed this for a while. Main issue I see is that the vehicle places tend to be placed as if they were for a static park. These days they're used for spawning land QRFs and the land-vehicle portion of attacks, so they need to have reasonably straightforward access to a road (note that the direction of the marker matters). I was gonna list the bad ones, but that seemed to be a common trend, so give it a pass and then I'll re-check.

2023-07-22 03:59 UTC, killerswin2 commented
Yeah, this was designed back in fall of 2021

2023-07-22 03:59 UTC, killerswin2 commented
so, it does make sense that those places are static, given the context of the port

2023-07-22 04:06 UTC, jaj22 commented
It's not about making sense. It's how the mechanics work. Every vehicle placement is assumed to be accessible to a road, and if that's not obeyed then you'd end up with vehicles humping H-barriers and flying a kilometer into the air.

2023-07-22 04:08 UTC, killerswin2 commented
I wasn't condoning the liberal use of the static markers, no one ever told that they were wrong. But now you have brought it to my attention, so I will fix them.

2023-11-19 16:12 UTC, Bob-Murphy commented
@killerswin2 I went through all the things. Please give it a spin

2023-11-19 17:05 UTC, jaj22 commented
@Bob-Murphy Did you redo the vehicle places?

2023-11-19 17:08 UTC, Bob-Murphy commented
yes

2023-11-19 22:02 UTC, killerswin2 commented on A3A/addons/maps/mapInfo.hpp
> +    #include "Antistasi_regero.regero\mapInfo.hpp"
That's a path. Will need to rename the folder.

2023-11-19 22:08 UTC, killerswin2 commented on A3A/addons/maps/mapInfo.hpp
> +    #include "Antistasi_regero.regero\mapInfo.hpp"
done

2023-11-19 22:09 UTC, killerswin2 commented
Good @Bob-Murphy

2023-11-19 22:10 UTC, Bob-Murphy commented on A3A/addons/maps/mapInfo.hpp
> +    #include "Antistasi_regero.regero\mapInfo.hpp"
I renamed the folder on my end but it seems like Git was like `naaah bruv, I ain't carry the change over`.
Cheers

2023-11-19 23:33 UTC, killerswin2 commented on A3A/addons/maps/mapInfo.hpp
> +    #include "Antistasi_regero.regero\mapInfo.hpp"
I did it for you, just pull the changes. If you're on windows it might not show up right.

2024-04-13 02:45 UTC, merged