added python bytecode-cache folder to gitignore
official-antistasi-community/A3-Antistasi pull request #2527
Opened 2022-11-05 15:34 UTC by Giddius

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:

For future tooling in python, I added the bytecode-stuff to the gitignore.

This does not change or break anything, as python bytecode should never be commited anyway and not other stuff uses either a folder named __pycache__ or files ending in .pyd, .pyc or .pyo.

    

### Please specify which Issue this PR Resolves.
None

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?
3. [x] Not necessary no changes to anything code-related

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

2022-11-05 15:39 UTC, killerswin2 requested changes

2022-11-05 15:39 UTC, killerswin2 commented on .gitignore
> +*.py[cod]
add *.pyc, and file should end with a new line

2022-11-05 15:50 UTC, Giddius commented on .gitignore
> +*.py[cod]
`*.py[cod]`

includes `.pyc`

adding newline now

2022-11-05 15:52 UTC, Giddius commented on .gitignore
> +*.py[cod]
newline should be added, but not sure if it gets stripped by git, after commiting.

2022-11-05 16:23 UTC, killerswin2 approved these changes

2022-11-06 13:42 UTC, HakonRydland approved these changes

2022-11-06 17:26 UTC, merged