Logistics items
official-antistasi-community/A3-Antistasi pull request #2542
Opened 2022-11-13 04:44 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:

DON'T MERGE THIS BEFORE THE BUY ITEM GUI (<- For Bob or Frost)

    This is part 2 buy item gui. It adds pack-able objects and more objects to buy.
    Repair stations can be bought for repairing.
    Vehicle ammo crates can be bought for rearming.
    Tired of having to load out your car with medical items, well now you don't have to. You can buy a medical box full of medical items, depending on whether or ace is on.
    Medical tents were added and the main motivation for packable objects. Place a medical tent down and start healing your allies in a mass cas.
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-11-13 04:46 UTC, killerswin2 commented
![overview](https://user-images.githubusercontent.com/8095345/201506193-a83f6db0-1118-4b5b-a8c4-1e6a4992e5ab.png)

2023-02-15 11:12 UTC, Bob-Murphy commented
@killerswin2 from what I see this is good to mess with and review, right?

2023-02-15 13:52 UTC, killerswin2 commented
@Bob-Murphy yes

2023-03-11 19:05 UTC, Bob-Murphy commented
Unpacking a large asset just plops it somewhere, not checking the environment

2023-03-11 19:08 UTC, Bob-Murphy commented
You should not be able to carry around the massive thingies once they are unpacked
- medical tent
- repair station

2023-03-11 19:17 UTC, Bob-Murphy commented
needs implementation into templates so we can set other assets for example for SOG PF

2023-03-15 20:13 UTC, killerswin2 commented
> You should not be able to carry around the massive thingies once they are unpacked
> 
>     * medical tent
> 
>     * repair station

That is allowed because packing and unpacking again to move the objects two more meters is detrimental to players.

2023-03-16 21:15 UTC, Lazejun requested changes
Most seems ok, Stuff works except Packing, see Comment.

We probably have to talk about the Prices so that it's not constantly available/useable early Game

2023-03-16 21:15 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
> +["vehicleFuelTank", ["B_Slingload_01_Fuel_F", 500]] call _fnc_saveToTemplate;
Fuel is fine, you constantly have Access to it/ You dont have to drive far to get it anyway.

I dont think 500 is a good price for the rest of the Items, we either increase the Prices or make them accessible at higher Warlevels


Repair, well with Vanilla its unlimited Repairs anywhere anytime, almost instantly, can lead to massive cheese if you carry it around everywhere and repair in Combat, With Ace it's not as Useful as you need to Manually repair/Perform the Full Repair (Depending on Settings etc.)

Ammo same as Above, Instant Rearm with Vanilla, sort of Infinite Ammo without reloads for Vehicles with Large Magazines that don't reload after one shot.

With Ace it's a lot more harmless and less Cheesy but any Ammo Vehicle allows Editing of Pylons so thats back on the Menu for currently 500€.


Medical Tent seems ok, with Vanilla you can just full heal yourself, with Ace and if its enabled via Settings you can use it for Medical Training boost to get downed people up easier/Fix the Medics.
Also it being big, clumsy and not good cover makes the current price pretty reasonable.

2023-03-17 16:06 UTC, killerswin2 commented on A3A/addons/logistics/Cargo/Vanilla.hpp
> +    size = 4;
increased the size too 5

2023-03-22 18:21 UTC, Lazejun approved these changes

2023-03-22 19:43 UTC, Bob-Murphy commented
Please add support which enables us to not have any of the added options for cases in which the modsets/templates either do not have matching assets and the vanilla ones can not be utilized.

2023-03-22 20:38 UTC, killerswin2 commented
already implemented in the code. If one of the templates defines it as "" then it is skip as that's not a valid cfgVechicle class.

2023-03-22 22:44 UTC, Bob-Murphy requested changes
Sorry, found more small shit to complain about :D

2023-03-22 22:44 UTC, Bob-Murphy commented on A3A/addons/garage/Public/fn_callbackHandler.sqf
> +                if (_lastTimePurchase > time) exitwith {["Item Purchase", format ["You already bought one, wait %1 seconds before you can buy another.", ceil (_lastTimePurchase - time)]] call A3A_fnc
Localize please.

2023-03-22 22:44 UTC, Bob-Murphy commented on A3A/addons/garage/Public/fn_callbackHandler.sqf
> +                    if (_insufficientFunds) exitwith {["Item Purchase", "You can't afford this Item."] call A3A_fnc_customHint};
Localize please.

2023-03-22 22:44 UTC, Bob-Murphy commented on A3A/addons/logistics/Private/fn_unpackObject.sqf
> +    ["Packing Objects", "refunding money to do error"] call A3A_fnc_customHint;
Localize please.

2023-03-22 22:44 UTC, Bob-Murphy commented on A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
>  if (_lastTimePurchase > time) exitwith {["Item Purchase", format ["You already bought one, wait %1 seconds before you can buy another.", ceil (_lastTimePurchase - time)]] call A3A_fnc_customHint;};
Localize please.

2023-03-22 22:44 UTC, Bob-Murphy commented on A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
> +    if (_insufficientFunds) exitwith {["Item Purchase", "You can't afford this Item."] call A3A_fnc_customHint};
Localize please.

2023-03-22 22:45 UTC, Bob-Murphy commented on A3A/addons/logistics/Private/fn_unpackObject.sqf
> +    ["Packing Objects", "refunding money to do error"] call A3A_fnc_customHint;
also, what?
`refunding money to do error`

2023-03-22 22:51 UTC, Bob-Murphy commented on A3A/addons/logistics/Private/fn_unpackObject.sqf
> +    ["Packing Objects", "refunding money to do error"] call A3A_fnc_customHint;
Oooooh, do you mean `due to error`?

2023-03-22 23:28 UTC, killerswin2 commented on A3A/addons/logistics/Private/fn_unpackObject.sqf
> +    ["Packing Objects", "refunding money to do error"] call A3A_fnc_customHint;
yes

2023-03-23 00:32 UTC, merged