More vehicles for rebels (BUY_ITEM_VEHICLE PART 3)
official-antistasi-community/A3-Antistasi pull request #2546
Opened 2022-11-13 22:52 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    This is part 3 of the buy item/vehicle gui. This time we expand the rebel defines to be array's. Mainly everything that was touched dealt with how the hash map only returned non array data, now everything works with arrays (or should work now).
    This allows third parties to have multiple vehicles instead of one in the rebel factions.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-01-21 19:56 UTC, killerswin2 commented
add check for cfg vehicles for classnames

2023-03-23 00:51 UTC, killerswin2 commented on A3A/addons/core/functions/Dialogs/fn_buyVehicle.sqf
> +	private _vehicleBasic = selectRandom (FactionGet(reb,"vehicleBasic"));
encase your wondering why this was done, remember that we used to have a param to allow the buy item.

2023-03-23 01:03 UTC, killerswin2 commented
![image](https://user-images.githubusercontent.com/8095345/227072355-b42c2f2e-c70b-468e-837d-08e6efb09b6b.png)

2023-03-23 01:05 UTC, killerswin2 commented
![image](https://user-images.githubusercontent.com/8095345/227072552-67bad43d-4838-4785-a213-620f69641258.png)

2023-03-25 19:17 UTC, jaj22 approved these changes

2023-03-25 19:17 UTC, jaj22 commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> +    + Reb("staticMGs") + Reb("staticAT") + Reb("staticAA") + Reb("staticMortar");
+ Reb("vehiclesAA") - [""]

2023-03-25 19:18 UTC, jaj22 requested changes
Whoops wrong button.

2023-03-25 20:56 UTC, killerswin2 commented on A3A/addons/core/functions/Dialogs/fn_buyVehicle.sqf
yeah, this was done back when we still used the old gui

2023-03-25 20:59 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +};
yes

2023-03-25 20:59 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +};
But It is a good check to have

2023-03-25 22:20 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +	if !(_vehType in _vehicleResourceCosts or _vehType in _rebelVehicleCosts) then { continue };
I need some explanation on what you mean here.

2023-03-25 23:31 UTC, killerswin2 commented
Removed all the heavy stuff.

2023-03-26 13:28 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf
> +["vehiclesHeavyArmed", []] call _fnc_saveToTemplate;
Might want to clean up the Examples.

2023-03-26 13:36 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
> +["vehiclesAA", ["UK3CB_TKM_I_V3S_Zu23", "UK3CB_NAP_I_Hilux_Zu23_Front", "UK3CB_MEI_I_Hilux_Vulcan_Front"]] call _fnc_saveToTemplate;
This is currently pointless as these vehicles are not Added to the Buyable list, but its a good idea.

For the love of god Dont use the MEI Vehicles, use the FIA variants if there is nothing else.

The Hiluxes should be a bit more expensive as they can move a lot quicker than the Trucks but have a limited firing Arc.

The Vulcan variant is very questionable, Full Automatic 1100 round magazine 360° Coverage but its still a soft Hilux, even with added Armor panels.

2023-03-26 13:37 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf
> +["vehiclesBoat", ["UK3CB_I_G_Fishing_Boat_SPG9"]] call _fnc_saveToTemplate;
There are Multiple Boat variants we could include but this boat is currently not buyable.

It never moved to the Buymenu, it was always a Scrollwheel option at seaports but got lost in Previous PRs.

2023-03-26 13:44 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +  _vehicleAA = ["I_Tura_Truck_02_aa_lxWS"];
The = can be changed for an Append so these Vehicles would be added to the Arrays.

2023-03-31 19:35 UTC, Bob-Murphy approved these changes
lgtm and works

2023-03-31 19:36 UTC, Bob-Murphy commented
Just to have it mentioned, I already am thinking about some price adjustments and maybe some asset replacements, but this calls can be made after some thorough testing.

2023-03-31 19:54 UTC, killerswin2 commented
that's my plan

2023-03-31 21:09 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["staticMortars", ["CUP_C_AN2_CIV", "CUP_C_C47_CIV"]] call _fnc_saveToTemplate;
I guess this was supposed to be vehiclesCivPlane?

2023-03-31 21:10 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesAA", ["CUP_I_Ural_ZU23_NAPA", "CUP_I_Hilux_zu23_NAPA"]] call _fnc_saveToTemplate;    // Add back as player-only vehicle: "CUP_I_Hilux_zu23_NAPA"
Can remove the comment here now.

2023-03-31 21:10 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
> +["vehiclesAA", ["CUP_I_Ural_ZU23_NAPA"]] call _fnc_saveToTemplate;             // Add back as player-only vehicle: "CUP_I_Hilux_zu23_NAPA"
No zu23 Hilux on this one?

2023-03-31 21:15 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf
> +["vehiclesCivHeli", [""]] call _fnc_saveToTemplate;
Should probably be `[]` now?

2023-03-31 21:18 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +  _vehicleAA append ["I_Tura_Truck_02_aa_lxWS"];
Doesn't work because the check in addFIAsquadHC is for `[""]`, so it'll decide this is a template with a valid AA truck, and select the first element, which is `""`.

Best way to handle this is use the empty array as the signifier (changing addFIAsquadHC and line 16 here to match). Then you can add or append here and it doesn't matter.

2023-03-31 21:20 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +  _staticAA append ["I_Tura_ZU23_lxWS"];
I don't think this is desired behaviour, because the AA launcher is a pain in the arse and also a fairly weird weapon for rebels to have. Either replace with the zu23 or at least put it first in the array.

2023-03-31 21:21 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
This one didn't get the append treatment but needs changes for the empty array convention.

2023-03-31 21:25 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_mortarDrill.sqf
> +{if (_x getVariable ["typeOfSoldier",""] == "staticMortars") then {_morty = _x} else {_helperX = _x}} forEach _this;
Bad find/replace. This is the old typeOfSoldier code and the string is still `"StaticMortar"`.

2023-03-31 21:25 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_mortyAI.sqf
> +_morty0 setVariable ["typeOfSoldier", if (_typeX in FactionGet(reb,"staticMGs")) then { "StaticGunner" } else { "staticMortars" }];
Bad find/replace on the third change. This is the old typeOfSoldier code and the string is still "StaticMortar".

2023-03-31 21:26 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_staticMGDrill.sqf
> +{if (_x getVariable ["typeOfSoldier",""] == "staticMortars") then {_gunner = _x;_isMortar = true} else {_helperX = _x}} forEach _this;
Bad find/replace again.

2023-03-31 21:27 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_typeOfSoldier.sqf
Bad find/replace in whole file. Ok, I guess you could replace all these but it's not a good idea.

2023-03-31 21:29 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +_statics = _statics select { !(_x isKindOf "staticMortars") };           // don't bother with mortars yet
Nope, that's a classname inheritance check. Must remain as `"StaticMortar"`

2023-03-31 21:29 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
> +			if !(_typeX isKindOf "staticMortars") then {
Classname inheritance check again.

2023-03-31 21:30 UTC, jaj22 commented on A3A/addons/core/functions/EventHandler/fn_enemyUnitKilledEH.sqf
> +    if (vehicle _killer isKindOf "staticMortars") then
Classname inheritance check.

2023-03-31 21:32 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf
> +        if (FactionGet(reb,"vehiclesAA") isEqualTo [""]) exitWith {_mounts pushBack [(FactionGet(reb,"staticAA")) # 0,-1,[[1],[],[]]]; (FactionGet(reb,"vehiclesTruck")) # 0};
Change the vehiclesAA check to empty array.

2023-03-31 21:35 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_dismissSquad.sqf
> +					case _assemblesTo in FactionGet(reb,"staticMortars"): {_resourcesFIA = _resourcesFIA + ([_assemblesTo] call A3A_fnc_vehiclePrice)/2};
Does this work? Original code would have had enclosing brackets from the macro so I suspect this is a syntax error.

2023-03-31 21:38 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_vehStats.sqf
> +if (!(isNull(_groupX getVariable ["mortarsX",objNull])) or ({_x call A3A_fnc_typeOfSoldier == "staticMortars"} count _unitsX > 0)) then
typeOfSoldier stuff, should remain "StaticMortar".

2023-03-31 21:38 UTC, jaj22 commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> +setVar("vehiclesAA", OccAndInv("vehiclesAA") + Reb("vehiclesAA") - [""]);
Can remove the latter element once the standard has changed to empty array.

2023-03-31 21:40 UTC, jaj22 commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> ++ Reb("vehiclesPlane");
Reb("vehiclesCivPlane") should probably go in here too, although I'm not sure what it's used for. Probably something dumb.

2023-03-31 21:41 UTC, jaj22 commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> +    + Reb("vehiclesHelis") + Reb("vehiclesPlane") + Reb("vehiclesMedical") + Reb("vehiclesAA") - [""];
Latter element can go once fixed.

2023-03-31 21:44 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +{ [_rebelVehicleCosts, _x, 10000] call _fnc_setPriceIfValid } forEach FactionGet(reb, "vehiclesPlane") + FactionGet(reb, "vehiclesCivPlane");
Seems far too high to me. What's the utility of these things that makes them worth 10k?

2023-03-31 21:45 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +	if !(_vehType in _vehicleResourceCosts or _vehType in _rebelVehicleCosts) then { continue };
Minor optimization. Make an array with `keys _vehicleResourceCosts + keys _rebelVehicleCosts`. Doesn't much matter.

2023-03-31 21:47 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
>  			if (_attr == "threat") then { _groundVehicleThreat set [_vehType, _val] };
Old bug, should have been exitWith like the others. Works as-is but suboptimal.

2023-03-31 21:48 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_getGroupInfo.sqf
> +if (!(isNull(_group getVariable ["mortarsX",objNull])) or ({_x call A3A_fnc_typeOfSoldier == "staticMortars"} count _units > 0)) then {
typeOfSoldier, should remain "StaticMortar".

2023-03-31 21:48 UTC, jaj22 commented on changelog.rst
> +* staticMGs assemble / dissassemble.
Bad find/replace.

2023-03-31 21:51 UTC, jaj22 requested changes
Forgot to start review. Anyway, looks to be conceptually sound but there are quite a few bugs to fix.

2023-03-31 21:57 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +{ [_rebelVehicleCosts, _x, 10000] call _fnc_setPriceIfValid } forEach FactionGet(reb, "vehiclesPlane") + FactionGet(reb, "vehiclesCivPlane");
Faster than a helicopter, but I'll make them the same price

2023-03-31 22:03 UTC, jaj22 commented
Could go with 5k for the civ plane and 1k for the non-civ plane. I'd like to see people trying to use those things :P

2023-03-31 22:05 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/3CB/3CB_Reb_Vehicle_Attributes.sqf
> +    ["UK3CB_C_AC500", ["rebCost", 7000]],
Probably needs an update.

2023-03-31 22:05 UTC, killerswin2 commented
You can't spawn in non-civ as for vn it is a jet

2023-03-31 22:06 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf
> +["vehiclesCivPlane", ["C_Plane_Civil_01_F"]] call _fnc_saveToTemplate;
This feels a bit "hidden" in here. Would rather move it into the templates selectively.

2023-03-31 22:06 UTC, killerswin2 commented
Do you want non-civ planes to be bought?

2023-03-31 22:08 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_attackDrillAI.sqf
> +		if (_result == "staticMortars") then
Another typeOfSoldier, should remain "StaticMortar".

2023-03-31 22:09 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_mortarDrill.sqf
> +{if (_x getVariable ["typeOfSoldier",""] == "staticMortar") then {_morty = _x} else {_helperX = _x}} forEach _this;
keep the original case, capital S.

2023-03-31 22:09 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_mortyAI.sqf
> +_morty0 setVariable ["typeOfSoldier", if (_typeX in FactionGet(reb,"staticMGs")) then { "StaticGunner" } else { "staticMortar" }];
Keep the original case on "StaticMortar".

2023-03-31 22:10 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_staticMGDrill.sqf
> +{if (_x getVariable ["typeOfSoldier",""] == "staticMortar") then {_gunner = _x;_isMortar = true} else {_helperX = _x}} forEach _this;
Keep the original case.

2023-03-31 22:10 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_typeOfSoldier.sqf
Keep the original case of "StaticMortar" in this file.

2023-03-31 22:11 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
> +_statics = _statics select { !(_x isKindOf "staticMortar") };           // don't bother with mortars yet
casing.

2023-03-31 22:11 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf
> +			if !(_typeX isKindOf "staticMortar") then {
casing.

2023-03-31 22:11 UTC, jaj22 commented on A3A/addons/core/functions/EventHandler/fn_enemyUnitKilledEH.sqf
> +    if (vehicle _killer isKindOf "staticMortar") then
Casing.

2023-03-31 22:13 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_vehStats.sqf
> +if (!(isNull(_groupX getVariable ["mortarsX",objNull])) or ({_x call A3A_fnc_typeOfSoldier == "staticMortar"} count _unitsX > 0)) then
casing.

2023-03-31 22:15 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_getGroupInfo.sqf
> +if (!(isNull(_group getVariable ["mortarsX",objNull])) or ({_x call A3A_fnc_typeOfSoldier == "staticMortar"} count _units > 0)) then {
Casing.

2023-03-31 22:15 UTC, jaj22 commented on changelog.rst
> +* staticMG assemble / dissassemble.
Casing.

2023-03-31 22:20 UTC, jaj22 commented
> Do you want non-civ planes to be bought?

Seems harmless enough to me as long as they don't have pylons. I guess if some of them do have pylons then we'd need to specify that they're AI-only, so that's trickier.

2023-03-31 22:24 UTC, killerswin2 commented
okay, it is done. They can be bought

2023-03-31 22:25 UTC, jaj22 approved these changes
Looks correct to me now. Can debate plane prices later.

2023-04-01 10:52 UTC, merged