UPSMON REFACTOR
official-antistasi-community/A3-Antistasi pull request #2548
Opened 2022-11-15 03:27 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
This was done because start up for UPSMON is slow.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2022-11-15 03:39 UTC, jaj22 commented
Was anything changed in here aside from what's listed in information?

2022-11-15 03:45 UTC, killerswin2 commented
Besides making a cfgfunction, not really. The only stuff I touched was renaming function global so that they called the right code. I mainly convert that script folder into a addon and removed all the execvm's and replaced them with spawns. I did kill UPSMON weird function compilation code because the bis init_functions does that better then UPSMON 15 year old code.

2022-11-15 04:24 UTC, jaj22 requested changes
Seems legit generally. Marked some minor errors.

Problem will be that it's quite non-obvious whether this stuff breaks (barring RPT errors), as we use it very much as a black box and no-one notices when AI stuff is even more busted than usual. Would still be inclined to merge for 3.1 although I suspect it doesn't make much difference after init. Spawn vs execVM saves a bit, but the unit spawning costs are probably orders of magnitude larger.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/UPSMON/Functions/INIT/fn_Init_UPSMON.sqf
> +UPSMON_fnc_TRACKednpcs = [];
Case screwup.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/UPSMON/Functions/INIT/fn_UPSMON.sqf
> +if ("NOSMOKE" in _UCthis) then {_grp setvariable ["UPSMON_fnc_NOSMOKE",true]};
Not a function.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/UPSMON/Functions/INIT/fn_UPSMON.sqf
> +_grp setvariable ["UPSMON_fnc_Shareinfos",_shareinfos];
Not a function.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/UPSMON/Functions/INIT/fn_UPSMON.sqf
> +_grp setvariable ["UPSMON_fnc_Nowp",_nowpType];
Not a function.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/UPSMON/Functions/INIT/fn_UPSMON.sqf
> +_grp setvariable ["UPSMON_fnc_Nowp",_nowpType];
Not a function.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/UPSMON/Functions/UPSMON_REINFORCEMENT/fn_GetReinfPos.sqf
> +					_grp setvariable ["UPSMON_fnc_Nowp",0];
Not a function.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/core/Scripts/UPSMON/Get_pos/UPSMON_pos_init.sqf
> -/*
The documentation from this file should probably go into UPSMON_fnc_pos.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf
> +		_nul=[_veh] spawn UPSMON_fnc_artillery_add;;//TODO need delete UPSMON link
Bonus semicolon. Don't think it matters but whatever.

2022-11-15 04:24 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_createSDKgarrisonsTemp.sqf
> +        _nul = [leader _groupX, _markerX, "SAFE","SPAWNED","NOVEH2","NOFOLLOW"] spawn UPSMON;//TODO need delete UPSMON link
should be UPSMON_fnc_UPSMON

2022-12-26 04:18 UTC, killerswin2 commented
test 1: PR 2548
fn_initServer: 814.8271ms
fn_Init_UPSMON: 806.1371ms

test 2: BASE UNSTABLE
fn_initServer: 929.2622ms
init_UPSMON: 926.1029ms

test 3: PR 2548 RHS
fn_initServer: 1969.1221ms
fn_Init_UPSMON: 1969.0442ms

test 4: BASE UNSTABLE RHS
fn_initServer: 1990.2078ms
init_UPSMON: 1987.0305ms

test 5 PR 2548 RHS after mine fix
fn_initServer: 0.9241ms
fn_Init_UPSMON: 0.8559ms

2022-12-26 04:19 UTC, killerswin2 commented
I'm going to need to have a test of this on main servers one day, but I think I finally got the init times to a low level.

2023-01-07 23:32 UTC, Bob-Murphy approved these changes
changes look consistent - found no typos
this review does not guarantee functionality

2023-01-08 04:17 UTC, jaj22 approved these changes
Ok, I'm not going to do another 1hr pass on this, and it's conceptually sound. Good enough for testing at least. Remind me to do a garrison functionality check before we release.

2023-01-08 12:09 UTC, merged