🗎 Leader Intel Search Fixes
official-antistasi-community/A3-Antistasi pull request #2551
Opened 2022-11-16 16:28 UTC by igorkis-scrts

# What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
For some reason players have a "Search for Intel" action on very alive and conscious enemy leaders which does not makes sense at all. Also, there are some exploits that allows to  search intel multiple times (I don't remember exact steps to reproduce as it was fixed in Antistasi Plus for about an year, but it seems it was tied to changing conscious/unconscious state of leader by wounding and reviving him).
This PR fixes both issues.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
1. Stay close to enemy SL with intel while being, for example, undercovered. "Search for Intel" action prompt will not appear.
2. Wound him until he will be unconscious.  "Search for Intel" action prompt should appear.
3. Perform intel search action. No additional "Search for Intel" actions will not appear as it already done on this particular SL.

2022-11-16 17:43 UTC, killerswin2 commented
You should be able to search while alive

2022-11-16 17:43 UTC, killerswin2 commented
That wasn't a bug

2022-11-16 17:46 UTC, killerswin2 requested changes

2022-11-16 17:46 UTC, killerswin2 commented on A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
> +_caller setVariable ["intelSearchDone", false];
Changes need to be broadcasted

2022-11-16 17:46 UTC, killerswin2 commented on A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
> +    _squadLeader setVariable ["intelSearchDone", true];
Broadcast the set variable

2022-11-16 17:46 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +            "!([_target] call A3A_fnc_canFight) && !(_target getVariable ['intelSearchDone', false]) && isPlayer _this",
Remove canFight condition

2022-11-16 17:54 UTC, jaj22 commented
I figured this out after writing a couple of paragraphs, but the actual bug is that you can search pre-surrender, for example when undercover. Pickpocketing an enemy leader while undercover would be neat but it'd need a large failure + undercover break chance. Maybe later.

The canFight check is fair enough (and should go into 3.0) but the other stuff is broken:
1. The _caller setVariables appear to be pointless.
2. The _squadLeader setVariable isn't global, so the bug is still exploitable with multiple players.

The exploit there is caused by the Intel_Small flagAction being re-added in unconsciousAAF, which isn't an easy fix as the flagAction usage is terrible. Maybe best for the moment to just use a global setVariable.

There's an additional exploit here where multiple players can search simultaneously (easier than it sounds because the remoteExec removeAction can be slow on a DS). Not dealing with that one yet though.

2022-11-17 14:46 UTC, igorkis-scrts commented
updated

2022-11-18 17:21 UTC, jaj22 commented on A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
> +    _caller setVariable ["intelSearchDone", nil];
Wait, I think I get it now. Was this and the line 22 one supposed to be setting the variable on the target, not the caller?

2022-11-18 17:26 UTC, igorkis-scrts commented on A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
> +    _caller setVariable ["intelSearchDone", nil];
Yeah, it's supposed to use `_squadLeader`. I guess it needs to be set only in the end after intel search is done.

2022-11-18 17:33 UTC, jaj22 commented on A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
> +    _caller setVariable ["intelSearchDone", nil];
Well, the advantage of setting intelSearchDone globally on trigger (and setting it to nil globally on cancel) would be that you no longer need to add and remove the action. Lines 13, 74, 90 and 94 can all go.

2022-11-25 05:26 UTC, jaj22 approved these changes
Looks good now.

2022-11-27 20:34 UTC, merged