version update and preliminary changelog for 3.0.0
official-antistasi-community/A3-Antistasi pull request #2567
Opened 2022-12-01 04:02 UTC by Bob-Murphy

### What have you changed and why?
- Changed version and added preliminary changelog for 3.0.0 release
- added 2.5.4 changelog which was prior only merged onto master
- added 2.5.5 changelog which was prior only merged onto master   

### What should the reviewers do?
- Check and complete the additional information of the Major changes
- Check for completion
- Check for typos
- Check for unnecessary information

2022-12-01 04:59 UTC, jaj22 commented
Provisional chunk for the attack/support rework. Skips most of the underlying changes, concentrating on stuff visible to players:
```
.. rubric:: Complete rework of the attack & support system
   * Enemy factions are now resource-limited:
      - Each faction has separate pools for attack and defence resources.
      - Any vehicle or unit spawned and/or destroyed has a cost related to their capability.
      - Resource income is dependent on war tier, aggro, active player count and difficulty.
      - Attack vs defence and occupant vs invader resource balances can be adjusted separately. 
      - Support system makes decisions based on available resources and location value.
      - Flag capture counterattacks are no longer automatic, instead depending on location and resources.
   * Vehicle selection improvements:
      - More gradual scaling of vehicle quality.
      - More ground and fewer air vehicles used, especially for factions with weak air options.
      - Proportions of transport and support vehicles are more controlled.
      - Punishments and HQ attacks may now include some ground vehicles.
   * Attack/support behaviour improvements:
      - Paratroopers (usually) drop further away and pull their chutes higher.
      - Transport helis land further from the target area.
      - Attack helis are less inclined to suicide into zu-23s.
      - Ground vehicle travel times reduced and infantry offload reliability improved.
      - CAS rewritten for reliability and fairness.
   * Attack target selection rewritten.
      - Enemies can now attack rebel targets outside mission distance at reduced probability.
   * Enemy HQ knowledge is now persistent:
      - Enemies may gain knowledge of HQ when supports are called nearby, or from traitor missions.
      - Once enemies are aware of the HQ, an HQ attack may be launched instead of a normal major attack.
      - Moving HQ more than 1km away will reset the HQ knowledge.
```

2022-12-01 17:53 UTC, targetingsnake requested changes

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. admonition:: Major
indents are missing for points under admonition, causes an error of sphinx in compilation, would add one indent to all rubrics till admonition 'Minor'

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. admonition:: Minor
missing empty line beneath

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. admonition:: Template updates
missing empty line beneath

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. admonition:: Map oupdates
missing empty line beneath

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. admonition:: Groundwork
missing empty line beneath

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. admonition:: Bugfixes
missing empty line beneath

2022-12-01 17:53 UTC, targetingsnake commented on changelog.rst
> +.. rubric:: Refactor
does this rubric belongs to any admunition?

2022-12-01 18:14 UTC, HakonRydland requested changes

2022-12-01 18:14 UTC, HakonRydland commented on changelog.rst
> +   * Added 3rd party supports
Added support for 3rd party mods to extend Antistasi

2022-12-01 18:14 UTC, HakonRydland commented on changelog.rst
> +   * :issue:`2356` Added buy menu vehicle render
Part of the buy menu point mentioned previously

2022-12-01 18:14 UTC, HakonRydland commented on changelog.rst
> +   * Basically every template was touched up or overhauled :issue:`2181`, :issue:`2276`, :issue:`2277`, :issue:`2278`, :issue:`2302`, :issue:`2316`, :issue:`2333`, :issue:`2467`, :issue:`2475`
Drop the basically

2022-12-01 18:14 UTC, HakonRydland commented on changelog.rst
> +   * :issue:`2047` Moved templates into a separate addon
Incorrect, templates are still in core

2022-12-01 19:15 UTC, Bob-Murphy commented on changelog.rst
> +.. admonition:: Major
solved

2022-12-01 19:16 UTC, Bob-Murphy commented on changelog.rst
> +.. admonition:: Minor
solved

2022-12-01 19:16 UTC, Bob-Murphy commented on changelog.rst
> +.. admonition:: Template updates
solved

2022-12-01 19:16 UTC, Bob-Murphy commented on changelog.rst
> +.. admonition:: Map oupdates
solved

2022-12-01 19:16 UTC, Bob-Murphy commented on changelog.rst
> +.. admonition:: Groundwork
solved

2022-12-01 19:16 UTC, Bob-Murphy commented on changelog.rst
> +.. admonition:: Bugfixes
solved

2022-12-01 19:16 UTC, Bob-Murphy commented on changelog.rst
> +.. rubric:: Refactor
solved

2022-12-01 19:17 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2356` Added buy menu vehicle render
solved

2022-12-01 19:17 UTC, Bob-Murphy commented on changelog.rst
> +   * Basically every template was touched up or overhauled :issue:`2181`, :issue:`2276`, :issue:`2277`, :issue:`2278`, :issue:`2302`, :issue:`2316`, :issue:`2333`, :issue:`2467`, :issue:`2475`
solved

2022-12-01 19:17 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2047` Moved templates into a separate addon
solved

2022-12-01 19:17 UTC, Bob-Murphy commented on changelog.rst
> +   * Added 3rd party supports
solved

2022-12-01 19:28 UTC, targetingsnake reviewed
i'll found another bug with the sphinx renderer, i already notified @Giddius on discord,
the rubrics beneath admonition 'major' are just got converted to a bunch of text instead of a list

2022-12-01 19:41 UTC, targetingsnake commented
``> i'll found another bug with the sphinx renderer, i already notified @Giddius on discord, the rubrics beneath admonition 'major' are just got converted to a bunch of text instead of a list

i spoke with giddi, we can solve the issue when rubrics and it's content are definied as following example:

```
  .. rubric:: Refactor

   * :issue:`2182` Refactored initZones to move relevant hardcoded map information to the map relevant files
   * :issue:`2238` Refactored BattleMenue to prevent conflicts with base game UIs
```

will open change requests for it

2022-12-01 19:45 UTC, targetingsnake requested changes

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Conversion to Mod
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Added Campaign StartUp UI and safe functionality :issue:`2488`
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Complete rework of the attack & support system
updated rubric as described in comments and keep list indents with seperation

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Fuel economy overhaul
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New Buy Vehicle UI - :issue:`2259`
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Added Guest Commander functionality :issue:`2428`
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New mod compatibilities
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New maps ports
updated rubric as described in comments

2022-12-01 19:45 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Translated Antistasi additional languages
updated rubric as described in comments

2022-12-03 04:57 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2510` Improved attack selection dependency on rebel HQ position
Can go, tweak to new behaviour.

2022-12-03 05:02 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2381` Added parameters for enemyNearCheck
This one is a more substantial change than described, especially from the player perspective. enemyNearCheck now only considers enemies in combat mode, and (nearly?) every enemy proximity check now uses the same rules.

2022-12-03 05:05 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2114` implemented system that gets compatible magazines for a weapon
Maybe too internal. The related external changes were elsewhere: Arsenal now listing all compatible magazines for weapons (doesn't even use 2114 anymore, as Arma 2.10 added commands), and vehicle arsenal now listing all compatible magazines for vehicles (important for 3CB BAF).

2022-12-03 05:07 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2472` Tweaked ability of rebels to respond to punishments and major attacks
Tweak to new behaviour, remove.

2022-12-03 05:09 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2297` Set Temperate as default for template auto selection
Superseded, dead.

2022-12-03 05:10 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2556` Fixed broken mortars at airports
Bug added since 2.5.5 so don't need to list.

2022-12-03 05:11 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2423` Fixed errors with event triggers
Pretty sure that was a post-2.5.5 bug.

2022-12-03 05:12 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2517` Fixed being able to load game saves with missing mods
Very-Post-2.5.5 bug.

2022-12-03 05:14 UTC, jaj22 commented on changelog.rst
> +   * :issue:`2326` Fixed players not being silent with ACE
I think this was a response to the face/voice patch.

2022-12-03 09:50 UTC, Lazejun commented on changelog.rst
> +   * :issue:`2326` Fixed players not being silent with ACE
yep

2022-12-03 10:47 UTC, HakonRydland approved these changes

2022-12-03 11:12 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2326` Fixed players not being silent with ACE
solved

2022-12-03 11:12 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2517` Fixed being able to load game saves with missing mods
solved

2022-12-03 11:12 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2423` Fixed errors with event triggers
solved

2022-12-03 11:12 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2556` Fixed broken mortars at airports
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2297` Set Temperate as default for template auto selection
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2472` Tweaked ability of rebels to respond to punishments and major attacks
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2114` implemented system that gets compatible magazines for a weapon
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2381` Added parameters for enemyNearCheck
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2510` Improved attack selection dependency on rebel HQ position
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: Translated Antistasi additional languages
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: New maps ports
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: New mod compatibilities
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: Added Guest Commander functionality :issue:`2428`
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: New Buy Vehicle UI - :issue:`2259`
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: Fuel economy overhaul
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: Complete rework of the attack & support system
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: Added Campaign StartUp UI and safe functionality :issue:`2488`
solved

2022-12-03 11:13 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: Conversion to Mod
solved

2022-12-03 11:53 UTC, Lazejun requested changes

2022-12-03 11:53 UTC, Lazejun commented on changelog.rst
> +   * :issue:`2280` You can now take 5, 10, or 25 items at a time from the vehicle arsenal
#2280 Could mention the Keybinds shift was 5, CTRL was 10 both is 25.
#2305 Could Rephrase that, they can now equip Items that are not Unlocked as soon as there is a Sufficient Amount.

Also they try to use Optics that are logical for the Equipment, no more Thermal SMGs, Sniper Optic SMGs etc.

The more you have of an Item the more likely they are to Equip it.

2022-12-03 11:53 UTC, Lazejun commented on changelog.rst
> +      * Fixed a syntax error in the MACV template
* Fixed a syntax error in the MACV template

Thats another in between Commits fix not work mentioning.

#2276 has nothing Todo with Templates.
#2277 and #2278, #2302, #2333 are all in 2.5.5. already not worth to mention here.
#2475 is an Inbetween changes fix, not worth being mentioned.

2022-12-03 11:53 UTC, Lazejun commented on changelog.rst
> +   * :issue:`2318` Vehicle locking system overhauled, vehicles start unlocked by default
#2318 as Players love taking stuff out of Context this has to be more specific.

This is about Player Vehicles being locked by Default for other Players that are not part of your Group,
Which was changed to being Unlocked by Default for everyone, Players in your Group Ignore locks and Members ignore locks.

----------> They dont get kicked out of the Vehicle when they enter.

In general its more of a Feature for bigger Public servers, which is funny as probably most people dont know about it.

2022-12-03 11:53 UTC, Lazejun commented on changelog.rst
> +   .. rubric:: New mod compatibilities
Mostly Pointless as you cant link to PRs Issues etc.
#2239 CUP
#2427 GM
#2379 Unsung

2022-12-03 17:48 UTC, targetingsnake requested changes

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Conversion to Mod
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Added Campaign StartUp UI and safe functionality :issue:`2488`
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Complete rework of the attack & support system
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Fuel economy overhaul
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New Buy Vehicle UI - :issue:`2259`
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Added Guest Commander functionality :issue:`2428`
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New mod compatibilities
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New mod compatibilities
afaik you can link to issues with the `:issue:` and then the number in specific high commata

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New maps ports
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-03 17:48 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Translated Antistasi additional languages
no, two emoty lines benath the `.. rubric::` are still missing and are very important

2022-12-12 23:35 UTC, killerswin2 approved these changes

2022-12-15 14:24 UTC, targetingsnake approved these changes

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Conversion to Mod
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Added Campaign StartUp UI and safe functionality :issue:`2488`
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Complete rework of the attack & support system
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Fuel economy overhaul
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New Buy Vehicle UI - :issue:`2259`
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Added Guest Commander functionality :issue:`2428`
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New mod compatibilities
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: New maps ports
solved

2022-12-15 14:24 UTC, targetingsnake commented on changelog.rst
> +   .. rubric:: Translated Antistasi additional languages
solved

2022-12-17 15:15 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2280` You can now take 5, 10, or 25 items at a time from the vehicle arsenal
Do we have a parameter for 2305 / what is the "suffucient amount"?

2022-12-17 15:29 UTC, Bob-Murphy commented on changelog.rst
> +   .. rubric:: New mod compatibilities
solved

2022-12-17 15:29 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`2318` Vehicle locking system overhauled, vehicles start unlocked by default
solved

2022-12-17 15:29 UTC, Bob-Murphy commented on changelog.rst
> +      * Fixed a syntax error in the MACV template
solved

2022-12-17 16:27 UTC, Lazejun commented on changelog.rst
> +   * :issue:`2280` You can now take 5, 10, or 25 items at a time from the vehicle arsenal
No Parameter,
ITEM_MIN 10
ITEM_MAX 50

They start with 10, highest chances are at 50

2022-12-17 16:28 UTC, Lazejun commented on changelog.rst
> +      * Fixed a syntax error in the MACV template
Should be good here

2022-12-17 16:28 UTC, Lazejun commented on changelog.rst
> +   * :issue:`2318` Vehicle locking system overhauled, vehicles start unlocked by default
✔️

2022-12-17 16:29 UTC, Lazejun commented on changelog.rst
> +   .. rubric:: New mod compatibilities
✔️

2022-12-17 16:30 UTC, Lazejun approved these changes

2022-12-17 20:06 UTC, merged