implement undercover removal when approaching downed heli
official-antistasi-community/A3-Antistasi pull request #2574
Opened 2022-12-06 01:47 UTC by ncermesoni

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
- Added logic to remove undercover status when players come within 150 units of crashed heli.
- Updated file with standardized header

### Please specify which Issue this PR Resolves.
closes #2311 

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
- Spawn mission
  - `["airport_1"] spawn A3A_fnc_DES_Heli`
- Be undercover
- Approach crash site on foot
- ~Get shot at~ lose undercover status
[helidown.webm](https://user-images.githubusercontent.com/733514/205788388-971825c2-9392-4847-8511-b58d6f8354eb.webm)

********************************************************
Notes:

2022-12-06 03:08 UTC, killerswin2 requested changes
Your current changes add edge cases that you didn't account for.
1) driving by a mission on a road
2) no validation that you are 150 meters away from the road.
3) etc...

The header isn't a header, who told you add one. It barely adds any information that a maintainer might need.

Finally, all the missions are currently in the process of being converted to a new task framework system. So these changes may end up in unstable but in a different pr. For now I'll leave this pr open to see your changes for conversion.

Nice job on your first pr, however I'm a little biased and think that players shouldn't lose undercover while near the mission.

2022-12-06 03:08 UTC, killerswin2 commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +		private _nearbyPlayers = allPlayers inAreaArray [getPos _heli, 150, 150];
150 meters is too big, what if I'm driving by this mission and it's by a road. I lose undercover, which is not right.

2022-12-06 03:27 UTC, Bob-Murphy commented
I agree that 150 is quite a bit, but having at 50m would be reasonable.
Killer, check the screenshot in #2311. Having players be able to do that just makes no sense, hence loosing undercover when close does make sense.

2022-12-06 03:28 UTC, Bob-Murphy commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +/*
It certainly is better than what was there before and I see resemplance to what we have in our wiki.
It doesn't contain all parts but it's an improvement
 https://github.com/official-antistasi-community/A3-Antistasi/wiki/Standardised-Header

2022-12-06 15:44 UTC, ncermesoni commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +		private _nearbyPlayers = allPlayers inAreaArray [getPos _heli, 150, 150];
I did think about roads. But if there's a crash site 35 meters away from the road, a security detail would probably not let you get close anyway. I'll reduce the distance as suggested in the thread for now. If road checks are really important, I can work on that after you guys agree on the approach to take.

2022-12-06 15:45 UTC, ncermesoni commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +/*
I was aiming for that but there are multiple sections that I just don't know how to fill. Was hoping to do so via PR feedback. Please let me know who the maintainers are and anything else I should add to it.

2022-12-06 15:54 UTC, Bob-Murphy commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +		private _nearbyPlayers = allPlayers inAreaArray [getPos _heli, 150, 150];
As we will have to rewrite the mission for the new framework either way I'm fine with just having this blanked 50m radius. No need to cover the edge case for roads.
I see this PR as a stop-gap for the exploit and for this purpose it's enough and fitting.

2022-12-06 15:55 UTC, Bob-Murphy commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +/*
Also here, will be rewritten.
No need to have a 100% header.
And feel free to put me in as a maintainer.

2022-12-06 16:03 UTC, killerswin2 commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +		private _nearbyPlayers = allPlayers inAreaArray [getPos _heli, 150, 150];
yeah just convert this to 50meters, and we are good for merging in.

2022-12-06 16:25 UTC, jaj22 commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +	while {alive _heli} do {
This will also apply after the heli is captured, so after you brought back the heli and parked it at HQ, it will continually reveal undercover players.

`_heli getVariable "ownerSide"` or `isPlayer driver _heli` check would be acceptable given that the mission requires a player pilot to complete successfully.

2022-12-07 06:17 UTC, jaj22 requested changes

2022-12-07 06:17 UTC, jaj22 commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +    };
Lost the `sleep 5`, so now the perf is unacceptable. If you're worried about the case where a player enters the heli briefly, use the ownerSide instead of the isPlayer driver. It's set reliably by event handlers in AIVEHinit.

An additional performance issue (strongly aggravated by the missing sleep) is that this routine will fire the setCaptive remoteExecs even if the players in question aren't undercover. Wrap it with an `if (captive _x)`.

Also getPos there should be getPosATL. Doesn't much matter here because it's a one-off, but it's a good habit to get into.

2022-12-10 16:38 UTC, jaj22 requested changes

2022-12-10 16:38 UTC, jaj22 commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +        { if (captive _x) then [_x, false] remoteExec ["setCaptive", _x] } forEach _nearbyPlayers;
Syntax error, `then` statement needs code brackets.

2022-12-10 16:38 UTC, jaj22 commented on A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
> +    while {alive _heli && _heli getVariable "ownerSide" != teamPlayer} do {
Because ownerSide doesn't exist until AIVEHinit is run on the heli, you need to move the AIVEHinit call up to where the heli is created (it's down with the pilots at the moment.

Hopefully no side effects. Destroyed-on-spawn case might be problematic.

2023-01-07 22:25 UTC, Bob-Murphy commented
Hey @ncermesoni , will you make the adaptations as requested or do you want is to take over and complete it?
An answer would be appreciated.

Cheers, Bob

2023-01-08 00:32 UTC, ncermesoni commented
@Bob-Murphy sorry about missing the 3.0 milestone - I unfortunately haven't had the bandwidth to get back to this PR, as simple as the changes were.
I've implemented @jaj22's suggestions, but can't test right now. It was working fine before the last 2 commits. I will try to test tonight.

2023-01-08 00:34 UTC, Bob-Murphy commented
No need to apologize. It's not mission critical so it's fine.
@jaj22 please review the changes

2023-03-25 20:16 UTC, jaj22 approved these changes
Looks fine now, should have a quick test run though.

2023-03-25 20:20 UTC, Bob-Murphy approved these changes

2023-03-25 20:21 UTC, merged