Gm templates other
official-antistasi-community/A3-Antistasi pull request #2601
Opened 2022-12-30 15:42 UTC by targetingsnake

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Added winter template for GM, maybe desert will follow here soon

### Please specify which Issue this PR Resolves.
none

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

1. Build mod
2. load with mods for GM
3. test winter template

********************************************************
Notes:

2022-12-30 15:52 UTC, targetingsnake commented
Desert Camo will be added soon, put this already up so winter stuff can be reviewed

2023-03-28 13:09 UTC, targetingsnake commented
desert camo will be delayed till 3.3 or so

2023-03-28 13:13 UTC, Bob-Murphy commented
Also, once done please adapt the title and the description accordingly.
Thank you

2023-03-28 13:58 UTC, targetingsnake commented
@Bob-Murphy done

2023-04-01 01:57 UTC, killerswin2 approved these changes
This is ready for merge and testing.

2023-04-01 11:40 UTC, Lazejun requested changes

2023-04-01 11:40 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +        name = "Bundeswehr Winter";
Please add the GM Prefix to the Name, so people know what is what.

Add Temperate in the name of the "Old" ones, so people know what they select.

add Tropical and Arid to the Climate for the "old" ones, so they arent hidden by default in the Camo selection.

2023-04-01 11:40 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW_arctic.sqf
> +["vehiclesTanks", ["gm_dk_army_m113a2dk_win", "gm_dk_army_m113a2dk_un", "gm_ge_army_leopard1a1a1_wiw", "gm_ge_army_leopard1a1a2_wiw", "gm_ge_army_leopard1a1a3_wiw", "gm_ge_army_leopard1a1a4_wiw", "gm
Kill the UN Variants if there are Winter variants.

2023-04-01 11:40 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA_arctic.sqf
> +["vehiclesTrucks", ["gm_gc_army_btr60pa_win", "gm_gc_army_btr60pa_un", "gm_gc_army_ural375d_cargo_un", "gm_gc_army_ural4320_cargo_un", "gm_gc_army_ural4320_cargo_win", "gm_gc_army_ural375d_cargo_win"
Same here,
Kill the UN Variants if there are Winter variants.

2023-04-01 11:40 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/GM/GM_Vehicle_Attributes.sqf
> +    ["gm_gc_army_bmp1sp2_olw", ["cost", 120], ["threat", 150]],
Same UN Cleanup

2023-04-01 16:46 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/GM/GM_AI_BW_arctic.sqf
> +["vehiclesTanks", ["gm_dk_army_m113a2dk_win", "gm_dk_army_m113a2dk_un", "gm_ge_army_leopard1a1a1_wiw", "gm_ge_army_leopard1a1a2_wiw", "gm_ge_army_leopard1a1a3_wiw", "gm_ge_army_leopard1a1a4_wiw", "gm
None of the UN variants have any UN markings. They are plain white.
![image](https://user-images.githubusercontent.com/50651578/229303775-3ba25220-20d6-4754-a564-342666fc4893.png)

2023-04-01 16:52 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/GM/GM_AI_NVA_arctic.sqf
> +["vehiclesTrucks", ["gm_gc_army_btr60pa_win", "gm_gc_army_btr60pa_un", "gm_gc_army_ural375d_cargo_un", "gm_gc_army_ural4320_cargo_un", "gm_gc_army_ural4320_cargo_win", "gm_gc_army_ural375d_cargo_win"
same as above, they are white without UN markings

2023-04-01 16:53 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/GM/GM_Vehicle_Attributes.sqf
> +    ["gm_gc_army_bmp1sp2_olw", ["cost", 120], ["threat", 150]],
same as above, they are white without UN markings

2023-04-01 16:58 UTC, Bob-Murphy commented
btw, changed `Winter` to `Arctic` to have it matching the other stuff we have

2023-04-01 16:59 UTC, Lazejun approved these changes
Good for now

2023-04-01 17:18 UTC, merged