Add CUP BW, HIL, TKM Reb, TKC Civs. (Some Love for CUP ☕)
official-antistasi-community/A3-Antistasi pull request #2616
Opened 2023-01-07 18:26 UTC by Lazejun

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Information:

### Template stuff
Added CUP BW Faction, Gaps filled with US Equipment,
Added CUP HIL Faction, Gaps filled with US Equipment,
Added Takistani Civilians as Civ Faction,
----> Difference to other Civ Factions: Uniforms, Faces, Headgear, Facewear
Added Takistani Militia as Rebell Faction,
----> Difference to other Reb Factions: Uniforms, Faces, Headgear, Facewear, Speaker (voices), Mi8 Instead of Bell 412.
Renamed CUP_Civ to CUP CHC for Chernarussian Civilians, changed Uniforms given to Ai to look a bit more fitting for Chernarus/Easter Europe, Arsenal Civ Uniforms are unchanged.
(Basically the same as above)
Renamed CUP_Reb to CUP Napa, changed Uniforms given to Ai to look a bit more fitting for Chernarus/Easter Europe, Arsenal Rebell Uniforms are unchanged.
Classes in Templates.hpp are not renamed so in theory saves should stay compatible

### Other Files
fn_undercoverAI: Apparently we never removed Vests so it kinda looked Silly and was mean to players as they cannot wear any Vests when undercover.
On Player Respawn: Got rid of the Random Civ Headgear as it looked silly most of the time

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-01-07 22:09 UTC, killerswin2 commented
Testing saves produced this.

> 16:07:09 2023-01-07 22:07:09:632 | Antistasi | Info | File: A3A_fnc_setupFactionsTab | Bad saved faction name CUP_NAPA | Called By: A3A_fnc_setupLoadgameTab

game still select correct faction. Civs also worked correctly.

2023-01-07 23:52 UTC, killerswin2 requested changes
just some small stuff

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["vehiclesAA", ["CUP_B_M6LineBacker_USA_D", "CUP_B_nM1097_AVENGER_USA_DES", "CUP_B_M163_Vulcan_USA"]] call _fnc_saveToTemplate;
You could remove the Avenger, the M163 and LineBacker are more in line with AA than a humeeve with stingers and 50 cals

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["vehiclesMilitiaTrucks", ["CUP_B_MTVR_BAF_DES"]] call _fnc_saveToTemplate;
CUP_B_MTVR_BAF_DES has L85s in the inventory, CUP_B_MTVR_USA is a desert variant (slight color difference) but it contains m4 instead ofL85s

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["CUP_arifle_G3A3_ris", "", "", "", ["CUP_20Rnd_762x51_G3", "CUP_20Rnd_TE1_Red_Tracer_762x51_G3"], [], ""],
G1 rifles for the Bundeswehr are in CUP, both rail and non. Maybe add the Railed version so that we have another 7.62 avaiable.

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf
> +["vehiclesAA", ["CUP_B_M6LineBacker_USA_W", "CUP_B_nM1097_AVENGER_USA_WDL", "CUP_B_M163_Vulcan_USA"]] call _fnc_saveToTemplate;
same as arid for Avenger.

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf
> +["vehiclesMilitiaTrucks", ["CUP_B_MTVR_BAF_WOOD"]] call _fnc_saveToTemplate;
same as arid, has L85 in cargo

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_HIL.sqf
> +["vehiclesMilitiaTrucks", ["CUP_B_MTVR_BAF_WOOD"]] call _fnc_saveToTemplate;
L85 here again

2023-01-07 23:52 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Civ_CHC.sqf
NOOOOOOOOOOOOO, MY CIV HELIS!!!! lol

2023-01-07 23:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["vehiclesMilitiaTrucks", ["CUP_B_MTVR_BAF_DES"]] call _fnc_saveToTemplate;
Yes but so Militia Units spawn in Militia vehicles it has to be a seperate Class.

2023-01-07 23:58 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["CUP_arifle_G3A3_ris", "", "", "", ["CUP_20Rnd_762x51_G3", "CUP_20Rnd_TE1_Red_Tracer_762x51_G3"], [], ""],
Thats more so you dont get a Weapon you can't "Upgrade" with Optics.
would be nice if CUP added Rails dynamicly if you add Optics but it doesent so this.

2023-01-07 23:58 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf
> +["vehiclesMilitiaTrucks", ["CUP_B_MTVR_BAF_WOOD"]] call _fnc_saveToTemplate;
Same as above

2023-01-07 23:58 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_HIL.sqf
> +["vehiclesMilitiaTrucks", ["CUP_B_MTVR_BAF_WOOD"]] call _fnc_saveToTemplate;
The same

2023-01-07 23:58 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_Civ_CHC.sqf
We dont need to constantly add Dead Code.

2023-01-08 00:06 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["vehiclesAA", ["CUP_B_M6LineBacker_USA_D", "CUP_B_nM1097_AVENGER_USA_DES", "CUP_B_M163_Vulcan_USA"]] call _fnc_saveToTemplate;
Its just general borrowed Gear, 2 Times good/Armored (Exept the Gunner on the M163) and 1 times poorly armored but with more Missiles.

Just funny for the Steal/Destroy armor Mission, also we use the Same on the US Army, Marines only get the Avenger, ACR only the Avenger its not realy a Reason against it.

2023-01-08 00:16 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf
> +["vehiclesAA", ["CUP_B_M6LineBacker_USA_D", "CUP_B_nM1097_AVENGER_USA_DES", "CUP_B_M163_Vulcan_USA"]] call _fnc_saveToTemplate;
alrighty

2023-01-08 00:17 UTC, killerswin2 approved these changes
This is ready for merge/testing later on the test server.

2023-01-08 17:01 UTC, merged