Garrison Limit
official-antistasi-community/A3-Antistasi pull request #2622
Opened 2023-01-09 13:24 UTC by igorkis-scrts

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
This PR introduces garrison limit for rebels, so they can no longer put excessive amount of troops to guard their precious outposts. 
Also, it fixes minor bug with garrisonInfo which could break if any garrisoned unit non-mentioned in function (for example, explosive specialists or engineers) will break the function as there was no default case in switch for other types of units.

![image](https://user-images.githubusercontent.com/6746043/211318028-519dcf01-2792-4b38-b43b-fe9255a8b95f.png)

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Add someone to garrison of captured outpost of any type.

2023-01-10 03:29 UTC, killerswin2 requested changes
Good Groundwork.

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10", "20", "30"};
We need a no limit option and continue the 10 inc to 50.

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
> +		floor (A3A_rebelGarrisonLimit * 0.5)
I feel like this is add complexity were it is not needed. Why increase or decrease the limit based on the limit? The limit should be the limit.

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
> +	["_marker", "", [""]]
check indention, might not be 4 spaces.

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +	["Garrison", "Adding this squad to garrison will exceed garrison limit."] call A3A_fnc_customHint;
localize/ make this a stringtable entry

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _markerX = positionXGarr;
??? why take that out of the private array?

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +	["Garrisons", "Garrison limit has reached, you can't add new units anymore."] call A3A_fnc_customHint;
localize/ make this a stringtable entry

2023-01-10 03:29 UTC, killerswin2 commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _garrison = garrison getVariable [_markerX,[]];
Um you killed guest commander features..... John might not like that.

2023-01-10 06:51 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _garrison = garrison getVariable [_markerX,[]];
I would say what's the practical reason of having guest commander garrison limits if we're introducing general garrison limit all the way?
@jaj22

2023-01-10 07:08 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _markerX = positionXGarr;
Bulk `private` declarations are nothing but code smell and "it was the nineties"-kind of thing. The most common reason to get rid of them is that people are forgetting to clear this private variables array from unused variables since IDE can't highlight unused variables and applying to Antistasi's codebase it's usually a really long string in code listing. Also, declaring all used variables in the beginning of file at the top is weird (what If my code will take `exitWith` route and will not use 90% of variables?).

Also, they have slightly less performance by itself (per BI wiki, basically private array splits declaration and initialization thus having less performance):
```sqf
private _a = 1;
private _b = 2;
private _c = 3;
private _d = 4;
// 0.0023 ms

private ["_a", "_b", "_c", "_d"];
_a = 1;
_b = 2;
_c = 3;
_d = 4;
// 0.0040 ms
```
So I don't see any valid reason to maintain them and they can be slowly removed out of codebase.

2023-01-10 07:08 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +	["Garrison", "Adding this squad to garrison will exceed garrison limit."] call A3A_fnc_customHint;
will do

2023-01-10 07:08 UTC, igorkis-scrts commented on A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
> +	["_marker", "", [""]]
will do

2023-01-10 07:10 UTC, igorkis-scrts commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10", "20", "30"};
Will do

2023-01-10 07:14 UTC, igorkis-scrts commented on A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
> +		floor (A3A_rebelGarrisonLimit * 0.5)
>  based on the limit
You probably meant marker/outpost type. Yeah, maybe it shouldn't be done. I thought that airbases probably would require a bit more troops than usual outpost as they're usually bigger. Resources could have default limit without 0.5x multiplier though.

2023-01-10 08:52 UTC, igorkis-scrts commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10", "20", "30"};
To be honest, I don't think that no limit option should be there - it is somewhat dangerous behaviour, players shouldn't be allowed to put unlimited amount of troops as it will tank FPS for everyone.

2023-01-10 09:38 UTC, Bob-Murphy commented on A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
> +		floor (A3A_rebelGarrisonLimit * 0.5)
It makes sense to have different limits for the different markers. Back in 2021 at a meeting we came up with the following limits:
```
Limit garrison sizes based on markers:
- resource & factory = 15
- outposts & seaports = 25
- airports = 40
```
I think that a base limit with multipliers is a good solution.
Sure, the values are not the same, but it's easy enough to tweak the percentages afterwards.

2023-01-10 09:41 UTC, Bob-Murphy commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10", "20", "30"};
We could have a `no limit` option. But then we should add a disclaimer that too many garrisoned troops could negatively impact the performance.
This way the player still has the possibility, but at least we have the"we told you so" when he fucks his shit up.

2023-01-10 09:43 UTC, Bob-Murphy commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _garrison = garrison getVariable [_markerX,[]];
I agree with Socrates. The reason for the guest commander feature here is that they don't fuck it up either by accident or on purpose.
With the limit there ain't nothing they can break anymore.

2023-01-10 16:50 UTC, killerswin2 commented on A3A/addons/core/functions/Garrison/fn_getGarrisonLimit.sqf
> +		floor (A3A_rebelGarrisonLimit * 0.5)
Yeah I meant the marker type. Thinking about this some more it actually is a good idea.

2023-01-10 16:55 UTC, killerswin2 commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _garrison = garrison getVariable [_markerX,[]];
I guess that is true.

2023-01-10 16:56 UTC, killerswin2 approved these changes
Alright that some good work!

2023-01-10 19:11 UTC, igorkis-scrts commented
> Is this intentionally using the same limit for cities as outposts?
Yeah, I think that 20 troops are enough for city. There are much more cities than airbases.

About taxes - I think that players are already pressured enough with the HR income and constant need of troops training. Tax system is interesting but I think it will punish players a lot more than it probably should ("we hired a lot people, where is muh FIA money, why it's constantly near zero?"). If the limit number is not too high (I would remove 50 value, maybe 40 too), the completionist nature of players will not hurt much.

Valid concern about HC squads. I'll see what I can do there.

2023-01-10 22:53 UTC, Bob-Murphy commented
I also would remove 40 and 50 as options.
Tax system could be interesting, but I would add that in a later step.

2023-01-10 23:04 UTC, Bob-Murphy reviewed
As you are already working on the files, could you please localize the other strings in `fn_addToGarrison.sqf` and `fn_resourcecheck.sqf`? That'd be nice.
Thank you.

2023-01-10 23:30 UTC, killerswin2 commented
Keep 40, you can remove 50

2023-01-10 23:37 UTC, Bob-Murphy commented
40 at outposts and every city/village is unreasonable.
If people want more than 30 as base, let them disable it and be fully unreasonable.
If your argument for example is "more at airfields" we can adjust the percentage after testing.

2023-01-10 23:54 UTC, killerswin2 commented
Bob, it is not us who decides what is unreasonable. Let the players decides by giving them options. There is no harm in have them.

2023-01-10 23:55 UTC, killerswin2 commented
case in point, with 30, I can't have two ai squads as limit is 15, not 16.

2023-01-11 11:20 UTC, igorkis-scrts commented
I would say that players have a tendency to shoot themselves in the foot and then blaming developers for it, so giving potentionally dangerous instruments to players is a risky move.
Prosumers will fork and make their edits anyway, so some boundaries how it should be played should exist.

2023-01-11 11:58 UTC, igorkis-scrts commented
> As you are already working on the files, could you please localize the other strings in fn_addToGarrison.sqf and fn_resourcecheck.sqf?
Done with the `fn_addToGarrison.sqf` only. `fn_resourcecheck` (and many other cases) has a problem - if Engilsh strings will be just swapped with `localize` call, already localized values will be broadcasted across all clients, so players might see not their language messages. It will require separate localization PR with a function that broadcasts "localize call" to clients (`fn_commsMP` already does that to some extent).

2023-01-21 12:08 UTC, Bob-Murphy commented on A3A/addons/GUI/dialogues/ids.inc
> +// #define A3A_IDC_ARSLIMARROWMINUS 9501
What are all this unused defines for, will they be needed in the future or can they be deleted?

2023-01-21 12:11 UTC, Bob-Murphy commented
@igorkis-scrts You added `GUI/fn_hcDismissalDialog.sqf` but that file is completely empty. Is that needed?

2023-01-21 12:11 UTC, Bob-Murphy commented
also, merge conflict

2023-01-21 12:12 UTC, igorkis-scrts commented
HC squad dismissal dialog is not yet ready, so this PR is still WIP. At this moment it's basically a placeholder dialog.

2023-01-21 12:13 UTC, Bob-Murphy commented
Copy that. Added a label.

2023-01-24 12:14 UTC, igorkis-scrts commented
Frankly, the more I'm thinking about it the more I feel like that dismissal dialog is an excessive thing and probably shouldn't needed at all - most players want to usefully get rid of HC squads (usually it's the squads that lost combat capability due distance, losses or simply being stuck somewhere), so they dump them to recently captured point and call it a day. Leaving "excessive" troops still leaves "what should I do with these HC squads?" question open and I don't think there is real practical use of squad that's left some chunk of their firepower in garrison.
So, maybe we should just refund over-the-limit troops with HR and/or money and that's basically it?

2023-01-28 06:13 UTC, jaj22 commented
Well, personally I don't think I'd benefit from a dismissal dialog: When I garrison an HC squad it's because I want it gone and the garrison filled as far as possible. As long as there's a hint on how many units were refunded (and why) and how many units were added to the garrison then it's fair enough. However, if the garrison is already 100% full it shouldn't dismiss the whole squad, because in that case you'd often want to garrison them elsewhere.

Would be slightly worried about some commanders having a different idea, but it's probably fine.

2023-01-28 11:47 UTC, igorkis-scrts commented
PR has been updated with previously discussed changes.

2023-02-15 11:10 UTC, Bob-Murphy commented
@jaj22 Please re-check.
Cheers

2023-02-15 13:50 UTC, jaj22 requested changes
Seems fine. Marked some minor stuff.

A design issue is that cities are using the outpost limit (24 by default) regardless of population, and I think players will be inclined to treat the visible limit as a target. Previously players rarely garrisoned towns, so this may end up hurting their performance by doing what they think is intended.

Would recommend setting city limits according to sqrt population (which lines up with the enemy targeting value), rounding to even numbers to make it look less random.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            private _unitsToRefund = _unitsX select {!isPlayer _x}; //commander may be amongst the units
isPlayer case is filtered out at line 59. Doesn't much matter, but the comment kinda opens a can of worms if it was possible.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            };
This is just an array reverse, isn't it? SQF actually has a command for that:
https://community.bistudio.com/wiki/reverse

Could also use deleteRange.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +    } forEach _unitsX;
Indentation is off for this section.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +_countX = count _garrison;
Old bug: `_countX` isn't declared private.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +private _markerX = positionXGarr;
I don't think killer would have objected if you'd removed the whole array. If you're not refactoring the whole file but you want to make it locally more readable then it's fair enough to pull these out.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_resourcecheck.sqf
>  			_mrkD setMarkerColor colorTeamPlayer;
Can remove these if you're calling mrkUpdate.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_resourcecheck.sqf
>  			_mrkD setMarkerColor colorOccupants;
Can remove these if you're calling mrkUpdate.

2023-02-15 13:50 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +        }];
That reminds me, need to refactor to a general rebelKilled event handler. Later...

2023-02-15 18:04 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            };
For some reason `reverse`  is not working for units array, it return `nil`.
```sqf
private _unitsX = groupselectedUnits player;
reverse _unitsX;
```

2023-02-15 18:13 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            private _unitsToRefund = _unitsX select {!isPlayer _x}; //commander may be amongst the units
Oh, I was using `units group player` for testing instead of selected counterpart.

2023-02-15 18:25 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            };
reverse and deleteRange both modify the array in-place and return nothing, so in this case you'd do something like:
```
private _unitsToRefund = +_unitsX;
reverse _unitsToRefund;
_unitsToRefund resize _unitsToRefundCount;
```

2023-02-15 18:33 UTC, igorkis-scrts commented on A3A/addons/core/functions/init/fn_resourcecheck.sqf
>  			_mrkD setMarkerColor colorOccupants;
fixed

2023-02-15 18:33 UTC, igorkis-scrts commented on A3A/addons/core/functions/init/fn_resourcecheck.sqf
>  			_mrkD setMarkerColor colorTeamPlayer;
fixed

2023-02-15 18:33 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
> +_countX = count _garrison;
fixed

2023-02-15 18:33 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +    } forEach _unitsX;
fixed

2023-02-15 18:33 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            };
fixed

2023-02-15 18:33 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            private _unitsToRefund = _unitsX select {!isPlayer _x}; //commander may be amongst the units
fixed

2023-02-15 18:47 UTC, jaj22 approved these changes
All looks good now.

2023-02-15 19:27 UTC, rautamiekka commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            private _unitsToRefund = _unitsX select {!isPlayer _x}; //commander may be amongst the units
Example 4 for [`units`](https://community.bistudio.com/wiki/units) says there's no use in `units group player` when `units player` gives the equal result.

2023-02-15 19:43 UTC, igorkis-scrts commented on A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
> +            _unitsX deleteRange [(count _unitsX - _unitsToRefundCount), count _unitsX];
updated

2023-02-16 09:36 UTC, Bob-Murphy requested changes
Some small and nice-to-have things.

2023-02-16 09:36 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +          <Original>Select the zone on where you will send the selected troops as garrison.</Original>
doubled indentation on the languages (Original and Russian) starting here and below.

2023-02-16 09:36 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_garrisonInfo.sqf
> +    "<br/><br/>Garrison units: %1%13<br/><br/>Squad Leaders: %2<br/>%12: %3<br/>Riflemen: %4<br/>Autoriflemen: %5<br/>Medics: %6<br/>Grenadiers: %7<br/>Marksmen: %8<br/>AT Men: %9<br/>Other: %10<br/>
Can we localize this fucker?

2023-02-16 09:36 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +          <Original>You must select at any %1 zone with marker.</Original>
`You must select at any %1 zone with marker.` sounds a bit wrong. I think the `at` can be deleted.

2023-02-16 09:36 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>Adding this squad to garrison will exceed garrison limit. Some part of them will join garrison, the rest will be dismissed and their cost will be refunded.</Original>
`Some part of them will join garrison,` --> `Some of them will join the garrison,`

2023-02-16 09:36 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +          <Original>%1 group is back to HC control because the zone which was pointed to garrison has been lost.</Original>
`%1 group is back to HC control because the zone which was pointed to garrison has been lost.` --> `%1 group has returned to HC control as the zone which was planned to be garrisoned has been lost.`

2023-02-16 09:36 UTC, Bob-Murphy commented on A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf
>  if ([_positionX] call A3A_fnc_enemyNearCheck) exitWith {["Garrisons", "You cannot Recruit Garrison Units with enemies near the zone."] call A3A_fnc_customHint;};
Please localize this as well as all the others in this file, as we are already working on it.
Thank you.

2023-02-16 14:26 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_garrisonInfo.sqf
> +    "<br/><br/>Garrison units: %1%13<br/><br/>Squad Leaders: %2<br/>%12: %3<br/>Riflemen: %4<br/>Autoriflemen: %5<br/>Medics: %6<br/>Grenadiers: %7<br/>Marksmen: %8<br/>AT Men: %9<br/>Other: %10<br/>
I wouldn't recommend it. That's going to be one hell of an ugly XML string, and I'm pretty sure it's redundant in the new UI.

2023-03-12 07:32 UTC, Bob-Murphy approved these changes
lgtm

2023-03-12 07:32 UTC, merged