Silent server setup notifications + custom hint dismiss tip localization
official-antistasi-community/A3-Antistasi pull request #2645
Opened 2023-01-29 15:18 UTC by igorkis-scrts

## What type of PR is this.
1. [x] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Server setup notifications produce annyoing looped "tick" sound.
Also, this PR adds localizable strings for custom hint dismiss tips.

### Please specify which Issue this PR Resolves.
-

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
-

2023-01-29 19:35 UTC, jaj22 requested changes
Otherwise looks fine.

2023-01-29 19:35 UTC, jaj22 commented on A3A/addons/core/Stringtable.xml
> +          <Russian>&lt;br/&gt;&lt;t size='0.8' color='#e5b348' shadow='1' shadowColor='#000000' valign='top'&gt;%1 предыдущих подсказок&lt;br/&gt;Назначить клавишу закрытия подсказок: &lt;t color='#f
Says "Antistasi Plus".

2023-01-29 19:58 UTC, igorkis-scrts commented on A3A/addons/core/Stringtable.xml
> +          <Russian>&lt;br/&gt;&lt;t size='0.8' color='#e5b348' shadow='1' shadowColor='#000000' valign='top'&gt;%1 предыдущих подсказок&lt;br/&gt;Назначить клавишу закрытия подсказок: &lt;t color='#f
whoops

2023-02-15 11:03 UTC, Bob-Murphy commented
@jaj22 I guess this is good now?

2023-02-15 12:48 UTC, jaj22 commented
@Bob-Murphy Actually had second thoughts. Do we really want epic formatting strings in the stringtable? Seems like that might be a pain to work with.

Alternative is to split into seven mini-strings.

2023-02-15 13:52 UTC, jaj22 commented
Your funeral. Merge it then :P

2023-02-16 09:10 UTC, Bob-Murphy approved these changes
lgtm

2023-02-16 09:11 UTC, Bob-Murphy commented
@jaj22 please approve, your change request is blocking

2023-02-16 14:14 UTC, jaj22 approved these changes

2023-02-21 18:50 UTC, igorkis-scrts commented
@Bob-Murphy 
Fixed.

2023-02-25 13:09 UTC, merged