Petros' new drip - Antistasi Berets
official-antistasi-community/A3-Antistasi pull request #2646
Opened 2023-01-30 21:45 UTC by Bob-Murphy

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Because style points.

![ArmA 3 Screenshot 2023 01 30 - 22 41 25 29](https://user-images.githubusercontent.com/50651578/215602280-07af4f91-08cb-42d8-825c-48395ef9045d.png)

![image](https://user-images.githubusercontent.com/50651578/215602301-3b455242-9029-476e-ae83-e86b3d5fc3d3.png)

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

********************************************************
Notes:

2023-01-30 21:50 UTC, killerswin2 commented
This should an optional addon, not tied to Antistasi

2023-01-30 22:11 UTC, killerswin2 requested changes
You have a lot work on. You have a a lot of redundant config assigns. You aren't following config making standards. You copied and pasted. You didn't learn of to do this. And how we need to talk about how this config is messy. You have wasted my Time Bob. Next time get some who knows what they are doing instead of doing this your self. 


Things you need to do. 
Move every fucking file in headgear into a new subfolder name the modelname. Inside of that folder, make a data folder. Place all the files there The .paa and .rvmat. in the modelname folder you make a hpp file of the configs in config.cpp.  Inside of config.cpp include that hpp file.

2023-01-30 22:11 UTC, killerswin2 commented on A3A/addons/gear/config.cpp
> +		model = "\A3\Weapons_F\DummyCap.p3d";		// Omit this, if the headgear is a helmet.
MY GOD, REALLY? YOU ALREADY HAD THE MODEL IN BASE. WHAT THE FUCK ARE YOU DOING. STOP. STOP.
NO, NO, NO. DON'T FUCKING DECLARE THE SAME MODEL.

2023-01-30 22:11 UTC, killerswin2 commented on A3A/addons/gear/config.cpp
> +		author=AUTHOR;
FOR FUCK SAKES MAN. YOU REALLY COPIED PASTED THIS.

2023-01-30 22:11 UTC, killerswin2 commented on A3A/addons/gear/config.cpp
> +class A3A {
You can remove this. We don't need for now. This can be added easily later.

2023-01-30 22:11 UTC, killerswin2 commented on A3A/addons/gear/config.cpp
> +	class H_Beret_02: H_Beret_blk
You don't have to do most of this stuff. You copied this from the sample/ or config.

2023-01-30 22:22 UTC, Bob-Murphy commented on A3A/addons/gear/CfgFunctions.hpp
> +class CfgFunctions {
I guess that I then also can delete the part at the end of config.cpp?

```
#if __A3_DEBUG__
    #include "CfgFunctions.hpp"
#endif
};
#if __A3_DEBUG__
#else
    #include "CfgFunctions.hpp"
#endif
```

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +	class H_Beret_02: H_Beret_blk
please clarify

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +class A3A {
ok

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		author=AUTHOR;
please clarify

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		model = "\A3\Weapons_F\DummyCap.p3d";		// Omit this, if the headgear is a helmet.
please clarify

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		model = "\A3\Weapons_F\DummyCap.p3d";		// Omit this, if the headgear is a helmet.
please clarify

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		scope = 2; ScopeArsenal = 2; ScopeCurator = 0;
ok

2023-01-30 22:27 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		_generalMacro="a3a_g_beret_01";
ok

2023-01-30 22:28 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +	class HelmetBase: ItemCore
ok

2023-01-30 22:28 UTC, Bob-Murphy commented on A3A/addons/gear/CfgFunctions.hpp
> +class CfgFunctions {
Nevermind, commented further below.
Ok

2023-01-30 22:29 UTC, killerswin2 commented on A3A/addons/gear/config.cpp
> +	class HelmetBase: ItemCore
it still needs to be declared.
so 
class HelmetBase;

2023-01-30 23:52 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +	class HelmetBase: ItemCore
seems to break things, won't apply.

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +	class H_Beret_02: H_Beret_blk
done

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +class A3A {
done

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		author=AUTHOR;
clarified on discord
done

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		model = "\A3\Weapons_F\DummyCap.p3d";		// Omit this, if the headgear is a helmet.
clarified on discord
done

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		model = "\A3\Weapons_F\DummyCap.p3d";		// Omit this, if the headgear is a helmet.
clarified on discord
done

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		scope = 2; ScopeArsenal = 2; ScopeCurator = 0;
done

2023-01-31 00:16 UTC, Bob-Murphy commented on A3A/addons/gear/config.cpp
> +		_generalMacro="a3a_g_beret_01";
done

2023-01-31 10:07 UTC, igorkis-scrts commented
> Petros, It's you! You were the Antistasi all along?!
😄 
On a serious note, I think having these berets as an optional item would be fine (same as ACE Banana or RHS deer horns on Christmas, for example), but it would kinda goofy/meme-y if Petros would always wear it.

2023-01-31 21:23 UTC, killerswin2 requested changes
All that's left is to move the files to new folders as we discussed on discord

2023-02-01 03:23 UTC, killerswin2 approved these changes
Good

2023-02-01 13:18 UTC, merged