RHS SAF Template/support
official-antistasi-community/A3-Antistasi pull request #2662
Opened 2023-03-02 23:40 UTC by baldtune

Added template file and callout for it.

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Added template file and callout for RHS:SAF support.

### Please specify which Issue this PR Resolves.
some old idea/this has been requested by others.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Load game and choose RHS SAF
********************************************************
Notes:
Let me know if anything needs change. I tried real life accuracy.

2023-03-03 16:17 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["flag", "Flag_Enoch_F"] call _fnc_saveToTemplate;
["flag", "rhssaf_flag_serbia"] call _fnc_saveToTemplate;
["flagTexture", "rhssaf\addons\rhssaf_main\data\flags\flag_serbia_co.paa"] call _fnc_saveToTemplate;
["flagMarkerType", "rhssaf_flag_serbia"] call _fnc_saveToTemplate;

2023-03-03 16:18 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesPlanesTransport", ["RHS_TU95MS_vvs_old"]] call _fnc_saveToTemplate;
Thats not a Transport Plane.

2023-03-03 16:59 UTC, Lazejun requested changes

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +    class RHS_SAF_Temperate : RHS_Base
You need to Add Detection.

SAF only works if you load SAF.

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +        name = "RHS SAF Temperate";
SAF does not include enough to Support any other Terrain so Remove the Temperate -----> Just RHS SAF.
(one Vest and one Uniform is not enough).

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +		flagTexture = "a3\data_f_enoch\flags\flag_enoch_co.paa";
See earlier for the Right Flag texture.

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesLightAPCs", ["rhsgref_BRDM2_HQ", "rhsgref_BRDM2", "", "", ""]] call _fnc_saveToTemplate;
This can be removed.

```sqf
, "", "", ""
```

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesAPCs", ["rhsgref_cdf_btr60", "rhsgref_cdf_btr70", "rhsgref_cdf_btr80"]] call _fnc_saveToTemplate;
BTRs are Light APCs.

See AFRF Template and others. https://github.com/official-antistasi-community/A3-Antistasi/blob/b3ad2ad59030e3e5553621e368263ee530685aae/A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf#L29-L31

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesPlanesAA", ["rhssaf_airforce_o_l_18_101"]] call _fnc_saveToTemplate;
AA Plane needs to be set up to work properly.

https://github.com/official-antistasi-community/A3-Antistasi/blob/master/A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf

2023-03-03 16:59 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +_militiaLoadoutData set ["vests", ["rhs_6b3_AK"]];
Militia is meant to be Early Game, Low Tier, no to shitty body Armor -----> Chest Rigs, Webbings up to Tactical Vests.

2023-03-03 17:26 UTC, baldtune commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["flag", "Flag_Enoch_F"] call _fnc_saveToTemplate;
I though so, wasn't sure. I'll make those changes.

2023-03-03 17:26 UTC, baldtune commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesPlanesTransport", ["RHS_TU95MS_vvs_old"]] call _fnc_saveToTemplate;
c130 it is

2023-03-03 17:27 UTC, baldtune commented on A3A/addons/core/Templates/Templates.hpp
> +        name = "RHS SAF Temperate";
I know, change it is

2023-03-04 12:17 UTC, baldtune commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +_militiaLoadoutData set ["vests", ["rhs_6b3_AK"]];
They are using same vests as AFRF militia. Still wanna change? Armor values are lower than miltitary vests.

2023-03-04 12:23 UTC, baldtune commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["voices", ["MALE01POL", "MALE02POL", "MALE03POL"]] call _fnc_saveToTemplate;
Polish is closest to actual language, but okay, ill change them. Are faces ok?

2023-03-04 13:23 UTC, baldtune commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesPlanesAA", ["rhssaf_airforce_o_l_18_101"]] call _fnc_saveToTemplate;
I added both with same loadout for now, do you wanna different loadouts?

2023-03-04 13:25 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesPlanesAA", ["rhssaf_airforce_o_l_18_101"]] call _fnc_saveToTemplate;
Only one Loadout Per Classname.

The AA Plane gets AA, CAS gets CAS, Bombs serve no purpose, if bombs can be replaced with ATGMs or Dumb Rockets then do that.

2023-03-04 13:47 UTC, baldtune commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +["vehiclesPlanesAA", ["rhssaf_airforce_o_l_18_101"]] call _fnc_saveToTemplate;
Done

2023-03-04 21:20 UTC, Lazejun requested changes

2023-03-04 21:21 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF_Temperate.sqf
> +_militiaLoadoutData set ["vests", ["rhs_6b3_AK"]];
Well SAF Units use their Own Vests and Not AFRF Vests.

2023-03-04 22:53 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +        case case "rhssaf_airforce_l_18":
```suggestion
        case "rhssaf_airforce_l_18":
```

2023-03-04 23:25 UTC, Lazejun requested changes

2023-03-04 23:25 UTC, Lazejun commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_r73m_Launcher"]];
https://en.wikipedia.org/wiki/R-73_(missile)

Air to Air is not for Ground usually.

2023-03-04 23:42 UTC, baldtune commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_r73m_Launcher"]];
Yes, if i understood correctly, nothing else can be added those two pylons. I can take them off or leave them for self defense

2023-03-04 23:44 UTC, baldtune commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_r73m_Launcher"]];
Or close air support also means attacking against players air vehicles ;)

2023-03-05 20:00 UTC, Lazejun commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_r73m_Launcher"]];
As i said above you can give them ATGMs, you dont have to fill them with S8s.

2023-03-26 02:02 UTC, Lazejun approved these changes
should be fine now.

2023-03-26 02:09 UTC, Bob-Murphy approved these changes
lgtm

2023-03-26 02:09 UTC, merged