Add Ace ropes to the starting Arsenal.
official-antistasi-community/A3-Antistasi pull request #2686
Opened 2023-03-29 04:16 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Adds all ace ropes to the arsenal, players always unlock them. Ace always adds them to the vehicle after init.

### Please specify which Issue this PR Resolves.
closes #2172

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-03-29 04:55 UTC, Lazejun reviewed
You might want to prevent undercover towing with ace before this is merged.

2023-04-15 01:20 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +    ["ace_towing_ropeDeployed", {
I can't find this event anywhere in the ACE codebase. What am I missing?

2023-04-15 01:59 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +    ["ace_towing_ropeDeployed", {
It doesn't exist. I had to make a pr to resolve this

2023-04-15 02:00 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +    ["ace_towing_ropeDeployed", {
https://github.com/acemod/ACE3/pull/9178

2023-04-15 02:10 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +    ["ace_towing_ropeDeployed", {
Hah ok, good job.

2023-10-17 23:31 UTC, rautamiekka requested changes

2023-10-17 23:31 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +        if (_unit == player) then { player setCaptive false };
```suggestion
    params ["_unit", "_target", "_ropeClass"]
    if (_unit == player) then { player setCaptive false };
```

2023-10-17 23:32 UTC, jaj22 approved these changes

2023-10-17 23:33 UTC, jaj22 commented
Oh yeah, you do have a double-tab there :P

2023-10-18 17:18 UTC, merged