Add Zues Logs
official-antistasi-community/A3-Antistasi pull request #2750
Opened 2023-04-25 22:15 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
  Adds logging of what zues is doing. Logs Zues activities for Admins of servers.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-04-25 22:17 UTC, killerswin2 commented
`17:01:50 2023-04-25 22:01:50:487 | Antistasi | Info | File: A3A_fnc_zuesLogging | Event: CuratorObjectSelectionChanged Curator: Killerswin2 Object: commanderX Object Type: I_G_Soldier_TL_F
17:01:54 2023-04-25 22:01:54:421 | Antistasi | Info | File: A3A_fnc_zuesLogging | Event: CuratorObjectSelectionChanged Curator: Killerswin2 Object: flagX Object Type: Flag_FIA_F` Example

2023-04-26 03:18 UTC, rautamiekka commented
All `zues` to `zeus`.

2023-04-26 13:48 UTC, CalebSerafin commented
Note, unless additional hooks are added, any actions done by Zeus modules spawned at runtime will be incognito.

2023-04-26 23:08 UTC, killerswin2 commented
Hmm, best recommendation? Just spawn a script that counts allCurators?

2023-04-27 17:02 UTC, CalebSerafin commented
You don't need to wipe the event handlers off all modules and then add them again. You can remember which modules you already added EHs to by keeping a list. Maybe see if and which event is raised when ACE or Zues enhanced creates a Curator Module. Checking for modules or tampering done by script kiddies is certainly out of scope because at that point it's a lost cause.

2023-04-27 17:21 UTC, HakonRydland commented
a eh would be much better see https://community.bistudio.com/wiki/Arma_3:_Mission_Event_Handlers#EntityCreated

2023-04-27 17:33 UTC, killerswin2 commented
um... you do realize that is executed on every created entity. Even butterflies and bunnies. I don't think searching for "curatorModuleF" for every created is smart

2023-04-27 18:20 UTC, CalebSerafin commented
ACE and Zues must create curator modules. Otherwise, people would not be able to promote others to Zeus or create for themselves. It just automates the process of using the debug console to create a module at runtime.

2023-04-27 18:23 UTC, CalebSerafin commented
But yeah, if one of those systems doesn't provide somewhere where you can hook in code, then a background server/HC side script that periodically scans for curator modules and filters the new ones would be the better solution.

2023-04-27 18:36 UTC, killerswin2 commented
I found the ace and zen events

2023-06-25 12:04 UTC, Bob-Murphy commented
@killerswin2 is this ready to review?
If so, please add the label.

2023-07-15 20:18 UTC, jaj22 commented
Ok, doesn't actually work on DS. The documentation is a disaster but the curator events must be added locally to the *player* who's in the curator AI (eg. from initClient), even though they're added to the curator object.

Move the initial zeus even call to initClient, I guess, and remoteExec it from the server events. At least you already have ServerInfo so that part is fine.

2023-07-16 18:09 UTC, rautamiekka requested changes
Not sure if outdated reviews got included since it said I had 4 unsubmitted.

2023-07-16 18:09 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initServer.sqf
> +            // wait encase our event was call first
```suggestion
            // wait in case our event was called first
```

2023-07-16 18:09 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initServer.sqf
> +            // wait encase our event was call first
```suggestion
            // wait in case our event was called first
```

2023-07-16 18:09 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +A3A_hasZen = (isClass(configFile >> "CfgPatches" >> "zen_common"));
```suggestion
A3A_hasZen = (isClass (configFile >> "CfgPatches" >> "zen_common"));
```

2023-07-16 18:12 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initZeusLogging.sqf
> +params ["_curatorModules"]
Missing semicolon.

2023-07-16 19:18 UTC, jaj22 approved these changes
Basic functionality with built-in zeus works. Haven't tested the others because they need multiple players, but it can't do anything show-stopping if it's broken.

2023-07-16 19:26 UTC, merged