started updating templates with new assets
official-antistasi-community/A3-Antistasi pull request #2754
Opened 2023-05-01 13:17 UTC by targetingsnake

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Updated templates with new GM stuff from Gm release 1.5

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Throw on server and play
********************************************************
Notes:

2023-05-06 12:43 UTC, Bob-Murphy requested changes
Please also check if you can crates to:
Trunk of `gm_gc_civ_p601`
Trunk of `gm_gc_army_uaz469_cargo`
Trunk of `gm_ge_civ_w123`

2023-05-06 12:43 UTC, Bob-Murphy commented on A3A/addons/logistics/Nodes/GM.hpp
> +};a
this `a` breaks shit

2023-05-06 12:43 UTC, Bob-Murphy commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ247 : TRIPLES(ADDON,Nodes,Base)
needs height adjustment
![ArmA 3 Screenshot 2023 05 06 - 14 35 00 73](https://user-images.githubusercontent.com/50651578/236624475-17860151-ee3f-4d83-9e2b-3ddcb756b761.png)

2023-05-06 12:43 UTC, Bob-Murphy commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ251 : TRIPLES(ADDON,Nodes,Base)
Height looks weird from the outside. Check if it can be improved.
![ArmA 3 Screenshot 2023 05 06 - 14 38 52 69](https://user-images.githubusercontent.com/50651578/236624669-288130a0-e5bd-45a5-af59-778e6e1b91e7.png)

2023-05-06 12:43 UTC, Bob-Murphy commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ253 : TRIPLES(ADDON,Nodes,Base)
Crate not fitting. Try slapping it on the back seat and then blocking thise.
![ArmA 3 Screenshot 2023 05 06 - 14 41 13 30](https://user-images.githubusercontent.com/50651578/236624713-b1dd72cc-c8e6-4f78-9716-0fd9610cb308.png)

2023-05-06 12:56 UTC, targetingsnake commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ251 : TRIPLES(ADDON,Nodes,Base)
issue here is the underground, it's uneven over the length of the load area, will probably remove the model then

2023-05-06 12:56 UTC, targetingsnake commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ253 : TRIPLES(ADDON,Nodes,Base)
move to bottom will be done

2023-05-06 12:58 UTC, targetingsnake commented
> Please also check if you can crates to: Trunk of `gm_gc_civ_p601` Trunk of `gm_gc_army_uaz469_cargo` Trunk of `gm_ge_civ_w123`

for now i would rather stick with the larger vics, but will look into it with the desert stuff of gm (please open an issue and put the request there)

2023-05-06 13:02 UTC, Bob-Murphy commented
#2761 for trunk spaces

2023-05-07 15:04 UTC, targetingsnake commented on A3A/addons/logistics/Nodes/GM.hpp
> +};a
removed

2023-05-07 15:05 UTC, targetingsnake commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ247 : TRIPLES(ADDON,Nodes,Base)
should be fine now
![20230507170208_1](https://user-images.githubusercontent.com/94396851/236685630-97aa535b-3952-4148-89c0-370ff98ccb1a.jpg)

2023-05-07 15:06 UTC, targetingsnake commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ251 : TRIPLES(ADDON,Nodes,Base)
improved but due to vehicle surface in the inside really doesn't get that much better
![20230507163500_1](https://user-images.githubusercontent.com/94396851/236685659-e276de0d-c969-4ba8-93fb-76a2e266be17.jpg)
![20230507170221_1](https://user-images.githubusercontent.com/94396851/236685665-7bcbaca7-4704-43c2-8ba8-3fcac8eca77f.jpg)
![20230507170222_1](https://user-images.githubusercontent.com/94396851/236685666-c22193ee-9f77-4d00-8639-16f38b9e9753.jpg)

2023-05-07 15:06 UTC, targetingsnake commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ253 : TRIPLES(ADDON,Nodes,Base)
should be fine now
![20230507170213_1](https://user-images.githubusercontent.com/94396851/236685689-3083e4ca-f3ce-42a2-b653-ca7a15972dae.jpg)

2023-05-07 19:44 UTC, Bob-Murphy commented on A3A/addons/logistics/Nodes/GM.hpp
> +class gm_gm_vehicles_gm_land_gm_wheeled_gm_typ2_gm_typ251 : TRIPLES(ADDON,Nodes,Base)
not optimal because of uneven space in the vehicle trunk but let's keep it

2023-05-07 21:46 UTC, Bob-Murphy approved these changes
lgtm

2023-05-07 23:05 UTC, merged