Refactor buyable item management
official-antistasi-community/A3-Antistasi pull request #2773
Opened 2023-05-15 20:47 UTC by jaj22

### What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
This is a rework on top of ##2685. The principle is to pull most of the data for buyable items (eg loot crate, fuel tank) out into a global variable so that other routines can determine how to handle these items without passing information around or special-casing.

Work done along the way:
- Converted HR Garage's confirmPlacement function and all callers to use true place/check callback functions as input rather than hiding code in callbackHandler.
- Moved pack, unpack and open doors actions into the new initObjectRemote.
- Moved surrenderCrate definition to the rebel template. Makes more sense really and it's easier to work with.
- buyItem is now a general function that handles both confirmPlacement and simple placement.
- Reworked the 50m object save functionality to specifically save crewed vehicles and flagged buyable items.

Two key design decisions are a questionable: 
- The data format for A3A_buyableItemHM uncomfortably contains a mix of UI and non-UI stuff, with the tooltips still being in the UI. There's probably a better way to split this 
- Using the object classname as the key might cause issues later: It doesn't fully support faction switching, and assumes that we don't use the same classname for multiple purposes (aside from object packing, which is kinda supported).

There's some cleanup still to be done and it's not sufficiently tested. Kinda tempted to also move logistics to a similar add-all-the-actions-with-conditions, and to implement proper ACE-compatible carry/attach tracking, but neither is strictly related. Also the HQ object carrying isn't merged in yet, although using initObject for those may not be a good idea.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

2023-05-15 21:20 UTC, killerswin2 requested changes

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
Given that players want bigger loot capacity for the crates, I would do something like this.
`[_object , (maxLoad _object) * A3A_loadScalar] remoteExecCall ["setMaxLoad", 2]`

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
A3A_loadScalar is a param, that will need to be set. Defaults to one.

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +// ok, have a classname -> this stuff hashmap, plus an ordered list of classnames.
no need for a ordered list of classnames. The key is already the class name. Keys returns that list already.

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +A3A_buyableItemList = _items select { _x#1 >= 0 } apply { _x#0 };
they are all greater than or equal to zero. just apply on the _items. Tho this isn't needed because the engine command keys returns what you are doing.

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +A3A_buyableItemHM = (_items apply { _x#0 }) createHashMapFromArray _items;
`A3A_buyableItemList = keys A3A_buyableItemHM; `

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +A3A_buyableItemList = _items select { _x#1 >= 0 } apply { _x#0 };
Are you doing this because an items can be negative. If so, change the data requirement. No item should be negative.

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf
> +// TODO: Do we really want rotate on everything?
one day we can separate the rotations. Honestly you could just remove them.

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
> +    _item allowDamage false;            // what, permanent? TODO: make this an item flag?
that was done because of the fuel tanks. They explodes in vanilla.

2023-05-15 21:20 UTC, killerswin2 commented on A3A/addons/core/functions/Save/fn_saveLoop.sqf
> +	// TODO: Do we need to refund the others?
really only the high end stuff needs to be save/refunded

2023-05-15 21:25 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +A3A_buyableItemList = _items select { _x#1 >= 0 } apply { _x#0 };
It's because we might have utility items that you can't buy. It's used for the packed objects atm.

2023-05-15 21:26 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +// ok, have a classname -> this stuff hashmap, plus an ordered list of classnames.
Unfortunately keys is not ordered.

2023-05-15 21:28 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +// ok, have a classname -> this stuff hashmap, plus an ordered list of classnames.
why do you need a ordered list?

2023-05-15 21:32 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initBuyableItems.sqf
> +// ok, have a classname -> this stuff hashmap, plus an ordered list of classnames.
Purely for the buy menu. It's nice to have stuff in a defined and semi-logical order rather than it swapping around pseudo-randomly each time we add something.

2023-05-15 21:33 UTC, jaj22 commented on A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
Ah yeah, meant to do something like that (although just for no-unlocks), and it's pretty easy with initObject. I'll throw it in.

2023-05-20 03:15 UTC, jaj22 commented
Ok, done a bit more cleanup and stringtabled the item names. Gonna take it out of draft now as I can't think of anything else I need to do on it. Tested with ACE now but still needs a DS run.

2023-05-20 03:18 UTC, jaj22 commented on A3A/addons/core/functions/Save/fn_saveLoop.sqf
> +	// TODO: Do we need to refund the others?
Yeah, that's what I've done so far. It'll do for now, as at least nothing got worse. Repair & ammo stations now save when they didn't in 3.2. Could change the medical tent and light to saveable but the save code would need switching to nearObjects.

2023-05-28 21:58 UTC, killerswin2 approved these changes
This should be fine

2023-06-11 21:44 UTC, HakonRydland approved these changes
The changes to the garage looks fine

2023-06-11 21:57 UTC, merged