Feature/add ws content for vanilla factions
official-antistasi-community/A3-Antistasi pull request #2776
Opened 2023-05-19 07:44 UTC by lmllr

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
The Western Sahara DLC includes some vehicles and weapons for vanilla factions.
I've added these to the vanilla factions, based on available camo schemes.

Lore-wise, the GLX 40 is exclusively used by CRTG, but since there where hex and digital camo patterns, I've added it for CSAT and AAF, but not for NATO.

Speaking of, I'm uncertain if I've added the ammo for the GLX correctly:
- I've taken the m79 from SOG PF as reference and added smokes and explosive rounds as primary and pellets as secondary rounds.
-  I've added all compatible ammo types, including 3GL rounds that are otherwise used exclusively by NATO. Even though I've added the GLX to CSAT and AAF.

Please let me know if this is correct, or how I should change it.

### Please specify which Issue this PR Resolves.
none

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes: I did not quite understand what role the militia units play, so I did not change those. Could you elaborate or point me to some documentation to better understand the difference between military and militia units?

2023-07-02 10:28 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> -    _cargoTrucks = ["I_Truck_02_flatbed_lxWS", "I_Truck_02_cargo_lxWS"];
is there any reason to kill the = and replace it with the Append?

The = gives the Better Cargotrucks, the Append throws in the normal Trucks as Vanilla lacks proper Cargotrucks.

2023-07-02 10:35 UTC, lmllr commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> -    _cargoTrucks = ["I_Truck_02_flatbed_lxWS", "I_Truck_02_cargo_lxWS"];
I wasn't aware, that this was the intention of the =, so I assumed it was an oversight.

2023-07-02 17:10 UTC, lmllr commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> -    _cargoTrucks = ["I_Truck_02_flatbed_lxWS", "I_Truck_02_cargo_lxWS"];
For some reason PR didn't sync when I pushed the revert, so I decided to merge the latest unstable branch.

2023-08-27 14:18 UTC, ante185 requested changes

2023-08-27 14:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +if (allowDLCWS) then {
May i suggest that you use (_militaryLoadoutData get "machineGuns") append []; instead of doing it this way?
As suggested here https://github.com/official-antistasi-community/A3-Antistasi/pull/2822#discussion_r1297552513

2023-08-27 14:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
> +    _vehiclesLightUnarmed append ["O_T_APC_Wheeled_02_unarmed_lxWS"];
This APC probably fits better as a truck than Light Unarmed, as it is armoured it's also kinda unfitting to throw into trucks.
It does unfortunately not fit into any of the APC categories as it is unarmed.
Move it to trucks or leave it out is my opinion on it, until such time that we have a category for unarmed APCs or a way to make specific vehicles breachable.

2023-08-27 14:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +        ["glaunch_GLX_camo_lxWS", "", "", "", ["1Rnd_HE_Grenade_shell", "3Rnd_HE_Grenade_shell", "1Rnd_Smoke_Grenade_shell", "3Rnd_Smoke_Grenade_shell", "UGL_FlareWhite_f", "3Rnd_UGL_FlareWhite_f"],
if you go down and look at the unit definition for grenadiers you will see 
`["primary", 6] call _fnc_addMagazines;`
`["primary", 10] call _fnc_addAdditionalMuzzleMagazines;`
To my knowledge the way you have set this up the unit would get 5 rounds from the first magazine array, which is quite an assortment here, and 10 rounds of 40mm pellets

2026-03-24 16:52 UTC, closed without merging