Add parameter to control Loot To Crate distance
official-antistasi-community/A3-Antistasi pull request #2777
Opened 2023-05-20 00:32 UTC by englerj

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    The distance at which the Loot to Crate function scans for objects is now controlled using a startup parameter. It can be set to 10 m (default & original), 15 m, 25 m, or 50 m.

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [x] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

Will be performing some additional testing on dedicated server.

### How can the changes be tested?
Steps: 
1. Start a new game.
2. Change the Loot to Crate distance parameter.
3. Find some loot.
4. Use loot to crate.
5. Profit

********************************************************
Notes:
Please let me know if the distances are acceptable, or you'd like to see more.

2023-05-20 02:33 UTC, rautamiekka requested changes
Typo fixes before it's too late.

_Ohhh I **so** hate GitHub without a mouse ..._

2023-05-20 02:33 UTC, rautamiekka commented on A3A/addons/core/Params.hpp
> +    class LootToCreateDistance
```suggestion
    class LootToCrateDistance
```

2023-05-20 02:33 UTC, rautamiekka commented on A3A/addons/core/functions/LTC/fn_lootToCrate.sqf
> +_targets = nearestObjects [getposATL _container, ["Man"], LootToCreateDistance];
```suggestion
_targets = nearestObjects [getposATL _container, ["Man"], LootToCrateDistance];
```

2023-05-20 02:33 UTC, rautamiekka commented on A3A/addons/core/functions/LTC/fn_lootToCrate.sqf
> +_weaponHolders = nearestObjects [getposATL _container, ["WeaponHolder","WeaponHolderSimulated"], LootToCreateDistance];
```suggestion
_weaponHolders = nearestObjects [getposATL _container, ["WeaponHolder","WeaponHolderSimulated"], LootToCrateDistance];
```

2023-05-20 12:09 UTC, englerj commented on A3A/addons/core/Params.hpp
> +    class LootToCreateDistance
How did I miss this!? 😑
Should be fixed now.

2023-05-20 13:03 UTC, Bob-Murphy requested changes

2023-05-20 13:03 UTC, Bob-Murphy commented on A3A/addons/core/Params.hpp
> +    class LootToCrateDistance
Please remove the 50m option, that's completely overpowered.
I can get that it might be advantageous to be able to cover a larger area, but we have to keep in mind that we are talking about the radius here.

| r  | m²  | ratio  |
|---|---|---|
| 10  | 314  | 1  |
| 15  | 706.5  | 2.25  |
| 25  | 1,926.5  | 6.25  |
| 50  | 7,850  | 25  |

With a radius of 25m you are already covering more than 6x the area you are covering with a 10m radius.
With a 50m radius you are at 25x of the area.

I personally would even remove the 25m option but whatever. Let the people be lazy I guess.

2023-05-20 13:21 UTC, englerj commented on A3A/addons/core/Params.hpp
> +    class LootToCrateDistance
Oh yeah, this is totally a lazy thing 😁.

To your point, would it be more appropriate to label this "Loot to crate radius"?

I'll go ahead and remove the 50m option. Putting it in m3 definitely adds perspective. What if we made the available options 10, 15, and 20 m?

2023-05-20 14:13 UTC, Bob-Murphy commented on A3A/addons/core/Params.hpp
> +    class LootToCrateDistance
I'd be happy with both, the name adjustment and going to 10, 15, 20.

| r  | m²  | ratio  |
|---|---|---|
| 10  | 314  | 1  |
| 15  | 706.5  | 2.25  |
| 20  | 1,256  | 4  |

2023-05-21 21:24 UTC, Bob-Murphy requested changes
Side question, why is this set as a draft?

2023-05-21 21:24 UTC, Bob-Murphy commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10 m","15 m","20 m"};
very nitpicky but no spaces between amount and unit
`10 m` --> `10m`

2023-05-22 00:27 UTC, englerj commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10 m","15 m","20 m"};
Fixed

2023-05-22 00:34 UTC, englerj commented on A3A/addons/core/Params.hpp
> +        texts[] = {"10 m","15 m","20 m"};
A bit out of scope, but it's bothering me now. Would you like me to also adjust the spaces of the 'memberDistance' parameter so it follows the same spacing (e.g. 4km, 5km, 6km)?

2023-05-22 00:47 UTC, englerj commented
@Bob-Murphy, I had it as a draft while I was testing it. Just set it as ready to review.

2023-05-22 01:26 UTC, MeltedPixel commented
IMO, you should now combine your added param with LootToCrateEnabled. Setting distance to 0 should disable the system and remove a redundant param.

Just a thought.

2023-05-27 12:33 UTC, englerj commented
@MeltedPixel, I have applied your suggestion.

2023-05-27 19:55 UTC, MeltedPixel approved these changes
Looks good to me.

2023-06-25 12:10 UTC, Bob-Murphy approved these changes
lgtm

2023-06-25 12:11 UTC, Bob-Murphy commented
@englerj Apologies for the delay.
Looks good besides the merge conflicts.
Please resolve and I'll merge.
Thank you.

2023-07-05 23:07 UTC, merged