Update Spanish translation
official-antistasi-community/A3-Antistasi pull request #2780
Opened 2023-05-23 08:24 UTC by regiregi22

This is an update for the stringtables that lacked Spanish translation.

## What type of PR is this.
3. [X ] Enhancement

### What have you changed and why?
Information: I have added the stringtables for the Spanish language
    

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: Load the mod and check that the strings are translated to spanish

********************************************************
Notes:

2023-05-23 15:13 UTC, Bob-Murphy commented
I changed it to merge into the `unstable` branch as this is our work-branch.

2023-05-23 15:17 UTC, Bob-Murphy requested changes
Please note that you used a different spaces on the stringtables of core, gui and maps than they initially have, hence basically overwriting every line rather than only the ones you worked with.
Please adapt, thank you.

2023-05-24 09:51 UTC, regiregi22 commented
> Please note that you used a different spaces on the stringtables of core, gui and maps than they initially have, hence basically overwriting every line rather than only the ones you worked with. Please adapt, thank you.

I just used tabler as the translation tool, so it used the standard spacing format. I will try to change that.

2023-06-02 22:43 UTC, Bob-Murphy approved these changes

2023-06-08 21:37 UTC, ncermesoni reviewed
Leaving some suggestions, as a native spanish speaker. Great job overall!

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/core/Stringtable.xml
> +        <Spanish>&lt;br/&gt; - repostado</Spanish>
```suggestion
        <Spanish>&lt;br/&gt; - han sido repostados</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/core/Stringtable.xml
> +        <Spanish>Completada carga del servidor.</Spanish>
```suggestion
        <Spanish>Completada la carga del servidor.</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/core/Stringtable.xml
> +        <Spanish>Añadir esta escuadra a la guarnición excederá el límite de la guarnición. Algunos de ellos se unirán a la guartnición, el resto serán descartados y su coste será reembolsado.</Spanis
```suggestion
        <Spanish>Añadir esta escuadra a la guarnición excederá el límite de la guarnición. Algunos de ellos se unirán a la guarnición, el resto serán descartados y su coste será reembolsado.</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/core/Stringtable.xml
> +        <Spanish>La guarnición ha alcanzado su límite, no puedes añadir más unidades nuevas.</Spanish>
```suggestion
        <Spanish>La guarnición ha alcanzado su límite, no puedes añadir nuevas unidades.</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/core/Stringtable.xml
> +        <Spanish>Selecciona la zona hacia la que vas a enviar los tropas seleccionadas como guarnición.</Spanish>
```suggestion
        <Spanish>Selecciona la zona en la que vas a guarnicionar los tropas seleccionadas.</Spanish>
```
https://dle.rae.es/guarnicionar?m=form

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/core/Stringtable.xml
> +        <Spanish>"El Seguimiento del Limpiador de Basura ejecuta un limpiador a causa de superar el umbral de tiempo. Manten supervisado el Limpiador de Basura."</Spanish>
```suggestion
        <Spanish>"El Seguimiento del Limpiador de Basura llevó a cabo una limpieza porque el umbral de tiempo fue superado. Mantén supervisado el Limpiador de Basura."</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/gui/Stringtable.xml
> +        <Spanish>Este objeto puede recolectar el loot \nLa carga máxima de %1 es %2</Spanish>
```suggestion
        <Spanish>Este objeto puede recolectar loot \nLa carga máxima de %1 es %2</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/gui/Stringtable.xml
> +        <Spanish>Partidas Guardados</Spanish>
```suggestion
        <Spanish>Partidas Guardadas</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/gui/Stringtable.xml
> +        <Spanish>Copiar Partida antigua</Spanish>
```suggestion
        <Spanish>Copiar Partida existente</Spanish>
```

2023-06-08 21:37 UTC, ncermesoni commented on A3A/addons/gui/Stringtable.xml
> +        <Spanish>Cargar parámetros antiguos</Spanish>
```suggestion
        <Spanish>Cargar parámetros existentes</Spanish>
```

2023-06-09 21:42 UTC, regiregi22 commented
Great suggestions [ncermesoni](https://github.com/ncermesoni), thank you for that! Un abrazo.

2023-06-25 12:29 UTC, merged