RHS Chdkz AI template
official-antistasi-community/A3-Antistasi pull request #2796
Opened 2023-06-14 22:20 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information: 
Adds a complete AI template for the ChDKZ faction from the RHS modpack.
Adds a ChDKZ flag map marker and corresponding texture.

The ChDKZ as a whole would feel like a mix of the CDF and the AFRF, but utilizing older and more mixed equipment.
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Testing shouldn't be required, it runs with no errors that could be caught by a rpt.
However trying out the template on the test server to assess and adjust balance may be desirable.

********************************************************
Notes:
The ChDKZ while not depicted as the most organised in Arma2 are still able to field large amounts of troops and armor, to a degree arguably beyond that of a paramilitary and able to nearly conquer a whole country without overt outside intervention. That and the fact that they're a good bad guy is why i'm proposing them as an faction.

2023-06-15 03:16 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesHelisTransport", ["RHS_Mi8mt_vvsc","RHS_Mi8mt_vvsc", "RHS_Mi24Vt_vvsc"]] call _fnc_saveToTemplate; //Mi8mt has pk's, Mi24Vt has 12.7 turret only
I think the Mi24Vt is acceptable as it doesn't have real pylons.

2023-06-15 03:17 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesHelisAttack", ["RHS_Mi8MTV3_vvsc","RHS_Mi8MTV3_heavy_vvsc", "RHS_Mi24P_vvsc", "RHS_Mi24V_vvsc"]] call _fnc_saveToTemplate;
The MTV3s are just light attack. Rockets + MGs. In the AFRF template I even put the 24P in light attack, as they have a lot of better helis and the AI are probably useless with the fixed gun. You can set it as a cheap attack heli for variety and tiering. Cost maybe 170 or so.

2023-06-15 03:21 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesAA", ["rhsgref_ins_ural_Zu23","rhsgref_ins_gaz66_zu23", "rhsgref_ins_zsu234"]] call _fnc_saveToTemplate;
Bump the zu trucks down to light armed. Anything in vehiclesAA needs to be armoured, unless you're desperate.

2023-06-15 03:24 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesLightAPCs", ["rhsgref_BRDM2_ins","rhsgref_BRDM2_ins", "rhsgref_BRDM2UM_ins", "rhsgref_BRDM2_HQ_ins"]] call _fnc_saveToTemplate;            //this line determines light APCs
Drop the unarmed one (UM) or put it into trucks or light unarmed. (very light) armour isn't relevant unless the vehicle itself is a threat. BRDMs can go in light armed instead but that's optional depending on what spaces you need to fill.

2023-06-15 03:34 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesIFVs", ["rhsgref_ins_bmd2","rhsgref_ins_bmd1p","rhsgref_ins_bmd1","rhsgref_ins_bmp2k","rhsgref_ins_bmp2d","rhsgref_ins_bmp2e","rhsgref_ins_bmp2","rhsgref_ins_bmp1p","rhsgref_ins_bmp1k","rhs
I'd bump the BMDs down to APC. They might have a lot of firepower but they seem a lot easier to kill than the BMPs, and the cargo guys ride in the open.

2023-06-15 12:52 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesHelisAttack", ["RHS_Mi8MTV3_vvsc","RHS_Mi8MTV3_heavy_vvsc", "RHS_Mi24P_vvsc", "RHS_Mi24V_vvsc"]] call _fnc_saveToTemplate;
I moved the rocket hips up to light attack, and added the AMTSh for varerity

2023-06-16 23:30 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesHelisAttack", ["RHS_Mi8MTV3_vvsc","RHS_Mi8MTV3_heavy_vvsc", "RHS_Mi24P_vvsc", "RHS_Mi24V_vvsc"]] call _fnc_saveToTemplate;
for clarity, when you talk about setting it as a cheap attack heli are you refering to the mtv3s or the Mi24's?

2023-06-16 23:35 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesHelisAttack", ["RHS_Mi8MTV3_vvsc","RHS_Mi8MTV3_heavy_vvsc", "RHS_Mi24P_vvsc", "RHS_Mi24V_vvsc"]] call _fnc_saveToTemplate;
The Mi-24P specifically. You can put it in attack helis but I don't think it's worth the full value.

2023-06-17 03:20 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["vehiclesHelisAttack", ["RHS_Mi8MTV3_vvsc","RHS_Mi8MTV3_heavy_vvsc", "RHS_Mi24P_vvsc", "RHS_Mi24V_vvsc"]] call _fnc_saveToTemplate;
Amended

2023-06-17 21:56 UTC, Lazejun requested changes
See Comments,

Stop being Special and Order the Loadouts like all the Other Templates are.
SF, Military, Police, Militia, Crew.

Not Military, Militia, SF, Police, Crew

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["voices", ["RHS_Male01RUS", "RHS_Male02RUS", "RHS_Male03RUS", "RHS_Male04RUS", "RHS_Male05RUS","Male01RUS","Male02RUS","Male03RUS"]] call _fnc_saveToTemplate;
Stick to RHS or Vanilla Voices.

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +_loadoutData set ["missileATLaunchers", ["launch_O_Oorona_green_F"]];
No Vanilla Weapons in RHS.

That is also Spelled wrong "launch_O_Oorona_green_F" should be "launch_O_Vorona_green_F"

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +//_militiaLoadoutData set ["SMGs", []];
just remove SMGs, dont add dead comments

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["rhs_weap_m76", "", "", "rhs_acc_pso1m2", ["rhsgref_10Rnd_792x57_m76", "rhssaf_10Rnd_792x57_m76_tracer"], [], ""]
There is no need to add a SAF Dependecy.

"rhssaf_10Rnd_792x57_m76_tracer" is not needed.

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["rhs_weap_aks74un", "rhs_acc_pbs4", "", "rhs_acc_ekp8_18", ["rhs_30Rnd_545x39_7U1_AK"], [], ""],
Optic: rhs_acc_ekp8_18 is incompatible with rhs_weap_m92 | Comaptible optics: []

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["rhs_weap_m92", "rhs_acc_pbs1", "", "rhs_acc_1p78", ["rhs_30Rnd_762x39mm_U"], [], ""],
Optic: rhs_acc_1p78 is incompatible with rhs_weap_m92 | Comaptible optics: []

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +//_militiaLoadoutData set ["vests", []];
No need for Dead Comments.

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["rhs_weap_akm", "rhs_acc_dtk", "rhs_acc_2dpZenit", "", ["rhs_30Rnd_762x39mm", "rhs_30Rnd_762x39mm_tracer"], [], ""],
Muzzle: rhs_acc_dtk is incompatible with rhs_weap_akm | Comaptible muzzles: ["rhs_acc_dtk1l","rhs_acc_dtkakm","rhs_acc_pbs1"]

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +_militaryLoadoutData set ["slBackpacks", ["rhs_r148"]];
rhs_r148 has almost no Cargo Space for Equipment.

The SL Loadout for Miltary will always be overfilled, reduce the SL Loadouts Magazines/Equipment or give a Backpack that can carry something.

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +_militaryLoadoutData set ["uniforms", ["rhsgref_uniform_reed","rhsgref_uniform_reed","rhs_uniform_gorka_r_y","rhs_uniform_gorka_r_g","rhsgref_uniform_vsr"]];
to many uniforms with Different Colors, stick to just a few Uniforms with matching Colors to the rest of their Equipment.

throw the worse ones to Militia.

2023-06-17 21:56 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["hgun_Rook40_F", "muzzle_snds_L", "", "", ["16Rnd_9x21_Mag"], [], ""]
No Vanilla Items.

2023-06-17 22:35 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +_militaryLoadoutData set ["slBackpacks", ["rhs_r148"]];
Unfortunate

2023-06-17 22:48 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +_militaryLoadoutData set ["uniforms", ["rhsgref_uniform_reed","rhsgref_uniform_reed","rhs_uniform_gorka_r_y","rhs_uniform_gorka_r_g","rhsgref_uniform_vsr"]];
fixed, but with regret

2023-07-02 11:39 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
> +["rhs_weap_m92", "rhs_acc_pbs1", "", "rhs_acc_1p78", ["rhs_30Rnd_762x39mm_U"], [], ""],
Optic: rhs_acc_1p78 is incompatible with rhs_weap_m92 | Comaptible optics: []

2023-07-05 23:19 UTC, ante185 commented
#2790 and this PR has the flag textures for the map markers in different locations
Should i, while resolving the conflicts, move my texture or theirs, or do i leave all of them where there are currently despite the fact that they should be in the same place?

2023-07-05 23:21 UTC, jaj22 commented
> #2790 and this PR has the flag textures for the map markers in different locations Should i, while resolving the conflicts, move my texture or theirs, or do i leave all of them where there are currently despite the fact that they should be in the same place?

Move theirs if you like. Make sure you use git mv rather than delete/add to reduce the chances of data-spamming.

2023-07-05 23:57 UTC, ante185 commented
> 
> Move theirs if you like. Make sure you use git mv rather than delete/add to reduce the chances of data-spamming.

Done, but might have possibly screwed up in another way instead

2023-07-16 21:28 UTC, ante185 commented
As done as can be following completion of requested changes, pending re-review.

2023-07-18 19:27 UTC, Lazejun approved these changes

2023-07-21 20:50 UTC, merged