3CB TLA ai template
official-antistasi-community/A3-Antistasi pull request #2812
Opened 2023-07-06 21:28 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds AI faction Tanoan Liberation Army (TLA) who uses leftover soviet stocks and what they can seize from the HIDF, and are with brute force and any means necessary trying to take over the island group.
Adds a RHS/3CB rebel template based of the SDK template.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Experimental CAS planes (An-2, Li-2) still need to have their dive bomb parameters dialed in to hit, i need a good way to test them so do please come with suggestions.

********************************************************
Notes:
The SDK template is very much a rider, to provide a faction to play as for Tanoa and other pacific maps, and on any other map where greek FIA, NAPA, or MEI doesn't quite make sense to play as on.

2023-07-18 19:47 UTC, Lazejun requested changes

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_Reb_SDK.sqf
> +private _staticMortars = ["rhsgref_tla_g_2b14"];
the Podnos is specifically avoided as the FIRST Entry for all Templates.

Its super Bouncy and barrely works for AI, give the M252 as first Entry.

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/RHS/RHS_Reb_SDK.sqf
> +    "U_I_C_Soldier_Bandit_2_F",
stop fighting the Format, Only 4 Spaces, no Tabs.

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +        forceDLC[] = {"expansion"};
I dont see any Point for this besides Uniforms that you can simply Put behind a DLC Check.

https://community.bistudio.com/wiki/Arma_3:_DLC_Restrictions

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates.hpp
> +    class 3CB_Reb_SDK : 3CBF_Base
You forgor about this.

Dead Code, no file exists for this.

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/3CB/3CB_AI_TLA.sqf
> +["vehiclesPlanesTransport", ["UK3CB_CW_SOV_O_EARLY_Antonov_AN2","UK3CB_CW_SOV_O_EARLY_LI2","UK3CB_CW_SOV_O_EARLY_LI2"]] call _fnc_saveToTemplate;
the AN2 is horrible, best to avoid it.

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/3CB/3CB_AI_TLA.sqf
> +["vehiclesHelisTransport", ["RHS_Mi24Vt_vvsc","UK3CB_CW_SOV_O_EARLY_Mi8","UK3CB_CW_SOV_O_EARLY_Mi8"]] call _fnc_saveToTemplate;
"RHS_Mi24Vt_vvsc" is a bit too much for Transport.

2023-07-18 19:47 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/3CB/3CB_AI_TLA.sqf
> +_sfLoadoutData set ["uniforms", ["U_I_C_Soldier_Para_1_F","U_I_C_Soldier_Para_2_F","U_I_C_Soldier_Para_3_F","U_I_C_Soldier_Para_4_F","U_I_C_Soldier_Camo_F"]];
Good luck telling Players to not use SDK VS TLA because of the Uniforms.

2023-07-18 20:01 UTC, ante185 commented on A3A/addons/core/Templates/Templates/3CB/3CB_AI_TLA.sqf
> +["vehiclesHelisTransport", ["RHS_Mi24Vt_vvsc","UK3CB_CW_SOV_O_EARLY_Mi8","UK3CB_CW_SOV_O_EARLY_Mi8"]] call _fnc_saveToTemplate;
Vt carries only its little .50 cal turret in the nose, its pylons are empty and are actually disabled so no easy fully armed attack helicopter for a player who captures it.
If that is not fine still, do you want me to take it out of the ChDKZ template as well? #2796

2023-07-18 20:03 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/3CB/3CB_AI_TLA.sqf
> +["vehiclesHelisTransport", ["RHS_Mi24Vt_vvsc","UK3CB_CW_SOV_O_EARLY_Mi8","UK3CB_CW_SOV_O_EARLY_Mi8"]] call _fnc_saveToTemplate;
If they are actually blocked then its fine, if not well yeah better to not hand out a Pylon capable helicopter in 1 of 3 Transport Helis

2023-07-23 22:16 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_Reb_SDK.sqf
> +private _staticMortars = ["rhsgref_tla_g_2b14"];
rgr changing that, but, is that not an issue for the AI templates as well? I had used it here as i've seen it used by several of the other RHS and 3CB templates?

2023-08-10 22:09 UTC, ante185 commented
Changes requested have been implemented or addressed.

2023-11-06 21:25 UTC, ante185 commented
Updated with 3.4.0, and separation of military and militia trucks

2024-03-21 16:35 UTC, closed without merging