Add member & guest lock limits to garage
official-antistasi-community/A3-Antistasi pull request #2829
Opened 2023-07-17 04:36 UTC by jaj22

### What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Heavily-requested community feature. Adds CBA-configurable member and guest limits to garage vehicle locks. It ignores source vehicles, as they are effectively public resources that should be managed by the commander.

Issue that needs resolving: Garage is currently rendered on top of customHint. Not sure why yet.

### Please specify which Issue this PR Resolves.
closes #2823

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

Need to fix the UI rendering order issue.

2023-07-17 23:00 UTC, jaj22 commented
Ok, ran out of plausible ideas for the dialog/hint rendering order problem, so I'll have to bench this for now.

2023-09-02 18:39 UTC, killerswin2 approved these changes

2023-09-03 13:48 UTC, Bob-Murphy requested changes

2023-09-03 13:48 UTC, Bob-Murphy commented on A3A/addons/garage/Public/config.inc
> +    ["HR_GRG_LockLimit_Member", "SLIDER", ["Member lock limit", "Maximum vehicles that can be locked by a member"], [HR_GRG_Prefix,"Garage"],
localize?

2023-09-03 13:48 UTC, Bob-Murphy commented on A3A/addons/garage/Public/config.inc
> +    ["HR_GRG_LockLimit_Guest", "SLIDER", ["Guest lock limit", "Maximum vehicles that can be locked by a guest"], [HR_GRG_Prefix,"Garage"],
localize?

2023-09-03 15:52 UTC, Bob-Murphy approved these changes
lgtm

2023-09-03 15:52 UTC, merged