Moving Ace Init
official-antistasi-community/A3-Antistasi pull request #2842
Opened 2023-07-21 22:07 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
    Moves the ACE initialization code to it's own function. Adds some more logging of specific actions that players can do with medical items.

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

2023-07-21 22:08 UTC, killerswin2 commented
Finally, had to fix my fork for it to work right!

2023-08-02 15:33 UTC, jaj22 requested changes

2023-08-02 15:33 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> -    if (A3A_hasACEMedical) then { call A3A_fnc_initACEUnconsciousHandler };
Problem here is that you've lost the installation of this handler on headless clients.

This handler is different from the others you moved to initACE: The others are all player-specific and don't need installation on a DS or HC, while the unconscious handler needs to be installed everywhere.

Maybe best to rename initACE to something more obviously player-specific, remove the iniACE call from initServer and keep both the initACEUnconscious handler calls where they are.

2023-08-02 15:33 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +["ace_explosives_place", {
While we're adding long-missing event handlers, let's get the ACE throw EH in here to fix the old undercover grenade throw exploit. For some reason I added it to punishment and not initClient.

Something like this:
```
    ["ace_throwableThrown", {
        params ["_unit", "_throwable"];
        if (isCaptive player && _unit == player) then { player setCaptive false };
    }] call CBA_fnc_addEventHandler;
    ```

2023-08-02 15:33 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +};
If we're restricting this file to player stuff then move this back to initServer (or another file), I guess.

2023-08-02 15:33 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +    call A3A_fnc_initACEUnconsciousHandler;
And lose this one.

2023-08-02 23:08 UTC, rautamiekka requested changes
Consistency fixes.

2023-08-02 23:08 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +        if(_usedItem in ["ACE_atropine", "ACE_epinephrine", "ACE_morphine"]) then {
```suggestion
        if (_usedItem in ["ACE_atropine", "ACE_epinephrine", "ACE_morphine"]) then {
```

2023-08-02 23:08 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +if(isServer) then {
```suggestion
if (isServer) then {
```

2023-08-02 23:08 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +if(A3A_hasACE) then {call A3A_fnc_initACE};
```suggestion
if (A3A_hasACE) then {call A3A_fnc_initACE};
```

2023-08-02 23:08 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_initServer.sqf
> +if(A3A_hasACE) then {call A3A_fnc_initACE};
```suggestion
if (A3A_hasACE) then {call A3A_fnc_initACE};
```

2023-08-03 04:47 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initACE.sqf
> +    call A3A_fnc_initACEUnconsciousHandler;
Missed this one btw. It doesn't have multiple init protection so you can't call it here.

2023-08-13 01:06 UTC, jaj22 commented
Fixed a bug in the throwableThrown EH, cleared out the surplus initACEUnconsciousHandler call and did some minor cleanup. Should be good to go now.

Tested on both localhost and DS with ACE:
- Logging with ACE-created zeus.
- Action-blocking on HQ objects and rebel group join/leave.
- Injector usage logging.
- Undercover removal on ACE throw.

 Non-ACE behaviour should be unchanged.

2023-08-19 21:31 UTC, Bob-Murphy approved these changes
lgtm

2023-08-19 21:32 UTC, merged