Improve SPE_IFA Template Vehicle Variety
official-antistasi-community/A3-Antistasi pull request #2859
Opened 2023-07-26 13:31 UTC by stutpip123

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-07-26 20:17 UTC, Bob-Murphy commented
@stutpip123 
Please make sure that the logistics-capable vehicles are also set up with the Antistasi Logistics System.
I don't know if they are all covered, but as a reminder this message.

2023-07-26 20:43 UTC, stutpip123 commented
that does need doing, thanks for the reminder

2023-07-26 21:30 UTC, stutpip123 commented
i believe thats the nodes sorted
theres no additional cargo items/statics etc to add as Spearhead has it all covered

2023-07-26 21:41 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
I don't think the Flak38 has any cargo slots so it can't go in IFVs. Hard rule. Generally anything with an open gunner needs to be reduced-price if it's put in vehiclesAA too, because the assumption is that those are fully armoured vehicles and can't be disabled with one bullet.

2023-07-26 22:06 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
I wasn't sure what the difference for APC and ifv was. Not sure why you have the ifv carry troops and the APC not do so, that's the opposite of each ones primary purpose

2023-07-26 22:07 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
The aa vehicle flak38 is not my change but yes that would apply to the sdkfz 7 aa

2023-07-26 22:07 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
APC and lightAPC have the same troops transport requirement. The differences are the war tiers they're used at and the resource cost.

2023-07-26 22:12 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
Thanks for the clarification

2023-07-27 09:09 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
when you say cargo slots, do you mean just troop passenger slots, or full cargo nodes?

2023-07-27 09:38 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
so interesting thing, the M18 Hellcat cannot have troops ride on its back, yet your official released templates use it in the IFV section

2023-07-27 10:04 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
i believe I have now moved all the vehicles that cannot carry troops out of the APC/IFV sections and either into the light armed or tanks respectively

2023-07-27 11:02 UTC, Lazejun commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
IFV is for cannot carry troops but big fire power.

M18 is to soft to be a "Tank"

2023-07-27 11:08 UTC, stutpip123 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
It would help if you guys weren't contradicting each other.

2023-07-27 15:11 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesIFVs", ["SPE_PzKpfwIII_N", "SPE_ST_OpelBlitz_Flak38", "SPE_PzKpfwIII_M", "SPE_PzKpfwIII_L"]] call _fnc_saveToTemplate;
<sigh>

Ok, the ground vehicle selection works like this: There are two general categories of vehicles, transport and support. The first vehicle in a QRF is always a transport, and after that it's randomized. This guarantees that there are at least some ground troops in any QRF, and the retreat condition is based on the condition of those troops. Hence if there are vehicles in any of the transport categories that don't carry troops, QRFs containing them may immediately retreat.

So yes, the Hellcat shouldn't be in IFVs (or APCs or lightAPCs) if it can't carry troops. What I'll probably do for 3.4 is add a lightTanks category for this stuff, as there's a lack of middle ground between tanks and light armed for some templates.

There's also some odd stuff with lightArmed vs lightAPC. Light armed is a dual category: There's a specific check for whether those vehicles carry 4+ troops in addition to the crew, so some vehicles from light armed can show up as both transports and support. The lightAPC category cuts into both APCs and trucks, so should ideally only be used for vehicles with 6+ cargo, because otherwise it'll cause the vehicle to infantry ratio to increase. Leaving lightAPC empty is preferred if there aren't vehicles that fit the role well (smaller armed vehicles should go in lightArmed), although what you can also do in low-tech templates is put trucks in there and set their value with vehicle attributes.

2023-07-27 19:33 UTC, stutpip123 commented
I have loaded the mission in LAN mode and checked factions for vehicle spawning and the rebel buy menu, all seems to be working fine. 
further more thorough testing will be wanted of course

2023-07-29 08:11 UTC, stutpip123 commented
My group has now played with the changes applied on my dedicated server, so far no issues have been found.

2023-08-03 19:54 UTC, MeltedPixel approved these changes
Changes look fine from a code stand point. Template changes will need additional approval from the team.

2023-09-23 18:16 UTC, killerswin2 commented
PENDING, TO BE MERGE A BRANCHING FOR TESTING

2024-03-24 03:11 UTC, ante185 requested changes
A very late review, having worked on some pure iron front templates recently i felt like i could have a say about some of these changes

2024-03-24 03:11 UTC, ante185 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
> +["vehiclesTruck", ["LIB_US6_Open"]] call _fnc_saveToTemplate;
Use the marked FFI citroen trucks instead

2024-03-24 03:11 UTC, ante185 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
> +["vehiclesLightUnarmed", ["LIB_Kfz1_Hood_sernyt","LIB_UK_Willys_MB_Hood"]] call _fnc_saveToTemplate;
There's two FFI marked Gaz M1 cars to use here instead.
vehicleBasic could be replaced with a hood-less Willys, the back of it is large enough to carry a small crate like what quadbikes do, increase its price correspondingly.

2024-03-24 03:11 UTC, ante185 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
> +["vehiclesLightArmed", ["LIB_UK_Willys_MB_M1919","LIB_Kfz1_MG42_sernyt"]] call _fnc_saveToTemplate;
remove the MG42 Sernyt - frankly letting WW2 rebels buy machineguns like this is a travesty, but one we have to live with

2024-03-24 03:11 UTC, ante185 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["vehiclesAPCs", ["LIB_SdKfz251_FFV", "SPE_PzKpfwIII_J"]] call _fnc_saveToTemplate;
Some of these tanks might be worth throwing into the lightTank category

2024-03-24 03:11 UTC, ante185 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
> +["voices", ["Male01Ger", "Male02Ger", "Male03Ger", "Male04Ger", "Male05Ger"]] call _fnc_saveToTemplate;
Not the most quality voices but will be acceptable.

2024-08-09 09:41 UTC, closed without merging

2024-08-09 09:41 UTC, stutpip123 commented
Should be no need for this now Spearhead has every required asset except Transport Planes and Civilian Vehicles