first iteration
official-antistasi-community/A3-Antistasi pull request #2863
Opened 2023-07-26 21:24 UTC by Giddius

Works, but is still reliant on jsut loop counts## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Created new way to keep track of GC, notify about time since Gc and trigger auto GC.
It now keeps track of when an manual GC happens and restarts the loop also it is done so, it is easy to change. 	

Changed the `disabled` value from 99999 to 0, because if 0 is a viable value it would probably break the sleeps or block the server to hell.

Added `time until Auto-GC` to the reminder and also added an `final warning` that happens 2 minutes before an auto-GC.
    
Discussion:

To give the player the `time until Auto-GC` I had to change the Stringtable text, because I do not know the translations of this new text, I just added the second parameter to it. Is there a special way how we should handle those kind of situations?

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
- start a game
- set the auto-GC threshold to a value that is not `disabled`
- check if the reminder, the final-warning and the auto-GC happens
- do a manual GC and check if the auto-GC happens after the set value in relation to this manual GC.
********************************************************
Notes:

2023-07-27 02:40 UTC, killerswin2 commented on A3A/addons/core/Stringtable.xml
>        <Key ID="STR_A3A_GCTracker_tracker_notification">
Cough, cough maybe you do a little German?? ;)

2023-07-27 02:48 UTC, killerswin2 requested changes

2023-07-27 02:48 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        sleep 1;
hmm... I how would you feel if we made the sleep 2 seconds instead of one.

2023-07-27 02:48 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    [localize "STR_A3A_GCTracker_tracker_title", format [localize "STR_A3A_GCTracker_tracker_notification", _timeSinceLastGC, _timeUntilForcedGC]] remoteExec ["A3A_fnc_customHint", 0];
we don't need the hint on the server. 
```
remoteExec ["A3A_fnc_customHint", -2];
```

2023-07-27 02:48 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    ["Final Warning", format ["Automatic Garbage Clean incoming in %1", _timeUntilForcedGC]] remoteExec ["A3A_fnc_customHint", 0];
same as before, no need for server to exec the hint, there is no display for it.

2023-07-27 03:13 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        sleep 1;
Could be done of course, I just thought that a check between two non dynamic numbers would be really cheap anyway.

2023-07-27 03:14 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    [localize "STR_A3A_GCTracker_tracker_title", format [localize "STR_A3A_GCTracker_tracker_notification", _timeSinceLastGC, _timeUntilForcedGC]] remoteExec ["A3A_fnc_customHint", 0];
I thought I just copied these lines from the original script, I probably missed the remoteexec, will change it.

2023-07-27 12:29 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        sleep 1;
Why not use `uiSleep`, unless there only needs to be a little bit of a delay at the absolute minimum ?

2023-07-27 12:32 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    [localize "STR_A3A_GCTracker_tracker_title", format [localize "STR_A3A_GCTracker_tracker_notification", _timeSinceLastGC, _timeUntilForcedGC]] remoteExec ["A3A_fnc_customHint", 0];
Would be much better if as many of the custom hints would be locally defined as possible, so only the bare minimum would broadcast over the network.

2023-07-27 15:41 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        sleep 1;
As far as I checked the only difference between `sleep` and `uiSleep` seems to be that the latter takes time acceleration into account and the former just uses the OS time. At least according to the Biki, or do you have some differing info?

2023-07-27 15:42 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    [localize "STR_A3A_GCTracker_tracker_title", format [localize "STR_A3A_GCTracker_tracker_notification", _timeSinceLastGC, _timeUntilForcedGC]] remoteExec ["A3A_fnc_customHint", 0];
As I am still getting to grips with sqf, can this be achieved by changes to this script? And if yes, ehat would I need to do generally?

2023-07-27 15:43 UTC, Giddius commented on A3A/addons/core/Stringtable.xml
>        <Key ID="STR_A3A_GCTracker_tracker_notification">
I guess you want me to add a german translation? I didn‘t want to muddle this pull request and also not encroach on the translation teams turf. Or are you meaning something else?

2023-07-27 17:36 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        sleep 1;
Changed it to 2 seconds

2023-07-27 17:37 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    ["Final Warning", format ["Automatic Garbage Clean incoming in %1", _timeUntilForcedGC]] remoteExec ["A3A_fnc_customHint", 0];
changed the remoteExcec to -2

2023-07-27 18:07 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        sleep 1;
> As far as I checked the only difference between `sleep` and `uiSleep` seems to be that the latter takes time acceleration into account and the former just uses the OS time. At least according to the Biki, or do you have some differing info?

That's also all I know, point being the entered value would be more truthful even if not completely.

2023-07-29 17:14 UTC, killerswin2 commented on A3A/addons/core/Stringtable.xml
>        <Key ID="STR_A3A_GCTracker_tracker_notification">
lol, no worries

2023-07-29 17:14 UTC, killerswin2 approved these changes

2023-07-29 17:33 UTC, rautamiekka requested changes

2023-07-29 17:33 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        if not (_storedLastGCTime isEqualTo A3A_lastGarbageCleanTime) then {
```suggestion
        if (_storedLastGCTime isNotEqualTo A3A_lastGarbageCleanTime) then {
```

2023-07-29 17:33 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +// Noop function just to be save and to not break the Context Queue format.
```suggestion
// Noop function just to be safe and to not break the Context Queue format.
```

2023-07-29 17:33 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +    if  (call _fnc_conditionalSleep) then {
```suggestion
    if (call _fnc_conditionalSleep) then {
```

2023-07-30 02:35 UTC, Giddius commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        if not (_storedLastGCTime isEqualTo A3A_lastGarbageCleanTime) then {
Just your preference or is there any benefit to it?

Please not that I see `makes it more readable` as being a `preference`.

2023-07-30 17:27 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf
> +        if not (_storedLastGCTime isEqualTo A3A_lastGarbageCleanTime) then {
I suppose it boils down to pref since it's pretty much only better readability, a lot at that. No clue if there's some internal optimization going on.

2023-08-12 12:48 UTC, Giddius commented
@jaj22 reverted it back to `0`, is this ok now?

2023-09-02 18:55 UTC, killerswin2 approved these changes

2023-09-03 13:43 UTC, Bob-Murphy requested changes
transfer non-english stringtable changes to tolgee

2023-09-23 19:58 UTC, Giddius commented
It should not matter if the non-english stuff was changed here, the tolgee sync will just ignore those and only apply the english changes. So I would feel safer by not editing the whole file now and just letting the syncer handle it.

2023-09-23 20:06 UTC, Bob-Murphy approved these changes

2023-09-23 20:07 UTC, merged