PATCOM Garrisons minor fixes and adjustments
official-antistasi-community/A3-Antistasi pull request #2876
Opened 2023-07-29 06:46 UTC by MeltedPixel

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Changed how garrison units are distributed to buildings. Instead of filling up all building positions and then moving to the next building in the list, the script now takes the amount of garrison-able buildings and units and distributes them evenly with a defined minimum allowed in each building.

Changes how finding garrison-able buildings functions. Instead of it being a one or the other choice,  it now just uses the A3A building blacklist and checks for pre-defined building positions in the whitelist. If pre-defined positions are not found, we use the default ones and randomize.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-07-29 06:49 UTC, MeltedPixel commented
It doesn't specifically close #2869, but it does sorta mesh with it.

2023-08-02 22:47 UTC, jaj22 approved these changes
Seems like good changes. Made a couple of optional notes.

2023-08-02 22:47 UTC, jaj22 commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
>              };
Should throw an error otherwise. It'll only happen if a whitelist entry is busted.

2023-08-02 22:47 UTC, jaj22 commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
>          private _unit = _units select 0;
You can combine these with the deleteAt:
`private _unit = _units deleteAt 0;`
`private _position = _buildingPositions deleteAt 0;`

2023-08-03 00:29 UTC, MeltedPixel commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
>              };
Resolved in [6ac8eda](https://github.com/official-antistasi-community/A3-Antistasi/pull/2876/commits/6ac8edad90e0aa28f073e0d8b6d957b8ef5a155b)

2023-08-03 00:29 UTC, MeltedPixel commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
>          private _unit = _units select 0;
Resolved in: [6ac8eda](https://github.com/official-antistasi-community/A3-Antistasi/pull/2876/commits/6ac8edad90e0aa28f073e0d8b6d957b8ef5a155b)

2023-08-06 15:27 UTC, ante185 commented
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/fcd214ef-5d7d-40be-a5bc-e1bea359e394)
this seems to happen much more reliably with this. Presumably because all the building-units don't end up all in the same building?

2023-08-07 17:47 UTC, ante185 commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +A3A_staticBuildingClasses = ["Land_BagBunker_Small_F", "Land_BagBunker_01_small_green_F"];
CUPs bunkers are "Fort_Nest", "Land_fortified_nest_small" and should go in here as well

2023-08-09 10:05 UTC, Bob-Murphy commented
Will check next week

2023-08-10 22:04 UTC, ante185 requested changes

2023-08-10 22:04 UTC, ante185 commented on A3A/addons/core/functions/init/fn_initVarCommon.sqf
> +A3A_staticBuildingClasses = ["Land_BagBunker_Small_F", "Land_BagBunker_01_small_green_F"];
CUPs bunkers are "Fort_Nest", "Land_fortified_nest_small", Land_fortified_nest_small_EP1" and should go in here as well

2023-08-13 03:44 UTC, jaj22 commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
> +    };
Hmm. nearObjects with a short range and a single class is cheap. nearEntities is even cheaper. Why not ditch staticBuildingClasses and instead simply check the building positions against nearby statics? The per-building loop would need a minor rejig but that's about it.

2023-08-20 21:54 UTC, MeltedPixel commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
> +    };
Converted in [e79482f](https://github.com/official-antistasi-community/A3-Antistasi/pull/2876/commits/e79482f703e522e6385001e7a568cc6979d4fd51) Good suggestion, much cleaner.

2023-08-20 21:58 UTC, jaj22 commented on A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
> +    };
I was suggesting to go further than that and check in the per-position loop rather the per-building loop. Otherwise it prevents buildings having both statics and troops placed in them.

2023-08-20 23:49 UTC, jaj22 approved these changes
Looks good.

2023-08-20 23:51 UTC, MeltedPixel commented
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/1194692/f58b3e27-8fb5-4073-95ba-2b2196fd38d3)
Ignore little guy close to the static in the building. He was running to arm it, but did not spawn close to it.

2023-08-21 14:18 UTC, ante185 commented
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/74364b2b-ce23-466d-9c59-6c2c25ccb2b8)
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/a5a84235-6da3-42b1-829e-6a2c35c601f0)
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/ab9372ec-ce61-4885-8a62-64a91c156218)
tried this out on my isla duala port, and the stuff looks great!
It seems to be decent at putting the garrison in either good overwatch location or at unexpecting angles, some positions are less than ideal but with the units spread out it's less of a big deal (No more wiping a resource or factory with a single nade into a warehouse)

2023-08-21 17:32 UTC, rautamiekka requested changes
Capitalization fix.

2023-08-27 23:16 UTC, merged