logistics_localization
official-antistasi-community/A3-Antistasi pull request #2881
Opened 2023-07-30 13:36 UTC by Bob-Murphy

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
localized logistics

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### Notes:
- needs adaptation to implement the ones in `fn_addOrRemoveObjectMass` as commented in the file
- needs proper testing

2023-07-30 16:35 UTC, targetingsnake requested changes
rest looks good

2023-07-30 16:35 UTC, targetingsnake commented on A3A/addons/core/functions/SalvageRope/fn_salvageRope.sqf
> +        [localize "STR_antistasi_logistics_logistics", format ["%1 does not have enough space to load %2.", _vehicleName, _cargoName]] remoteExec ["A3A_fnc_customHint", remoteExecutedOwner];
shouldn't there also be a localize in the format[]-part?

2023-07-30 16:35 UTC, targetingsnake commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
>  private _text = format [
Todo: Fix Block with localite

2023-07-31 16:00 UTC, MeltedPixel commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
>  private _text = format [
@targetingsnake It's not too bad. You just need to change around the assembly of the text. Meaning, you'll need to separate the image so that line 99 becomes `_text = _image + _text + _msg;` 

Once you separate the image from the format, you just need to move the structured text to the string table using HTML Entities. https://www.w3schools.com/html/html_entities.asp

Here's an example from TFAR: https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/212c022ef1aef18621dd2aecc51717caea5b6e71/addons/core/stringtable.xml#L2413C86-L2413C86

2023-08-03 05:26 UTC, MeltedPixel commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
>  private _text = format [
Resolved in [e54abbc](https://github.com/official-antistasi-community/A3-Antistasi/pull/2881/commits/e54abbcaa1bbc1cc79e318456a96fde39db017ab)

2023-08-03 05:26 UTC, MeltedPixel commented on A3A/addons/core/functions/SalvageRope/fn_salvageRope.sqf
> +        [localize "STR_antistasi_logistics_logistics", format ["%1 does not have enough space to load %2.", _vehicleName, _cargoName]] remoteExec ["A3A_fnc_customHint", remoteExecutedOwner];
Resolved in [e54abbc](https://github.com/official-antistasi-community/A3-Antistasi/pull/2881/commits/e54abbcaa1bbc1cc79e318456a96fde39db017ab)

2023-08-03 16:48 UTC, MeltedPixel commented
@targetingsnake When you get a second, can you check the change request and approve when able.

2023-08-03 17:19 UTC, targetingsnake approved these changes
lgtm

2023-08-09 10:10 UTC, merged