Added self-revive and modified damage system
official-antistasi-community/A3-Antistasi pull request #2890
Opened 2023-08-02 02:22 UTC by jaj22

### What type of PR is this.
1. [X] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Optional self-revive mechanic:
- Requires first aid kit.
- Once per 5min, reset by vehicle box restore and respawning.
- During 5min timeout, adds desaturation effect and increased sway.

New stuff is mostly stringtabled.

I was going to add a second self-revive method where you transfer bodies to a squad AI, but that's on hold for a player event handler refactor.

Modifications to Antistasi damage system:
- Reworked unarmoured body damage reduction. The old system had a hard 0.9 cap on body shots that sometimes worked. This system instead rescales body armour effects so that a level 1 vest is the baseline.
- Reworked hitpoint-dependent down/kill results. Downing a unit by limb shots now consistently marks them as easier to revive. Downing an enemy with a body or head shot has a chance of killing them outright.
- Fixed various issues with finishing off downed units. Should now be consistent and intuitive, rather than requiring leg shots or a whole SMG magazine.
- Fixed automatic hard-kill from 50cal. Large bullets essentially kill a unit twice in two different frames, so that was a pain.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

It's had a fair amount of testing but probably needs more. Shouldn't need a DS test though, it's almost all local stuff aside from the one healing-box call.

2023-08-18 03:31 UTC, wriley commented
I've been using this on my locally hosted single player game the last couple play sessions and it works great. It's nice having the option of getting back into the fight when your AI are busy or just standing there watching you bleed to death. With the desaturation and weakened condition it doesn't feel OP to me

2023-08-20 18:57 UTC, wriley commented
During play testing I did run across a case where the self-revive didn't work. I was in a truck and got hit by what I think was a grenade launcher. The truck exploded and I was down beside the truck. Using the H key did the usual popup about being back up and not feeling great but I was still stuck in a downed state. Another press of H informed me I had already used the revive. Maybe the explosion did more damage than normal?
https://imgur.com/a/GvdtmbT

2023-08-20 19:42 UTC, jaj22 commented
> During play testing I did run across a case where the self-revive didn't work. I was in a truck and got hit by what I think was a grenade launcher. The truck exploded and I was down beside the truck. Using the H key did the usual popup about being back up and not feeling great but I was still stuck in a downed state. Another press of H informed me I had already used the revive. Maybe the explosion did more damage than normal?

Nah, the revive just clears the incap var and sets global damage to 0.5 so it's not really possible for it to break. What seems most likely here is that you were downed again immediately after using the self-revive, as there's no invulnerability period. Cook off explosion or fire, maybe.

2023-08-20 20:49 UTC, MeltedPixel commented
> 



> > During play testing I did run across a case where the self-revive didn't work. I was in a truck and got hit by what I think was a grenade launcher. The truck exploded and I was down beside the truck. Using the H key did the usual popup about being back up and not feeling great but I was still stuck in a downed state. Another press of H informed me I had already used the revive. Maybe the explosion did more damage than normal?
> 
> Nah, the revive just clears the incap var and sets global damage to 0.5 so it's not really possible for it to break. What seems most likely here is that you were downed again immediately after using the self-revive, as there's no invulnerability period. Cook off explosion or fire, maybe.

Should we maybe add in like a 5 second invulnerability period?

2023-08-21 23:33 UTC, jaj22 commented
> Should we maybe add in like a 5 second invulnerability period? This is mostly for small groups and single player anyway. I don't think we really need to worry about it being "over powered". Or "Abused".

Hmm. I'm not super-happy about this idea. One issue is that setCaptive is cleared (nearly) immediately by fn_unconscious, so if there's an enemy watching you when you revive, they'll magdump you for five seconds with no effect, which looks very weird. Other way is that we give every rebel revive that 5-second immunity and kill setCaptive at the same timing. I'll have to think whether that's likely to cause further problems.

2023-08-22 00:03 UTC, jaj22 commented
There's some related stuff here with undocumented behaviour. Antistasi will setCaptive on down but only if the killer wasn't invaders. Not sure why this is useful as vanilla AI behaviour on localhost seems to stop shooting as soon as the target is unconscious, and start again once they're conscious. On the other hand I recall getting magdumped with ACE on community, so maybe it's working around an Arma locality bug.

2023-08-22 00:30 UTC, jaj22 commented
Ah whatever, this works well on localhost and at worst it'll be a bit flaky on DS, but players won't stick with allowDamage false or anything bad like that. Five seconds is about the same time as the rollout animation takes, btw, so if there's an enemy looking right at you it's still a shootout.

Threw in a fix for the revive parameter not working for players. Not strictly related to this PR but close enough.

2023-08-22 21:20 UTC, rautamiekka requested changes

2023-08-22 21:20 UTC, rautamiekka commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +    sleep _this;
```suggestion
    uiSleep _this;
```

2023-08-22 21:20 UTC, rautamiekka commented on A3A/addons/core/functions/Revive/fn_selfReviveReset.sqf
> +        sleep 10;
```suggestion
        uiSleep 10;
```

2023-08-22 21:28 UTC, jaj22 commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +    sleep _this;
1. uiSleep is identical to sleep except in SP, which we don't support.
2. Even in SP, uiSleep isn't appopriate for any of these. Consider whether you'd want them to continue if the player hit escape. The answer is clearly no for everything except the ppEffect, which I'd lean no on.

2023-08-22 21:43 UTC, rautamiekka commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +    sleep _this;
Fair enough, totally forgot about that.

2023-09-02 00:59 UTC, killerswin2 commented on A3A/addons/core/functions/EventHandler/fn_enemyUnitKilledEH.sqf
> +			[0,-2,getPosATL _victim] remoteExec ["A3A_fnc_citySupportChange",2];
good change

2023-09-02 01:01 UTC, killerswin2 commented on A3A/addons/core/functions/Revive/fn_actionRevive.sqf
> +private _timer = [10, A3A_reviveTime] select (_player or _inPlayerGroup);
lol, branch-less programming

2023-09-02 01:15 UTC, killerswin2 requested changes

2023-09-02 01:15 UTC, killerswin2 commented on A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
> +    // Contact report generation for PvP players
just remove the dead code, we have version tracking

2023-09-02 01:15 UTC, killerswin2 commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +private _hasFAKs = _firstAidKits arrayIntersect items player;
I feel like someone told me that items returns a large array. Could we replace this with uniqueUnitItems?

2023-09-02 01:31 UTC, jaj22 commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +private _hasFAKs = _firstAidKits arrayIntersect items player;
Because `uniqueUnitItems` also includes assigned items and magazines, it's far slower than `items` for any vanilla case I can find. Might be a bit different with ACE medical items, but that's not relevant here.

Now `findAny` would be faster than `arrayIntersect` here, but slightly messier.

2023-09-02 18:09 UTC, rautamiekka commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +private _hasFAKs = _firstAidKits arrayIntersect items player;
Agree on being messier, but faster is more important:
```sqf
private _hasFAKs = _firstAidKits findAny items player isNotEqualTo -1;
```

2023-09-02 18:42 UTC, killerswin2 commented on A3A/addons/core/functions/Revive/fn_selfRevive.sqf
> +private _hasFAKs = _firstAidKits arrayIntersect items player;
Yeah, should do

2023-09-23 18:15 UTC, killerswin2 approved these changes
Approved, after fixing merge confilcts

2023-09-24 16:17 UTC, jaj22 commented on A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf
> +    // Contact report generation for PvP players
Done.

2023-09-24 17:07 UTC, Bob-Murphy approved these changes

2023-09-24 17:07 UTC, merged