CUP civilian vehicles pack
official-antistasi-community/A3-Antistasi pull request #2919
Opened 2023-08-20 18:11 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

Added civilian vehicles from CUP to AddonVics
    
1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Running around cities?
********************************************************
Notes:
!!!!
 requiredAddons[] = {"CUP_Vehicles"}; is 99% wrong, I just don't know what to wright here.

2023-09-03 10:01 UTC, Lazejun requested changes

2023-09-03 10:01 UTC, Lazejun commented on A3A/addons/core/Templates/AddonVics/cup_veh_Civ.sqf
> +//_addon set ["vehiclesCivHeli", [    //planes for test
No need to add Dead code

2023-09-23 13:12 UTC, Bob-Murphy commented on A3A/addons/core/Templates/AddonVics/cup_veh_Civ.sqf
> +//_addon set ["vehiclesCivHeli", [    //planes for test
done

2023-09-23 15:04 UTC, Bob-Murphy reviewed
Please check if the vehicles which could load cargo are defined in logistics/Nodes/CUP.hpp and define the ones which are not covered.

2023-10-07 19:24 UTC, killerswin2 approved these changes

2023-10-07 20:09 UTC, merged

2023-10-16 18:58 UTC, wersal454 commented
Hello there! so you merged my PR, but did you test it? Is it working like it should? For example: playing with vanilla factions but additionally civis will use vehicles from CUP and vanilla vehicles. Problem originally was that CUP vehicles just won't spawn no matter what. So if you fixed it I would love to know how so me or guys from Ultimate can fix similar PR there.

2023-10-16 21:11 UTC, jaj22 commented
In future do say if your PR doesn't work. PRs are generally assumed to run, and reviewers will be looking for other things.