core localization ai --> missions
official-antistasi-community/A3-Antistasi pull request #2920
Opened 2023-08-21 22:44 UTC by Bob-Murphy

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Adds 351 new strings from the following folders:
- core/functions/AI
- core/functions/Ammunition
- core/functions/Base
- core/functions/Convoy
- core/functions/Create
- core/functions/Dialogs
- core/functions/init
- core/functions/Intel
- core/functions/LTC
- core/functions/Missions

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### Notes:
- needs some adaptations to fully implement all strings
- needs proper testing
- needs check for typos and punctuation

Dev Team: Feel free to commit changes directly to this branch rather than asking me.

2023-09-02 00:53 UTC, killerswin2 commented on A3A/addons/core/Stringtable.xml
> +	      <Original>Artillery Support</Original>
bad spacing

2023-09-02 16:05 UTC, killerswin2 requested changes

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
> +    "Load loot from crate to vehicle",//localize "STR_A3A_fn_ltc_init_addact_ltv"
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
> +    "Load loot to crate", //localize "STR_A3A_fn_ltc_init_addact_ltc"
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_placementselection.sqf
> +// localize "STR_A3A_fn_base_placeselec_petros_dead" - implement into line 8
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_onHeadlessClientDisconnect.sqf
> +//STR_A3A_fn_base_hcdics_hc - needs implementation in line 14
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +        _flag addAction ["<t>Release POW</t> <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_unbind_ca.paa' size='1.6' shadow=2 />", { _this spawn A3A_fnc_captureX; },false,6,true,true,"","
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +        _flag addAction ["<t>Liberate POW</t> <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_unbind_ca.paa' size='1.6' shadow=2 />", A3A_fnc_liberatePOW,nil,6,true,true,"","(isPlayer _this
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +        _flag addAction ["<t>Liberate</t> <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_unbind_ca.paa' size='1.6' shadow=2 />", A3A_fnc_liberaterefugee,nil,6,true,true,"","(isPlayer _this
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +            _actionX = _flag addAction [format ["<t>Carry %1</t> <img image='\A3\ui_f\data\igui\cfg\actions\take_ca.paa' size='1.6' shadow=2 />",name _flag], A3A_fnc_carry,nil,5,true,false,"","(isPla
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +                _actionX = _flag addAction [format ["<t>Revive %1</t> <img size='1.8' <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_revive_ca.paa' />",name _flag], A3A_fnc_actionRevive,ni
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +                _actionX = _flag addAction [format ["<t>Revive %1</t> <img size='1.8' <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_reviveMedic_ca.paa' />",name _flag], A3A_fnc_actionRevi
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +                _actionX = _flag addAction [format ["<t>Revive %1 </t> <img size='1.8' <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_revive_ca.paa' />",name _flag], A3A_fnc_actionRevive,n
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +                _actionX = _flag addAction [format ["<t>Revive %1 </t> <img size='1.8' <img image='\a3\ui_f\data\IGUI\Cfg\holdactions\holdAction_reviveMedic_ca.paa' />",name _flag], A3A_fnc_actionRev
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +        actionX = _flag addAction ["<t>Transfer Ammobox to Truck<t> <img image='\A3\ui_f\data\igui\cfg\actions\unloadVehicle_ca.paa' size='1.8' shadow=2 />", A3A_fnc_transfer,nil,6,true,true,"","(isP
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +        _flag setUserActionText [_actionX,"Take the Flag","<img size='2' image='\A3\ui_f\data\igui\cfg\actions\takeflag_ca.paa'/>"];//string created, unsure about implementation
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_flagaction.sqf
> +        _actionX = _flag addAction ["<t>Take the Flag<t> <img image='\A3\ui_f\data\igui\cfg\actions\takeflag_ca.paa' size='1.8' shadow=2 />", A3A_fnc_mrkWIN,nil,6,true,true,"","(isNil 'A3A_isPlayerCa
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_commsMP.sqf
> +	_textX = format ["War Level Changed<br/><br/>Current Level: %1",tierWar]; //localize "STR_A3A_fn_base_commsmp_warlvlchange"
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_canMoveHQ.sqf
> +    _result pushBack "Petros currently picked up";// localize "STR_A3A_fn_base_canmovehq_petros_pickedup"
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_canMoveHQ.sqf
> +    _result pushBack "Arsenal inventory must be empty";// localize "STR_A3A_fn_base_canmovehq_no_empty2"
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_calculateAggression.sqf
> +        _notificationText = format ["<t size='0.6' color='#C1C0BB'>Aggression level changed<br/> <t size='0.5' color='#C1C0BB'><br/>%1", _notificationText];// localize "STR_A3A_fn_base_caclaggro_leve
done

2023-09-17 15:12 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_calculateAggression.sqf
> +        _notificationText = format ["%1%2 aggression level increased to %3", _notificationText, FactionGet(inv,"name"), [aggressionLevelInvaders] call A3A_fnc_getAggroLevelString];// localize "STR_A3
done

2023-09-17 15:13 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_calculateAggression.sqf
> +    _notificationText = format ["%1%2 aggression level reduced to %3", _notificationText, FactionGet(inv,"name"), [aggressionLevelInvaders] call A3A_fnc_getAggroLevelString];// localize "STR_A3A_fn_b
done

2023-09-17 15:13 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_calculateAggression.sqf
> +        _notificationText = format ["%1 aggression level increased to %2<br/>", FactionGet(occ,"name"), [aggressionLevelOccupants] call A3A_fnc_getAggroLevelString];// localize "STR_A3A_fn_base_cacla
done

2023-09-17 15:13 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_calculateAggression.sqf
> +    _notificationText = format ["%1 aggression level reduced to %2<br/>", FactionGet(occ,"name"), [aggressionLevelOccupants] call A3A_fnc_getAggroLevelString];// localize "STR_A3A_fn_base_caclaggro_o
done

2023-09-17 15:13 UTC, Bob-Murphy commented on A3A/addons/core/functions/Base/fn_airspaceControl.sqf
> +            private _warningText = format ["Unidentified helicopter<br/><br/>You are closing in on the airspace of %1.<br/><br/> Change your course or we will take defensive actions!", [_x] call A3A_
done

2023-09-17 15:13 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +	      <Original>Artillery Support</Original>
done

2023-09-23 18:02 UTC, killerswin2 approved these changes

2023-09-23 18:11 UTC, merged