Vanilla DLC Vehicles
official-antistasi-community/A3-Antistasi pull request #2931
Opened 2023-09-06 20:44 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Adds DLC vehicles and the conditions for them

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-09-23 13:24 UTC, Bob-Murphy commented
This does not only add Vanilla DLC content but also adds Western Sahara CDLC content.

2023-09-23 13:58 UTC, Bob-Murphy requested changes

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
> +["vehiclesLightArmed",["B_T_MRAP_01_hmg_F","B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F", "B_T_MRAP_01_gmg_F", "B_T_LSV_01_AT_F", "B_T_LSV_01_armed_F"]] call _fnc_saveToTemplate;
remove duplicate gmg entry

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
> +["vehiclesLightArmed",["B_T_MRAP_01_hmg_F","B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F", "B_T_MRAP_01_gmg_F", "B_T_LSV_01_AT_F", "B_T_LSV_01_armed_F"]] call _fnc_saveToTemplate;
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +	_LightArmed append ["B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F", "B_T_LSV_01_AT_F", "B_T_LSV_01_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +private _LightArmed = ["B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
> +	_LightArmed append ["O_T_MRAP_02_hmg_ghex_F", "O_T_MRAP_02_gmg_ghex_F", "O_T_LSV_02_AT_F", "O_T_LSV_02_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
> +	_LightArmed append ["O_T_MRAP_02_hmg_ghex_F", "O_T_MRAP_02_gmg_ghex_F", "O_T_LSV_02_AT_F", "O_T_LSV_02_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
> +	_LightArmed append ["O_MRAP_02_hmg_F", "O_MRAP_02_gmg_F", "O_LSV_02_AT_F", "O_LSV_02_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +private _LightArmed = ["B_MRAP_01_gmg_F", "B_MRAP_01_hmg_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +	_LightArmed append ["B_MRAP_01_gmg_F", "B_MRAP_01_hmg_F","B_LSV_01_AT_F","B_LSV_01_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +private _LightArmed = ["B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F"]; //this line determines light and armed vehicles -- Example: ["vehiclesLightArmed", ["B_MRAP_01_hmg_F", "B_MRAP_01_gmg_F"]] -- Array,
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +	_LightArmed append ["B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F", "B_T_LSV_01_AT_F", "B_T_LSV_01_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +private _LightArmed = ["B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-23 13:58 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +	_LightArmed append ["B_T_MRAP_01_hmg_F", "B_T_MRAP_01_gmg_F", "B_T_LSV_01_AT_F", "B_T_LSV_01_armed_F"];
Please duplicate the non-gmg entries so gmg has a lower chance spawning as it's OP.

2023-09-24 00:34 UTC, ante185 commented
in _Vanilla_Reb_Vehicle_Attributes_ I moved the western sahara uparmoured offroads into a if statement based of whether western sahara is loaded or not, as these would cause errors otherwise.

2023-09-24 00:54 UTC, ante185 commented
GMG likely hood should be sufficiently reduced/addressed now.
1 in 3 for vanilla, 1 in 5 with apex enabled.

2023-09-24 13:17 UTC, Bob-Murphy approved these changes

2023-09-24 17:10 UTC, Bob-Murphy approved these changes

2023-09-24 17:11 UTC, merged