Adds Vanilla DLC Weapons
official-antistasi-community/A3-Antistasi pull request #2932
Opened 2023-09-07 20:20 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds conditional checks for adding marksmen DLC rifles and MGs to thew vanilla templates.
Minor adjustments and tweaks to the regular loadouts, such as colour matching using dlc attachments which are not restricted.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

Each tampered template has been loaded with all DLC enabled - no issues reported in RPT or by the template validator.

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Enable DLCs, load templates, observe enemy machine gunners, snipers, and marksmen.

********************************************************
Notes:

2023-09-23 14:19 UTC, Bob-Murphy requested changes

2023-09-23 14:19 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +_initialRebelEquipment append [["launch_RPG7_F", 15], ["RPG7_F", 45]];
Did you lose the (allowDLCExpansion) condition?

2023-09-23 14:42 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +_initialRebelEquipment append [["launch_RPG7_F", 15], ["RPG7_F", 45]];
SDK forces the APEX expansion, the if statement would have always been true

2023-09-23 15:59 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +_initialRebelEquipment append [["launch_RPG7_F", 15], ["RPG7_F", 45]];
I can change it back, do what we do in the FIA template, but then I'd wanna remove the force forceDLC[] = {"expansion"} from the SDK entry in template.hpp as adding that condition back is not gonna change anything as is.

2023-09-23 16:03 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +_initialRebelEquipment append [["launch_RPG7_F", 15], ["RPG7_F", 45]];
Nah, this is fine. Maybe make a note at the top of templates about what DLC they require, but yeah, this one is Apex-specific.

2023-09-23 16:05 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +_initialRebelEquipment append [["launch_RPG7_F", 15], ["RPG7_F", 45]];
Gotcha

2023-09-24 13:18 UTC, Bob-Murphy approved these changes

2023-10-07 18:58 UTC, merged