Militia offroads & civilian CH-49
official-antistasi-community/A3-Antistasi pull request #2933
Opened 2023-09-07 22:16 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds retextured FIA offroads to the vanilla factions - color choice depending on environment or what would be faction-suitable.
Adds the Ch-49 in its civilian livery as a purchasable helicopter, for 6500€.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Militia offroads: Load template, observe militia roadblocks
Civilian helicopter: buy the helicopter

********************************************************
Notes:

2023-09-23 14:59 UTC, Bob-Murphy requested changes

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_black_F	:	B_G_Offroad_01_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_black_armed_F	:	B_G_Offroad_01_armed_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_green_F	:	B_G_Offroad_01_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_green_armed_F	:	B_G_Offroad_01_armed_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_comms_green_F	:	I_E_Offroad_01_comms_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_tan_F	:	B_G_Offroad_01_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_tan_armed_F	:	B_G_Offroad_01_armed_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_comms_tan_F	:	I_E_Offroad_01_comms_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_ldf_armed_F	:	B_G_Offroad_01_armed_F
change tabs to space

2023-09-23 14:59 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/soft.hpp
> +class a3a_Offroad_01_GEN_armed_F	:	B_G_Offroad_01_armed_F
change tabs to space

2023-09-24 00:08 UTC, ante185 commented
Tabs exchanged for spaces, merge conflicts solved.

2023-09-24 15:11 UTC, Bob-Murphy approved these changes

2023-10-06 16:26 UTC, jaj22 commented
This should be on ready-for-merge now, right?

2023-10-07 18:54 UTC, Bob-Murphy approved these changes
lgtm

2023-10-07 18:54 UTC, merged