Vanilla Slat Caged APCs
official-antistasi-community/A3-Antistasi pull request #3049
Opened 2023-11-13 22:38 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Patched the vanilla APCs to spawn with **Slat cages**, increasing the number of hits that they can take.
Moved the AFV Rhino down to light tank category.
Moved the IFV Mora and Kamysh up to IFV category.

**Reduced or removed the overlap between militia and military trucks of the vanilla templates.**

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-11-14 08:11 UTC, Lazejun reviewed
No idea what's Bob's and John's opinion but Fucking around with Vanilla Classes is the wrong approach.

This could cause funny problems for people that load Antistasi + it messes with mods that Base assets on the base Class.

The safer approach is create a new Class based on the Base one and add shit to the new class

2023-11-14 15:51 UTC, jaj22 commented
Makes me wonder if I've been reading previous patches correctly (ok I mostly left them to Bob), but yes: Add new version with slats enabled. Then maybe use both in the templates in different places.

2023-11-15 16:25 UTC, ante185 commented
Updated

2023-12-23 13:56 UTC, Bob-Murphy requested changes

2023-12-23 13:56 UTC, Bob-Murphy commented on A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp
> +#include "ifv.hpp"
please put into alphabetical order

2023-12-23 13:56 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +["vehiclesMilitiaTrucks", ["I_C_Van_01_transport_F"]] call _fnc_saveToTemplate;
Revert please.
Van is Laws of War DLC content.

2023-12-23 13:56 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +["vehiclesMilitiaTrucks", ["I_E_Van_02_transport_F", "I_E_Van_02_vehicle_F"]] call _fnc_saveToTemplate;
Revert please.
Van is Laws of War DLC content.

2023-12-23 15:20 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +["vehiclesMilitiaTrucks", ["I_C_Van_01_transport_F"]] call _fnc_saveToTemplate;
I_C_Van_01_transport_F, you're thinking of Van_02

2023-12-23 15:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +["vehiclesMilitiaTrucks", ["I_E_Van_02_transport_F", "I_E_Van_02_vehicle_F"]] call _fnc_saveToTemplate;
Resolved.

2024-01-24 16:29 UTC, Bob-Murphy approved these changes
lgtm

2024-01-24 16:29 UTC, merged