English Stringtable Update
official-antistasi-community/A3-Antistasi pull request #3051
Opened 2023-11-15 01:24 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:

A lot of changes to addons/core/Stringtable.xml to improve clarity and grammar errors in certain places. Beyond a few specific grammar errors or typos, most of the changes were left to my purview and I've attempted to make them clearer for new players to understand. Let me know about any changes you think are necessary.

### Please specify which Issue this PR Resolves.
closes #3046 

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
All of the "problematic strings"' have been tested (e.g. strings with specific formatting and breaks in them), the only strings left are the strings relating to Garbage Cleaning, members, and FF punishments because those aren't things I can test on a LAN host and I am far too smooth brain to go through the effort of setting up a dedicated server to test basic changes to strings. 

********************************************************
Notes:

2023-11-18 01:38 UTC, Bob-Murphy requested changes

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>The mortar has run out of rounds. Wait a few minutes to restock it.</Original>
not entirely sure if it reloads automatically or you actually have to send it to HQ

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>Clear fog</Original>
Denied - please revert back

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>Clear rain</Original>
Denied - please revert back

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>A truck with medical supplies, destination %3, is about to depart at %2 from %1. Intercept the convoy, steal the truck, and bring it to %3, and let the people know the %4 is giving
steal the truck, and bring it to %3
-->
steal the truck, bring it to %3

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>We know an enemy armor (%3) is stationed in %1. We have a unique opportunity to steal or destroy the armor before it becomes a issue later on. Do it before %2.</Original>
becomes a issue
-->
becomes an issue

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>A squad of Gendarmeries are guarding a large amount of money in the bank of %1. Take the Box Truck and go there before %2. Once you're there, hold the truck next to the bank's main
please remove the word "Box" from "Box Truck"

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>We can't cover you there!</Original>
Please revert, too long and not clear enough

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>Petros will join your group. The arsenal box must be empty to move HQ. To rebuild, select the Build HQ here option on Petros.</Original>
The inventory of the arsenal box must....

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>Having a commander is necessary because they are the commander of the Faction attacking ground forces. Many options are available only to the commander and, depending on your settin
Change "they are" back to "he is".

2023-11-18 01:38 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>Having a commander is necessary because they are the commander of the Faction attacking ground forces. Many options are available only to the commander and, depending on your settin
End review 17.11.2023 - continue after

2023-11-18 01:42 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Original>The mortar has run out of rounds. Wait a few minutes to restock it.</Original>
mortars resupply on resource ticks as long as a there is no player in it. teleporting it to hq just means you can hit the box

2023-11-18 01:51 UTC, Tiny-DM commented
Fixed. Are 860 and 886 just for consistency?

2023-11-18 01:56 UTC, Bob-Murphy commented
> Fixed. Are 860 and 886 just for consistency?

It's fun, known and already translated. No real need to change it.

2023-11-18 11:11 UTC, Bob-Murphy requested changes

2023-11-18 11:11 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>The Commander is responsible for assigning units as garrisons in conquered areas. Use the Garrison Management option in Petros in order to add or remove garrison troops at each zone
wouldn't "on Petros" be better than "in Petros"?

2023-11-18 20:20 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Original>The Commander is responsible for assigning units as garrisons in conquered areas. Use the Garrison Management option in Petros in order to add or remove garrison troops at each zone
It's inside the HQ management menu on Petros, so I'll change it to "Garrison Management option inside the HQ Management action on Petros." Does that work?

2023-11-18 20:23 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Original>The Commander is responsible for assigning units as garrisons in conquered areas. Use the Garrison Management option in Petros in order to add or remove garrison troops at each zone
Regardless, the entire in-game guide needs to be redone anyways. I fixed everything glaring (e.g. all the actions used to be on the flag/campfire) but after this I'll probably work on redoing that by just using the data on the wiki

2023-11-22 19:09 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>The Commander is responsible for assigning units as garrisons in conquered areas. Use the Garrison Management option in Petros in order to add or remove garrison troops at each zone
works for me

2023-11-22 19:35 UTC, Bob-Murphy approved these changes

2023-11-22 19:36 UTC, merged