Assassinate mission misc fixes
official-antistasi-community/A3-Antistasi pull request #3064
Opened 2023-11-23 00:40 UTC by Tiny-DM

## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Stringtable: Changed SpecOps to Special Forces. Personal preference, I've heard this and "SF" a lot more than SpecOps, and it's a bit less confusing
Officer mission should render time and faction correctly, and removed a few useless lines
Traitor mission, removed a few useless lines and the old pvp mission
SpecOps: The faction should be displayed correctly, SEE BELOW    

### Please specify which Issue this PR Resolves.
closes https://discord.com/channels/449481990513754112/647694189236322305/1139340437132419212 

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Officer: Move to the middle of the peninsula south of the southwest airbase, and call an assassinate mission, or move HQ to the middle of the ocean.

********************************************************
Notes:
SpecOps is BROKEN, in vanilla or in this PR it seems to be impossible to force the specops task to spawn so I cant test the changes to the SpecOps task. This code also generates a non-critical error in the log, although it is the same code used in fn_unAtt and the newly committed fn_AS_Official and it works fine. However, assuming the task is created as expected, the changes should be fine. I have no clue what the root cause of the SpecOps issue is, I've put some details of the issue in #help

2023-11-23 09:46 UTC, jaj22 commented on A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
> +[[teamPlayer,civilian],_taskID,[format [localize "STR_A3A_fn_mission_as_traitor_text",_nameDest,_displayTime,FactionGet(occ,"name")],localize "STR_A3A_fn_mission_as_traitor_titel",_markerX],_posTsk,f
If you remove the blufor task then you need to adjust the A3A_fnc_taskSetState calls accordingly. I believe that's the fourth parameter.

2023-11-23 09:46 UTC, jaj22 commented on A3A/addons/core/Stringtable.xml
> +        <Original>A traitor has scheduled a meeting with %3 forces in %1. Kill him before he provides enough intel to give us trouble. Do this before %2. We don't know where exactly this meeting will
Is it always camo-painted?

2023-11-23 11:53 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>A traitor has scheduled a meeting with %3 forces in %1. Kill him before he provides enough intel to give us trouble. Do this before %2. We don't know where exactly this meeting will
It's neither always an offroad nor is it camo-painted. Depends on modsets/templates.

2023-11-23 15:45 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Original>A traitor has scheduled a meeting with %3 forces in %1. Kill him before he provides enough intel to give us trouble. Do this before %2. We don't know where exactly this meeting will
Got it, I'll remove it. I was hoping to help distinguish between the other parked civilian vehicles, but there aren't that many anyways.

2023-11-23 17:47 UTC, Tiny-DM commented on A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
> +[[teamPlayer,civilian],_taskID,[format [localize "STR_A3A_fn_mission_as_traitor_text",_nameDest,_displayTime,FactionGet(occ,"name")],localize "STR_A3A_fn_mission_as_traitor_titel",_markerX],_posTsk,f
bump from Discord

2023-11-23 17:50 UTC, jaj22 commented on A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf
> +[[teamPlayer,civilian],_taskID,[format [localize "STR_A3A_fn_mission_as_traitor_text",_nameDest,_displayTime,FactionGet(occ,"name")],localize "STR_A3A_fn_mission_as_traitor_titel",_markerX],_posTsk,f
Lines 135 and 174.

2023-11-23 19:24 UTC, Tiny-DM commented
all issues should be fixed. ready for review

2023-11-24 03:16 UTC, jaj22 commented
You managed to test the specops mission eventually, right?

2023-11-24 03:46 UTC, Tiny-DM commented
@jaj22 Yes. I got the file running properly with the includes, I really should have asked for clarification earlier. Sorry about that.

2023-11-24 03:48 UTC, jaj22 approved these changes

2023-11-24 10:07 UTC, Bob-Murphy requested changes

2023-11-24 10:07 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>A traitor has scheduled a meeting with %3 forces in %1. Kill him before he provides enough intel to give us trouble. Do this before %2. We don't know where exactly this meeting will
As stated, it ain't always an offroad like for example when playing with SOG or Spearhead.
`You will recognize the building by the nearby parked vehicle and %3 presence.` would make more sense.

2023-11-24 16:15 UTC, Tiny-DM commented
Change resolved. In the future it might be cool to grab the name for the vehicle it spawns and trim it down, but that's a minor fix for the future.

2023-11-25 13:38 UTC, Bob-Murphy approved these changes

2023-11-25 19:17 UTC, merged