3CB LSM rebel template.
official-antistasi-community/A3-Antistasi pull request #3081
Opened 2023-12-03 20:56 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Adds template for 3CB's  Livonian Separatist Militia.
Adds name to the LDF template.
Adds the 8mm CZ550 "Lux", derived from the 3CB CZ550 but in a caliber that does not 1-shot through every body armor.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-12-23 14:02 UTC, Bob-Murphy requested changes
Not loaded but looks good.
In addition, please triple-check if vehicle and static nodes are defined. Doesn't hurt.
Thank you.

2023-12-23 14:02 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/3CB/3CB_Reb_LSM.sqf
> +_rebUniforms append _nonSmockUniforms;
dublication for balancing reasons or by mistake?

2023-12-23 15:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/3CB/3CB_Reb_LSM.sqf
> +_rebUniforms append _nonSmockUniforms;
duplication because the non smock uniforms are outnumbered 2 to 1 by the smock uniforms, and i'd like the friendly AI to wear a more even mix of uniforms.

2024-01-24 17:00 UTC, Bob-Murphy approved these changes
Checked myself - lgtm

2024-01-24 18:49 UTC, merged