Vanilla LFF rebel faction
official-antistasi-community/A3-Antistasi pull request #3082
Opened 2023-12-03 23:08 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Adds a Livonia-appropriate rebel faction for Vanilla.
It'd be the only vanilla faction that doesn't start with SMGs.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-12-23 14:11 UTC, Bob-Murphy requested changes
not loaded but looks good besides the vans

2023-12-23 14:11 UTC, Bob-Murphy commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
> +["vehiclesCivTruck", ["C_Van_01_transport_F", "C_Van_02_transport_F", "C_Van_02_vehicle_F"]] call _fnc_saveToTemplate;
Again, the vans you picked are Laws of War DLC.

2023-12-23 15:12 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
> +["vehiclesCivTruck", ["C_Van_01_transport_F", "C_Van_02_transport_F", "C_Van_02_vehicle_F"]] call _fnc_saveToTemplate;
This is carried over from the other rebel templates, both vanilla and not, as they're not something that'd get used against the will of the player it should be fine.

2024-01-02 03:14 UTC, Tiny-DM approved these changes
The van thing is because every other vanilla faction also includes the Laws of War locked vans, to work as another high capacity transport option when sushi trucks are out of style. This matches the FIA template, and it might be worth having a conversation later about locking the vans behind the Laws of War checkbox. It seems reasonable if we restrict other vehicles (I want to say the M249 Jeep but I'm not sure) with similar conditions.

2024-01-21 16:14 UTC, Bob-Murphy approved these changes

2024-01-21 16:14 UTC, merged