Stringtabling the rest of core
official-antistasi-community/A3-Antistasi pull request #3089
Opened 2023-12-11 01:14 UTC by Tiny-DM

Yes, stringtabling is now a word.

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Almost every remaining string inside `core` has been made into a stringtable entry. I'm going to go back and find the few remaining strings soon, but this is the main set. Other stuff that's been changed while I was doing the stringtables:

- Artillery now displays "Rounds" or "Round" depending on salvo count
- Roadblocks and Watchposts are now regarded separately for tasks and descriptions
- Roadblocks and Watchposts render properly in contact reports. Support Corridor line has been removed.
- Conquest missions now display roadblocks properly ([thanks ante](https://discord.com/channels/449481990513754112/647694189236322305/1139340686471217234)).
- Removed some old code for resource ticks (involved removing certain elements when resourcesFIA was 0, makes it less intuitive overall and adds extra baggage)

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
The solo testing I did for this isn't complete. After I got all the errors out of the log, I realized it's a lot more efficient to test these strings on a dedicated server where the events will actually happen, as opposed to trying to recreate them in Zeus. It would be *preferred* to spin up a test server and try it there. Once we've made sure that every string renders correctly in English (I've checked about 80% of them) the translators can work on their translations and making sure that everything renders properly in their language, and this can hopefully be merged in the next major update. In terms of further changes, like I said I'll hunt down the last few strings over the next few days in case anyone spots any errors.
********************************************************
Notes:
[I expect you to very carefully do your code reviews](https://discord.com/channels/449481990513754112/649353838616117259/1181405753467211776)

2023-12-11 15:59 UTC, rautamiekka requested changes

2023-12-11 15:59 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_getAggroLevelString.sqf
> +if(_level == 5) exitWith {localize "STR_A3A_fn_getAggroLevelString_5"};
```suggestion
if(_level in [1, 2, 3, 4, 5]) exitWith {localize ("STR_A3A_fn_getAggroLevelString_" + _level)};
```

2023-12-11 18:19 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_getAggroLevelString.sqf
> +if(_level == 5) exitWith {localize "STR_A3A_fn_getAggroLevelString_5"};
Resolved. I had to change _level to a string to get it to work, but it's functional now. I tried to do this before but because I'm criminally stupid I fucked it up and scrapped it

2023-12-11 22:25 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_getAggroLevelString.sqf
> +if(_level == 5) exitWith {localize "STR_A3A_fn_getAggroLevelString_5"};
Oh yeah, facepalm, I forgot you need `str _level` to make it work. This is why I use `format`.

2023-12-15 00:31 UTC, Tiny-DM commented
Finalized. Every instance of the //TODO: Localize comment left over from #2920 and #3015 is stringtabled, (stuff from ``garage`` and ``gui`` and a few strings have been changed for clarity in ``core``. Ready for review.

2023-12-15 02:01 UTC, rautamiekka requested changes
Hoo boy, my eyes hurt. Everything I could find at 3-4am.

2023-12-15 02:01 UTC, rautamiekka commented on A3A/addons/core/functions/REINF/fn_NATObomb.sqf
> +driver _plane sideChat [localize "STR_A3A_fn_reinf_NATObomb_run"];
```suggestion
driver _plane sideChat localize "STR_A3A_fn_reinf_NATObomb_run";
```
`sideChat` doesn't accept array, and `(localize ...)` wouldn't be necessary.

2023-12-15 02:20 UTC, Tiny-DM commented
Pal, sleep is more important than reviewing my shit code. I'll get all this fixed, thank you.

2023-12-15 03:20 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_attackHQ.sqf
> +[[teamPlayer,civilian],_taskId,[format (localize "STR_A3A_fn_base_attackHQ_defendLong"),format (localize "STR_A3A_fn_base_attackHQ_defendTitle"),respawnTeamPlayer],_targPos,true,10,true,"Defend",true
Localize returns a string anyway, so format is invalid and str will wrap with double quotes, which is probably unwanted. Just strip the formats here if there's no longer any processing required (I guess because Petros is always Petros?).

2023-12-15 03:59 UTC, Tiny-DM commented on A3A/addons/core/functions/AI/fn_liberatePOW.sqf
> +_response = localize {"STR_A3A_fn_ai_captureX_libresponse" + _responseNum};
Resolved

2023-12-15 04:00 UTC, Tiny-DM commented on A3A/addons/core/functions/AI/fn_liberaterefugee.sqf
> +_response = localize {"STR_A3A_fn_ai_captureX_libresponse" + _responseNum};
Resolved

2023-12-15 04:02 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_placementselection.sqf
> +format [localize "STR_A3A_fn_base_placeselec_petros_dead"] hintC format [localize "STR_A3A_fn_base_placeselec_petros_dead_long"];
Format here was left over from the original line which had Petros' name in a variable, so the format can be removed entirely. Resolved.

2023-12-15 04:03 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_rebuildRadioTower.sqf
> +_mrkFinal setMarkerText (localize "STR_A3A_fn_base_rebuildRadioTower_marker");
Resolved

2023-12-15 17:22 UTC, rautamiekka commented
> Pal, sleep is more important than reviewing my shit code.

If only it was that simple anymore, it was either that or something else, nothing in the middle.

2023-12-15 17:37 UTC, Tiny-DM commented
Updated and resolved all previous issues. One thing I should note, the garage script "config.inc" throws an error upon game startup. I've uploaded the error below and as far as I can see, there's nothing wrong with the changes I've made. Is it not possible to localize the settings, or is there something else I'm missing? 
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/148804148/40bb34b5-ba41-4ae8-a2af-b95d92abc6cc)
Beyond that, every other change is handled

2023-12-15 18:48 UTC, Tiny-DM commented
Should be resolved now. Not sure about the garage thing still

2023-12-15 18:54 UTC, jaj22 commented
> Should be resolved now. Not sure about the garage thing still

It's actually two problems:
1. Some of the config.inc lines have a missing quote on the end of the second localized string.
2. The third parameter of CBA_fnc_addSetting is an array containing two strings. You have lost the array.

2023-12-15 19:03 UTC, Tiny-DM commented
Shit, I need to be more careful about that. Thank you, it's resolved.

2023-12-23 19:36 UTC, jaj22 commented on A3A/addons/core/functions/AI/fn_liberatePOW.sqf
> +_response = localize ("STR_A3A_fn_ai_captureX_libresponse" + _responseNum);
The responseNum part isn't going to work. It'll evaluate to something like `"[1.523534]"`

Random is busted (can roll max val) so best to do this:
`private _responseNum = str selectRandom [1,2,3];`

Or just put the stringed numbers straight into the array. Similar for liberaterefugee.

2023-12-24 03:56 UTC, Tiny-DM commented on A3A/addons/core/functions/AI/fn_liberatePOW.sqf
> +_response = localize ("STR_A3A_fn_ai_captureX_libresponse" + _responseNum);
Fixed for next commit. captureX, liberatePOW, and liberateRefugee all use a similar function with `round` used. But if `random` is busted I'll just use selectRandom instead.

2023-12-24 07:30 UTC, Bob-Murphy commented
@Tiny-DM please start locally, there is at least one error that popped up.
The unfortunate thing is that they don't all show up at once but you gotta fix one, save and then test again to find the next error.

2023-12-24 09:13 UTC, Bob-Murphy requested changes

2023-12-24 09:13 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>%1 is scrambling an air superiority fighter</Original>
scrambling --> preparing

2023-12-24 09:13 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>A %1 air QRF is landing</Original>
arriving, not necessarily landing

2023-12-24 09:13 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> +        <Original>A %1 fixed-wing CAS has visual on target and is preparing for run</Original>
not necessarily fixed wing, please adapt

2023-12-24 09:15 UTC, Bob-Murphy requested changes
You seem to have quite a few copy paste errors or such with string names.
Some friendly fire ones for example are missing an `_FF_` in the middle of the string name but they do exist.

2023-12-24 17:32 UTC, Tiny-DM commented on A3A/addons/core/functions/AI/fn_artySupport.sqf
> +	_mrkFinal setMarkerTextLocal localize "STR_A3A_fn_ai_artySupport_mortarStrike";
Resolved. It feels like it would be more accurate than an artillery strike for newcomers, to avoid confusing them into believing they have friendly howitzers or MLRS incoming, but it's changed in next commit.

2023-12-24 17:36 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Original>%1 is scrambling an air superiority fighter</Original>
Feels more immersive to be "scrambling", but "prepared" is more versatile. Resolved.

2023-12-24 17:50 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_localizar.sqf
> +	if (isOnRoad _pos) then {_textX = format [localize "STR_A3A_fn_base_localizar_roadblock",_city]}; //For friendly roadblocks, next checks will overwrite it if neccesary
There should be no scenario where a marker is 
on a road
not a marker
not a SpecOps location
and isn't an allied outpost

and even if a bug does happen and a roadblock is not in controlsX and is enemy, the text will still apply.

2023-12-24 18:26 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_resourcesFIA.sqf
> +_faction = format ["<t size='0.6' color='#C1C0BB'>" + localize "STR_A3A_fn_base_resourcesFIA_resources" + ".<br/> ", FactionGet(reb,"name")];
Having the title of a mini pop-up have a period looks weird anyway. The period is removed.

2023-12-24 18:43 UTC, Tiny-DM commented
All changes resolved, and no apparent bugs on startup. I have a few more changes I'm going to merge with the next commit as well (strings for "You damaged a friendly as driver" were in the stringtable but not in the file itself).

2023-12-25 20:05 UTC, Bob-Murphy reviewed
The last things I need to check are the actual stringtables. Nevertheless, I'll do that once I'm at my flat again because going through that with a laptop sucks.

2023-12-25 20:09 UTC, Tiny-DM commented on A3A/addons/garage/Public/config.inc
> +    ["HR_GRG_PoolBase", "SLIDER", [localize "STR_A3A_inc_public_config_baseCapTitle", localize "STR_A3A_inc_public_config_baseCapTitle"], [HR_GRG_Prefix,"Garage"], [0, 50, HR_GRG_PoolBase, 0], true,
Fuck, I thought I hit all of those. Resolved.

2024-01-03 02:50 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_localizar.sqf
> +	if (isOnRoad _pos) then {_textX = format [localize "STR_A3A_fn_base_localizar_roadblock",_city]}; //For friendly roadblocks, next checks will overwrite it if neccesary
No. _textX will be overwritten if it ends up being an enemy point. And if it is a roadblock, it will get caught anyways.

2024-01-21 01:42 UTC, Bob-Murphy commented on A3A/addons/core/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
> +_saveString = if (autoSave) then { [_saveString,format[localize "STR_A3A_fn_dialogs_createDialog_SLPS_line2", _autoSaveInterval]] joinString "" }
Are you not missing the "minutes" after the time?

2024-01-21 02:08 UTC, Bob-Murphy approved these changes

2024-01-21 02:14 UTC, merged