Miscellaneous logs fix for garage
official-antistasi-community/A3-Antistasi pull request #3090
Opened 2023-12-11 18:00 UTC by Tiny-DM

## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Changed the line to update the garage interface to only work when there's someone in the garage interface, removing 2 startup errors and 1 error every time someone garaged a vehicle. All errors purely present in the logs with no gameplay impact

### Please specify which Issue this PR Resolves.
closes [this discord comment from John](https://discord.com/channels/449481990513754112/637869964107186199/1183578742598148187)

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

2023-12-11 23:22 UTC, rautamiekka requested changes
Trying to check a nil against anything will break, so it's 1 of the cases where lazy eval is mandatory.

2023-12-11 23:22 UTC, rautamiekka commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +if !(isNil "HR_GRG_Users" || HR_GRG_Users isEqualTo[]) then {
```suggestion
if !(isNil "HR_GRG_Users" || {HR_GRG_Users isEqualTo []}) then {
```

2023-12-11 23:22 UTC, rautamiekka commented on A3A/addons/garage/Public/fn_addVehiclesByClass.sqf
> +if !(isNil "HR_GRG_Users" || HR_GRG_Users isEqualTo[]) then {
```suggestion
if !(isNil "HR_GRG_Users" || {HR_GRG_Users isEqualTo []}) then {
```

2023-12-11 23:58 UTC, Tiny-DM commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +if !(isNil "HR_GRG_Users" || HR_GRG_Users isEqualTo[]) then {
Resolved x2

2023-12-12 03:25 UTC, jaj22 commented
I'd just pull the isNils personally. If HR_GRG_Users is nil at that point then the rest of the code isn't going to work either. Having the isNil in there makes it look like it's a valid possibility.

2023-12-12 03:28 UTC, jaj22 approved these changes
Would rather it didn't have the isNil statements but it'll work.

2023-12-12 13:57 UTC, Tiny-DM commented
You guys are too picky :P That's my excuse for not writing it properly the first time. Regardless, the isNil's have been pulled for clarity.

2023-12-12 16:23 UTC, rautamiekka commented
> I'd just pull the isNils personally. If HR_GRG_Users is nil at that point then the rest of the code isn't going to work either. Having the isNil in there makes it look like it's a valid possibility.

Good point.

2023-12-23 18:27 UTC, merged