Added: New mass calculations based on wheel springs
official-antistasi-community/A3-Antistasi pull request #3099
Opened 2023-12-21 20:39 UTC by killerswin2

## What type of PR is this.
1. [x] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    Changing the mass calculation for attached objects on logistic vehicles. This prevents mass from being too heavy and clipping the wheel into the ground.

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2023-12-21 22:29 UTC, rautamiekka requested changes
Couple simplifications.

2023-12-21 22:29 UTC, rautamiekka commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +_sprungMassLoad = _sprungMassLoad - _defaultMass;
```suggestion
private _sprungMassLoad = 0 - _defaultMass; 
{_sprungMassLoad = _sprungMassLoad + _x} forEach _sprungMasses;
```

2023-12-21 22:29 UTC, rautamiekka commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +_maxSupportedLoad = _maxSupportedLoad + _sprungMassLoad;
```suggestion
_maxSupportedLoad = _maxSupportedLoad / 9.81 + _sprungMassLoad;
```

2023-12-22 11:00 UTC, HakonRydland commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +_maxSupportedLoad = _maxSupportedLoad + _sprungMassLoad;
Should probably block loading if the cargo would overload the vehicle

2024-01-27 18:55 UTC, Bob-Murphy commented
Example values from own M38A1
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/50651578/1fe6a183-e15f-4b5f-bbf1-7842717925cf)

2024-01-27 19:19 UTC, jaj22 requested changes

2024-01-27 19:19 UTC, jaj22 commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +private _wheelsConfigs = "true" configClasses (configFile >> "CfgVehicles" >> typeOf TRUCK >> "Wheels");
TRUCK doesn't exist. Should probably be `_vehicle`. I assume this was only tested in the debug console?

Could also use configOf instead.

2024-01-27 19:19 UTC, jaj22 commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +private _attachedMass = _currentMass - _defaultMass;
I don't think this is correct, because _sprungMassLoad is the mass of the vehicle itself (minus the wheels), and therefore _maxSupportedLoad is vehicle mass + attached mass. See bob's example pic. If you only wanted the maximum attached mass you could ignore _sprungMassLoad entirely.

2024-01-27 19:19 UTC, jaj22 commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +_objectMass = if(_currentSupportedLoad - _objectMass > 0) then {_objectMass} else {_currentSupportedLoad};
This is weird for adding and I'm pretty sure it's broken for removing. Probably need to move the code to the Load function and exit out from there if it's overweight.

2024-04-13 02:41 UTC, merged