Miscellaneous fixes - Batch 1 (Tiny)
official-antistasi-community/A3-Antistasi pull request #3102
Opened 2023-12-28 00:02 UTC by Tiny-DM

ok this time we make sure everything works on the FIRST commit not the 29TH

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Fixed a few bugs that I have the SQF expertise to accomplish now. Full list of changes can be seen below. Most of these were either standing issues or reports from various people. Thanks skill and player specifically.
   

- Removed a stray period from the hint that displays with your chosen role when you first join.
- The punishment hint sent to admins will now include the name of the person who the detainee last hit, if available. #2770 
- Fixed a few other stringtable typos and added some more restrictions for converting vehicles to airstrikes
- fn_ammunitionTransfer and fn_resourcesFIA now have an optional parameter to return the update instead of displaying it
- AA vehicles at airports will now stop until everything is spawned in, resolves #3074 
- Guided launchers can no longer be unlocked from large intel. IMPORTANT: Even if allowGuidedLaunchers is true, you still can't roll the guided launchers for balance reasons. The line above that can be reenabled if deemed neccesary.
- The winning condition for the traitor mission now calls canFight, so the traitor can surrender and win the mission.
- Refugee missions *should* stop spawning on top of people. Might need tweaking. #2835
- fn_addBombRun: code reworked to fix a few edge cases, with the same restrictions as are necessary to garage a vehicle.
- Potential fix for ASFs space climbing
- initClient stringtable fix for when enemies are near HQ and you try to buy a vehicle
- Garage will now delete blacklisted vehicles on its checks. The list of blacklisted vehicles is in the garage config file, but right now includes the rhino trigger from RHS and the ACE spotting scopes. Fixes #3040 and lays the groundwork for if this happens in the future.
- The highlight of my coding career: as commander, garaging a loot crate which unlocks something will  display both the resource update and the arsenal update. #3048 

### Please specify which Issue this PR Resolves.
closes #3074
closes #3048
closes #3040
closes #2835
closes #2770
resolves [adding vehicles to airstrikes being weird](https://discord.com/channels/449481990513754112/647694189236322305/1189175608714997760)
resolves [quick typo](https://discord.com/channels/449481990513754112/647694189236322305/1185733546179051631)
potential fix for [planes space climbing](https://discord.com/channels/449481990513754112/647694189236322305/1186394939890880532)
fixes [another quick typo](https://discord.com/channels/449481990513754112/647694189236322305/1184947020025319485)
resolves [traitor mission breaking if he surrenders](https://discord.com/channels/449481990513754112/647694189236322305/1184887175452561458)
guided launchers could be unlocked through [large intel](https://discord.com/channels/449481990513754112/647694189236322305/1154239908483964958)

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: A few of the scenarios listed here were for bugs obscure enough there was no good way to reproduce them. The two primary examples are the refugee mission fix and the fighter space climbing fix, neither of which is straightforward to recreate. These should be tested when the test servers are running again.

********************************************************
Notes: I want to add a few more fixes here before release (noting here before I forget: intel search bug, AIVEHinit for rebel vehicles) but I wanted to get the majority of the fixes on GitHub and reviewed, since I'm mostly done.

2023-12-28 18:57 UTC, rautamiekka requested changes

2023-12-28 18:57 UTC, rautamiekka commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +        };
```suggestion
    if (_updated isNotEqualTo "") then {
        _nonBossComms = _updated;
        _bossComms = _bossComms + "<br/><br/>" + _updated;
    } else {
        _nonBossComms = "";
    };
```

2023-12-29 03:51 UTC, Tiny-DM commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +        };
damn it. Resolved.

2024-01-03 02:41 UTC, Tiny-DM commented
Another commit with a few additional minor changes.

- createAIAirplane has been renamed to createAIAirbase to avoid confusing people (specifically myself)(can be changed back if neccesary)
- The arsenal box no longer needs to have an empty inventory to move HQ. Proposed by John a while back.
- Friendly watchpost/roadblock vehicles will run through AIVEHinit to prevent a potential exploit
- New function: fn_checkCampaignEnd. Checks the population and airport status, logs it, and executes an appropriate ending. Used in invaderPunish, markerChange, and resourcecheck to provide a faster response to a game win or loss
- Removed ACE actions from the supplies pallet to prevent a mission critical asset from being loaded into areas where it cannot be retrieved (some minor community server tomfoolery took place here)
- Tower Rebuild Disrupt will now end immediately and succeed if rebels take the outpost with the tower.

This is all the changes I plan to make in this PR, so feel free to review. I will be working on another project.

2024-01-13 15:29 UTC, Tiny-DM commented
Ignore me struggling to use basic GitHub functionality, everything should work now. 

- Changed Antitank to Anti-Tank in some places to look a bit cleaner and match other languages. Translations DO NOT need updating.
- The pallet from the City Supplies mission instantly despawns now when the mission is over, to prevent a few weird things with the empty pallet.
- In the Y menu, Undercover can now be toggled. The code and stringtables have been updated to reflect such. Translations DO need updating.
- Minor performance and readability changes.

I keep adding stuff to these changes as I think of things, but this is the last set of changes for this PR, unless issues are discovered.

2024-01-13 19:31 UTC, jaj22 commented on A3A/addons/core/functions/Intel/fn_selectIntel.sqf
> +            _newWeapon = selectRandom _noLaunchers;
Easier way of doing this one is just `allWeapons - unlockedWeapons - allMissileLaunchers`. There are allXXX arrays automatically filled from the categories.

2024-01-13 20:24 UTC, jaj22 commented on A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
> +_instigator setVariable ["_lastFriendlyHit", name _victim, true];
This shouldn't be broadcast everywhere, because it's only used on the server. Could use 2 as the third parameter but maybe there's a better solution where the data is only passed to server on the call to A3A_punishment.

2024-01-13 21:00 UTC, jaj22 commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +    diag_log str _nonBossComms;
Debug code left in. Couple more further up too.

2024-01-21 21:42 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +	driver _veh disableAI "MOVE";
Is this necessary? Usually they need some encouragement to drive anywhere.

2024-01-21 21:43 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
> +    [] spawn A3A_fnc_checkCampaignEnd; // If a town is destroyed, check for loss
The orbital laser can also destroy towns, so you might want to check that.

2024-01-21 21:49 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_checkCampaignEnd.sqf
New files should have new indentation. Which means 4-space.

2024-01-21 21:57 UTC, jaj22 commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +            _resourcesFIA = [0,_toRefund,true] call A3A_fnc_resourcesFIA;
Ok, this doesn't work. resourcesFIA is scheduled by design (it has a waitUntil in it for sequencing), while addVehicle is unscheduled by design. You could rework resourcesFIA to be unscheduled (it should have been in the first place) but that's probably another 50 files to modify. Might need to revert all the related code and make another PR for that branch of changes.

2024-01-22 01:07 UTC, Tiny-DM commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +	driver _veh disableAI "MOVE";
More of a safety mechanism than anything. Potentially if they spot an enemy before the patrol loop starts. I'm going to keep it unless there's a strong reason to remove.

2024-01-22 01:19 UTC, jaj22 commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +	driver _veh disableAI "MOVE";
Fair enough.

2024-01-22 01:21 UTC, Tiny-DM commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +            _resourcesFIA = [0,_toRefund,true] call A3A_fnc_resourcesFIA;
Can you elaborate a bit on the changes neccesary for this? Because the function only really waits to modify a global variable, couldn't the wait be removed and all instances changed to spawn instead of call? I most likely will revert though until its sorted.

2024-01-22 01:27 UTC, Tiny-DM commented on A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf
> +    [] spawn A3A_fnc_checkCampaignEnd; // If a town is destroyed, check for loss
you did WHAT now

Resolved. It was also missing a stringtable and the function to spawn mines, so those have been added as well.

2024-01-22 01:28 UTC, jaj22 commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +            _resourcesFIA = [0,_toRefund,true] call A3A_fnc_resourcesFIA;
1. Every remoteExec of resourcesFIA would change to remoteExecCall.
2. Every spawn of resourcesFIA would need context checking. If they're from unscheduled code then they can switch to call. Otherwise remoteExecCall or an isNil wrapper would be required.
3. Remove the waitUntil and the now-redundant variable.

The vast majority of uses seem to be remoteExec, so it wouldn't be a complex change, but it is ~38 extra files to modify.

2024-01-22 01:29 UTC, Tiny-DM commented on A3A/addons/garage/Public/fn_addVehicle.sqf
> +            _resourcesFIA = [0,_toRefund,true] call A3A_fnc_resourcesFIA;
Ah, understood. I will pull the changes for now.

2024-01-22 04:51 UTC, Tiny-DM commented
Did a quick fix before bed. Note that this currently has the fixes to all of the issues above and contains fixes to a few minor issues from #3089 , so I would prefer to get a review and merge done shortly. 

- reverted all code around garaging items with inventories and instant refund
- removed stray periods from support calls and made a few calls shorter
- the hint for promoting players now renders correctly (was [text] joinstring [text2] not [text,text2] joinstring "")
- orbital strikes now are stringtabled and undergo the same city destroy functions as other sources e.g. mine placement
- at Bob's request, seaport nerf. Seaports now only cut 5% off of vehicle cost and the bonus maxes out at 6 seaports owned for a total of 30% discount. Changes are welcome, attempting to implement a more granular logarithmic function ended up giving vehicles very odd prices.
- spaces instead of....I dont know what vscode was doing, but it's been fixed.
- minor fix for the mass calculations where the notification would remoteExec onto an empty crew.

2024-01-22 05:17 UTC, jaj22 submitted a review, later dismissed

2024-01-22 05:17 UTC, jaj22 commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +if (crew _vehicle isNotEqualTo []) then [localize "STR_A3A_logi_title", _bodyText] remoteExec ["A3A_fnc_customHint", crew _vehicle];
I think you're missing the curly brackets here. I'd just drop the line personally though: No-one needs to know about the mass change aside from the person adding the object. Hell, they don't really need to know either but whoever wrote this code liked their textual feedback. Also customHint should technically be a remoteExecCall, but there are a lot of bad ones around.

2024-01-22 06:29 UTC, jaj22 commented on A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
> +if (crew _vehicle isNotEqualTo []) then [localize "STR_A3A_logi_title", _bodyText] remoteExec ["A3A_fnc_customHint", crew _vehicle];
Better idea, send to the driver (if present) rather than the whole crew.

2024-01-22 08:06 UTC, killerswin2 commented on A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
> +    ["Undercover OFF", 0, 0, 4, 0, 0, _layer] spawn bis_fnc_dynamicText;
stringtable

2024-01-22 08:08 UTC, killerswin2 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    <Int> category index, -1 if it has no category, and -2 if it is found on the blacklist. Used for deleting the vehicle after being found on the blacklist.
the first comma should be a semi colon

2024-01-22 13:50 UTC, rautamiekka commented on A3A/addons/core/functions/Punishment/fn_punishment_sentence_server.sqf
> +                [localize "STR_A3A_fn_punish_ff_noti", _punishAdminText] remoteExecCall ["A3A_fnc_customHint",_admin,false];
`A3A_fnc_customHint` should be doing the `localize` locally instead of passing whole strings like this.

2024-01-22 13:51 UTC, rautamiekka commented on A3A/addons/core/functions/REINF/fn_addBombRun.sqf
> +if (isNull _veh) exitWith {[_titleStr, localize "STR_A3A_fn_reinf_bombrun_no_looking"] call A3A_fnc_customHint;}; // cursorObject null i.e. not looking at vehicle
> These one-liners are giving me a head-ache

Inclined to agree.

2024-01-22 14:01 UTC, rautamiekka requested changes

2024-01-22 15:03 UTC, Tiny-DM commented on A3A/addons/core/functions/init/fn_checkCampaignEnd.sqf
> +_popReport = format["Total Pop: %1, Dead Pop: %2, Rebel Support: %3, Gov Support: %4", _popTotal, _popKilled, _popReb, _popGov];
That goes in the logs, we aren't doing stringtables for log messages yet AFAIK.

2024-01-22 15:06 UTC, Bob-Murphy commented on A3A/addons/core/functions/init/fn_checkCampaignEnd.sqf
> +_popReport = format["Total Pop: %1, Dead Pop: %2, Rebel Support: %3, Gov Support: %4", _popTotal, _popKilled, _popReb, _popGov];
No stringtables for logs.

2024-01-22 15:12 UTC, Tiny-DM commented on A3A/addons/core/functions/Punishment/fn_punishment_sentence_server.sqf
> +                [localize "STR_A3A_fn_punish_ff_noti", _punishAdminText] remoteExecCall ["A3A_fnc_customHint",_admin,false];
Correct me if I'm wrong, but this is a server script sending a local exec to the client. So the only thing sent across the network is `localize "STR_A3A_fn_punish_ff_noti"` instead of the structured text we want to avoid. And regardless, this is the same structure across every hint call, so it would be a much bigger PR to fix any bugs.

2024-01-22 16:49 UTC, Tiny-DM commented on A3A/addons/core/functions/Punishment/fn_punishment_sentence_server.sqf
> +                [localize "STR_A3A_fn_punish_ff_noti", _punishAdminText] remoteExecCall ["A3A_fnc_customHint",_admin,false];
Disregard. I just looked at it more in-depth and the entire system often sends structured text over the network because keys are localized in the original script. This implementation is the same as other systems and works for now until the localization code can be moved locally. Detailed in #3106 , closing for now as I want to fix every instance at the same time in a separate PR

2024-01-22 17:13 UTC, Tiny-DM commented on A3A/addons/core/functions/REINF/fn_addBombRun.sqf
> +if (isNull _veh) exitWith {[_titleStr, localize "STR_A3A_fn_reinf_bombrun_no_looking"] call A3A_fnc_customHint;}; // cursorObject null i.e. not looking at vehicle
The function body has been rebuilt to one large switch case statement, with a few more additional statements for the more complicated stuff.

2024-01-22 18:02 UTC, Tiny-DM commented
All changes resolved. I'll be able to test these changes locally in a few hours and I've already proofread the code (for what its worth), but I would appreciate a second set of eyes. I want to get these changes done because there's a few annoying stringtable fixes for community in there.

2024-01-22 18:28 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_addBombRun.sqf
> +private _wrongOwner = !(isNil "_owner" && {_owner isEqualType ""} && {getPlayerUID player != _owner});
I think you lost `_owner = _veh getVariable "ownerX";` somewhere along the line.

2024-01-22 22:36 UTC, Tiny-DM commented
Fixed, also resolved a minor formatting bug in the construction of the save loading message.

2024-01-23 11:19 UTC, Bob-Murphy commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +sleep 5;
Please move this block before the "location spawned" event aka 3 lines higher.
Please also remove the 5 second sleep.
From my testing (I just solved the issue myself as I didn't see that you got it covered in here) defining it as _AAvehicles further above and specifying it here is not necessary as well as `_groupVeh` only is being used for the one AA vehicle.

2024-01-23 12:00 UTC, Bob-Murphy reviewed
To have it also in writing and not only verbal, whilst of course multiple issues can be fixed in one PR, please keep it to a reasonable amount so it's better reviewable and mergeable in smaller chunks.

Cheers for cleaning up so much stuff.

2024-01-23 12:15 UTC, rautamiekka requested changes

2024-01-23 12:15 UTC, rautamiekka commented on A3A/addons/core/functions/init/fn_checkCampaignEnd.sqf
> +    _popGov = _popGov + (_numCiv * (_supportGov / 100)); // support only matters if the city isn't destroyed
```suggestion
        _popReb = _popReb + (_numCiv * (_supportReb / 100));
        _popGov = _popGov + (_numCiv * (_supportGov / 100)); // support only matters if the city isn't destroyed
```

2024-01-23 14:09 UTC, Tiny-DM commented on A3A/addons/core/functions/Base/fn_canMoveHQ.sqf
>  };
That is correct. This has been confirmed by John.

2024-01-23 14:10 UTC, Tiny-DM commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +	private _numFriendlySeaports = ({sidesX getVariable [_x,sideUnknown] == teamPlayer} count seaports) min 6;
I think you're misunderstanding. If the rebels own 3 seaports, the bonus is 3 min 6 for 3. 6 seaports, 6 min 6 for 6. 9 seaports, 9 min 6 for 6. So it functions as a cap here.

2024-01-23 14:14 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Italian>Hai selezionato %1</Italian>
Punctuation was initially removed because the messages internally tack on punctuation and stuff, which seems like somewhat bad practice. I'll revert the punctuation changes and remove the internal formatter instead, makes everything a bit easier

2024-01-23 14:30 UTC, Tiny-DM commented on A3A/addons/core/functions/Intel/fn_selectIntel.sqf
> +            private _notYetUnlocked = allWeapons - unlockedWeapons - allMissileLaunchers; // to prevent guided launchers from being unlocked by large intel
Sorry, should I remove the code or keep it? Because allowing guided launchers to be unlocked randomly is a problem when the parameter is turned off.

2024-01-23 14:36 UTC, Bob-Murphy commented on A3A/addons/core/functions/Intel/fn_selectIntel.sqf
> +            private _notYetUnlocked = allWeapons - unlockedWeapons - allMissileLaunchers; // to prevent guided launchers from being unlocked by large intel
Keep

2024-01-23 16:40 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> +        <Italian>Hai selezionato %1</Italian>
Looked into this specific instance more. The issue is that the string it's referencing pulls, for example, `Grenadier role. + <br/> + Grenadiers have a slight bonus on carry capacity, but are easy to spot.` Since the original string being modified has a period at the end, the period's double up and form `You have selected Grenadier role. + <br/> + Grenadiers have a slight bonus on carry capacity, but are easy to **spot..** One of them has to be removed, and I'll probably remove the stray period from the role features line.

I need a better hobby than hunting down periods.

2024-01-23 16:49 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> -        <Original>%1 is about to execute an airstrike.</Original>
The original phrasing for these before they got stringtabled did not include a period, and if you have low reveal on a support call it probably looks better and is a bit less error prone to not have the period in the default notification. The function for adding "Target marked on map!" adds a period to the original phrase if neccesary. AFAIK no changes needed but removing these periods.

2024-01-23 16:58 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> -        <Original>%1 is about to execute an airstrike.</Original>
You mean for example this line?
`    _text = format ["%1. " + localize "STR_A3A_fn_support_showIntSPTCll_TARGET", _text];`

In my eyes that's bad practice.
The punctuation should be within the string, not the code. Hence it should be removed after the `%1` rather than in the stringtable entries.

2024-01-23 17:00 UTC, Bob-Murphy commented on A3A/addons/core/Stringtable.xml
> -        <Original>%1 is about to execute an airstrike.</Original>
This is from `A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf` line 107 where the `_text` is the `STR_A3A_fn_support_showIntSPTCll_AIRSTRIKELONG` from above.

2024-01-23 17:04 UTC, Tiny-DM commented on A3A/addons/core/Stringtable.xml
> -        <Original>%1 is about to execute an airstrike.</Original>
Ah, alright. I will readd the periods and change the offending line to `_text = [_text,localize "STR_A3A_fn_support_showIntSPTCll_TARGET"] joinString " ";` , which should leave the period in the original message, add a space, and add the target message.

2024-01-23 17:36 UTC, Tiny-DM commented
All changes resolved. I'm not at home to test these changes locally, but it's mostly adding and removing periods, and nothing should have broken.

2024-01-23 17:45 UTC, Bob-Murphy approved these changes
Changes tested and confirmed working.

2024-01-23 19:05 UTC, jaj22 approved these changes

2024-01-23 22:29 UTC, merged