preliminary 3.5.0 changelog
official-antistasi-community/A3-Antistasi pull request #3135
Opened 2024-02-09 20:26 UTC by Bob-Murphy

Adds preliminary changelog for 3.5.0 update
version number in code as well as readme is already adjusted

2024-02-09 21:00 UTC, Tiny-DM commented on changelog.rst
> +   * In summer and in winter, resistance fighters armed with their R-700 bolt-action rifles trudge through the fields towards ill-prepared Bundeswehr and NVA roadblocks. In an occupied post-WW2 Germa
The summer and The winter

2024-02-09 21:00 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3102` Added garage now deleting bugged vehicles instead of registering them.
The garage now deletes bugged vehicles instead of registering them.

2024-02-09 21:00 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3102` Fixed Kill the Traitor mission will not succeeding if the traitor surrenders.
Fixed a bug where the Kill the Traitor mission would break if the traitor surrendered.

2024-02-09 21:00 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3110` Added garbage cleans moving dead soldiers out of their vehicle, which fixes a bug with ACE where seats would be locked if a garbage clean happened.
Garbage cleans now move dead soldiers out of their vehicle, fixing a bug with ACE where seats would be locked if bodies were deleted in a seat.

2024-02-10 18:40 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3079` Fixed a bug where trying to breach whilst undercover will do nothing and an exploit where you could breach for free under certain circumstances.
Can probably truncate this to "fixed two bugs with breaching vehicles".

2024-02-10 18:52 UTC, targetingsnake requested changes

2024-02-10 18:52 UTC, targetingsnake commented on changelog.rst
> +
if we add #3131 we should mentioned it here or at minor stuff

2024-02-10 18:52 UTC, targetingsnake commented on changelog.rst
> +
issue https://github.com/official-antistasi-community/A3-Antistasi/pull/2802 swaped rebel transport truck with cargo truck

2024-02-10 19:38 UTC, jaj22 commented on changelog.rst
> +   * :issue:`3102` Added the last victim to the hint admins recieve for friendly fire.
recieve -> receive

2024-02-10 22:40 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`3079` Fixed a bug where trying to breach whilst undercover will do nothing and an exploit where you could breach for free under certain circumstances.
eh, can stay this way. doesn't hurt to point out exploits fixed

2024-02-10 23:03 UTC, targetingsnake approved these changes

2024-02-11 18:27 UTC, merged