Params for no fast travel and no box restore
official-antistasi-community/A3-Antistasi pull request #3152
Opened 2024-02-17 01:53 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Added a param to disable the "restore nearby units" option on the garage box.
Added an option to the fast travel param to completely block fast traveling.
Fixed a typo in a string I found on accident.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Everything should be visible and work from the setup GUI.
********************************************************
Notes:
This is all Bob's fault.

2024-03-02 18:57 UTC, jaj22 requested changes

2024-03-02 18:57 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +vehicleBox addAction [localize "STR_A3A_actions_restore_units", A3A_fnc_vehicleBoxRestore,nil,0,false,true,"","(isPlayer _this) and (_this == _this getVariable ['owner',objNull]) and (side (group _th
A3A_removeRestore is probably bool-translated so this is incorrect.

2024-03-02 18:57 UTC, jaj22 commented on A3A/addons/core/Params.hpp
> +        values[] = {0,1,2};
There's code since 3.5 to do the saved bool -> live number translation but I don't think it's been tested, so load in an older save with this code and make sure the value is 0 or 1.

2024-03-03 19:38 UTC, Tiny-DM commented on A3A/addons/core/functions/init/fn_initClient.sqf
> +vehicleBox addAction [localize "STR_A3A_actions_restore_units", A3A_fnc_vehicleBoxRestore,nil,0,false,true,"","(isPlayer _this) and (_this == _this getVariable ['owner',objNull]) and (side (group _th
Changed this part to ` and !A3A_removeRestore` , tested.

2024-03-03 19:38 UTC, Tiny-DM commented on A3A/addons/core/Params.hpp
> +        values[] = {0,1,2};
Checked with a save on 3.4.1, which should be old enough, seems to work as intended.

2024-03-03 19:39 UTC, Tiny-DM commented
Did some more testing and fixed an issue with the bool-translating, ready for review.

2024-03-03 19:42 UTC, jaj22 approved these changes

2024-03-30 20:04 UTC, merged