Rhs/3cb a29 t28 plane fix attempt
official-antistasi-community/A3-Antistasi pull request #3172
Opened 2024-03-15 00:01 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Attempts making the A29 and T28 from RHS and 3CB respectively to work

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-03-15 13:23 UTC, ante185 commented
addendum: Perhaps some of the templates that would be receiving these planes could loose their CAS jets : Prop-Plane CAS would be a signature of these factions and it'd set them apart - that is probably for a separate PR though.

2024-03-16 14:35 UTC, ante185 commented
I have tested both planes, and the MD-454 Mystere as a control, both with and without ACE and everything behaves as desired/as i would expect it to

2024-05-17 14:29 UTC, jaj22 requested changes

2024-05-17 14:29 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_AGM114L_Launcher", "rhs_weap_gbu12"]];
The GBU-12 won't work here, will it?

2024-05-17 14:29 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Data needs moving to config now that the setPlaneLoadout -> config PR has been merged.

2024-05-17 14:29 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_CASRun.sqf
> +};
Better way of doing this is to add a config parameter for "gunnerLaser" or similar for the plane. If that's not an empty string then fire it here.

2024-05-17 15:07 UTC, ante185 commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_AGM114L_Launcher", "rhs_weap_gbu12"]];
It does, and it is from my testing accurate enough unless the target is atop a hill.
The GBU12 working out this well is very much an accident though, i think it works well enough to include it as a bonus - the pylon would otherwise be empty.

2024-05-17 16:16 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
> +            _plane setVariable ["missileLauncher", ["rhs_weap_AGM114L_Launcher", "rhs_weap_gbu12"]];
Hmm. CAS approach slope is probably supposed to be terrain-invariant...

2024-05-17 21:04 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_CASRun.sqf
> +private _gunnerLaser = getText(configFile >> "A3A" >> "Loadouts" >> "CASPlane" >> typeOf _plane >> "gunnerLaser";
Missing close bracket.

2024-05-18 04:10 UTC, jaj22 approved these changes
Seems plausible. Haven't tested.

2024-05-24 11:40 UTC, merged