CDLC Compatibility - Reaction Forces
official-antistasi-community/A3-Antistasi pull request #3185
Opened 2024-03-26 22:51 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Updated existing templates to use RF assets.
All rebel and civ factions for WS and vanilla are done, and all enemy factions for vanilla are done.
(will fill this section in later with details, review for now)

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Would prefer additional playtesting, but as it stands everything should be relatively solid.
KNOWN BUG: The non-undercover pickup will sometimes don civilian camos
Making the PR from internal branch to unstable now for testing purposes

2024-03-26 23:29 UTC, ante185 requested changes
Some stray errors that need fixing, but it is looking promising

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +                    }; // this is why we cant have nice things
remove comment

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    _sfLoadoutData set ["sidearms",[
Justify overwriting instead of appending

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    ["hgun_Glock19_auto_Tan_RF", "muzzle_snds_L", "acc_flashlight_pistol", "optic_MRD_tan_RF", [], [], ""],
SF should probably be using the IR flashlights or lasers

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
Appending just the RF smg will be fine

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
> +    ["arifle_ash12_LR_wood_RF","suppressor_127x55_small_wood_RF""acc_pointer_IR","optic_Arco_ghex_F",["10Rnd_127x55_Mag_wood_RF","10Rnd_127x55_Mag_wood_RF","10Rnd_127x55_Mag_wood_RF"], [], "bipod_02_
typo, missing comma " suppressor_127x55_small_RF"acc_pointer_IR "

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
You don't need to append extra vanilla SMGs

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
> +    ["arifle_ash12_LR_blk_RF","suppressor_127x55_small_RF""acc_pointer_IR","optic_SOS",["10Rnd_127x55_Mag_RF","10Rnd_127x55_Mag_RF","10Rnd_127x55_Mag_RF"], [], "bipod_02_F_hex"]
typo, missing comma between suppressor and pointer

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
same as before, append just the new SMG

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
> +    ["arifle_ash12_LR_blk_RF","suppressor_127x55_small_RF""acc_pointer_IR","optic_SOS",["10Rnd_127x55_Mag_RF","10Rnd_127x55_Mag_RF","10Rnd_127x55_Mag_RF"], [], "bipod_02_F_hex"]
missing comma

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
drop vanilla smgs

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
> +    ["arifle_ash12_LR_wood_RF","suppressor_127x55_small_wood_RF""acc_pointer_IR","optic_SOS",["10Rnd_127x55_Mag_wood_RF","10Rnd_127x55_Mag_wood_RF","10Rnd_127x55_Mag_wood_RF"], [], "bipod_02_F_hex"]
missing comma

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
drop vanilla smgs

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +    _vehiclesHelisAttack = ["a3a_LDF_Heli_EC_02_RF"];
LDF is NATO aligned perhaps they should still have access to the Blackfoot

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +    _sfLoadoutData set ["sidearms",[
consider appending instead

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
drop the vanilla SMGs

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
> +    _sfLoadoutData set ["sidearms",[
consider appending instead

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
vanilla smgs can be dropped

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _sfLoadoutData set ["sidearms",[
consider appending

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
drop the vanilla SMGs, the RF guns will be rare enough as is

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +    _militaryLoadoutData set ["sidearms", [
Consider appending instead?

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
drop vanilla SMGs

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +    _militaryLoadoutData set ["sidearms", [
append instead of set?

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +    ["SMG_02_F", "", "acc_flashlight", "optic_Aco_smg", [], [], ""]
drop vanilla smgs

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +    _vehiclesCivHeli append ["C_Heli_EC_01A_civ_RF","C_Heli_EC_01_civ_RF","C_Heli_EC_04_rescue_RF"];
Might be preferable if reduced to only one helicopter, instead of having 5 helicopters in total taking up the buy menu.
If it's only a texture difference i don't see it as justifiable, as it is something players can change when ungaraging.

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +    _initialRebelEquipment append ["SMG_01_F","hgun_PDW2000_F","SMG_02_F","30Rnd_45ACP_Mag_SMG_01","30Rnd_9x21_Mag_SMG_02"];
leftover else and code, remove please

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +if ("rf" in A3A_enabledDLC) then {_dlcUniforms append [
new line before starting the code

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
> +    _vehiclesCivHeli append ["C_Heli_EC_01A_civ_RF","C_Heli_EC_01_civ_RF","C_Heli_EC_04_rescue_RF"];
see FIA comment

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf
> +if ("rf" in A3A_enabledDLC) then {_dlcUniforms append [
new line before starting the code

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +    _initialRebelEquipment append ["SMG_05_F","hgun_PDW2000_F","30Rnd_9x21_Mag_SMG_02"];
leftover else and append code

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +if ("rf" in A3A_enabledDLC) then {_dlcUniforms append [
new line

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
> +    _vehiclesCivHeli append ["C_Heli_EC_01A_civ_RF","C_Heli_EC_01_civ_RF","C_Heli_EC_04_rescue_RF"];
probably too many helicopters here too

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
> +        ["C_Pickup_covered_rf", ["rebCost, 250"]]
erroneous quotation marks

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
> +    _vehiclesCivHeli append ["C_Heli_EC_01A_civ_RF","C_Heli_EC_01_civ_RF","C_Heli_EC_04_rescue_RF"];
reduce to 1

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
> +    _initialRebelEquipment append ["hgun_PDW2000_F","SMG_02_F","30Rnd_9x21_Mag_SMG_02"];
leftovers

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
> +if ("rf" in A3A_enabledDLC) then {_dlcUniforms append [
formatting

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_Reb_Vehicle_Attributes.sqf
> +];
ok

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +	(_x#3) and {!(_x#1 in ["A3","curator","argo","tacops"])}
Unsure about what this does

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/core/functions/init/fn_setupMonitor.sqf
> +	(_x#3) and {!(_x#1 in ["A3","curator","argo","tacops"])}
Unsure about what this does

2024-03-26 23:29 UTC, ante185 commented on A3A/addons/logistics/Nodes/RF.hpp
> +        class Nodes
extra indentations

2024-03-27 01:16 UTC, Tiny-DM commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +	(_x#3) and {!(_x#1 in ["A3","curator","argo","tacops"])}
This was added at the very start of the integration of WS, almost precisely a year ago. The fourth selection in an entry about whether the DLC is official, i.e. something that should be added in the setup monitor. It's more clear if you run the command in game and see what counts as an official mod and what doesn't. The previous way was janky and entirely unneccesary, so it has been pulled.

2024-03-27 01:51 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf
> +    _vehiclesCivHeli append ["C_Heli_EC_01A_civ_RF","C_Heli_EC_01_civ_RF","C_Heli_EC_04_rescue_RF"];
Compromised, removed one helicopter from the lineup. Can potentially remove another if deemed absolutely neccesary

2024-03-27 02:21 UTC, jaj22 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +	(_x#3) and {!(_x#1 in ["A3","curator","argo","tacops"])}
It was added by Socrates because apparently his copy of WS was busted? I didn't have WS at the time so it was hard to prove that it wasn't necessary. Fine with removing it.

2024-03-28 14:27 UTC, ante185 requested changes
RPTs are clean, changes look good.
Only minor issues remain

2024-03-28 18:04 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    (_militiaLoadoutData get "SMGs") append ["SMG_01_black_RF", "SMG_02_F", "SMG_03_black", "SMG_03C_black"];
lack of flashlights is intentional, same way it was before

2024-03-28 21:10 UTC, ante185 approved these changes
Looks good to me

2024-03-30 21:09 UTC, merged