Adds vehiclesHeavyTanks template category
official-antistasi-community/A3-Antistasi pull request #3200
Opened 2024-04-04 17:15 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
adds a vehicle category for heavy tanks

### Please specify which Issue this PR Resolves.
I need this for the IFA AIO templates im working on, surely useful for other things too.

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
RFC on cost and threat i set in initVarServer
Need feedback on the weights set in getVehicleGroundSupport

2024-04-05 00:36 UTC, killerswin2 commented on A3A/addons/core/functions/init/fn_initVarServer.sqf
> +{ _vehicleResourceCosts set [_x, 280] } forEach FactionGet(all, "vehiclesHeavyTanks");
probably want this to be 300.

2024-04-05 00:37 UTC, killerswin2 commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +	private _vehTypesHeavy = (_faction get "vehiclesLightAPCs") + (_faction get "vehiclesAPCs") + (_faction get "vehiclesIFVs") + (_faction get "vehiclesLightTanks") + (_faction get "vehiclesTanks") + (
mind add a new line here. It is getting long!

2024-04-05 00:39 UTC, killerswin2 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
> +private _hvytWeight =       [ 0,  0,  0,  3,  6, 10, 14, 18, 22, 26] select _level;
Will need to talk with John on about the weights, he may have some suggestions to change the lighter tank's weight.

2024-04-05 01:51 UTC, ante185 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
> +private _hvytWeight =       [ 0,  0,  0,  3,  6, 10, 14, 18, 22, 26] select _level;
Agreed, it's also a question if we wanna/need to do something like we do at L35-L36

2024-04-05 05:26 UTC, targetingsnake requested changes

2024-04-05 05:26 UTC, targetingsnake commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> +setVar("vehiclesHeavyTanks", OccAndInv("vehiclesLightTanks"));
Are you sure you want to Insert Light Tanks as heavy ones?

2024-04-05 13:04 UTC, ante185 commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> +setVar("vehiclesHeavyTanks", OccAndInv("vehiclesLightTanks"));
thanks for that catch

2024-04-07 18:22 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
> +//Do vehiclesHeavyTanks need to be factored in here? How? TODO
Yes. Consider that you don't want to spawn more tanks overall just because a template has something in heavy tanks. The table should have the values for _tankWeight reduced by the amount added in _hvytWeight, and if there's nothing in vehiclesHeavyTanks then the values should be merged back into _tankWeight.

2024-04-08 21:39 UTC, ante185 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
> +//Do vehiclesHeavyTanks need to be factored in here? How? TODO
i see, it'd be something like this then?
`if (_faction get "vehiclesHeavyTanks" isEqualTo []) then { _tankWeight = _tankWeight + _hvytWeight };`

2024-04-09 21:58 UTC, ante185 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
> +//Do vehiclesHeavyTanks need to be factored in here? How? TODO
hm, no i don't think my math there works out

2024-04-22 17:54 UTC, ante185 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
> +//Do vehiclesHeavyTanks need to be factored in here? How? TODO
divided the heavy tank weight between light and regular tanks, decreased the latter two accordingly

2024-04-23 15:57 UTC, jaj22 requested changes
Missing changes to CASApproach (probably doesn't matter unless heavy tanks get used in non-WW2 templates) and startBreachVehicle. Search for "vehiclesTanks" in those.

2024-04-23 15:57 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
>  // Only one of these two is mandatory
Comment should be moved down a line or reworded. Heavy tanks are optional, one of light tanks or tanks is mandatory.

2024-04-24 00:17 UTC, ante185 commented on A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf
>  // Only one of these two is mandatory
Updated comment to reflect on this.
I've also updated startBreachVehicle and CASApproach, which i will test tomorrow.

2024-04-28 16:34 UTC, jaj22 approved these changes
Fine to merge now, I think.

2024-04-28 21:12 UTC, merged