RF Compatibility - WS Templates
official-antistasi-community/A3-Antistasi pull request #3204
Opened 2024-04-07 03:25 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Added RF compatibility to the WS templates, as well as adding pickups to the militia vehicle pool for most factions.
Switched the SF marksmen to using the big suppressor for their 12.7mm rifle.
Several known bugs right now, but since the RPT has no errors I'm throwing this up now for a preliminary review.

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Known bugs:
Military vehicles will take on civilian colors sometimes when bought.
LDF Pickup MMG renders in all-black instead of the geometric pattern.
The fuel pickup has cargo nodes on the bed.

********************************************************
Notes:

2024-04-07 16:00 UTC, ante185 reviewed
Suggestions

2024-04-07 16:00 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
>  ["vehiclesHelisAttack", ["O_Heli_Attack_02_dynamicLoadout_black_F"]] call _fnc_saveToTemplate;
ION could have their AH lineup supplemented with the new cougar AH

2024-04-07 17:13 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
> +    _vehiclesAA append ["B_ION_Pickup_aat_rf"];
SAAMI go fwoosh, fly straight line
But more seriously, a ZU is pretty limiting. RFC requested

2024-04-10 15:27 UTC, ante185 requested changes

2024-04-10 15:27 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
> +    _vehiclesHelisLightAttack append ["a3a_Heli_light_03_dynamicLoadout_RF","a3a_tan_Heli_EC_04_military_RF"];
Armed and unarmed are switched around

2024-04-10 15:27 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
> +    _vehiclesHelisLightAttack append ["a3a_black_Heli_light_03_dynamicLoadout_RF","a3a_ION_Heli_EC_04_military_RF"];
Armed and unarmed are switched around

2024-04-10 15:27 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
> +    _vehiclesHelisLightAttack append ["a3a_Heli_light_03_dynamicLoadout_RF","a3a_tan_Heli_EC_04_military_RF"];
Armed and unarmed are switched around

2024-04-10 15:27 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
> +};
no SFIA helicopters?

2024-04-12 13:00 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
> +    ];
IIRC you don't need the check here because there's no actual use of the classname unless the vehicle also exists in the spawn arrays. You can just dump everything into the main array, regardless of whether the vehicle exists in the modset.

2024-04-12 13:03 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
> +    _vehiclesHelisLightAttack append ["a3a_tan_Heli_light_03_dynamicLoadout_RF","a3a_tan_Heli_EC_04_military_RF"];
Good catch. Thought I hit all of them

2024-04-12 14:03 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
> +    ];
It throws a validation error when RF isn't loaded.
Since validation errors are benign it isn't technically a problem i suppose.

2024-04-12 14:55 UTC, ante185 requested changes
Several issues :(

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +    class a3a_civ_Pickup_covered_RF : C_Pickup_covered_RF {
is this and a3a_civ_Pickup_RF really necessary?

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
>          factions = "CIV_F";
ION chopper maybe shouldn't be civilian

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +        factions = "CIV_F";
ION choppers maybe shouldn't be civilian

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf
> +    _vehiclesHelisLightAttack append ["a3a_green_Heli_light_03_unarmed_RF"];
unarmed heli in lightAttack, did you mean to put this in helisLight?

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
> +["vehiclesHelisLight", _vehiclesHelisLight] call _fnc_saveToTemplate;
_vehiclesHelisLight made into an array but you never add anything to it

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _vehiclesHelisLight append ["a3a_tan_Heli_light_03_unarmed_RF"];
very much armed
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/3277295d-f99f-46a5-9070-1449406d13a7)

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +    _vehiclesHelisLight append ["a3a_tan_Heli_light_03_unarmed_RF"];
tan, armed

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +    _vehiclesHelisLightAttack append ["a3a_tan_Heli_light_03_dynamicLoadout_RF","B_Heli_EC_03_RF"];
tan hellcat instead of olive or whatever would be suitable for temperate

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +    _vehiclesHelisLight append ["a3a_green_Heli_light_03_unarmed_RF"];
olive would probably be more suitable than green, would fit the NATO tropical colour scheme better?
At least this one is unarmed.

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
> +    _vehiclesHelisLightAttack append ["a3a_green_Heli_light_03_dynamicLoadout_RF","B_Heli_EC_03_RF"];
same colour thing as above

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
> -        ["C_Pickup_covered_rf", ["rebCost", 250]]
you need to change these to your custom classes since you've replaced them all

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
> +    _vehiclesHelisLight append ["a3a_tan_Heli_light_03_unarmed_RF"];
armed

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
> +    _vehiclesHelisLightAttack append ["a3a_tan_Heli_light_03_dynamicLoadout_RF","a3a_tan_Heli_EC_04_military_RF"];
unarmed cougar

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf
> +    _vehiclesHelisAttack append ["a3a_Heli_EC_02_RF"];
the RF helicopters are much more suitable for the ADF than any of the NATO choppers will ever be, you can replace the appends with = for all four categories.

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
> +    _vehiclesHelisLightAttack append ["a3a_black_Heli_light_03_dynamicLoadout_RF","a3a_ION_Heli_EC_04_military_RF"];
Armed and unarmed EC 03 and EC 04 are still switched around

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
> +    _vehiclesLightUnarmed append ["B_ION_Pickup_rf"];
this is OK but i wish it was armored

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
> +    _vehiclesLightArmed append ["B_ION_Pickup_mmg_rf"];
same wish as for "B_ION_Pickup_rf"

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
> +    _HelisTransport append ["a3a_tan_Heli_EC_03_RF"];
armed

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
> +    _vehiclesHelisLight append ["a3a_tan_Heli_light_03_unarmed_RF"];
also armed

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
> +    _vehiclesHelisLightAttack append ["a3a_tan_Heli_light_03_dynamicLoadout_RF","a3a_tan_Heli_EC_04_military_RF"];
"a3a_tan_Heli_EC_04_military_RF" is unarmed

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
> +    _vehiclesMilitiaLightArmed append ["B_Pickup_mmg_rf"];
with there being 6 armed offroads in the militialightarmed array you'll practically never see the mmg pickup

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf
> +    _vehiclesHelisAttack append ["a3a_Heli_EC_02_RF"];
NATO Deserts gets given the attack helicopter version of the cougar unlike all the others who only get the 2-pylon one?

2024-04-12 14:55 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
> +    _vehiclesHeliAttack append ["a3a_sfia_Heli_EC_02_RF"];
Only one SFIA helicopter?

2024-04-12 20:27 UTC, Tiny-DM commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +    class a3a_civ_Pickup_covered_RF : C_Pickup_covered_RF {
I mean, it's a pickup and a covered pickup. Not sure what's wrong.

2024-04-12 20:28 UTC, Tiny-DM commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
>          factions = "CIV_F";
Fixed an issue, I don't remember what it did. I'll revert and see what it breaks.

2024-04-12 20:29 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf
> +    ];
Would prefer to avoid errors if possible, plus saves a tiny bit of performance. Closing for now, going to remain as-is.

2024-04-12 21:30 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +    class a3a_civ_Pickup_covered_RF : C_Pickup_covered_RF {
I mean as in do the C_Pickup_covered_RF and C_Pickup_RF randomly spawn in with undesired textures?

2024-04-12 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
> +    _vehiclesHelisLightAttack append ["a3a_tan_Heli_light_03_dynamicLoadout_RF","B_Heli_EC_03_RF"];
clarification: the tan version may be less suitable than the alternatives for temperate NATO

2024-04-13 17:05 UTC, ante185 requested changes
two missing semi colons, and an annoying casing validation failure

2024-04-13 17:05 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
> +        ["C_Pickup_covered_RF", ["rebCost", 250]],
these give a case complaint saying that it is supposed to be _rf and not _RF

2024-04-13 17:06 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
> +        ["C_Pickup_covered_RF", ["rebCost", 250]],
try switching the case in both the rebel templates and in the vehicle attributes?

2024-04-14 18:30 UTC, ante185 requested changes
Annnd i can't approve it yet :(

2024-04-14 18:30 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +    class C_Pickup_covered_RF;
unused parent classes

2024-04-14 18:30 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _HelisTransport append ["a3a_tan_Heli_EC_04_military_RF"];
Were we not supposed to use the og Olive camo here?
Not a big deal change at your discretion

2024-04-14 18:30 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +    class a3a_black_Pickup_mmg_rf : a3a_fia_Pickup_mmg_RF
this is gonna be really annoying but can we have some case-consistency?

2024-04-14 18:30 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
>      class I_G_Pickup_mmg_rf;
this class is protected as of the last RF update, so i cannot have a look at the classes derived from the MMG pickup

2024-04-14 18:56 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf
> +    _HelisTransport append ["a3a_tan_Heli_EC_04_military_RF"];
Good catch, tan is saved for WS

2024-04-14 23:09 UTC, ante185 requested changes
cannot approve yet.

2024-04-14 23:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
> +    _vehiclesLightArmed append ["B_ION_Pickup_mmg_rf","B_ION_Pickup_mmg_rf","a3a_ION_Pickup_hmg_rfF"];
typo
Stray F at the end, a3a_ION_Pickup_hmg_rfF instead of a3a_ION_Pickup_hmg_rf

2024-04-14 23:27 UTC, Tiny-DM commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +                        attachment[] = {"PylonRack_19Rnd_missiles_olive_rf","PylonRack_4Rnd_LG_scalpel","PylonRack_4Rnd_LG_scalpel","PylonRack_19Rnd_missiles_olive_rf"};
Just checked, doesn't matter

2024-04-14 23:34 UTC, ante185 approved these changes
Approved

2024-04-14 23:35 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +                        attachment[] = {"PylonRack_19Rnd_missiles_olive_rf","PylonRack_4Rnd_LG_scalpel","PylonRack_4Rnd_LG_scalpel","PylonRack_19Rnd_missiles_olive_rf"};
Works for me

2024-04-17 22:19 UTC, ante185 requested changes

2024-04-17 22:19 UTC, ante185 commented on A3A/addons/config_fixes/RF/CfgVehicles.hpp
> +    class B_ION_Pickup_aat_rf;
this, and any classes with it as a parent has to be moved to a separate config with both WS and RF as requirements.
Or you can change it and make the inheriting classes inherit from I_Pickup_aat_rf instead.

2024-05-04 21:02 UTC, ante185 approved these changes
lgtm

2024-05-17 14:05 UTC, merged