Rhs hidf
official-antistasi-community/A3-Antistasi pull request #3209
Opened 2024-04-09 00:30 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds the RHS HIDF faction.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-06-03 19:44 UTC, Tiny-DM requested changes

2024-06-03 19:44 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +["vehiclesArtillery", ["RHS_M119_WD"]] call _fnc_saveToTemplate;        // "rhsusf_M142_usarmy_D" - OP until we can customize magazines
remove comment

2024-06-03 19:44 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +["rhsusf_m109_usarmy", ["rhs_mag_155mm_m795_28"]],
remove unnecessary ammo entries

2024-06-03 19:44 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +["vehiclesMilitiaTrucks", ["rhs_zil131_msv"]] call _fnc_saveToTemplate;
Eastern truck stands out in a template of US surplus

2024-06-03 19:44 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +_loadoutData set ["ATLaunchers", [
Less optics maybe? The faction is supposed to be really poor.

2024-06-03 19:44 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +["rhs_weap_m4a1_carryhandle", "rhsusf_acc_rotex5_grey", "acc_flashlight", "", ["rhs_mag_30Rnd_556x45_M855A1_Stanag"], [], ""]
An M4 in the SMGs?

2024-06-04 15:45 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +["rhs_weap_m4a1_carryhandle", "rhsusf_acc_rotex5_grey", "acc_flashlight", "", ["rhs_mag_30Rnd_556x45_M855A1_Stanag"], [], ""]
yep

2024-06-08 23:53 UTC, Tiny-DM approved these changes
lgtm

2024-06-12 14:18 UTC, ante185 commented
Update:
Replaced the modern US trucks with trucks of a more suitable vintage.
Created olive green versions of the TOW hmmwv, m113 m240, m113 MEV, and M2A2, added to template

2024-06-12 18:10 UTC, merged