Update fn_vehiclePrice to not fail on absent vehicles.
official-antistasi-community/A3-Antistasi pull request #3228
Opened 2024-04-17 22:04 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Adds a check to fn_vehiclePrice that ensure the function doesn't error when _typeX is nil.
This would be the first step in the direction of letting some rebel templates have less stuff.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-04-18 16:00 UTC, jaj22 requested changes

2024-04-18 16:00 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
>  else
May as well do a full reformat on this function while you're in there. The stuff below the else is pretty messed up.

2024-04-18 17:25 UTC, ante185 commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +_costs = 0;
yeah that was supposed to be that way

2024-04-18 17:36 UTC, ante185 commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
>  else
reformatted and cleaned up

2024-04-18 17:49 UTC, jaj22 approved these changes

2024-04-18 17:49 UTC, jaj22 commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +		_discount = 0 max ((tierWar - 4) * 0.5);	//4 is the last war tier before discounts, the 0.5 makes the discount go from 0-3 instead of 0-6.
Note that this gives a lower result for tiers 5, 7 and 8 because it's not rounded. Fine this way though.

2024-04-22 17:33 UTC, Tiny-DM commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +		_discount = 0 max ((tierWar - 4) * 0.5);	//4 is the last war tier before discounts, the 0.5 makes the discount go from 0-3 instead of 0-6.
Would it potentially be worth rounding this? Wanted to avoid vehicles costing 187 euros for a reason.

2024-04-22 17:35 UTC, ante185 commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +		_discount = 0 max ((tierWar - 4) * 0.5);	//4 is the last war tier before discounts, the 0.5 makes the discount go from 0-3 instead of 0-6.
That'd be more sensible to round away in the final calculation on line 33.
I think rounding to the nearest 5€ would be the most sensible?

2024-04-22 17:39 UTC, Tiny-DM commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +		_discount = 0 max ((tierWar - 4) * 0.5);	//4 is the last war tier before discounts, the 0.5 makes the discount go from 0-3 instead of 0-6.
That should work fine, yeah.

2024-04-22 19:05 UTC, ante185 commented on A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
> +		_discount = 0 max ((tierWar - 4) * 0.5);	//4 is the last war tier before discounts, the 0.5 makes the discount go from 0-3 instead of 0-6.
Price rounding updated

2024-04-28 21:17 UTC, merged