Added GUI prefix and Experimental Battle Menu
official-antistasi-community/A3-Antistasi pull request #3229
Opened 2024-04-18 13:50 UTC by CalebSerafin

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Changes to existing external functionality:
* Fast travel uses fancy timeSpan formatting to see the remaining travel time.
* String table entries for fast travel have the `s`(second) (or language equivalent) removed.
* String table entries for donateMoney have a format template for the amount.

Changes to the current battle menu:
* Added button for new menu.

New to Experimental Battle Menu:
* Functions inside the GUI addon have a A3A_GUI_ prefix.
* Some functionality inside of the new battle menu has been implemented.
  * Donate Money to player
  * Donate money to faction
  * Hide Top Bar
  * Resign
  * Garbage Clean
  * Call air-strike
  * See player UID and add member
  * See money
  * Change Spawn Distance
  * Open normal fast travel map (Integrated fast travel will be added later after de-spaghettification)
  * Go undercover and discover any unsatisfied requirements
  * Teleport HQ assets

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

Multiplayer testing is required for:
* Donate money to a player
* Add player as a Member

### How can the changes be tested?
Try:
* Donate money to a player
* Add player as a Member

********************************************************
Notes:

2024-04-18 13:59 UTC, jaj22 commented on A3A/addons/core/functions/OrgPlayers/fn_resourcesPlayer.sqf
> +    this remoteExecCall ["A3A_fnc_resourcesPlayer", 2];
this -> _this

2024-04-27 17:02 UTC, jaj22 commented
I see that the new menu is now accessible regardless of whether the option is checked in parameters. Probably don't want to do that if most of the options are non-working and/or placeholders.

Initial notes:
- The timespan fomatting is (intentionally?) ridiculous. One does not measure microseconds in Arma.
- Teleport assets maybe shouldn't work unless the player is at HQ? Need to think about the risks.
- Donate money to faction doesn't update the current money display.
- Spawn distance change doesn't seem to stick. Not sure if intentional.
- Going undercover will throw the message "You are undercover already".
- Going overt will report you (30 min timeout), even at HQ with no enemies nearby.

Tested working:
- Hide/show top bar
- Resign
- Garbage clean (all)
- Teleport assets.
- Fast travel probably works to the extent it's supposed to.

2024-04-27 17:26 UTC, jaj22 commented
MP testing:
- Admin tab is entirely missing on a DS. Was logged in before the mission started.
- Donate money to player doesn't seem to do anything. Doesn't indicate player under cursor, doesn't remove money, doesn't throw any message.

2024-05-14 13:21 UTC, CalebSerafin commented
"Going overt will report you (30 min timeout), even at HQ with no enemies nearby."
---
After reading through `fn_goUndercover`, I discovered that if the player is `!captive player` it sets the `_reason = "Reported"` and compromises the player for the next 30 minutes.

The rest of the code is also pretty scary . So I'll think I'll make the button behave the same as on the old menu and only make you undercover. And postpone the Undercover re-write to the future or some other poor soul.

I also suspect that the undercover check loop dies randomly

Going undercover will throw the message "You are undercover already".
--- 
That is current behaviour as I have not changed `fn_goUndercover` or `fn_canGoUndercover`.
However, `fn_canGoUndercover` is called whenthe menu is open to get information about any undercover blockers. That will execute `[_titleStr, localize "STR_A3A_fn_undercover_canGoUn_already"] call A3A_fnc_customHint;`. That will need to be fixed by differing responsibility of all customHints to the caller (`fn_goUndercover`) rather than `fn_canGoUndercover`

2024-05-14 16:58 UTC, CalebSerafin commented
Going undercover will throw the message "You are undercover already".
---
In some cases, the player cannot go undercover, but this is only caught in the fn_goUndercover loop.
Since the fn_goUndercover script is spawned and has a delayed loop. It will not have marked the player as overt when the button handler invokes `["update"] spawn FUNC(playerTab)`
The main solution to fix this is to make A3A_fnc_goUndercover use A3A_fnc_canGoUndercover  under the hood.

2024-05-14 20:11 UTC, rautamiekka requested changes

2024-05-14 20:11 UTC, rautamiekka commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +		if (_checkForPlayer and ((_base != "SYND_HQ") and !(_base in airportsX)))
```suggestion
		if (_checkForPlayer and ((_base isNotEqualTo "SYND_HQ") and !(_base in airportsX)))
```

2024-05-14 20:11 UTC, rautamiekka commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +	if (_checkForPlayer and ((_base != "SYND_HQ") and !(_base in airportsX)))
```suggestion
	if (_checkForPlayer and ((_base isNotEqualTo "SYND_HQ") and !(_base in airportsX)))
```

2024-05-14 20:11 UTC, rautamiekka commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +	if ((sidesX getVariable [_base,sideUnknown] == Occupants) or (sidesX getVariable [_base,sideUnknown] == Invaders))
```suggestion
    if ((sidesX getVariable [_base,sideUnknown]) in [Occupants, Invaders])
```

2024-05-14 20:21 UTC, ante185 commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +		if (_checkForPlayer and ((_base != "SYND_HQ") and !(_base in airportsX)))
this would add case sensitivity to the check.
Unlikely to be a problem but likely unnecessary.

2024-05-14 21:27 UTC, rautamiekka commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +		if (_checkForPlayer and ((_base != "SYND_HQ") and !(_base in airportsX)))
The whole point is you don't need case-insensitivity.

2024-05-14 22:12 UTC, CalebSerafin commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +	if ((sidesX getVariable [_base,sideUnknown] == Occupants) or (sidesX getVariable [_base,sideUnknown] == Invaders))
Yeah looks good.

2024-05-14 22:12 UTC, CalebSerafin commented on A3A/addons/core/functions/Dialogs/fn_HQGameOptions.sqf
> +    <SCALER> Amount to adjust by or set [DEFAULT: nil]
Thanks

2024-05-14 22:13 UTC, CalebSerafin commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +		if (_checkForPlayer and ((_base != "SYND_HQ") and !(_base in airportsX)))
Hmm, I'm personally not sure if I can count on _base to always be cased correctly. I'll need to read some of the other code that users & defines it.

2024-05-15 23:39 UTC, rautamiekka requested changes

2024-05-15 23:39 UTC, rautamiekka commented on A3A/addons/core/functions/Time/fn_timeSpan_format.sqf
> +    <SCALAR> Fields Amount | <SCALAR,SCALAR> Slice   Number of significant fields to display. | First & last Index to be displayed. Days #0, hours #1 ect.. [DEFAULT=1e7]
```suggestion
    <SCALAR> Fields Amount | <SCALAR,SCALAR> Slice   Number of significant fields to display. | First & last index to be displayed. Days #0, hours #1 etc. [DEFAULT=1e7]
```

2024-05-16 17:48 UTC, jaj22 commented on A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
> +		if (_checkForPlayer and ((_base != "SYND_HQ") and !(_base in airportsX)))
The casing of Synd_HQ is consistently "Synd_HQ" at the moment (not "SYND_HQ", so the suggested code is incorrect). I believe this is the only function in the codebase that uses the wrong case.

I'd still use != here personally but the casing should be fixed either way.

2024-05-21 21:45 UTC, CalebSerafin commented
## Spawn distance change doesn't seem to stick. Not sure if intentional.
The same function used by the HQ map board Civ cap limiter was broken. it is now fixed.
Menu will not auto-close after committing changes.

2024-05-21 21:48 UTC, CalebSerafin commented
> * Teleport assets maybe shouldn't work unless the player is at HQ? Need to think about the risks.
It should be fine as it only allows admins this privilege.

2024-05-27 22:38 UTC, rautamiekka requested changes

2024-05-27 22:38 UTC, rautamiekka commented on A3A/addons/core/functions/OrgPlayers/fn_sendMoney.sqf
> +if (typeName _donateTo isEqualTo "STRING") exitWith {
```suggestion
if (_donateTo isEqualType "") exitWith {
```
[https://community.bistudio.com/wiki/isEqualType](https://community.bistudio.com/wiki/isEqualType):
> A much faster alternative to [typeName](https://community.bistudio.com/wiki/typeName) a [==](https://community.bistudio.com/wiki/a_==_b) [typeName](https://community.bistudio.com/wiki/typeName) b.

2024-05-29 18:26 UTC, jaj22 requested changes
Partial review. Haven't read all the UI stuff yet.

2024-05-29 18:26 UTC, jaj22 commented on A3A/addons/core/functions/OrgPlayers/fn_sendMoney.sqf
> +    false;  // false
Won't this code fire regardless of the value of _donateTo? Pretty sure it's supposed to be in a default statement inside the switch. Note that the if (true) exitWith above doesn't do anything, because exitWith only exits the current scope.

2024-05-29 18:26 UTC, jaj22 commented on A3A/addons/core/functions/Dialogs/fn_calculateFastTravelCost.sqf
> +} forEach _allObjectCargo;
Is this just `_things = _things - _allObjectCargo` except you're only removing items once, which I hope doesn't matter? For what it's worth, `_things deleteAt (_things find _x)` also works by design.

2024-05-29 18:26 UTC, jaj22 commented on A3A/addons/core/functions/Dialogs/fn_calculateFastTravelCost.sqf
> +{ _things pushBackUnique _x } forEach _allInfantryCargo;
Don't need to worry about pushBackUnique perf cost unless you have hundreds of items, which shouldn't be the case here.

2024-06-03 16:22 UTC, CalebSerafin commented on A3A/addons/core/functions/OrgPlayers/fn_isClientAdmin.sqf
> Normally when we're using these functions the question is about player permissions, not machine permissions.
It could be used to control if a script executes on the machine or not.

2024-06-03 16:33 UTC, CalebSerafin commented on A3A/addons/core/functions/OrgPlayers/fn_sendMoney.sqf
> +    false;  // false
Oops. I need to check that I didn't make that mistake somewhere else.

2024-06-03 16:36 UTC, CalebSerafin commented on A3A/addons/core/functions/OrgPlayers/fn_resourcesPlayer.sqf
> +    _this remoteExecCall ["A3A_fnc_resourcesPlayer", 2];
Good catch 👍

2024-06-03 16:45 UTC, CalebSerafin commented on A3A/addons/core/functions/Dialogs/fn_calculateFastTravelCost.sqf
> +} forEach _allObjectCargo;
I think I wrote it that way for performance reasons. But its probably not necessary and I've simplified it to using the array subtraction operator.

2024-06-09 17:48 UTC, jaj22 approved these changes
Generally fine. Made some optional notes.

2024-06-09 17:48 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_hqDialog.sqf
> +        _garrisonMap ctrlAddEventHandler ["Draw","_this call A3A_GUI_fnc_mapDrawOutpostsEH"];
Inconsistent with the rest of the file?

2024-06-09 17:48 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
> +        if (player isNotEqualTo theBoss) then {
[Raises eyebrow in suspicion]

2024-06-09 17:48 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
Very inconsistent usage of FUNC and absolute function names in this file?

2024-06-09 17:48 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_playerTab.sqf
> +        _aliveText ctrlSetText format [[[_time] call A3A_fnc_secondsToTimeSpan,1,1,false,2,false,true] call A3A_fnc_timeSpan_format];
Given that this is a common usage, and kinda messy, maybe make a small wrapper function or adjust timespan_format to take seconds as an option for the first parameter? I assume a timespan is an array so it seems like the latter would be easy to implement.

2024-06-11 14:51 UTC, CalebSerafin commented on A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
> +        if (player isNotEqualTo theBoss) then {
I think it was a suggestion in GitHub i implemented

2024-06-11 18:56 UTC, jaj22 commented
Ok, finding quite a lot of bugs in the HQ management menu. The garrisons menu in particular looks dangerously broken (maybe causing persistent save bugs) so I think bench it for now.

Found one additional bug in the battle menu that might need fixing: If you select a high command squad in the commander menu then you get an SQF error in canFastTravel.

Also you have merge conflicts with arsenalLimitsDialog.hpp to clear up. The file was largely rewritten so you'll need to do the function tagging again there.

2024-06-11 18:56 UTC, jaj22 requested changes
Changes requested as above.

2024-06-11 23:39 UTC, jaj22 commented
You didn't deal with the HC fast travel bug or the merge conflicts?

2024-06-12 15:57 UTC, CalebSerafin commented
Oops; I forgot after fixing the first issue 💀.
Fixed issue and merge conflicts.
Did a quick test with DS and two clients 👍.

2024-06-12 16:01 UTC, jaj22 approved these changes

2024-06-12 18:12 UTC, merged