Make artillery rotate to target before firing
official-antistasi-community/A3-Antistasi pull request #3231
Opened 2024-04-18 16:41 UTC by jaj22

### What type of PR is this.
1. [X] Bug
2. [X] Change
3. [ ] Enhancement

### What have you changed and why?
Some artillery vehicles have a limited firing arc and the artillery support code didn't take account of that. This PR fixes the issue by making artillery vehicles rotate towards the target before firing. Method should be solid. Adjusted the firing rate to 1/sec max as previously it varied based on rotation distance.

Not tested with anything except vanilla mortars, but should work fine.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Adjust as required:
`["MORTAR", Occupants, "defence", 500, objNull, markerPos "Therisa", 0.8, 20] call A3A_fnc_createSupport;`

2024-04-18 18:33 UTC, ante185 requested changes

2024-04-18 18:33 UTC, ante185 commented on A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
> +        private _interval = 10 * (time - _startTime) / abs _change;        // 10 degree/sec turn
possible zero divisor

2024-04-18 19:15 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
> +        private _interval = 10 * (time - _startTime) / abs _change;        // 10 degree/sec turn
Good call.

2024-04-22 17:41 UTC, Tiny-DM commented on A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
> +                sleep 1;
What is this change for? Just seems to lengthen the delay between the request and the firing

2024-04-22 17:45 UTC, ante185 approved these changes
Tested with IFA as this modset offers the artillery that'd require the ability to rotate.
For mortars it looks just like the regular aiming rotation, so that's about as good as is possible.
Bigger pieces do look odd, but given the low probability of seeing this occurring this is a concession that's gonna be alright to make.

TLDR: lgtm

2024-04-22 17:45 UTC, Tiny-DM approved these changes
lgtm

2024-04-28 21:19 UTC, merged