Garage Sell Button
official-antistasi-community/A3-Antistasi pull request #3237
Opened 2024-04-21 19:33 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information: Added an integrated sell button to the garage GUI.
Checks for commander status and locked status before selling
    

### Please specify which Issue this PR Resolves.
closes #2377

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Mostly needs testing to see if everything works in a multiplayer setting. None of the core functionality was changed too much, so it should be fine but still needs to be tested
********************************************************
Notes:

2024-04-29 15:44 UTC, jaj22 requested changes
Just dealing with the Antistasi/Garage split for now.

2024-04-29 15:45 UTC, jaj22 commented on A3A/addons/garage/Core/fn_sellVehGRG.sqf
> +if (_player != theBoss) exitWith {["STR_HR_GRG_Feedback_sellVehicle_comOnly"] call HR_GRG_fnc_Hint; diag_log "Not Commander"};
Old note, ignore.

2024-04-30 04:07 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
> +private _typeX = if (_isGRG) then {_veh;} else {typeOf _veh;};
If you want the function to accept both objects and classnames then just do that and drop the `_isGRG` parameter entirely:
`private _typeX = if (_veh isEqualType objNull) then {typeOf _veh} else {_veh};`

Should put a header on this function too.

2024-04-30 21:39 UTC, wersal454 commented
Is editing garage code legal? Or you asked Hakon for it?

2024-04-30 22:09 UTC, jaj22 commented
> Is editing garage code legal? Or you asked Hakon for it?

Asked Hakon, yes.

2024-05-04 20:17 UTC, rautamiekka requested changes
Consistency, a spelling error, and an optimization.

2024-05-04 20:17 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
> +        0. <Object, Str> Vehicle Object / Vehicle Class
```suggestion
        0. <OBJECT, STRING> Vehicle object / vehicle class
```

2024-05-04 20:17 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
> +        <Int> Sell price. 0 if invaLid or otherwise not found.
```suggestion
        <INT> Sell price. 0 if invalid or otherwise not found.
```

2024-05-04 20:17 UTC, rautamiekka commented on A3A/addons/garage/Core/fn_sellVehGRGLocal.sqf
> +    _ctrl = _disp displayCtrl _x;
```suggestion
    private _ctrl = _disp displayCtrl _x;
```

2024-05-05 00:31 UTC, jaj22 approved these changes
This is fine. Could be refactored a bit, but that wouldn't necessarily make it more readable or substantially reduce the code size. I think I'd also prefer the sell price on the button, but whatever.

Marked one chunk of dead code that can be cleared out.

2024-05-05 00:31 UTC, jaj22 commented on A3A/addons/garage/Core/fn_sellVehGRGLocal.sqf
> +} forEach [HR_GRG_IDC_ExtraMounts,HR_GRG_IDC_ExtraTexture,HR_GRG_IDC_ExtraAnim,HR_GRG_IDC_ExtraPylonsContainer];
This doesn't do anything and can be stripped out. It's only present in onLoad because these controls all start enabled, and switchExtrasMenu only disables the currently-enabled control for some reason.

2024-05-05 12:02 UTC, rautamiekka requested changes
Another consistency.

2024-05-05 12:02 UTC, rautamiekka commented on A3A/addons/garage/Core/fn_sellVehGRGLocal.sqf
> +    <nil>
```suggestion
    <NIL>
```
I missed this one somehow.

2024-05-17 14:08 UTC, merged