Artillery marker improvements
official-antistasi-community/A3-Antistasi pull request #3260
Opened 2024-05-25 03:26 UTC by Tiny-DM

## What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Added markers and hints to the friendly mortar strikes
Increased the accuracy of the marker lifetime for enemy artillery supports

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Need to make sure every friendly marker is at the right scope and can be seen by everyone
Need to make sure the enemy arty markers last for an appropriate time in other modsets. Currently working in vanilla
********************************************************
Notes:

2024-05-27 18:10 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
> +    private _weaponArray = getArray (configFile >> "CfgVehicles" >> _mortarType >> "Turrets" >> "MainTurret" >> "weapons");
IIRC there's at least one vehicle (RHS maybe? Not sure) where the artillery turret isn't the main turret, and another where the weapon lookup doesn't work either (pylon-based). Could maybe fetch the reload time in getArtilleryRanges because that's at least doing the work of finding the correct weapon. Might do that shortly because I'm fixing the function atm for IFA.

2024-05-27 19:02 UTC, rautamiekka requested changes

2024-05-27 19:02 UTC, rautamiekka commented on A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf
> +[_reveal, _targetPos, _side, "Airstrike", 150, 120] spawn A3A_fnc_showInterceptedSupportCall; // no better way to time this with the current system, unfortunantly
```suggestion
[_reveal, _targetPos, _side, "Airstrike", 150, 120] spawn A3A_fnc_showInterceptedSupportCall; // no better way to time this with the current system, unfortunately
```

2024-05-28 03:36 UTC, jaj22 commented on A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
> +    private _weaponArray = getArray (configFile >> "CfgVehicles" >> _mortarType >> "Turrets" >> "MainTurret" >> "weapons");
On second thoughts, it's not that predictable anyway because there might be a magazine reload in the middle of a volley. I'd recommend stripping out the config reading and just use the 3/5 check. Also you can just do `_mortar isKindOf "StaticMortar"` instead of passing through the type.

2024-06-04 21:23 UTC, Tiny-DM commented on A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
> +    private _weaponArray = getArray (configFile >> "CfgVehicles" >> _mortarType >> "Turrets" >> "MainTurret" >> "weapons");
The issue with the 3/5 check is that while it's spot on for mortars and fairly accurate for MLRS (at least in vanilla), it falls very far short for heavy arty. I will probably change it to 3/10 and accept that the MLRS will stay around for way longer than it needs to

2024-06-05 20:47 UTC, ante185 commented
when firing a barrage strike of smoke or HE using a CUP PODNOS mortar

```22:41:15 Ref to nonnetwork object 622228: shell.p3d
22:41:17 Ref to nonnetwork object 622232: shell.p3d
22:41:27 Error in expression < {deleteMarker _mrkFinal2; deleteMarker _mrkEllipse2; deleteMarker _mrkBarrageLi>
22:41:27   Error position: <_mrkEllipse2; deleteMarker _mrkBarrageLi>
22:41:27   Error Undefined variable in expression: _mrkellipse2
22:41:27 File x\A3A\addons\core\functions\AI\fn_artySupport.sqf..., line 319
22:41:27  ➥ Context: 	[] L319 (x\A3A\addons\core\functions\AI\fn_artySupport.sqf)
	[] L319 (x\A3A\addons\core\functions\AI\fn_artySupport.sqf)
```


![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/e4ebb6ba-e8a1-4e7b-b1f6-f0751b449c97)

2024-06-05 21:01 UTC, ante185 commented
more errors, testing the markers for enemy artillery
```==============
["MORTAR", Occupants, "defence", 500, objNull, markerPos "Therisa", 0.8, 1] call A3A_fnc_createSupport;
==============
22:59:13 2024-06-05 20:59:13:174 | Antistasi | Info | File: A3A_fnc_addSupportTarget | Added target <NULL-object> (position [10638.6,12227.1,0]) to support MORTAR1 | Called By: A3A_fnc_createSupport
22:59:14 Ref to nonnetwork object 1815186: shell.p3d
22:59:15 2024-06-05 20:59:15:147 | Antistasi | Info | File: A3A_fnc_logPerformance |  ServerFPS:31.6206, Players:1, DeadUnits:0, AllUnits:4, UnitsAwareOfEnemies:0, AllVehicles:5, WreckedVehicles:0, Entities:19, GroupsRebels:3, GroupsInvaders:0, GroupsOccupants:2, GroupsCiv:0, GroupsTotal:5, GroupsCombatBehaviour:2, Faction Cash:1000, HR:8, OccAggro: 0, InvAggro: 0, Warlevel: 1
22:59:18 Error in expression <, _side, _suppType, 150, 30+_flightTime+_realReloadTime*_numberOfRounds] spawn A>
22:59:18   Error position: <_realReloadTime*_numberOfRounds] spawn A>
22:59:18   Error Undefined variable in expression: _realreloadtime
22:59:18 File x\A3A\addons\core\functions\Supports\fn_SUP_mortarRoutine.sqf..., line 130
22:59:18  ➥ Context: 	[] L92 (x\A3A\addons\core\functions\Supports\fn_SUP_mortarRoutine.sqf)
	[] L130 (x\A3A\addons\core\functions\Supports\fn_SUP_mortarRoutine.sqf)

22:59:18 Error in expression <pha 0.75;

[_textMarker, _targetMarker, _markerLifeTime] spawn {
params ["_textM>
22:59:18   Error position: <_markerLifeTime] spawn {
params ["_textM>
22:59:18   Error Undefined variable in expression: _markerlifetime
22:59:18 File x\A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf..., line 126
22:59:18  ➥ Context: 	[] L28 (x\A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf)
	[] L111 (x\A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf)
	[] L126 (x\A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf)

22:59:18 Error in expression <", "_targetMarker", "_lifeTime"];
sleep _lifeTime;
deleteMarker _textMarker;
del>
22:59:18   Error position: <_lifeTime;
deleteMarker _textMarker;
del>
22:59:18   Error Undefined variable in expression: _lifetime
22:59:18 File x\A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf..., line 128
22:59:18  ➥ Context: 	[] L130 (x\A3A\addons\core\functions\Supports\fn_showInterceptedSupportCall.sqf)
```

2024-06-06 19:01 UTC, jaj22 commented
The artySupport one is a scope issue with the two additional barrage markers. Their vars need to be declared at higher scope so that they're visible to the deletion routine.

2024-06-09 13:38 UTC, ante185 requested changes
the area markers need higher opacity 
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/a652208b-2dd0-4a5c-bc1b-c9af67c5ab57)

Script error when rebels call barrage strikes with HC teams
```
15:34:42 Ref to nonnetwork object 1815438: shell.p3d
15:34:45 Error in expression < {deleteMarker _mrkFinal2; deleteMarker _mrkEllipse2; deleteMarker _mrkBarrageLi>
15:34:45   Error position: <_mrkEllipse2; deleteMarker _mrkBarrageLi>
15:34:45   Error Undefined variable in expression: _mrkellipse2
15:34:45 File x\A3A\addons\core\functions\AI\fn_artySupport.sqf..., line 319
15:34:45  ➥ Context: 	[] L319 (x\A3A\addons\core\functions\AI\fn_artySupport.sqf)
	[] L319 (x\A3A\addons\core\functions\AI\fn_artySupport.sqf)

15:34:47 Ref to nonnetwork object 1815441: shell.p3d
```

2024-06-10 01:26 UTC, Tiny-DM commented
Discussed internally, no good way to fix the issue with overlapping markers causing opacity issues. Awaiting review.

2024-06-12 00:03 UTC, ante185 requested changes
Enemy artillery seem to like to spawn far enough away from the target that the marker disappears early, by the third or before the 4th round impacts.
enemy mortar markers seem to, hit the mark with the timing.

rebel strike option seems to about right, if a little tight.
**rebel barrage strikes get their markers removed before the last rounds are even fired.**

2024-06-12 00:06 UTC, jaj22 commented
> Enemy artillery seem to like to spawn far enough away from the target that the marker disappears early, by the third or before the 4th round impacts. enemy mortar markers seem to, hit the mark with the timing.

Distance shouldn't matter because it's using getArtilleryETA. Unless that's broken.

2024-06-13 18:49 UTC, ante185 approved these changes
rebel barrages seem to be correctly timed, timings overall seem to be better

lgtm

2024-06-15 14:42 UTC, merged