RHS Tanoan Liberation Army (TLA)
official-antistasi-community/A3-Antistasi pull request #3267
Opened 2024-06-02 23:40 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Adds the RHS TLA 
The TLA uses a wide range of old soviet cold war equipment, in addition to whatever they can capture, scavenge, or steal from the [HIDF (#3209)](https://github.com/official-antistasi-community/A3-Antistasi/pull/3209)
They are slightly held back by a lack of their own air logistics and maintenance, letting them field fewer helicopters and aircraft as compared to their principle enemy the HIDF
 
### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
This PR has a soft dependency on #3209 as that PR has a config fix for the M3A1 smg, which is used in a limited amount in this template as well

2024-06-03 19:54 UTC, Tiny-DM requested changes

2024-06-03 19:54 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
> +["vehiclesArtillery", ["rhs_2s1_tv", "rhsgref_ins_d30", "RHS_BM21_VV_01", "RHS_BM21_VV_01"]] call _fnc_saveToTemplate;
Consider removing the 2S1 unless it actually covers a vital range discrepancy or otherwise make the static and BM21 more often. The HIDF only have the static.

2024-06-03 19:54 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
> +["vehiclesHelisAttack", ["rhsgref_mi24g_CAS", "RHS_Mi24V_vvsc"]] call _fnc_saveToTemplate;
Probably should add the P variant and remove the G variant unless there's a really good reason for a modern Hind to be present

2024-06-03 19:54 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
> +["rhs_weap_rpg7", "", "", "",["rhs_rpg7_type69_airburst_mag", "rhs_rpg7_PG7VL_mag", "rhs_rpg7_OG7V_mag"], [], ""]
Airburst should probably be somewhat less common IMO. Up to personal discretion

2024-06-03 19:54 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
> +["vehiclesIFVs", ["rhs_bmp1_msv"]] call _fnc_saveToTemplate;                //this line determines IFVs
The BMP1 is....barely an IFV. Not sure what better options there are though. Maybe add a rare BMP2 or something?

2024-06-04 14:24 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
> +["rhs_weap_rpg7", "", "", "",["rhs_rpg7_type69_airburst_mag", "rhs_rpg7_PG7VL_mag", "rhs_rpg7_OG7V_mag"], [], ""]
there's only a roughly 1 in 6 chance for that particular RPG7 loadout, as the AT unit randomly selects between AT and heavyAT when their loadout is built

2024-06-05 14:55 UTC, Tiny-DM approved these changes

2024-06-08 10:48 UTC, Bob-Murphy commented
`Don't merge` because #3209 dependency

2024-06-09 01:13 UTC, ante185 commented
> `Don't merge` because #3209 dependency

3209 has been approved, removing label `Don't merge`

Merge order does not matter

2024-06-12 18:39 UTC, merged