RHS VDV (Temperate) Template
official-antistasi-community/A3-Antistasi pull request #3271
Opened 2024-06-05 20:50 UTC by Play3rgg

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds the VDV as a faction to RHS, only a temperate template exists for now.
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

*******************************************
![20240605234743_1](https://github.com/official-antistasi-community/A3-Antistasi/assets/39414270/8c4a8ede-1a9e-4c0f-b896-20b4f12198f1)
*************
Notes:
Made by skilless802 on the discord, PR made for him

2024-06-05 21:33 UTC, ante185 requested changes
some tweaks are possible, not a comprehensive review yet

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesPlanesTransport", []] call _fnc_saveToTemplate;
the VDV being unable to paradrop troops in may be a little odd?
C130 is an acceptable stand in for a lack of a russian para tropper plane.

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesHelisLightAttack", ["RHS_Mi8MTV3_heavy_vvs", "RHS_Mi24Vt_vvs", "RHS_Mi8MTV3_heavy_vvs"]] call _fnc_saveToTemplate;
Mi-24VT is a bit weak to be light attack, Mi-24V is a bit strong instead.
Mi-24P has been used as a light attack helicopter previously.
```suggestion
["vehiclesHelisLightAttack", ["RHS_Mi8MTV3_heavy_vvs", "RHS_Mi24P_CAS_vdv", "RHS_Mi8MTV3_heavy_vvs"]] call _fnc_saveToTemplate;
```

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_2s1_tv", ["rhs_mag_3of56_10"]],
Wrong magazine, artillery wont fire
```suggestion
["rhs_2s1_tv", ["rhs_mag_3of56_35"]],
```

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesMilitiaLightArmed", ["rhsgref_ins_uaz_dshkm", "rhsgref_ins_uaz_spg9", "rhsgref_ins_uaz_ags"]] call _fnc_saveToTemplate;
These cars have the olive colour that you'd more likely expect, adding another dshkm uaz also balances out the proportions of explosive vs 50 cal cars, fitting better when the MSV UAZ's used for militia cars
```suggestion
["vehiclesMilitiaLightArmed", ["rhsgref_nat_uaz_dshkm", "rhsgref_nat_uaz_dshkm", "rhsgref_nat_uaz_spg9", "rhsgref_nat_uaz_ags"]] call _fnc_saveToTemplate;
```

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesMilitiaTrucks", ["rhsgref_ins_zil131", "rhsgref_ins_zil131_open"]] call _fnc_saveToTemplate;
for the same reason as the cars consider using some of the trucks within the RHSAFRF MSV, those versions of the Zil, ural, or gaz66 would be good fits here and match in camo.

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesPolice", ["B_GEN_Offroad_01_gen_F", "rhs_uaz_open_vv"]] call _fnc_saveToTemplate;
pick one or the other - preferably the uaz imo

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["staticMGs", ["rhs_KORD_high_MSV", "rhsgref_ins_DSHKM"]] call _fnc_saveToTemplate;
Would the modern VDV still use the dshkm? Use your own judgement.

2024-06-05 21:33 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_scorpion", "", "", "", ["rhsgref_20rnd_765x17_vz61"], [], ""]
i mean there's nothing wrong with this but a few lines down you use the pp2000 as a SMG

2024-06-05 22:55 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesPlanesTransport", []] call _fnc_saveToTemplate;
Apparently skill wants them to use the Mi-8 as a plane to paradrop from? Even though generally thatll happen in edgecases only?
to quote him "They should use the mi8 to paradrop shouldn't need a plane" which to I answered
"thats  uhh only if the heli cant find a landing spot which it usually will"
which he replied to with "Not for all case iirc"

Unsure if adding a mi-8 as a Transport Plane to use it for paradropping would be viable

2024-06-06 11:26 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesPolice", ["B_GEN_Offroad_01_gen_F", "rhs_uaz_open_vv"]] call _fnc_saveToTemplate;
Changed to UAZ only

2024-06-06 11:26 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["staticMGs", ["rhs_KORD_high_MSV", "rhsgref_ins_DSHKM"]] call _fnc_saveToTemplate;
Changed to KORD only

2024-06-06 11:27 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesMilitiaTrucks", ["rhsgref_ins_zil131", "rhsgref_ins_zil131_open"]] call _fnc_saveToTemplate;
Changed Chedaki and MSV etc. vehicles to VDV variants where applicable

2024-06-06 11:29 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesPlanesTransport", []] call _fnc_saveToTemplate;
Added the unarmed grey Mi-8 to the PlanesTransport

2024-06-06 12:40 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_scorpion", "", "", "", ["rhsgref_20rnd_765x17_vz61"], [], ""]
Scorpion moved to police SMGs, PP2000 added to the military carbines

2024-06-06 12:42 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["vehiclesHelisLightAttack", ["RHS_Mi8MTV3_heavy_vvs", "RHS_Mi24Vt_vvs", "RHS_Mi8MTV3_heavy_vvs"]] call _fnc_saveToTemplate;
Helis have been moved around

2024-06-06 15:01 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Arid.sqf
> +["vehiclesRepairTrucks", ["rhs_gaz66_repair_vdv"]] call _fnc_saveToTemplate;
Not super important but i'd like to highlight/suggest.
rhs_typhoon_vdv is a valid repair truck and could be used instead of the older truck

rhs_kamaz5350_ammo_vdv is a valid ammo truck -||-

2024-06-07 16:14 UTC, ante185 requested changes
ifvs

2024-06-07 16:14 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Arid.sqf
> +["vehiclesIFVs", ["rhs_bmd2m"]] call _fnc_saveToTemplate;
Still need to empty the IFV category

2024-06-07 20:14 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Arid.sqf
> +["vehiclesIFVs", ["rhs_bmd2m"]] call _fnc_saveToTemplate;
Still needs to be removed from the arid template, make sure that both templates match in the way they're supposed to match.

2024-06-08 21:03 UTC, ante185 requested changes
a classname is wrong and several attachments failed validation - cross check and make sure you catch them all.

2024-06-08 21:03 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_ak104", "rhs_acc_dtk3", "rhs_acc_perst3_2dp_light_h", "rhs_acc_1p78", ["rhs_30Rnd_762x39mm", "rhs_30Rnd_762x39mm_tracer"], [], ""],
Rail: rhs_acc_perst3_2dp_light_h is incompatible with rhs_weap_ak104 | Comaptible rails: ["rhs_acc_2dpZenit","rhs_acc_perst1ik"]

2024-06-08 21:03 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_ak74m_zenitco01_b33", "rhs_acc_dtk", "", "rhs_acc_1p78", ["rhs_30Rnd_545x39_7U1_AK"], [], ""],
Optic: rhs_acc_1p78 is incompatible with rhs_weap_ak74m_zenitco01_b33

2024-06-08 21:03 UTC, ante185 commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_ak103_gp25", "rhs_acc_dtkakm", "", "rhs_acc_1p63", ["rhs_30Rnd_762x39mm", "rhs_30Rnd_762x39mm_tracer"], ["rhs_VOG25", "rhs_VOG25", "rhs_VOG25P", "rhs_VG40OP_white"], ""],
Muzzle: rhs_acc_dtkakm is incompatible with rhs_weap_ak103_gp25 | Comaptible muzzles: ["rhs_acc_dtk","rhs_acc_dtk1","rhs_acc_dtk2","rhs_acc_dtk3","rhs_acc_dtk4long","rhs_acc_dtk4screws","rhs_acc_ak5","rhs_acc_pbs1"]

2024-06-08 21:16 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Arid.sqf
> +["rhs_weap_ak74m_zenitco01_b33", "rhs_acc_dtk", "", "rhs_acc_1p78", ["rhs_30Rnd_545x39_7U1_AK"], [], ""],
changed to 1p87

2024-06-08 21:22 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_ak104", "rhs_acc_dtk3", "rhs_acc_perst3_2dp_light_h", "rhs_acc_1p78", ["rhs_30Rnd_762x39mm", "rhs_30Rnd_762x39mm_tracer"], [], ""],
replaced with perst1k

2024-06-08 21:25 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_ak74m_zenitco01_b33", "rhs_acc_dtk", "", "rhs_acc_1p78", ["rhs_30Rnd_545x39_7U1_AK"], [], ""],
switched 1p87

2024-06-08 21:43 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
> +["rhs_weap_ak103_gp25", "rhs_acc_dtkakm", "", "rhs_acc_1p63", ["rhs_30Rnd_762x39mm", "rhs_30Rnd_762x39mm_tracer"], ["rhs_VOG25", "rhs_VOG25", "rhs_VOG25P", "rhs_VG40OP_white"], ""],
switched to dtk1

2024-06-09 00:12 UTC, Tiny-DM approved these changes
I will never allow Skill to make any templates on his own again, but it does look good.

2024-06-09 12:54 UTC, ante185 approved these changes

2024-06-09 13:47 UTC, Play3rgg commented
No more validation errors.

2024-06-12 18:19 UTC, merged