Updated Garage store
official-antistasi-community/A3-Antistasi pull request #3277
Opened 2024-06-08 23:42 UTC by ZukiAimi

Added more CIV vehicles and one Static AT with custom price

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement

### What have you changed and why?
Information: Added a few CIV ground vics to the already lacking CUP vehicle store that's mostly dominated by Heli's. Also added one Static that may or may not be to much. But setting the price high so it's not so easily obtained and abused.
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-06-09 00:16 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
> +    ["CUP_I_M119_RACS", ["rebCost", 50000]],
```suggestion
///    ["CUP_I_M119_RACS", ["rebCost", 50000]],
```

2024-06-09 00:23 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
> +    ["CUP_I_M119_RACS", ["rebCost", 50000]],
wait

2024-06-09 00:24 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
> +    ["CUP_I_M119_RACS", ["rebCost", 50000]],
hold up

2024-06-09 03:00 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesCivTruck", ["CUP_C_Ural_Civ_03", "CUP_C_Ikarus_Chernarus"]] call _fnc_saveToTemplate;
CUP_C_Ikarus_Chernarus, that's the bus no? Those blow up all the time in towns.

2024-06-09 03:01 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesCivTruck", ["CUP_C_Ural_Civ_03", "CUP_C_Ikarus_Chernarus"]] call _fnc_saveToTemplate;
Honestly better in the rebel template than the civ one :P

2024-06-09 03:04 UTC, killerswin2 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesCivTruck", ["CUP_C_Ural_Civ_03", "CUP_C_Ikarus_Chernarus"]] call _fnc_saveToTemplate;
Did, you change that variable? Because they used to append the reb civ in the civ vehicles.

2024-06-09 08:36 UTC, ZukiAimi commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
> +    ["CUP_I_M119_RACS", ["rebCost", 50000]],
Do we not allow custom prices?

2024-06-09 08:45 UTC, ZukiAimi commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesCivTruck", ["CUP_C_Ural_Civ_03", "CUP_C_Ikarus_Chernarus"]] call _fnc_saveToTemplate;
Yes it's a bus and is civilian

2024-06-09 13:05 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesCivTruck", ["CUP_C_Ural_Civ_03", "CUP_C_Ikarus_Chernarus"]] call _fnc_saveToTemplate;
I believe the CUP bus is still used by the CUP civilian templates, it is in the 3CB faction's civ template were the bus' weight is set to zero, presumably due to issue mentioned here.

2024-06-09 13:08 UTC, ante185 requested changes

2024-06-09 13:08 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["staticAT", ["CUP_I_SPG9_NAPA", "CUP_I_M119_RACS"]] call _fnc_saveToTemplate;
```suggestion
["staticAT", ["CUP_I_SPG9_NAPA"]] call _fnc_saveToTemplate;
```
The rebels aren't allowed artillery pieces.

2024-06-09 13:08 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf
> +
```suggestion

```
Don't need this, remove the M119

2024-06-09 15:40 UTC, ZukiAimi commented
oh no

2024-06-09 19:01 UTC, ante185 commented
You could do similar additions to CUP_Reb_TKM.
Additionally you could remove one or two helicopters as these rebel templates have too many of them.

2024-06-09 19:52 UTC, ZukiAimi commented
Was planning to. But do i have to make a separate pull request for that?

2024-06-09 19:54 UTC, ante185 commented
> Was planning to. But do i have to make a separate pull request for that?

if you're doing the same kind of thing you can do it

2024-06-12 20:09 UTC, ante185 requested changes

2024-06-12 20:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesBoat", ["I_G_Boat_Transport_01_F", "CUP_I_RHIB2Turret_RACS"]] call _fnc_saveToTemplate;
CUP_I_RHIB_RACS with it's single .50 cal is gonna be more acceptable, price needs to correspond to being both a boat and .50 cal.

2024-06-12 20:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesLightArmed", ["CUP_I_Hilux_DSHKM_NAPA", "CUP_I_Datsun_PK", "CUP_I_Hilux_armored_BTR60_IND_G_F"]] call _fnc_saveToTemplate;
no

2024-06-12 20:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["staticAT", ["CUP_I_SPG9_NAPA", "CUP_I_D30_AT_TK_GUE"]] call _fnc_saveToTemplate;
no, the SPG9 is enough

2024-06-12 20:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
> +["vehiclesLightArmed", ["CUP_I_Hilux_DSHKM_NAPA", "CUP_I_Hilux_armored_BTR60_IND_G_F"]] call _fnc_saveToTemplate;
no

2024-06-12 20:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
> +["staticAT", ["CUP_I_SPG9_NAPA", "CUP_I_D30_AT_TK_GUE"]] call _fnc_saveToTemplate;
no, the SPG9 is enough

2024-06-12 20:09 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf
> +["vehiclesBoat", ["I_G_Boat_Transport_01_F", "CUP_I_RHIB2Turret_RACS"]] call _fnc_saveToTemplate;
CUP_I_RHIB_RACS with it's single .50 cal is gonna be more acceptable, price needs to correspond to being both a boat and .50 cal though.

2024-06-12 21:38 UTC, ZukiAimi commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesBoat", ["I_G_Boat_Transport_01_F", "CUP_I_RHIB2Turret_RACS"]] call _fnc_saveToTemplate;
ok i will change that

2024-06-12 21:42 UTC, ZukiAimi commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["vehiclesLightArmed", ["CUP_I_Hilux_DSHKM_NAPA", "CUP_I_Datsun_PK", "CUP_I_Hilux_armored_BTR60_IND_G_F"]] call _fnc_saveToTemplate;
I knew you wouldn't maybe like this, but it is really weak. Since it can't stop a static MG, which every outpost has and can't pen an APC from the front

2024-06-12 21:45 UTC, ZukiAimi commented on A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf
> +["staticAT", ["CUP_I_SPG9_NAPA", "CUP_I_D30_AT_TK_GUE"]] call _fnc_saveToTemplate;
yeah, couldn't see much of reason to it, other than SOG having it's cannon. Just a nice little special for CUP. But will change back

2024-06-13 18:54 UTC, Play3rgg approved these changes
lgtm

2024-06-13 18:54 UTC, Tiny-DM approved these changes
lgtm

2024-06-13 18:54 UTC, ante185 approved these changes
lgtm

2024-06-16 12:39 UTC, merged