Added: Admin tab updates now recieves data from server
official-antistasi-community/A3-Antistasi pull request #3303
Opened 2024-06-20 01:13 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
server now sends data over the net to the admin only. used in admin tab 

### Please specify which Issue this PR Resolves.
N/A

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-06-26 23:32 UTC, CalebSerafin requested changes
Couple improvements to boost reliability. other than that it seems alright.

2024-06-26 23:32 UTC, CalebSerafin commented on A3A/addons/core/functions/Utility/fn_adminData.sqf
> +            if (isNull _admin) exitWith {};
This wouldn't exit the loop, it will jump to line 88 and repeat indefinitly.

2024-06-26 23:32 UTC, CalebSerafin commented on A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
> +                    while {true} do
Could put the condition from Line 260 `if(!isNull (_display getVariable ["A3A_adminTabUpdateSpawn", scriptNull])) then {`
in here instead.

2024-06-27 17:52 UTC, killerswin2 commented on A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
> +                    while {true} do
that's not possible, because that won't ever do anything as the A3A_adminTabUpdateSpawn is not set in the spawn, but after.

2024-06-28 02:25 UTC, jaj22 commented on A3A/addons/core/functions/Utility/fn_adminData.sqf
> +if(!A3A_DoSendAdminData) exitWith {};
The disconnect functionality here seems to rely on the check happening at least once while there isn't an admin before another admin is selected. In theory you could get unlucky and then it'll spam the data until the new admin opens and then closes the admin tab.

Not really a big issue, but it'd also simplify the control flow here if you made A3A_doSendAdminData an owner ID rather than a bool. Then you can just run `admin A3A_adminUIDataTarget` instead of all these conditions, and it's more correct.

2024-06-28 02:27 UTC, jaj22 commented on A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
> +        if(!isNull (_display getVariable ["A3A_adminTabUpdateSpawn", scriptNull])) then { terminate (_display getVariable "A3A_adminTabUpdateSpawn"); };
`terminate scriptNull` is a no-op, so you can simplify these lines: 
`terminate (_display getVariable ["A3A_adminTabUpdateSpawn", scriptNull]);`

2024-06-30 16:37 UTC, killerswin2 commented on A3A/addons/core/functions/Utility/fn_adminData.sqf
> +if(!A3A_DoSendAdminData) exitWith {};
there is a check in the loop

2024-07-11 07:15 UTC, closed without merging

2025-05-09 22:31 UTC, Tiny-DM commented
Integrated into #3515