Added: Steal the fuel truck
official-antistasi-community/A3-Antistasi pull request #3307
Opened 2024-06-21 02:38 UTC by killerswin2

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
    This was supposed to be added during fuel reworks

### Please specify which Issue this PR Resolves.

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [x] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-06-21 12:28 UTC, rautamiekka requested changes

2024-06-21 12:28 UTC, rautamiekka commented on A3A/addons/core/Stringtable.xml
> +        <Original>Ammotruck Stolen in an %1</Original>
```suggestion
        <Original>Ammo truck stolen in an %1</Original>
```

2024-06-21 12:28 UTC, rautamiekka commented on A3A/addons/core/Stringtable.xml
> +        <Original>Fuel truck Stolen in an %1</Original>
```suggestion
        <Original>Fuel truck stolen in an %1</Original>
```

2024-06-24 15:51 UTC, jaj22 reviewed
Looks fine generally, although as this change halves the number of ammo truck missions, we might need to balance by adding more ways to acquire gear.

2024-06-24 16:29 UTC, killerswin2 commented
the fuel truck still has the ammo in it.

2024-06-24 16:47 UTC, ante185 commented
Don't add ammo/gear loot to the fuel truck.
Make the fuel truck mission less probable than the ammo truck mission, ie select random weighted or if random > x or something.
additional suggestion is to make the fuel truck mission more likely when there's none in the civilian template / less likely if there's fuel trucks in the civilian template

2024-06-24 17:57 UTC, killerswin2 commented
> Don't add ammo/gear loot to the fuel truck. Make the fuel truck mission less probable than the ammo truck mission, ie select random weighted or if random > x or something. additional suggestion is to make the fuel truck mission more likely when there's none in the civilian template / less likely if there's fuel trucks in the civilian template

no, that was an unintended feature

2024-07-11 07:15 UTC, closed without merging