SPE_IFA 1.1 Template Updates
official-antistasi-community/A3-Antistasi pull request #3356
Opened 2024-08-06 14:06 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [X] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Added 1.1 content to the SPE_IFA templates. The SPE templates themselves have not been updated, support for SPEX will have to be made at some point.

### Please verify the following and ensure all checks are completed.

1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

********************************************************
Notes:
Templates are still rough around the edges and could use some more work in terms of balancing vehicle prices, for both enemies and rebels. Transferring to @ante185 for polishing.

2024-08-06 16:14 UTC, rautamiekka requested changes

2024-08-06 16:14 UTC, rautamiekka commented on A3A/addons/logistics/Nodes/SPE.hpp
> +        class Nodes
```suggestion
    class Nodes
```

2024-08-06 16:14 UTC, rautamiekka commented on A3A/addons/logistics/Nodes/SPE.hpp
> +        class Nodes
```suggestion
    class Nodes
```

2024-08-06 16:14 UTC, rautamiekka commented on A3A/addons/logistics/Nodes/SPE.hpp
> +        class Nodes
```suggestion
    class Nodes
```

2024-08-10 01:32 UTC, ante185 commented
- Set the US militia up with their thematically appropriate weapons.
- Set the WEH militia and police up themed after the forces of Vichy France.
- Made WEH military and SF not share uniforms. WEH snipers are now slightly camouflaged. 
- Shuffled vehicles around until i couldn't stand my indecision anymore.
- Updated the civ template so that it no longer spawns military trucks or military utility vehicles.
- Gave rebels their appropriate vests and backpacks.
- Set the factions with appropriate names and radio protocols.
- Gave US and WEH a distinct looking police force.
- Several passed on faction small arms to make sure they were appropiate for the faction and the military/militia/police units that will use them.

2024-08-10 17:49 UTC, jaj22 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
> +["vehiclesLightAPCs", []] call _fnc_saveToTemplate;
Remember that if you want to expand truck usage, one option is to add them to lightAPCs and/or APCs and force the price down in vehicle attributes. I think I did that in some of the Vietnam NVA templates.

Not sure if that's necessary here though. Depends how plausible it is to have large quantities of the APCs.

2024-08-10 22:14 UTC, ante185 commented on A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf
> +["vehiclesLightAPCs", []] call _fnc_saveToTemplate;
this should be fine for this faction

2024-08-11 17:59 UTC, Bob-Murphy approved these changes
lgtm

2024-08-11 20:00 UTC, merged