Fix issue where running destroyCity with CUP interiors could crash
official-antistasi-community/A3-Antistasi pull request #3359
Opened 2024-08-08 19:06 UTC by jaj22

### What type of PR is this.
1. [X] Bug
2. [ ] Change
3. [ ] Enhancement

### What have you changed and why?
When loading the Interiors for CUP mod, destroyCity (used when a punishment fails) would crash on some cities. Apparently this is because the mod incorrectly removes the models for some sign objects, causing setHit to crash Arma. This PR works around the problem by not calling setHit on selections that don't exist, which was rather dangerous behaviour anyway.

Shouldn't have any functional changes in other cases. Note that CUP buildings are mostly lacking in building damage modelling compared to vanilla A3 buildings, so destroyed cities don't look much different.

### Please specify which Issue this PR Resolves.
closes #3357

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [X] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Load CUP maps with Interiors for CUP. Run `["Pustoshka"] call A3A_fnc_destroyCity;` on Chernarus Autumn, see if it crashes.

2024-08-08 21:06 UTC, rautamiekka requested changes

2024-08-08 21:06 UTC, rautamiekka commented on A3A/addons/core/functions/Base/fn_destroyCity.sqf
> +private _buildings = _positionX nearobjects ["house",_size];
```suggestion
private _buildings = _positionX nearObjects ["house",_size];
```

2024-08-09 04:54 UTC, jaj22 commented on A3A/addons/core/functions/Base/fn_destroyCity.sqf
> +private _buildings = _positionX nearobjects ["house",_size];
Fine, I'm gonna fix this just because I still have the PR open :P

2024-08-10 01:55 UTC, Tiny-DM approved these changes
lgtm

2024-08-10 23:25 UTC, merged