Additional garage categories
official-antistasi-community/A3-Antistasi pull request #3378
Opened 2024-08-15 20:01 UTC by wersal454

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:

Separated Air vehicles category into 3 separate ones:
Helicopters,VTOLs and planes

Reason to why, because there is no real point in blocking access(and ability to store) to air vehicles if they are helicopters or VTOLs because they don't require airstrip to take off.

So plane category will still be blocked as usual

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Add different vehicles to the garage and try to interact with them inside garage(?)
********************************************************
Notes:
Static category for some reason gives an error upon selecting any vehicle in it. Can't find a reason as to why it's the case.
![image](https://github.com/user-attachments/assets/caa9b8a0-9a52-44e4-921c-3c51340a2033)
Upon selection
![image](https://github.com/user-attachments/assets/40a53f84-ff5f-42d3-98c1-14037f879403)

Also Helicopter category displays incorrectly, yet again don't know why at the moment
![image](https://github.com/user-attachments/assets/08ed4efe-8afc-4ac4-9ed0-7b79c3f94265)

2024-08-15 21:06 UTC, Bob-Murphy commented
The blocking is done deliberately. 
I'm happy to take the categories but the blocking will persist in our version. Reason being, air assets can get overpowered very quick and whilst you usually have the means to repair cars and trucks at a normal workshop (forget about APCs and tanks), air assets need a completely different set of tools, maintenance etc, hence why we limit it to airports.

2024-08-15 21:21 UTC, wersal454 commented
> The blocking is done deliberately. I'm happy to take the categories but the blocking will persist in our version. Reason being, air assets can get overpowered very quick and whilst you usually have the means to repair cars and trucks at a normal workshop (forget about APCs and tanks), air assets need a completely different set of tools, maintenance etc, hence why we limit it to airports.

That's fine, I can add categories 2 and 3 so helis and VTOLs won't be accessible. Usually in our version we leave a choice for the players to do what they want, like play with fast travel or not, could put some sort of check here as well, but that's up to you guys. I also tried adding unmanned category, but figured out it will mess with the statics because some statics are unmanned, and maybe I could somehow add to unmanned category only UAVs and UGVs, but idk. 
Also I had an idea with button in the garage that adds friendly ai into unmanned vehicle upon spawn, so you can choose to spawn vehicle empty or with the "crew"

2024-08-17 23:37 UTC, wersal454 commented
![image](https://github.com/user-attachments/assets/0674adf7-baea-4c5a-93da-29658620af0a)
![image](https://github.com/user-attachments/assets/16802e94-6573-4be2-af5b-ff245b0e31b5)
![image](https://github.com/user-attachments/assets/896a2cc0-edfc-4e1c-a07d-79739a909e82)
![image](https://github.com/user-attachments/assets/24b014ec-cc78-44b9-9ad0-5e4e8327c650)
![image](https://github.com/user-attachments/assets/179c6282-2c36-4407-bd55-4aebb7376828)
![image](https://github.com/user-attachments/assets/a59d467d-2cfc-4179-8521-1ffbfa614c0e)
![image](https://github.com/user-attachments/assets/9d0832b3-1335-40ce-99b7-5ae9520c3535)
![image](https://github.com/user-attachments/assets/f47de6dc-f357-4663-bdd4-7e6a82b6e594)
Everything working

Except, as you can see I somehow managed to add tent hangar to the garage. My guess it's due to category check, I think tent hangar just falls either in this check
```case (_editorCat isEqualTo "EdSubcat_Turrets"): { 6 };
    case (_class isKindOf "staticWeapon"): {6}; //some non-vanilla artillery is statics
```
or this one
```case (_class isKindOf "Static"): { 6 };```

2024-09-02 22:22 UTC, wersal454 commented
"Thought about separating armored category to apcs and tanks(maybe more), but I think it wouldn't make much sense from gameplay perspective

Also thought about adding Unmanned category, but I think it would break things, like statics that have uav controls(vanilla sams for example), probably can avoid it by creating proper check in A3A/addons/garage/Core/fn_getCatIndex.sqf , but I think it's up for debate"

2024-09-09 15:24 UTC, wersal454 commented
> Thinking about it a bit more, I don't believe that a Vtol class is needed. There are not that many matching vehicles and there are quite a lot of playthroughs where there will be not a single Vtol, especially when having something like WW2, Vietnam, 80s/90s or such.

Well, I guess helis and planes, then? Community version doesn't support any OPTRE or STARWARS modsets, + we make usage out of VTOL's more often. Can we left VTOL's in ours?

And what about unmanned category and separating apcs and tanks?

2024-09-09 16:09 UTC, Bob-Murphy commented
It makes sense to create categories which are compatible with most modsets and not orient them based on edgecases.
If there would be way to automatically have empty categories hidden, then I would be fine with having edge-cases like for Vtols or unmanned vehicles.
Unless we have that, having Vtols and unmanned shouldn't be done.
Regarding APCs vs Tanks, I will check with the team and let you know. That's nothing I want to decide on my own.

And regarding having Vtols in your version, License says No.

2024-09-09 18:43 UTC, wersal454 commented
> It makes sense to create categories which are compatible with most modsets and not orient them based on edgecases. If there would be way to automatically have empty categories hidden, then I would be fine with having edge-cases like for Vtols or unmanned vehicles. Unless we have that, having Vtols and unmanned shouldn't be done. Regarding APCs vs Tanks, I will check with the team and let you know. That's nothing I want to decide on my own.
> 
> And regarding having Vtols in your version, License says No.

I have cut vtols, waiting for the apcs and tanks decision
![image](https://github.com/user-attachments/assets/7e251728-9b9f-4f4e-93be-9d66700c1934)
![image](https://github.com/user-attachments/assets/8448f36b-8f5e-4742-b0ab-ef6369fe84e5)

2024-09-19 07:49 UTC, wersal454 commented
> > It makes sense to create categories which are compatible with most modsets and not orient them based on edgecases. If there would be way to automatically have empty categories hidden, then I would be fine with having edge-cases like for Vtols or unmanned vehicles. Unless we have that, having Vtols and unmanned shouldn't be done. Regarding APCs vs Tanks, I will check with the team and let you know. That's nothing I want to decide on my own.
> > And regarding having Vtols in your version, License says No.
> 
> I have cut vtols, waiting for the apcs and tanks decision ![image](https://private-user-images.githubusercontent.com/29953387/365771336-7e251728-9b9f-4f4e-93be-9d66700c1934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIzODksIm5iZiI6MTcyNjczMjA4OSwicGF0aCI6Ii8yOTk1MzM4Ny8zNjU3NzEzMzYtN2UyNTE3MjgtOWI5Zi00ZjRlLTkzYmUtOWQ2NjcwMGMxOTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWZlMjQ1NDM5M2FkMDZmMTI1YTFhMmYxNmJmMGI1OGFmNmQ1MTRmNDJjMmYxNzRmZThmYjI2ODhiZjVhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h1oTMR7NwrQWhtSoeJhros6PrejS1bPsJuKx2r1H73A) ![image](https://private-user-images.githubusercontent.com/29953387/365771403-8448f36b-8f5e-4742-b0ab-ef6369fe84e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzIzODksIm5iZiI6MTcyNjczMjA4OSwicGF0aCI6Ii8yOTk1MzM4Ny8zNjU3NzE0MDMtODQ0OGYzNmItOGY1ZS00NzQyLWIwYWItZWY2MzY5ZmU4NGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NGRhZGJhM2EyODQzNmY1OTVmZWUzMWEyMDgyOTI4MzJkZDU0ZTJlZGZkODY2ZDc0ZTUxZmRlMjcyNjIyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C-AzJg0rUJuo3H4H2prk8wNXhmpT_kDX2_BK6eMphFA)

Technically, we could add artillery category, since it has actually a different game/control mechanics

2024-10-10 20:31 UTC, wersal454 commented
![mr-bean-waiting](https://github.com/user-attachments/assets/6bd19ca9-5c93-4191-aa11-c59f51cf2dad)

2024-11-10 19:09 UTC, Bob-Murphy commented
@wersal454 
First and foremost, kinda sorry for the late reply :D
So, we just had the first meeting in a while and finally talked about the PR.

Here our notesfor the categories:
1. adding a category at the top for land vehicles that can go undercover as it can be hard to quickly distinguish them, especially when the camo is changed
2. keep normal land vehicles
3. implement APCs as split from Tanks
4. Keep tanks
5. Helis
6. Planes
7. Boats
8. Mortars

Again, apologies for the late reply.
Nevertheless, the PR will make it in the next version, even if it took a while to reply.

Cheers mate!

2024-11-10 19:30 UTC, wersal454 commented
> @wersal454 First and foremost, kinda sorry for the late reply :D So, we just had the first meeting in a while and finally talked about the PR.
> 
> Here our notesfor the categories:
> 
> 1. adding a category at the top for land vehicles that can go undercover as it can be hard to quickly distinguish them, especially when the camo is changed
> 2. keep normal land vehicles
> 3. implement APCs as split from Tanks
> 4. Keep tanks
> 5. Helis
> 6. Planes
> 7. Boats
> 8. Mortars
> 
> Again, apologies for the late reply. Nevertheless, the PR will make it in the next version, even if it took a while to reply.
> 
> Cheers mate!

1. not sure if doable, only if to check ```case (_class in undercoverVehicles"): { 0 }``` in fn_getCatIndex

8. eeh, 
![image](https://github.com/user-attachments/assets/d9e68dd9-e481-4a3e-bf9d-e198bb2cf867)
"mortars" are all turrets (hmg,AT,AA,MORTARS,unmanned turrets)

2024-11-10 19:42 UTC, Tiny-DM commented
> 
> 1. not sure if doable, only if to check `case (_class in undercoverVehicles): { 0 }` in fn_getCatIndex
> 2. eeh,
>   
>    "mortars" are all turrets (hmg,AT,AA,MORTARS,unmanned turrets)

"Mortars" was a bit of a misnomer, a general statics category is what we were looking for.
The idea for the undercover vehicles is that the current "cars" category is split into undercover and overt vehicles.

2024-11-28 22:44 UTC, wersal454 commented
![image](https://github.com/user-attachments/assets/e0cfc60c-d726-4496-b80c-5925f6c9da00)

2024-12-06 21:45 UTC, ante185 commented
![image](https://github.com/user-attachments/assets/b4237717-2331-4646-9be0-4f76d3059114)
![image](https://github.com/user-attachments/assets/ff01e80e-d1a5-4755-a518-73b4bc40d212)

`22:42:29 Warning Message: Picture a3a_icon_hidevic not found`

2024-12-06 21:56 UTC, wersal454 commented
> ![image](https://private-user-images.githubusercontent.com/49555217/393412094-b4237717-2331-4646-9be0-4f76d3059114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjIwMDMsIm5iZiI6MTczMzUyMTcwMywicGF0aCI6Ii80OTU1NTIxNy8zOTM0MTIwOTQtYjQyMzc3MTctMjMzMS00NjQ2LTliZTAtNGY3NmQzMDU5MTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDIxNDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NDM1Y2ViN2E0MzIwOWIxZjlkYTBiNjU3MmYyZjc4OGIzMWMwZjdjNjFhNmU5NTFiYjI4ODU3Yjc1NmMwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GguOFzfCi8QiGlL_sfb6cwHYaAKD4PJ303DJ9pbR4A4) ![image](https://private-user-images.githubusercontent.com/49555217/393412160-ff01e80e-d1a5-4755-a518-73b4bc40d212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjIwMDMsIm5iZiI6MTczMzUyMTcwMywicGF0aCI6Ii80OTU1NTIxNy8zOTM0MTIxNjAtZmYwMWU4MGUtZDFhNS00NzU1LWE1MTgtNzNiNGJjNDBkMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDIxNDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNWRlNDI0ODcyMTY4ZWQ3NDg4NDcyZWIxOGRhZTE0NWJmNTJmNDc1NzQxNjY5OTI5NGYyODZhZjMzNTM1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H60lJfzzhFNQGKHyAm07DNqEhNzuyZCT3ScFSKdE4ls)
> 
> `22:42:29 Warning Message: Picture a3a_icon_hidevic not found`

try again

2024-12-12 17:19 UTC, ante185 submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/23aeb5d1-54ce-4f70-bca4-e776cb538960)
Selecting statics appears to break the interface. Is the first category supposed to be a question mark?
Garaging vehicles straight up doesn't work, RPT attached
[Arma3_x64_2024-12-12_18-08-58.txt](https://github.com/user-attachments/files/18115246/Arma3_x64_2024-12-12_18-08-58.txt)

2024-12-12 22:01 UTC, wersal454 commented
should be fixed

2024-12-12 22:02 UTC, wersal454 commented
about question mark category, I couldn't find fitting undercover icon, seems as your version doesn't have undercover icon or for some reason I can't access it

2024-12-12 22:05 UTC, wersal454 commented
Also, kinda a big deal(not really), vehicles stored in the garage before the update will be deleted, so this update will be incompatible with old saves(not really, people will loose their vehicles, that's all)

2024-12-13 19:27 UTC, ante185 reviewed
Checked the functionality, and it works now.

![image](https://github.com/user-attachments/assets/1015df88-7bd2-44b1-9623-5e422d8193e3)
Believe this isn't necessarily the fault of the changes made here - the DLC icon on (presumably only certain) this resolution pushes the text to two lines making it cut off

2024-12-13 19:27 UTC, ante185 commented on A3A/addons/garage/Stringtable.xml
> +        <Russian>Беспилотники</Russian>
Believe localisation is left to be done through the tolgee tool, not in the PR

2024-12-13 19:28 UTC, ante185 commented
> Also, kinda a big deal(not really), vehicles stored in the garage before the update will be deleted, so this update will be incompatible with old saves(not really, people will loose their vehicles, that's all)

I'm not able to approve this PR because of this, anything messing with forward compatibility I don't feel comfortable unilaterally approving.

2024-12-13 19:34 UTC, wersal454 commented
> > Also, kinda a big deal(not really), vehicles stored in the garage before the update will be deleted, so this update will be incompatible with old saves(not really, people will loose their vehicles, that's all)
> 
> I'm not able to approve this PR because of this, anything messing with forward compatibility I don't feel comfortable unilaterally approving.

welp, you do you, but as I said, it's just peoples garages will be wiped, after that it will work fine on old saves. New saves will work out of the box

2024-12-13 19:44 UTC, wersal454 commented on A3A/addons/garage/Stringtable.xml
> +        <Russian>Беспилотники</Russian>
Ru translation is fine, except for undercover(I just could came up with good translation), I just hope that tool won't make translation worse)

2024-12-13 19:47 UTC, wersal454 commented
> Checked the functionality, and it works now.
> 
> ![image](https://private-user-images.githubusercontent.com/49555217/395676526-1015df88-7bd2-44b1-9623-5e422d8193e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMTk1MjgsIm5iZiI6MTczNDExOTIyOCwicGF0aCI6Ii80OTU1NTIxNy8zOTU2NzY1MjYtMTAxNWRmODgtN2JkMi00NGIxLTk2MjMtNWU0MjJkODE5M2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE5NDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NTkyM2Q5Nzk5NTAwMzA5MTA2OGZmYTQzZWJlZDEyOGFkMGM5NDU4MDViMjk5NmUxODRmNmZkZDliZjUxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.urvqN_uy7P2tHLTGWq6MOz79OXrrurVzGnW67PnAEQ0) Believe this isn't necessarily the fault of the changes made here - the DLC icon on (presumably only certain) this resolution pushes the text to two lines making it cut off

should be better(?) now

2024-12-22 19:36 UTC, Tiny-DM commented
This PR looks pretty good overall, with the main issue being the forward compatibility. This also kicks out a script error when loading an old garage, which isn't critical but is worth noting and also helps point towards a potential fix.
```
13:52:35 Error in expression <[], [[]] ]];
private _validSave = _save params [
["_garage", [createHashMap,crea>
13:52:35   Error position: <params [
["_garage", [createHashMap,crea>
13:52:35   Error 5 elements provided, 8 expected
13:52:35 File x\A3A\addons\garage\Public\fn_loadSaveData.sqf..., line 44
13:52:35  ➥ Context: 	[] L1 (x\A3A\addons\maps\Antistasi_Altis.Altis\initServer.sqf)
```
We're gonna try to avoid breaking forwards compatibility if at all possible under any circumstances; garage, resources, locations, just a overall rule. Since we're just now wrapping up testing, this will probably not make it into the next major update unless something changes on our side very shortly.
Fortunately, the forwards compatibility may be fixable. The data entries just need to be recategorized into their new categories, which can be done in `loadSaveData` ; if the function receives 5 elements for the array instead of 8 it iterates across all of the vehicle entries and recategorizes them with `getCatIndex` and places them in the right place again. It's something that I can add to this PR if you don't want to; we've been in straits for a while now :P
Overall, this PR looks good. A few things I noticed (subjective stuff, just caught my eye, can absolutely be fixed later)
- The author listing is weird overall; there's a seperate `HUGE` text size created here to make it fit the box. Don't really have a solution; preferably it would be moved to the info panel in some way but every extra line there takes space away from the dropdowns and selections above. We could use some sort of extra panel on the left side, taking space from the vehicle list to be honest; especially with more subdivisions making the lists shorter overall. But that's well outside the scope of this PR and there's no real solution; its probably fine for now.
- `Armor` in the category selection should probably be some form of "Heavy Armor" but I like how its short so idk
- The undercover icon being a question mark kinda works, kinda doesn't; it was mentioned that we didn't have an icon for it. Is there a better one that you suggest we use?

2024-12-22 19:56 UTC, wersal454 commented
> This PR looks pretty good overall, with the main issue being the forward compatibility. This also kicks out a script error when loading an old garage, which isn't critical but is worth noting and also helps point towards a potential fix.
> 
> ```
> 13:52:35 Error in expression <[], [[]] ]];
> private _validSave = _save params [
> ["_garage", [createHashMap,crea>
> 13:52:35   Error position: <params [
> ["_garage", [createHashMap,crea>
> 13:52:35   Error 5 elements provided, 8 expected
> 13:52:35 File x\A3A\addons\garage\Public\fn_loadSaveData.sqf..., line 44
> 13:52:35  ➥ Context: 	[] L1 (x\A3A\addons\maps\Antistasi_Altis.Altis\initServer.sqf)
> ```
> 
> We're gonna try to avoid breaking forwards compatibility if at all possible under any circumstances; garage, resources, locations, just a overall rule. Since we're just now wrapping up testing, this will probably not make it into the next major update unless something changes on our side very shortly. Fortunately, the forwards compatibility may be fixable. The data entries just need to be recategorized into their new categories, which can be done in `loadSaveData` ; if the function receives 5 elements for the array instead of 8 it iterates across all of the vehicle entries and recategorizes them with `getCatIndex` and places them in the right place again. It's something that I can add to this PR if you don't want to; we've been in straits for a while now :P Overall, this PR looks good. A few things I noticed (subjective stuff, just caught my eye, can absolutely be fixed later)
> 
> * The author listing is weird overall; there's a seperate `HUGE` text size created here to make it fit the box. Don't really have a solution; preferably it would be moved to the info panel in some way but every extra line there takes space away from the dropdowns and selections above. We could use some sort of extra panel on the left side, taking space from the vehicle list to be honest; especially with more subdivisions making the lists shorter overall. But that's well outside the scope of this PR and there's no real solution; its probably fine for now.
> * `Armor` in the category selection should probably be some form of "Heavy Armor" but I like how its short so idk
> * The undercover icon being a question mark kinda works, kinda doesn't; it was mentioned that we didn't have an icon for it. Is there a better one that you suggest we use?

I can look into `loadSaveData` stuff, but idk what exactly you are talking about so...
idk, if you already have a solution, you can put it in the comments, or push it yourself or idk
IDK!

emm, well about undercover icon, Plus and Ultimate versions have this ```#define A3A_Icon_HideVic A3A_GUI_QTEXTURE_PATH_OF(icon_hidevic.paa)```, I've tried to use it, but it seems that either I missing something or Community version doesn't have it

2024-12-23 01:41 UTC, Tiny-DM commented
threw something together for the compat, seems to be working. also removed some of the VTOL stuff cause it was breaking my function call and I spent about an hour trying to figure out what on earth was going on there and how my code was breaking and yours wasnt, and seperating VTOLs was already talked about. you understand better what's going on there, you can readd it if you can get it working

2024-12-23 03:39 UTC, wersal454 commented
hmm, maybe something like this? 
```
if (count _garage != EXPECTED_LENGTH) then {
    Info_1("Reformatting an existing saved garage to %1 categories. This happens after an update and will not run again.", EXPECTED_LENGTH)
    {
        private _dataHM = _x;
        {
            private _data = _dataHM get _x;
            private _class = _data#1;
            private _vehicle = _data#0;

            _newCat = [_class, _vehicle] call HR_GRG_fnc_getCatIndex;

            _newGarage#_newCat set [_x, _data];
        } forEach _x;
    } forEach _garage;
    _garage = _newGarage;
};
```

2024-12-23 04:11 UTC, Tiny-DM commented
well, I took a bit more of a look at the extra argument, and I'm not quite sure what is being achieved here anyway.

`params [["_class", "_vehicle", [""]]]`

the way this was structured before, you have _vehicle as the default argument for _class. _vehicle itself is never defined but is used to get the VTOL status, which you should still be able to grab with the classname anyways (something like `getText(configFile >> CfgVehicles >> _class >> "vtol"` maybe? I havent checked)

you had the extra argument once in the addvehicle function, not doing anything useful. It should have thrown a script error since there wasnt actual space for another argument but it doesnt appear cause of the environment of the script doesnt throw errors

the code is also looking for an object to get the `configOf`. since most of the mentions are in addVehicle, this would be fine, but the conversion im suggesting doesn't spawn objects, and you're trying to send that function the display name of the vehicle

overall though, you should be able to get the vtol status through the classname, you dont need a extra argument. but im more trying to figure out why this is still needed. didnt we agree to scrap a seperate VTOL category? thats done from what I can see, is it just moving them down to helicopters instead of jets?

2024-12-23 14:00 UTC, wersal454 commented
> well, I took a bit more of a look at the extra argument, and I'm not quite sure what is being achieved here anyway.
> 
> `params [["_class", "_vehicle", [""]]]`
> 
> the way this was structured before, you have _vehicle as the default argument for _class. _vehicle itself is never defined but is used to get the VTOL status, which you should still be able to grab with the classname anyways (something like `getText(configFile >> CfgVehicles >> _class >> "vtol"` maybe? I havent checked)
> 
> you had the extra argument once in the addvehicle function, not doing anything useful. It should have thrown a script error since there wasnt actual space for another argument but it doesnt appear cause of the environment of the script doesnt throw errors
> 
> the code is also looking for an object to get the `configOf`. since most of the mentions are in addVehicle, this would be fine, but the conversion im suggesting doesn't spawn objects, and you're trying to send that function the display name of the vehicle
> 
> overall though, you should be able to get the vtol status through the classname, you dont need a extra argument. but im more trying to figure out why this is still needed. didnt we agree to scrap a seperate VTOL category? thats done from what I can see, is it just moving them down to helicopters instead of jets?

Yeah, no separate VTOL category, but imo vtols are more helicopters then planes(if it makes sense)

And about checking if vehicle is a vtol, I've looked into it, and only thing I could find is doing it by checking the object and not classname(I hope there is a way, but I doubt it)

2024-12-23 14:13 UTC, wersal454 commented
maybe something like this 
```
_vtolConfig = configFile >> "CfgVehicles" >> _className;

if (getNumber(_vtolConfig >> "vtol") > 0) then {
```
but idk

2024-12-27 02:02 UTC, wersal454 commented
> maybe something like this
> 
> ```
> _vtolConfig = configFile >> "CfgVehicles" >> _className;
> 
> if (getNumber(_vtolConfig >> "vtol") > 0) then {
> ```
> 
> but idk

can confirm, this one works

2025-01-12 19:47 UTC, jaj22 requested changes
Apologies for not looking at this before.

2025-01-12 19:47 UTC, jaj22 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_editorCat isEqualTo "EdSubcat_Cars" && !(_class in undercoverVehicles)): { 1 };
Most of the garage code isn't supposed to have anything Antistasi-specific in it, so accessing `undercoverVehicles` here isn't allowed. You need to create a tiny function in garage/Public/config.inc which accesses undercoverVehicles and then call that from here.

2025-01-12 19:47 UTC, jaj22 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_editorCat in ["EdSubcat_Helicopters"] || getNumber (_vtolConfig >> "vtol") > 0): { 4 };
Putting VTOLs in the same category as helis is... interesting. I guess if we have an option in future to allow placing helis from a non-airbase HQ then it makes sense.

2025-01-12 19:47 UTC, jaj22 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_editorCat in ["CUP_EdSubcat_Bikes","CUP_EdSubCat_Cars_Woodland","CUP_EdSubCat_UpHMMWV_Cars_Desert","CUP_EdSubCat_Cars_Winter"] and !(_class in undercoverVehicles)): { 1 };
undercoverVehicles usage again. See above.

2025-01-12 19:47 UTC, jaj22 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_class isKindOf "Car" and !(_class in undercoverVehicles)): { 1 };
undercoverVehicles usage again. See above.

2025-01-12 19:47 UTC, jaj22 commented on A3A/addons/garage/Public/fn_loadSaveData.sqf
> +if (count _garage != EXPECTED_LENGTH) then {
I think there's a good argument for running this code regardless of the garage count. Categories might change due to config or faction changes. For example if a civ addon pack is added, the undercover vehicles list changes.

2025-01-12 20:07 UTC, wersal454 commented on A3A/addons/garage/Public/fn_loadSaveData.sqf
> +if (count _garage != EXPECTED_LENGTH) then {
@Tiny-DM

2025-01-12 22:38 UTC, wersal454 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_editorCat isEqualTo "EdSubcat_Cars" && !(_class in undercoverVehicles)): { 1 };
I can't think of a way on how this can be done tbh

2025-01-12 22:39 UTC, wersal454 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_editorCat isEqualTo "EdSubcat_Cars" && !(_class in undercoverVehicles)): { 1 };
or I can

but it doesn't make sense since you would still be calling antistasi specific function in here

2025-01-13 02:27 UTC, jaj22 commented on A3A/addons/garage/Core/fn_getCatIndex.sqf
> +    case (_editorCat isEqualTo "EdSubcat_Cars" && !(_class in undercoverVehicles)): { 1 };
The garage isn't really part of Antistasi. It's written as general purpose code, and if you look at the comments at the top you'll see that most of it is licensed as APL-ND, while config.inc (where you're supposed to put most mission-specific changes) is MIT.

The Antistasi community has permission from the author to modify APL-ND parts, but it's important to retain that rule so that other projects can still use the code without having to touch the APL-ND sections.

2025-01-25 09:25 UTC, wersal454 commented
might as well move ```switch (true) do {
    //filter blacklist first
    case (_class in HR_GRG_blacklistVehicles): { -2 };
    //vanilla
    case (_editorCat isEqualTo "EdSubcat_Cars"): { [_class] call HR_GRG_AntistasiOrNot }; // Returns 0 (undercover) or 1 (not undercover) 
    case (_editorCat isEqualTo "EdSubcat_APCs"): { 2 };
    case (_editorCat in ["EdSubcat_Tanks","EdSubcat_AAs","EdSubcat_Artillery"]): { 3 };
    case (_editorCat in ["EdSubcat_Helicopters"] || getNumber (_vtolConfig >> "vtol") > 0): { 4 };
    //case (getNumber (configOf _vehicle >> "vtol") > 0): { 5 };
    case (_editorCat in ["EdSubcat_Planes"] && (getNumber (_vtolConfig >> "vtol") == 0)): { 5 };
    case (_editorCat in ["EdSubcat_Boats","EdSubcat_Submersibles"]): { 6 };
    case (_editorCat isEqualTo "EdSubcat_Turrets"): { 7 };

    //rhs
    case (_editorCat in ["rhs_EdSubcat_car", "rhs_EdSubcat_truck", "rhs_EdSubcat_mrap"]): { [_class] call HR_GRG_AntistasiOrNot }; // Returns 0 (undercover) or 1 (not undercover)
    case (_editorCat in ["rhs_EdSubcat_apc","rhs_EdSubcat_ifv"]): {2};
    case (_editorCat in ["rhs_EdSubcat_tank","rhs_EdSubcat_aa","rhs_EdSubcat_artillery"]): {3};
    case (_editorCat in ["rhs_EdSubcat_helicopter","rhs_EdSubcat_helicopter_d","rhs_EdSubcat_helicopter_wd"]): { 4 };
    case (_editorCat in ["rhs_EdSubcat_aircraft"]): { 5 };
    case (_editorCat isEqualTo "rhs_EdSubcat_boat"): { 6 };

    //cup
    case (_editorCat in ["CUP_EdSubcat_Bikes", "CUP_EdSubCat_Cars_Woodland", "CUP_EdSubCat_UpHMMWV_Cars_Desert", "CUP_EdSubCat_Cars_Winter"]): { [_class] call HR_GRG_AntistasiOrNot }; // Returns 0 (undercover) or 1 (not undercover)
    
    //Fallback
    case (_class isKindOf "Car"): { [_class] call HR_GRG_AntistasiOrNot }; // Returns 0 (undercover) or 1 (not undercover)
    case (_class isKindOf "Tracked_APC"): { 2 }; //?
    case (_class isKindOf "Tank"): { 3 };
    case (_class isKindOf "Helicopter"): { 4 };
    case (_class isKindOf "Plane"): { 5 };
    case (_class isKindOf "Ship"): { 6 };
    case (_class isKindOf "staticWeapon"): { 7 }; //some non-vanilla artillery is statics

    default { -1 };
};``` 

into ```config.inc``` and check if garage is in antistasi or not

2025-02-10 20:22 UTC, jaj22 commented on A3A/addons/garage/Public/config.inc
> +    if (_class isEqualTo "") exitWith {-1}
Nil or empty strings shouldn't happen here. If it does, it's a pretty serious bug in the garage and it's going to break elsewhere. I'd just drop the "safety" checks.

2025-02-10 20:24 UTC, jaj22 commented on A3A/addons/garage/Public/config.inc
> +    _isUndercover;
Or just `[1, 0] select (_class in undercoverVehicles);`

2025-02-14 22:56 UTC, jaj22 commented on A3A/addons/garage/Public/config.inc
> +    _isUndercover;
This line needs to go too, because we're trying to return the value from the select.

Also you forgot to change the function name from AntistasiOrNot in the four calls in getCatIndex.

2025-02-15 03:03 UTC, jaj22 approved these changes
Played around with it. Some oddities with category selection and naming but it works, and I think it's an improvement overall, even just from splitting the cars.

2025-02-15 11:42 UTC, wersal454 commented
> Played around with it. Some oddities with category selection and naming but it works, and I think it's an improvement overall, even just from splitting the cars.

It's not too late to make the quick changes if you have any considerations

2025-03-18 02:22 UTC, jaj22 commented
> > Played around with it. Some oddities with category selection and naming but it works, and I think it's an improvement overall, even just from splitting the cars.
> 
> It's not too late to make the quick changes if you have any considerations

Sorry, forgot to reply to this. Minor issues from memory:
- Category is called undercover (at least in the english text) rather than civilian. They're the same thing in Antistasi but not necessarily for other garage uses.
- Similarly, the category has a question mark as an icon, which I assume was the most appropriate for "undercover".
- Surprised there wasn't a separate category for fuel/repair/ammo sources. That seemed like the most obvious and useful split to me.
- Wouldn't have bothered with the APC/tank split from an Antistasi perspective personally, although maybe people hoard enough armoured vehicles to make it worthwhile.

Probably everyone has their own opinion on garage categories though.

2025-03-18 17:29 UTC, jaj22 commented on A3A/addons/garage/Public/fn_loadSaveData.sqf
> +if (count _garage != EXPECTED_LENGTH) then {
Yes.

2025-03-23 21:38 UTC, jaj22 commented
I think everything's correct & working now, but now there are even more tracked vehicle categories so I'm less happy about it. I guess I'll merge as-is and we'll have to run a poll on the categories during testing.

Reference for how to reduce the categories if we need it: https://github.com/official-antistasi-community/A3-Antistasi/pull/3378/commits/e4f95a336303becd12bf253f8fd99801cb5d3894

2025-04-10 23:56 UTC, merged