Add UI and supporting code to set custom loadouts for rebel troops
official-antistasi-community/A3-Antistasi pull request #3392
Opened 2024-08-28 20:27 UTC by jaj22

### What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Added a UI and supporting code to set partial custom loadouts for rebel troops. This is strictly vetted by unit type to avoid exploits: Only grenadiers can use grenade launchers, for example. Ammunition is only lightly configurable (choice of "normal" or "high").  If there aren't enough weapons of a type, they can't be selected although in some cases they may spawn with the "random" option. If you only want to force some aspects of a loadout and leave the rest random, this is also possible.

Optics button is a placeholder. Not sure whether to implement anything here. There's currently no vetting for item existence, so if you change modset within a saved game then you might need to reset the loadouts in the UI.

The button to access the UI is on the right in the commander menu. There was a free slot after I switched it to 2x5.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.
1. [X] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

Needs a DS test but it uses similar mechanics to A3A_rebelGear so it should be fine.

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

2024-09-02 03:44 UTC, jaj22 commented
UI screenshot as requested:
![20240901193949_1](https://github.com/user-attachments/assets/58013c01-1e9b-4405-9aa5-a6d18ea73b42)

2024-09-29 18:38 UTC, killerswin2 approved these changes
LGTM

2024-09-29 18:39 UTC, Tiny-DM commented on A3A/addons/core/dialogs.hpp
> +			action = "if (player == theBoss) then {closeDialog 0; createDialog ""A3A_customLoadoutsDialog""} else {[""Custom Loadouts"", ""Only commanders have access to this function""] call A3A_fnc_customHi
// TODO: Localize
Or just localize it yourself.

2024-10-21 14:41 UTC, ante185 reviewed
This will to a degree invalidate #3083, but i suppose it's fine.

the optics selection should probably be removed for now, or set to always display random until there's any particular way we want it to work

2024-10-21 20:21 UTC, ante185 approved these changes
actually, lgtm

2024-12-01 19:07 UTC, jaj22 commented
> This will to a degree invalidate #3083, but i suppose it's fine.

To check I'm not missing something here, I don't see how it affects #3083, because the pistols are only used before a rifle is unlocked, and this UI only gives you any control once a rifle is unlocked?

Going to put the fix for Tiny's click-spam bug in here too, otherwise it'll collide.

2024-12-02 20:14 UTC, jaj22 commented
Added the likely fix for #3449. It's not easy to prove because it depends on specific network & thread timings.

2024-12-02 22:04 UTC, rautamiekka requested changes

2024-12-02 22:04 UTC, rautamiekka commented on A3A/addons/gui/functions/GUI/fn_customLoadoutsDialog.sqf
> +        // disable if not valid?
```suggestion
        // TODO disable if not valid?
```

2024-12-02 22:24 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_addPrimaryAndMags.sqf
> +if ("GrenadeLaunchers" in _categories && {"Rifles" in _categories} ) then {
It's wrong though. Should be comparing to -1

2024-12-03 00:18 UTC, rautamiekka commented on A3A/addons/core/functions/Ammunition/fn_addPrimaryAndMags.sqf
> +if ("GrenadeLaunchers" in _categories && {"Rifles" in _categories} ) then {
Yeah, I only just now realized that mistake. I keep forgetting this thing doesn't return boolean. Fixed.

2024-12-04 15:41 UTC, ante185 commented
> > This will to a degree invalidate #3083, but i suppose it's fine.
> 
> To check I'm not missing something here, I don't see how it affects #3083, because the pistols are only used before a rifle is unlocked, and this UI only gives you any control once a rifle is unlocked?
> 
> Going to put the fix for Tiny's click-spam bug in here too, otherwise it'll collide.

Okay then i'm not sure, is this working like you intended it to? this is just the starting vanilla FIA arsenal.
![image](https://github.com/user-attachments/assets/dd722fae-3144-4907-a2fc-d4106a66a2e5)
Just following up to make sure, as the purpose of the random pistols were to round out the capability of the early game rebel ai, so it's not necessarily a benefit for the player to make them not equip them, AKA I'm unbothered by this bypassing that.

2024-12-04 15:43 UTC, Play3rgg commented
> > > This will to a degree invalidate #3083, but i suppose it's fine.
> > 
> > 
> > To check I'm not missing something here, I don't see how it affects #3083, because the pistols are only used before a rifle is unlocked, and this UI only gives you any control once a rifle is unlocked?
> > Going to put the fix for Tiny's click-spam bug in here too, otherwise it'll collide.
> 
> Okay then i'm not sure, is this working like you intended it to? this is just the starting vanilla FIA arsenal. ![image](https://private-user-images.githubusercontent.com/49555217/392450315-dd722fae-3144-4907-a2fc-d4106a66a2e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjcyMTAsIm5iZiI6MTczMzMyNjkxMCwicGF0aCI6Ii80OTU1NTIxNy8zOTI0NTAzMTUtZGQ3MjJmYWUtMzE0NC00OTA3LWEyZmMtZDQxMDZhNjZhMmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1NDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMzliNWQ4ZTFmMDY2Zjc0NjFlYzFjZDI0NDBlODliY2MwYWJlNTc3ZjlkMDRkNjhlMDc4MWZiYjAxOTE0YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EiWRxxwA4zDmvA-ys8k0hWblfad0VQG4MPgN9x0GAIU) Just following up to make sure, as the purpose of the random pistols were to round out the capability of the early game rebel ai, so it's not necessarily a benefit for the player to make them not equip them, AKA I'm unbothered by this bypassing that.

Please make the opacity higher on the drop down, the current UI hurts my brain

2024-12-04 17:10 UTC, jaj22 commented
>  Just following up to make sure, as the purpose of the random pistols were to round out the capability of the early game rebel ai, so it's not necessarily a benefit for the player to make them not equip them, AKA I'm unbothered by this bypassing that.

Ah, I forgot that I included shotguns & SMGs in the list. Do you think any of these options is preferable?:
1. Include pistols if there are no rifles.
2. Include pistols regardless.
3. Don't show anything until there are rifles.

2024-12-04 17:12 UTC, jaj22 commented
> Please make the opacity higher on the drop down, the current UI hurts my brain

I remember trying that with the startup parameters and it was actually worse (more background/foreground confusion).

2024-12-04 18:14 UTC, jaj22 commented
The idea of 3 would be to still show SMG and shotgun choices, but only once you've unlocked a rifle. Doesn't make sense in the case where players unlock a better shotgun first though. Will probably leave it as is: In practice I doubt many people would be forcing a single-barrel shotgun over a random handgun choice.

2024-12-04 18:21 UTC, jaj22 commented on A3A/addons/core/functions/Ammunition/fn_addPrimaryAndMags.sqf
> +if ("GrenadeLaunchers" in _categories && {"Rifles" in _categories} ) then {
Still wrong. It's an AND, while findAny can only do an OR.

2024-12-05 03:28 UTC, killerswin2 approved these changes

2024-12-06 21:28 UTC, merged