Added CWR3 Templates
official-antistasi-community/A3-Antistasi pull request #3413
Opened 2024-10-13 19:11 UTC by skillless402

added the mod cold war rearmed 3

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information: Added templates for the cold war rearmed 3 Mod
    

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [x] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps:  More play testing

********************************************************
Notes:

2024-10-13 19:13 UTC, Tiny-DM commented on A3A/addons/config_fixes/CWR/CfgVehicles.hpp
> +
Delete this file if you don't need any vehicle fixes, also delete the include from config.cpp

2024-10-13 19:13 UTC, Tiny-DM commented on A3A/addons/config_fixes/CWR/CfgVehicles.hpp
> +
Wait, nevermind, you have one fix here. Just put the contents of cfg,hpp into this file, no need to seperate it.

2024-10-13 19:16 UTC, ante185 reviewed
needs some tidying up so far

2024-10-13 19:16 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CUP_Reb_Vehicle_Attributes.sqf
> +]] call _fnc_saveToTemplate;
if these are identical to the ones from the CUP template you should be using those files directly rather than duplicating the file

2024-10-13 19:16 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CUP_Vehicle_Attributes.sqf
> +]] call _fnc_saveToTemplate;
if these are identical to the ones from the CUP template you should be using those files directly rather than duplicating the file
See the Western Sahara factions for examples.

2024-10-13 19:22 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates.hpp
> +        shortName = "US Army";
Add lore description to all 3 factions

2024-10-13 19:22 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/CWR/CUP_Reb_Vehicle_Attributes.sqf
> +["attributesVehicles", [
Delete, include from CUP folder

2024-10-13 19:22 UTC, Tiny-DM commented on A3A/addons/core/Templates/Templates/CWR/CUP_Vehicle_Attributes.sqf
> +["attributesVehicles", [
Delete, include from CUP folder

2024-10-13 19:30 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_Reb_FIA.sqf
> +#include "CUP_Reb_Vehicle_Attributes.sqf"
```suggestion
#include "..\CUP\CUP_Reb_Vehicle_Attributes.sqf"
```

2024-10-13 19:50 UTC, ante185 commented on A3A/addons/config_fixes/CWR/config.cpp
> +//#include "CfgWeapons.hpp"
remove unused comments

2024-10-13 19:50 UTC, ante185 commented on A3A/addons/core/Templates/AircraftLoadouts/CWR/config.cpp
> +        };
removed the entire class Helicopter {};

2024-10-13 19:50 UTC, ante185 commented on A3A/addons/core/Templates/Templates.hpp
> +        //requiredAddons[] = {"cwr3_core"};        // vehicles requires units & weapons
remove comments

2024-10-13 19:50 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_Reb_Vehicle_Attributes.sqf
> +    ["cwr3_i_ural_zu23", ["rebCost", 1000]],
cheap for a zu ural

2024-10-13 20:03 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_Reb_FIA.sqf
> +
You want to include your CWR_Reb_Vehicle_Attributes here

2024-10-14 21:28 UTC, ante185 requested changes
No rpt errors or loadout validation errors

2024-10-14 21:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +["vehiclesPlanesCAS", ["cwr3_o_su17m4"]] call _fnc_saveToTemplate;
suggestion, add the mig-27 for CAS

2024-10-14 21:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +["vehiclesHelisAttack", ["cwr3_o_mi24d", "cwr3_o_mi24d", "cwr3_o_mi24p", "cwr3_o_mi24v"]] call _fnc_saveToTemplate;
cwr3_o_mi24p has no gun turret and can't go as a regular attack helicopter, it can go in light attack.
Also no low probability for the V80?

2024-10-14 21:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +["vehiclesArtillery", ["CUP_O_BM21_RU"]] call _fnc_saveToTemplate;
only the bm21 grad for artillery?

2024-10-14 21:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +    ["CUP_launch_RPG7V", "", "", "", ["CUP_OG7_M", "CUP_PG7V_M"], [], ""],
should probably just move these up to the _loadoutData.

2024-10-14 21:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +    ["CUP_launch_RPG7V", "", "", "", ["CUP_OG7_M", "CUP_PG7V_M"], [], ""]
this is a lot of RPGs with HE rounds loaded first, this'll impact the enemy's ability to engage hostile vehicles. May annoy players as they get a lot more rockets shot at them

2024-10-14 21:28 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_US_Army_Temperate.sqf
> +    ["cwr3_launch_m67_rcl", "", "", "", ["cwr3_m67_rcl_heat_m", "cwr3_m67_rcl_heat_m"], [], ""]
No complementary Carl Gustav?

2024-10-14 21:52 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +["vehiclesAA", ["cwr3_o_mtlb_sa13", "cwr3_o_zsu", "cwr3_o_bmp2_zu23"]] call _fnc_saveToTemplate;
cwr3_o_mtlb_sa13 isn't capable of attacking ground targets, and has to go unfortunately

2024-10-14 23:20 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_US_Army_Temperate.sqf
> +["vehiclesTanks", ["cwr3_b_m60a3", "cwr3_b_m60a3_tts", "cwr3_b_m1"]] call _fnc_saveToTemplate;
```suggestion
["vehiclesTanks", ["cwr3_b_m60a3", "cwr3_b_m60a3_tts", "cwr3_b_m1"]] call _fnc_saveToTemplate;
["vehiclesLightTanks", ["cwr3_b_fia_m41a1"]] call _fnc_saveToTemplate;
```

2024-10-15 15:16 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +    ["CUP_arifle_AKM_Early", "", "", "", ["CUP_30Rnd_762x39_AK47_bakelite_M"], [], ""]
Could do with some pruning of the excess duplicates in this template too.

2024-10-16 17:17 UTC, ante185 commented on A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf
> +["vehiclesLightAPCs", [""cwr3_o_mtlb_pk"]] call _fnc_saveToTemplate;
```suggestion
["vehiclesLightAPCs", ["cwr3_o_mtlb_pk"]] call _fnc_saveToTemplate;
```

2024-10-17 18:33 UTC, ante185 approved these changes
looks good

2024-10-17 18:33 UTC, ante185 commented on A3A/addons/core/Templates/AircraftLoadouts/CWR/config.cpp
> +                loadout[] = {"CUP_PylonPod_16Rnd_S5_plane_M","CUP_PylonPod_16Rnd_S5_plane_M","CUP_PylonPod_1Rnd_FAB250_plane_M","CUP_PylonPod_1Rnd_FAB250_plane_M","PylonMissile_Missile_AGM_KH25_x1","
bombs aren't a necessity for modern planes, you can lose them or replace them, but i think the plane should have sufficient weapons as is

2024-10-17 18:33 UTC, ante185 commented on A3A/addons/core/Templates/AircraftLoadouts/CWR/config.cpp
> +                loadout[] = {"PylonMissile_Missile_AA_R73_x1","PylonMissile_Missile_AA_R73_x1","PylonRack_1Rnd_Missile_AGM_01_F","PylonRack_1Rnd_Missile_AGM_01_F","CUP_PylonPod_32Rnd_S5_plane_M"};
```suggestion
                loadout[] = {"","","PylonRack_1Rnd_Missile_AGM_01_F","PylonRack_1Rnd_Missile_AGM_01_F","CUP_PylonPod_32Rnd_S5_plane_M"};
```
Gotta drop the the AA missiles from cas planes
If you want you can replace those vanilla missiles with CUP ones.

2024-10-17 18:33 UTC, ante185 commented on A3A/addons/core/Templates/AircraftLoadouts/CWR/config.cpp
> +                loadout[] = {"CUP_PylonPod_2Rnd_AIM_9L_LAU_Sidewinder_M","CUP_PylonPod_19Rnd_Rocket_FFAR_plane_M","CUP_PylonPod_19Rnd_Rocket_FFAR_plane_M","PylonRack_Missile_AGM_02_x2","CUP_PylonPod_
```suggestion
                loadout[] = {"","CUP_PylonPod_19Rnd_Rocket_FFAR_plane_M","CUP_PylonPod_19Rnd_Rocket_FFAR_plane_M","PylonRack_Missile_AGM_02_x2","CUP_PylonPod_2Rnd_Mk82_M","","CUP_PylonPod_2Rnd_Mk82_M","PylonRack_Missile_AGM_02_x2","CUP_PylonPod_19Rnd_Rocket_FFAR_plane_M","CUP_PylonPod_19Rnd_Rocket_FFAR_plane_M","CUP_PylonPod_ALQ_131"};
```
same as with the aa missiles on the mig 27

2024-10-17 21:51 UTC, ante185 requested changes
You've input magazines instead of weapons for all the rocket and missiles weapons of the CAS planes

2024-10-17 21:51 UTC, ante185 commented on A3A/addons/core/Templates/AircraftLoadouts/CWR/config.cpp
> +                mainGun[] = {"CUP_PylonPod_250Rnd_TE2_Green_Tracer_GSh23_23mm_APHE_M"};
mainGun has to be a weapon not a magazine

2024-10-20 15:51 UTC, ante185 approved these changes
lgtm

2024-10-22 21:04 UTC, merged