Aegis factions Compatability
official-antistasi-community/A3-Antistasi pull request #3414
Opened 2024-10-13 20:46 UTC by RetardedFoX

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [x] Enhancement

### What have you changed and why?
Information:
Adds Aegis factions (Excluding Argana) to the gamemode.
Mod complains if you run without WS CDLC, but no assets will be used without it enabled (I hope).

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [x] Yes (Please provide further detail below.)

### How can the changes be tested?
Gaming time.
I haven't tested this at all :)

********************************************************
Notes:

2024-10-13 21:32 UTC, ante185 reviewed
Could perhaps use more Aegis stuff in place of vanilla weapons

2024-10-13 21:32 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_China.sqf
> +	["sgun_aa40_lxWS", "", "acc_pointer_IR", "optic_Holosight_smg_blk_F", ["8Rnd_12Gauge_AA40_Pellets_lxWS", "8Rnd_12Gauge_AA40_Slug_lxWS"], [], ""],
this should prob not be dependent on the marksmen DLC

2024-10-13 22:21 UTC, RetardedFoX commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_China.sqf
> +	["sgun_aa40_lxWS", "", "acc_pointer_IR", "optic_Holosight_smg_blk_F", ["8Rnd_12Gauge_AA40_Pellets_lxWS", "8Rnd_12Gauge_AA40_Slug_lxWS"], [], ""],
Fixed in 360c426

2024-10-14 22:18 UTC, ante185 reviewed
Suggested changes

2024-10-14 22:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_BAF_Arid.sqf
> +["vehiclesPlanesTransport", ["B_A_VTOL_01_infantry_F"]] call _fnc_saveToTemplate;
```suggestion
["vehiclesPlanesTransport", ["B_A_Plane_Transport_01_infantry_F"]] call _fnc_saveToTemplate;
```

2024-10-14 22:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_China.sqf
> +["vehiclesPlanesTransport", ["O_T_VTOL_02_infantry_dynamicLoadout_F", "O_T_Plane_Transport_01_infantry_ghex_F"]] call _fnc_saveToTemplate;
```suggestion
["vehiclesPlanesTransport", ["O_T_Plane_Transport_01_infantry_ghex_F"]] call _fnc_saveToTemplate;
```

2024-10-14 22:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_LDF.sqf
> +["vehiclesPlanesTransport", []] call _fnc_saveToTemplate;
```suggestion
["vehiclesPlanesTransport", ["B_T_Plane_Transport_01_infantry_F"]] call _fnc_saveToTemplate;
```

2024-10-14 22:18 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_US_Arid.sqf
> +["vehiclesPlanesTransport", ["B_T_VTOL_01_infantry_F","B_T_VTOL_01_infantry_blue_F"]] call _fnc_saveToTemplate;
```suggestion
["vehiclesPlanesTransport", ["B_T_Plane_Transport_01_infantry_F"]] call _fnc_saveToTemplate;
```

2024-10-20 15:58 UTC, ante185 commented
Any new vehiclesPlanesCAS and vehiclesPlanesAA classnames are going to need a class each for their loadouts in core/Templates/AircraftLoadouts/Aegis, even if they're just inheriting from the existing vanilla loadouts.

Each faction in the template.hpp are going to need an lore entry, see @Tiny-DM for instructions.

2024-11-02 22:50 UTC, ante185 commented on A3A/addons/core/Templates/AircraftLoadouts/Aegis/config.cpp
> +            class B_Plane_CAS_01_dynamicLoadout_F : baseCAS {
Do not re-specify the vanilla loadouts

2024-11-02 22:55 UTC, RetardedFoX commented on A3A/addons/core/Templates/AircraftLoadouts/Aegis/config.cpp
> +            class B_Plane_CAS_01_dynamicLoadout_F : baseCAS {
Woopsie

2024-11-12 20:14 UTC, ante185 requested changes
Look over the traitor loadout data, they don't seem to align with expectations.
the rebel factions don't need to start with SMGs if you're giving them semi automatic shotguns.
Situationally you should perhaps use a couple of the guns the military uses in the SF category but otherwise the SF stuff looks good.

2024-11-12 20:14 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_LDF.sqf
> +["arifle_RPK_F", "", "acc_flashlight_pistol", "", ["75Rnd_762x39_Mag_F", "75Rnd_762x39_Mag_F", "75Rnd_762x39_Mag_Tracer_F"], [], ""]
Consider giving military and especially militia units less high capacity mags when those mags are compatible with the regular rifles.

2024-11-12 20:14 UTC, ante185 commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_LDF.sqf
> +["arifle_RPK_F", "", "acc_flashlight_pistol", "", ["75Rnd_762x39_Mag_F", "75Rnd_762x39_Mag_F", "75Rnd_762x39_Mag_Tracer_F"], [], ""]
You wanted a reminder that there exists a 5.45 RPK with wooden stock

2024-11-13 19:23 UTC, RetardedFoX commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_BAF_Tropical.sqf
> +_sfLoadoutData set ["uniforms", ["U_B_UBACS_mtp_f", "U_B_UBACS_vest_tna_f", "U_B_UBACS_tshirt_tna_f"]];
7222e5c

2024-11-13 19:23 UTC, RetardedFoX commented on A3A/addons/core/Templates/Templates/Aegis/Aegis_AI_BAF_Temperate.sqf
> +["arifle_MXM_Black_F", "", "acc_pointer_IR", "optic_SOS", ["30Rnd_65x39_caseless_black_mag", "30Rnd_65x39_caseless_black_mag", "30Rnd_65x39_caseless_black_mag_Tracer"], [], "bipod_01_F_blk"],
7222e5c

2024-11-17 20:36 UTC, ante185 approved these changes
Good for testing

2024-11-27 20:08 UTC, merged