3CBF weapon integration into RHS factions
official-antistasi-community/A3-Antistasi pull request #3422
Opened 2024-11-10 03:09 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
added a case that adds a couple appropriate weapons in the case that an pure RHS faction is used while 3CB Factions is loaded.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:

2024-11-10 13:18 UTC, rautamiekka requested changes

2024-11-10 13:18 UTC, rautamiekka commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf
> +    ];
All of these lines ain't exactly very readable like this.

2024-11-11 18:37 UTC, Play3rgg requested changes
looks fine for the most part

2024-11-11 18:37 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
> +    ["uk3cb_sks_01", "", "", "", ["uk3cb_10rnd_magazine_sks", "uk3cb_10rnd_magazine_sks_G", "uk3cb_10rnd_magazine_sks_GT"], [], ""]
sks on HIDF?

2024-11-11 18:37 UTC, Play3rgg commented on A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
> +    ["UK3CB_SVD_OLD", "", "", "rhs_acc_1pn93_1", ["rhs_10Rnd_762x54mmR_7N1"], [], ""]
lol

2024-11-21 17:54 UTC, Play3rgg approved these changes
(I still think M193/M196 on RHS USAF is a bit silly since the normal RHS ones get M855 and only the 3cbf ones get the worse ammo
more variety ig)

LGTM

2024-12-06 21:28 UTC, merged