Normalised and weighted vehicle spawns for airbases
official-antistasi-community/A3-Antistasi pull request #3440
Opened 2024-11-26 00:46 UTC by ante185

## What type of PR is this.
1. [ ] Bug
2. [x] Change
3. [ ] Enhancement

### What have you changed and why?
Information:
Previous behaviour would spawn all vehicles with equal probability, which would make certain categories of vehicles much much more probable than others. a big issue for factions which had certain categories that were unusually lean or heavily stacked.
New behaviour adds per category weights, that then get divided by the count of the vehicle category to "flatten" out the probabilities and remove effect of having more vehicles in one category than in the others.
This will also let us more closely tune the spawn behaviour to balance it as we'd like to.

### Please specify which Issue this PR Resolves.
closes #XXXX

### Please verify the following and ensure all checks are completed.

1. [ ] Have you loaded the mission in LAN host?
2. [ ] Have you loaded the mission on a dedicated server?

### Is further testing or are further changes required?
1. [ ] No
2. [ ] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 

********************************************************
Notes:
TODO: estimate roughly what the previous spawn chances were, maybe accept vanilla factions as a rule to go by?

2024-11-26 03:54 UTC, rautamiekka requested changes

2024-11-26 03:54 UTC, rautamiekka commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +				if(count _vehs == 0) then {continue};
```suggestion
				if (_vehs isEqualTo []) then {continue};
```

2024-11-26 03:54 UTC, rautamiekka commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +					if(count _vehs == 0) then {continue};
```suggestion
					if (_vehs isEqualTo []) then {continue};
```

2024-11-26 03:54 UTC, rautamiekka commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +		if(count _vehs == 0) then {continue};
```suggestion
		if (_vehs isEqualTo []) then {continue};
```

2024-11-26 03:54 UTC, rautamiekka commented on A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
> +	if(count _vehs == 0) then {continue};
```suggestion
	if(_vehs isEqualTo []) then {continue};
```

2025-03-18 02:25 UTC, jaj22 commented
Gonna give myself another week to see if I can make good progress on the garrison rework, which obsoletes this. If not, it gets merged for 3.9.0.

2025-04-15 19:18 UTC, ante185 commented
adjusted IFV, Tank, and utility vehicle weights

2025-04-25 00:35 UTC, merged