Naval Support for Attacks
official-antistasi-community/A3-Antistasi pull request #3454
Opened 2024-12-05 23:35 UTC by Tiny-DM

## What type of PR is this.
1. [ ] Bug
2. [ ] Change
3. [X] Enhancement

### What have you changed and why?
Information:
Attacks will now spawn boats which will arrive, cover the troops, and leave. Hopefully.

Known issues:
- Waypoints spawn far off shore. Boats seem to automatically compensate and drop troops on shore?
- Boats dont RTB, they only spawn with TR UNLOAD point
- The timing sync needs another look; there are boats that go 70kmh+ and others in vanilla that go 20 kmh tops
- plagued with diag_logs for fixing dumb errors

### Is further testing or are further changes required?
1. [ ] No
2. [X] Yes (Please provide further detail below.)

### How can the changes be tested?
Steps: 
Bunch of stuff needs to be fixed and tested. Hardpoint idea may not be reliable

2024-12-06 19:09 UTC, wersal454 commented
Have you thought about using Sea Attack Spawns as spawn positions? What you are doing is probably better as it allows for more maps to be compatible.

I'm just thinking, if there is a Sea Attack Spawn marker on the map, then that means that, there is an actual way for boats to arrive from somewhere. Also it prevent a situation where boats would spawn in puddle(relatively small lake). But some over engineered way to check if spawn position is realistic(i.e. not the puddle) will do.

2024-12-24 22:03 UTC, Tiny-DM commented
all functionality should be done, working well in case testing. need to test with plenty of maps and plenty of boats. attack and transport still spawn at the same time so they arrive at wildly different times if they spawn an Assault Boat, but that's a price im willing to pay. otherwise, everything is working.

for case test, open Stratis, run
`["outpost_3","airport_1",1] spawn A3A_fnc_wavedAttack;`

2024-12-29 03:36 UTC, rautamiekka requested changes

2024-12-29 03:36 UTC, rautamiekka commented on A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
> +setVar("vehiclesGunBoats",OccAndInv("vehiclesGunBoats"));
```suggestion
setVar("vehiclesTransportBoats", OccAndInv("vehiclesTransportBoats"));
setVar("vehiclesGunBoats", OccAndInv("vehiclesGunBoats"));
```
For consistency.

2025-01-13 22:15 UTC, jaj22 commented
Ok, some general notes:
1. By using the nearest seaAttackSpawn you'll have the same issues as the original code, namely that it'll spawn the boats on the other side of a peninsula in some cases. Adding more sea spawns would fix that, but I think there are better solutions that also fix the "might send a sea attack to a pond" case. I might have a crack at that later.
2. The actual spawning code would be much simpler if you didn't use BIS_fnc_findSafePos or the blacklist. The only required conditions here are that the point is in water and there isn't already a boat nearby.
3. I guess you could use limitSpeed to improve the boat grouping, assuming that it works on boats. I should probably use that for other vehicles too. The original idea was to rewrite vehicle AI entirely and use something more like the convoy code, but that got benched for a while.

2025-03-06 02:18 UTC, jaj22 commented
Ok, I managed to get the automatic coast + path detection working reasonably well. Rewrote a lot of this to work with it, cleaned things up and fixed some bits and pieces.

The delay calc still isn't good because it doesn't take account of spawning times or boat turning (all boats are spawned pointing north, and they take a while to get going), but it does at least do things in the right order. There's some other slightly wacky stuff that doesn't much matter, like boats getting despawned and leaving their cargo swimming, or the land waypoints having the wrong altitude. Mostly works though.

2025-03-06 19:08 UTC, jaj22 commented on A3A/addons/core/functions/Pathfinding/fn_findSeaPath.sqf
> +    for "_offset" from -50 to +50 step 10 do {
Hmm, figured it was a no-op from the wiki so I kept it in for clarity, but apparently it does have a perf cost.

2025-03-06 19:32 UTC, rautamiekka commented on A3A/addons/core/functions/Pathfinding/fn_findSeaPath.sqf
> +    for "_offset" from -50 to +50 step 10 do {
I dunno for sure and haven't tried, but knowing SQF there has to be a cost no matter how small.

2025-03-07 05:24 UTC, jaj22 commented
Did some tweaks:
- Boats now face the target when spawned.
- Boats now count towards total vehicles in the attack.
- Waypoints now have relatively correct Z values, for what it's worth.
- Removed a + sign.

2025-04-06 21:25 UTC, Tiny-DM reviewed
See comment on Discord, otherwise this is probably as good as it's gonna get. AI boating is never going to be great. Tested locally.

2025-04-08 01:16 UTC, jaj22 commented
Future work: 
- VN and possibly CUP piers should be added to the blacklist.
- Cam Lao Nam has a lot of ROCKS terrain objects that are much smaller than the normal usage. Needs different approach.

2025-04-12 05:02 UTC, jaj22 approved these changes

2025-04-14 23:29 UTC, jaj22 commented
Reminder: Need to remove the markPoints and check if there's any other excessive debug logging.

2025-04-15 00:41 UTC, merged