changlog and version
official-antistasi-community/A3-Antistasi pull request #3456
Opened 2024-12-08 15:45 UTC by Bob-Murphy

updates changelog and version for 3.8.0 udpate

2024-12-08 17:37 UTC, ante185 requested changes

2024-12-08 17:37 UTC, ante185 commented on changelog.rst
> +   * :issue:`3441` & :issue:`3442` Added Expeditionary Forces MJTF factions plus Vanilla and Western Sahara compatibility
clarify/reword that it's EF intigration into the vanilla and WS factions

2024-12-08 17:37 UTC, ante185 commented on changelog.rst
> +   * :issue:`3407` Updated Vanilla/WS Factions, fine tuning, officer loadouts, further RF integration on missed factions
```suggestion
   * :issue:`3407` Updated Vanilla/WS Factions, fine tuning, officer loadouts, further RF integration in vanilla and WS factions
```

2024-12-10 23:55 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3443` Fixed EF CDLC detection
This PR should be dropped. It was a hotfix for EF support

2024-12-15 23:57 UTC, ante185 commented on changelog.rst
> +   * :issue:`3424` & :issue:`3448` Updated Isla Duala to hide "bad" objects and cull obsolete enemy locations
This also enables/unhides the Isla Duala mission

2024-12-27 23:08 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`3441` & :issue:`3442` Added Expeditionary Forces MJTF factions plus Vanilla and Western Sahara compatibility
done

2024-12-27 23:08 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`3407` Updated Vanilla/WS Factions, fine tuning, officer loadouts, further RF integration on missed factions
done

2024-12-27 23:08 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`3443` Fixed EF CDLC detection
done

2024-12-27 23:08 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`3424` & :issue:`3448` Updated Isla Duala to hide "bad" objects and cull obsolete enemy locations
done

2024-12-27 23:23 UTC, ante185 reviewed
Some things i appear to have glossed over when i last looked through these

2024-12-27 23:23 UTC, ante185 commented on changelog.rst
> +   * :issue:`3441` & :issue:`3442` Added Expeditionary Forces MJTF factions and added EF integration Vanilla and Western Sahara templates
```suggestion
   * :issue:`3441` & :issue:`3442` Added Expeditionary Forces MJTF factions and added EF integration in Vanilla and Western Sahara templates
```

2024-12-27 23:23 UTC, ante185 commented on changelog.rst
> +   * :issue:`3376` Changed to have more frequent militia vehicles/transports early game
this effect war level 1-4, worthwhile to note maybe?

2024-12-27 23:23 UTC, ante185 commented on changelog.rst
> +   * :issue:`3437` Updated IFA Faction Templates
```suggestion
   * :issue:`3437` Updated IFA Faction Templates to solve a bug with the large intel item. Adds Churchills to the IFA UK faction IFV lineup
```

2024-12-27 23:23 UTC, ante185 commented on changelog.rst
> +   * :issue:`3451` Fixed CUP template in BAF, ION
```suggestion
   * :issue:`3451` Fixed missing comma and incorrect artillery classnames in CUP template in BAF, ION
```

2024-12-27 23:23 UTC, ante185 commented on changelog.rst
> +   * :issue:`3452` Updated 3CB Ranger and fixed artillery
```suggestion
   * :issue:`3452` Updated 3CB LDF with the Livonian Armed Forest Rangers, and corrected magazine classname for the rocket artillery
```

2024-12-27 23:23 UTC, ante185 commented on changelog.rst
> +   * :issue:`3457` Fixed NVG entry in RHS HIDF and flagged RHS HIDF and TLA as lowtech
```suggestion
   * :issue:`3457` Fixed NVG entry in RHS HIDF
```
My bad, did not keep the PR description up to date

2024-12-27 23:28 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3376` Changed to have more frequent militia vehicles/transports early game
eh, its implied by militia imo

2024-12-27 23:29 UTC, Tiny-DM commented on changelog.rst
> +   * :issue:`3459` Added various TFAR bagpacks and to multiple templates
backpacks? bagpacks?

2024-12-27 23:36 UTC, Bob-Murphy commented on changelog.rst
> +   * :issue:`3376` Changed to have more frequent militia vehicles/transports early game
good as is as it's mentioning militia as well as early game

2024-12-29 11:45 UTC, ante185 approved these changes
lgtm i think

2024-12-29 18:19 UTC, merged